/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID lab1-4.eng.utah.edu)
#  Generated on:      Mon Nov 27 18:45:24 2023
#  Design:            soc_top
#  Command:           saveNetlist -excludeLeafCell ../HDL/PLACED/soc_top_placed_modelsim.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Nov 27 2023 18:23:33 MST (Nov 28 2023 01:23:33 UTC)
// Verification Directory fv/soc_top 
module binToBCD (
	clk, 
	rst, 
	bin, 
	BCD);
   input clk;
   input rst;
   input [5:0] bin;
   output [7:0] BCD;
endmodule

module binToBCD_SPC_1 (
	clk, 
	rst, 
	bin, 
	BCD);
   input clk;
   input rst;
   input [5:0] bin;
   output [7:0] BCD;
endmodule

module binToBCD_SPC_2 (
	clk, 
	rst, 
	bin, 
	BCD);
   input clk;
   input rst;
   input [5:0] bin;
   output [7:0] BCD;
endmodule

module Seg7Display (
	clk, 
	reset, 
	seconds_clk, 
	state, 
	current_s, 
	current_m, 
	current_h, 
	stopwatch_s, 
	stopwatch_m, 
	stopwatch_h, 
	display_s1, 
	display_m1, 
	display_h1, 
	display_s2, 
	display_m2, 
	display_h2, 
	second, 
	p1, 
	p2, 
	clk_clone3, 
	clk_clone2, 
	clk_clone1);
   input clk;
   input reset;
   input seconds_clk;
   input [2:0] state;
   input [5:0] current_s;
   input [5:0] current_m;
   input [5:0] current_h;
   input [5:0] stopwatch_s;
   input [5:0] stopwatch_m;
   input [5:0] stopwatch_h;
   output [6:0] display_s1;
   output [6:0] display_m1;
   output [6:0] display_h1;
   output [6:0] display_s2;
   output [6:0] display_m2;
   output [6:0] display_h2;
   output second;
   input p1;
   input p2;
   input clk_clone3;
   input clk_clone2;
   input clk_clone1;

   // Internal wires
   wire CTS_4;
   wire CTS_3;
   wire CTS_2;
   wire CTS_1;
   wire CTS_7;
   wire CTS_6;
   wire [7:0] bcdCurrHour;
   wire [7:0] bcdCurrMin;
   wire [7:0] bcdCurrSec;
   wire enable_7seg;
   wire last_seconds_clk;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_212;
   wire n_213;
   wire n_214;
   wire n_215;
   wire n_216;
   wire n_217;
   wire n_218;
   wire n_219;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_223;
   wire n_224;
   wire n_225;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_230;
   wire n_231;
   wire n_232;
   wire n_233;
   wire n_234;
   wire n_235;
   wire n_236;
   wire n_237;
   wire n_238;
   wire n_239;
   wire n_240;
   wire n_241;
   wire n_242;
   wire n_243;
   wire n_244;
   wire n_245;
   wire n_246;
   wire n_247;
   wire n_248;
   wire n_249;
   wire n_250;
   wire n_251;
   wire n_252;
   wire n_253;
   wire n_254;
   wire n_255;
   wire n_256;
   wire n_257;
   wire n_258;
   wire n_259;
   wire n_260;
   wire n_261;
   wire n_262;
   wire n_263;
   wire n_264;
   wire n_265;
   wire n_266;
   wire n_267;
   wire n_268;
   wire n_269;
   wire n_270;
   wire n_271;
   wire n_272;
   wire n_273;
   wire n_274;
   wire n_275;
   wire n_276;
   wire n_277;
   wire n_278;
   wire n_279;
   wire n_280;
   wire n_281;
   wire n_282;
   wire n_283;
   wire n_284;
   wire n_285;
   wire n_286;
   wire n_287;
   wire n_288;
   wire n_289;
   wire n_290;
   wire n_291;
   wire n_292;
   wire n_293;
   wire n_294;
   wire n_295;
   wire n_296;
   wire n_297;
   wire n_298;
   wire n_299;
   wire n_300;
   wire n_301;
   wire n_302;
   wire n_303;
   wire n_304;
   wire n_305;
   wire n_306;
   wire n_307;
   wire n_308;
   wire n_309;
   wire n_310;
   wire n_311;
   wire n_312;
   wire n_313;
   wire n_314;

   ANTENNA DIODE_8 (.A(display_h1[3]));
   ANTENNA DIODE_7 (.A(display_h1[1]));
   ANTENNA DIODE_6 (.A(display_s1[3]));
   ANTENNA DIODE_5 (.A(display_m2[1]));
   ANTENNA DIODE_4 (.A(display_m2[3]));
   ANTENNA DIODE_3 (.A(display_h1[5]));
   ANTENNA DIODE_2 (.A(display_m1[4]));
   ANTENNA DIODE_1 (.A(display_m1[0]));
   BUFX1 CTS_ccl_a_buf_00018 (.Z(CTS_4),
	.A(clk));
   BUFX1 CTS_ccl_a_buf_00017 (.Z(CTS_3),
	.A(clk));
   BUFX1 CTS_ccl_a_buf_00016 (.Z(CTS_2),
	.A(clk));
   BUFX1 CTS_ccl_a_buf_00015 (.Z(CTS_1),
	.A(clk));
   BUFX1 CTS_ccl_a_buf_00014 (.Z(CTS_7),
	.A(clk));
   BUFX1 CTS_ccl_a_buf_00013 (.Z(CTS_6),
	.A(clk));
   binToBCD bcdCurrH (.clk(clk),
	.rst(reset),
	.bin(current_h),
	.BCD(bcdCurrHour));
   binToBCD_SPC_1 bcdCurrM (.clk(clk),
	.rst(reset),
	.bin(current_m),
	.BCD(bcdCurrMin));
   binToBCD_SPC_2 bcdCurrS (.clk(clk),
	.rst(reset),
	.bin(current_s),
	.BCD(bcdCurrSec));
   DFFQX1 \display_h1_reg[0]  (.Q(display_h1[0]),
	.CLK(CTS_3),
	.D(n_303));
   DFFQX1 \display_h1_reg[1]  (.Q(display_h1[1]),
	.CLK(clk_clone1),
	.D(n_275));
   DFFQX1 \display_h1_reg[2]  (.Q(display_h1[2]),
	.CLK(CTS_4),
	.D(n_274));
   DFFQX1 \display_h1_reg[3]  (.Q(display_h1[3]),
	.CLK(clk_clone1),
	.D(n_314));
   DFFQX1 \display_h1_reg[4]  (.Q(display_h1[4]),
	.CLK(CTS_4),
	.D(n_287));
   DFFQX1 \display_h1_reg[5]  (.Q(display_h1[5]),
	.CLK(clk_clone1),
	.D(n_310));
   DFFQX1 \display_h1_reg[6]  (.Q(display_h1[6]),
	.CLK(CTS_4),
	.D(n_283));
   DFFQX1 \display_h2_reg[0]  (.Q(display_h2[0]),
	.CLK(CTS_4),
	.D(n_306));
   DFFQX1 \display_h2_reg[1]  (.Q(display_h2[1]),
	.CLK(CTS_3),
	.D(n_277));
   DFFQX1 \display_h2_reg[2]  (.Q(display_h2[2]),
	.CLK(CTS_7),
	.D(n_276));
   DFFQX1 \display_h2_reg[3]  (.Q(display_h2[3]),
	.CLK(CTS_4),
	.D(n_307));
   DFFQX1 \display_h2_reg[4]  (.Q(display_h2[4]),
	.CLK(clk_clone2),
	.D(n_273));
   DFFQX1 \display_h2_reg[5]  (.Q(display_h2[5]),
	.CLK(CTS_3),
	.D(n_313));
   DFFQX1 \display_h2_reg[6]  (.Q(display_h2[6]),
	.CLK(CTS_2),
	.D(n_288));
   DFFQX1 \display_m1_reg[0]  (.Q(display_m1[0]),
	.CLK(CTS_4),
	.D(n_304));
   DFFQX1 \display_m1_reg[1]  (.Q(display_m1[1]),
	.CLK(CTS_2),
	.D(n_286));
   DFFQX1 \display_m1_reg[2]  (.Q(display_m1[2]),
	.CLK(CTS_7),
	.D(n_285));
   DFFQX1 \display_m1_reg[3]  (.Q(display_m1[3]),
	.CLK(clk_clone1),
	.D(n_312));
   DFFQX1 \display_m1_reg[4]  (.Q(display_m1[4]),
	.CLK(CTS_4),
	.D(n_284));
   DFFQX1 \display_m1_reg[5]  (.Q(display_m1[5]),
	.CLK(CTS_3),
	.D(n_311));
   DFFQX1 \display_m1_reg[6]  (.Q(display_m1[6]),
	.CLK(CTS_2),
	.D(n_282));
   DFFQX1 \display_m2_reg[0]  (.Q(display_m2[0]),
	.CLK(CTS_7),
	.D(n_305));
   DFFQX1 \display_m2_reg[1]  (.Q(display_m2[1]),
	.CLK(CTS_6),
	.D(n_290));
   DFFQX1 \display_m2_reg[2]  (.Q(display_m2[2]),
	.CLK(CTS_2),
	.D(n_280));
   DFFQX1 \display_m2_reg[3]  (.Q(display_m2[3]),
	.CLK(CTS_2),
	.D(n_309));
   DFFQX1 \display_m2_reg[4]  (.Q(display_m2[4]),
	.CLK(CTS_7),
	.D(n_279));
   DFFQX1 \display_m2_reg[5]  (.Q(display_m2[5]),
	.CLK(CTS_3),
	.D(n_308));
   DFFQX1 \display_m2_reg[6]  (.Q(display_m2[6]),
	.CLK(CTS_2),
	.D(n_278));
   DFFQX1 \display_s1_reg[0]  (.Q(display_s1[0]),
	.CLK(CTS_7),
	.D(n_298));
   DFFQX1 \display_s1_reg[1]  (.Q(display_s1[1]),
	.CLK(CTS_6),
	.D(n_254));
   DFFQX1 \display_s1_reg[2]  (.Q(display_s1[2]),
	.CLK(CTS_1),
	.D(n_253));
   DFFQX1 \display_s1_reg[3]  (.Q(display_s1[3]),
	.CLK(CTS_1),
	.D(n_299));
   DFFQX1 \display_s1_reg[4]  (.Q(display_s1[4]),
	.CLK(CTS_7),
	.D(n_214));
   DFFQX1 \display_s1_reg[5]  (.Q(display_s1[5]),
	.CLK(CTS_6),
	.D(n_300));
   DFFQX1 \display_s1_reg[6]  (.Q(display_s1[6]),
	.CLK(CTS_1),
	.D(n_251));
   DFFQX1 \display_s2_reg[0]  (.Q(display_s2[0]),
	.CLK(CTS_1),
	.D(n_301));
   DFFQX1 \display_s2_reg[1]  (.Q(display_s2[1]),
	.CLK(CTS_7),
	.D(n_249));
   DFFQX1 \display_s2_reg[2]  (.Q(display_s2[2]),
	.CLK(CTS_6),
	.D(n_248));
   DFFQX1 \display_s2_reg[3]  (.Q(display_s2[3]),
	.CLK(CTS_1),
	.D(n_281));
   DFFQX1 \display_s2_reg[4]  (.Q(display_s2[4]),
	.CLK(CTS_1),
	.D(n_211));
   DFFQX1 \display_s2_reg[5]  (.Q(display_s2[5]),
	.CLK(CTS_7),
	.D(n_289));
   DFFQX1 \display_s2_reg[6]  (.Q(display_s2[6]),
	.CLK(CTS_6),
	.D(n_245));
   DFFQSRX1 enable_7seg_reg (.Q(enable_7seg),
	.CLK(clk_clone3),
	.D(n_200),
	.RESETB(p2),
	.SETB(1'b1));
   DFFQX1 last_seconds_clk_reg (.Q(last_seconds_clk),
	.CLK(clk_clone1),
	.D(n_199));
   NAND3X1 g5898__2398 (.Z(n_314),
	.A(n_30),
	.B(n_271),
	.C(n_295));
   NAND3X1 g5899__5107 (.Z(n_313),
	.A(n_66),
	.B(n_296),
	.C(n_268));
   NAND3X1 g5904__6260 (.Z(n_312),
	.A(n_38),
	.B(n_271),
	.C(n_294));
   NAND3X1 g5905__4319 (.Z(n_311),
	.A(n_58),
	.B(n_292),
	.C(n_272));
   NAND3X1 g5906__8428 (.Z(n_310),
	.A(n_39),
	.B(n_302),
	.C(n_272));
   NAND3X1 g5907__5526 (.Z(n_309),
	.A(n_74),
	.B(n_259),
	.C(n_291));
   NAND3X1 g5908__6783 (.Z(n_308),
	.A(n_15),
	.B(n_293),
	.C(n_268));
   NAND3X1 g5909__3680 (.Z(n_307),
	.A(n_84),
	.B(n_259),
	.C(n_297));
   NAND3X1 g5923__1617 (.Z(n_306),
	.A(n_20),
	.B(n_270),
	.C(n_263));
   NAND3X1 g5924__2802 (.Z(n_305),
	.A(n_42),
	.B(n_270),
	.C(n_260));
   NAND3X1 g5925__1705 (.Z(n_304),
	.A(n_61),
	.B(n_269),
	.C(n_262));
   NAND3X1 g5926__5122 (.Z(n_303),
	.A(n_75),
	.B(n_269),
	.C(n_261));
   NAND2X1 g5936__8246 (.Z(n_302),
	.A(n_192),
	.B(n_267));
   NAND2X1 g5937__7098 (.Z(n_301),
	.A(n_72),
	.B(n_250));
   NAND2X1 g5938__6131 (.Z(n_300),
	.A(n_28),
	.B(n_252));
   NAND2X1 g5939__1881 (.Z(n_299),
	.A(n_16),
	.B(n_247));
   NAND2X1 g5940__5115 (.Z(n_298),
	.A(n_29),
	.B(n_255));
   NAND2X1 g5941__7482 (.Z(n_297),
	.A(n_192),
	.B(n_244));
   NAND2X1 g5942__4733 (.Z(n_296),
	.A(n_192),
	.B(n_264));
   NAND2X1 g5943__6161 (.Z(n_295),
	.A(n_192),
	.B(n_265));
   NAND2X1 g5944__9315 (.Z(n_294),
	.A(n_193),
	.B(n_266));
   NAND2X1 g5945__9945 (.Z(n_293),
	.A(n_193),
	.B(n_256));
   NAND2X1 g5946__2883 (.Z(n_292),
	.A(n_193),
	.B(n_258));
   NAND2X1 g5947__2346 (.Z(n_291),
	.A(n_193),
	.B(n_257));
   NAND3X1 g5954__1666 (.Z(n_290),
	.A(n_60),
	.B(n_242),
	.C(n_225));
   NAND2X1 g5955__7410 (.Z(n_289),
	.A(n_37),
	.B(n_246));
   NAND3X1 g5956__6417 (.Z(n_288),
	.A(n_55),
	.B(n_237),
	.C(n_206));
   NAND3X1 g5957__5477 (.Z(n_287),
	.A(n_59),
	.B(n_231),
	.C(n_223));
   NAND3X1 g5958__2398 (.Z(n_286),
	.A(n_51),
	.B(n_239),
	.C(n_222));
   NAND3X1 g5959__5107 (.Z(n_285),
	.A(n_46),
	.B(n_241),
	.C(n_229));
   NAND3X1 g5960__6260 (.Z(n_284),
	.A(n_45),
	.B(n_231),
	.C(n_221));
   NAND3X1 g5961__4319 (.Z(n_283),
	.A(n_21),
	.B(n_234),
	.C(n_202));
   NAND3X1 g5962__8428 (.Z(n_282),
	.A(n_50),
	.B(n_234),
	.C(n_203));
   NAND2X1 g5963__5526 (.Z(n_281),
	.A(n_23),
	.B(n_243));
   NAND3X1 g5964__6783 (.Z(n_280),
	.A(n_27),
	.B(n_240),
	.C(n_207));
   NAND3X1 g5965__3680 (.Z(n_279),
	.A(n_48),
	.B(n_236),
	.C(n_230));
   NAND3X1 g5966__1617 (.Z(n_278),
	.A(n_62),
	.B(n_237),
	.C(n_201));
   NAND3X1 g5967__2802 (.Z(n_277),
	.A(n_69),
	.B(n_242),
	.C(n_226));
   NAND3X1 g5968__1705 (.Z(n_276),
	.A(n_22),
	.B(n_240),
	.C(n_213));
   NAND3X1 g5969__5122 (.Z(n_275),
	.A(n_25),
	.B(n_239),
	.C(n_227));
   NAND3X1 g5970__8246 (.Z(n_274),
	.A(n_65),
	.B(n_241),
	.C(n_228));
   NAND3X1 g5971__7098 (.Z(n_273),
	.A(n_73),
	.B(n_236),
	.C(n_224));
   NAND3X1 g5972__6131 (.Z(n_267),
	.A(n_174),
	.B(n_141),
	.C(n_107));
   NAND3X1 g5973__1881 (.Z(n_266),
	.A(n_168),
	.B(n_116),
	.C(n_136));
   NAND3X1 g5974__5115 (.Z(n_265),
	.A(n_170),
	.B(n_141),
	.C(n_107));
   NAND3X1 g5975__7482 (.Z(n_264),
	.A(n_176),
	.B(n_117),
	.C(n_109));
   NAND2X1 g5976__4733 (.Z(n_263),
	.A(n_192),
	.B(n_208));
   NAND2X1 g5977__6161 (.Z(n_262),
	.A(n_193),
	.B(n_210));
   NAND2X1 g5978__9315 (.Z(n_261),
	.A(n_192),
	.B(n_218));
   NAND2X1 g5979__9945 (.Z(n_260),
	.A(n_193),
	.B(n_209));
   OR2X1 g5980__2883 (.Z(n_272),
	.A(n_235),
	.B(n_182));
   OR2X1 g5981__2346 (.Z(n_271),
	.A(n_219),
	.B(n_182));
   NAND2X1 g5982__1666 (.Z(n_270),
	.A(n_181),
	.B(n_232));
   NAND2X1 g5983__7410 (.Z(n_269),
	.A(n_181),
	.B(n_233));
   OR2X1 g5984__6417 (.Z(n_268),
	.A(n_238),
	.B(n_182));
   NAND3X1 g5989__5477 (.Z(n_258),
	.A(n_175),
	.B(n_116),
	.C(n_136));
   NAND3X1 g5990__2398 (.Z(n_257),
	.A(n_167),
	.B(n_118),
	.C(n_108));
   NAND3X1 g5991__5107 (.Z(n_256),
	.A(n_173),
	.B(n_118),
	.C(n_108));
   NAND2X1 g5992__6260 (.Z(n_255),
	.A(n_150),
	.B(n_233));
   NAND2X1 g5993__4319 (.Z(n_254),
	.A(n_40),
	.B(n_216));
   NAND2X1 g5994__8428 (.Z(n_253),
	.A(n_44),
	.B(n_217));
   OR2X1 g5995__5526 (.Z(n_252),
	.A(n_235),
	.B(n_149));
   NAND2X1 g5996__6783 (.Z(n_251),
	.A(n_17),
	.B(n_205));
   NAND2X1 g5997__3680 (.Z(n_250),
	.A(n_150),
	.B(n_232));
   NAND2X1 g5998__1617 (.Z(n_249),
	.A(n_18),
	.B(n_212));
   NAND2X1 g5999__2802 (.Z(n_248),
	.A(n_63),
	.B(n_215));
   OR2X1 g6000__1705 (.Z(n_247),
	.A(n_219),
	.B(n_149));
   OR2X1 g6001__5122 (.Z(n_246),
	.A(n_238),
	.B(n_149));
   NAND2X1 g6002__8246 (.Z(n_245),
	.A(n_41),
	.B(n_204));
   NAND3X1 g6003__7098 (.Z(n_244),
	.A(n_171),
	.B(n_117),
	.C(n_109));
   NAND2X1 g6004__6131 (.Z(n_243),
	.A(n_150),
	.B(n_220));
   NAND2X1 g6005__1881 (.Z(n_259),
	.A(n_181),
	.B(n_220));
   NAND2X1 g6006__5115 (.Z(n_230),
	.A(n_193),
	.B(n_147));
   NAND3X1 g6007__7482 (.Z(n_229),
	.A(n_193),
	.B(n_164),
	.C(n_4));
   NAND3X1 g6008__4733 (.Z(n_228),
	.A(n_192),
	.B(n_166),
	.C(n_3));
   NAND2X1 g6009__6161 (.Z(n_227),
	.A(n_192),
	.B(n_178));
   NAND2X1 g6010__9315 (.Z(n_226),
	.A(n_192),
	.B(n_179));
   NAND2X1 g6011__9945 (.Z(n_225),
	.A(n_193),
	.B(n_189));
   NAND2X1 g6012__2883 (.Z(n_224),
	.A(n_192),
	.B(n_148));
   NAND2X1 g6013__2346 (.Z(n_223),
	.A(n_192),
	.B(n_144));
   NAND2X1 g6014__1666 (.Z(n_222),
	.A(n_193),
	.B(n_185));
   NAND2X1 g6015__7410 (.Z(n_221),
	.A(n_193),
	.B(n_145));
   NAND2X1 g6016__6417 (.Z(n_242),
	.A(n_181),
	.B(n_183));
   NAND2X1 g6017__5477 (.Z(n_241),
	.A(n_181),
	.B(n_197));
   NAND2X1 g6018__2398 (.Z(n_240),
	.A(n_181),
	.B(n_198));
   NAND2X1 g6019__5107 (.Z(n_239),
	.A(n_181),
	.B(n_194));
   NOR2X1 g6020__6260 (.Z(n_238),
	.A(n_159),
	.B(n_177));
   NAND2X1 g6021__4319 (.Z(n_237),
	.A(n_181),
	.B(n_195));
   NAND2X1 g6022__8428 (.Z(n_236),
	.A(n_181),
	.B(n_152));
   NOR2X1 g6023__5526 (.Z(n_235),
	.A(n_158),
	.B(n_180));
   NAND2X1 g6024__6783 (.Z(n_234),
	.A(n_181),
	.B(n_196));
   NAND3X1 g6025__3680 (.Z(n_233),
	.A(n_157),
	.B(n_138),
	.C(n_49));
   NAND3X1 g6026__1617 (.Z(n_232),
	.A(n_160),
	.B(n_114),
	.C(n_47));
   NAND2X1 g6027__2802 (.Z(n_231),
	.A(n_181),
	.B(n_153));
   NAND3X1 g6028__1705 (.Z(n_218),
	.A(n_146),
	.B(n_110),
	.C(n_107));
   NAND2X1 g6029__5122 (.Z(n_217),
	.A(n_150),
	.B(n_197));
   NAND2X1 g6030__8246 (.Z(n_216),
	.A(n_150),
	.B(n_194));
   NAND2X1 g6031__7098 (.Z(n_215),
	.A(n_150),
	.B(n_198));
   NAND2X1 g6032__6131 (.Z(n_214),
	.A(n_76),
	.B(n_187));
   NAND3X1 g6033__1881 (.Z(n_213),
	.A(n_192),
	.B(n_165),
	.C(n_9));
   NAND2X1 g6034__5115 (.Z(n_212),
	.A(n_150),
	.B(n_183));
   NAND2X1 g6035__7482 (.Z(n_211),
	.A(n_35),
	.B(n_191));
   NAND3X1 g6036__4733 (.Z(n_210),
	.A(n_156),
	.B(n_137),
	.C(n_136));
   NAND3X1 g6037__6161 (.Z(n_209),
	.A(n_155),
	.B(n_111),
	.C(n_108));
   NAND3X1 g6038__9315 (.Z(n_208),
	.A(n_143),
	.B(n_115),
	.C(n_109));
   NAND3X1 g6039__9945 (.Z(n_207),
	.A(n_193),
	.B(n_162),
	.C(n_8));
   NAND2X1 g6040__2883 (.Z(n_206),
	.A(n_192),
	.B(n_188));
   NAND2X1 g6041__2346 (.Z(n_205),
	.A(n_150),
	.B(n_196));
   NAND2X1 g6042__1666 (.Z(n_204),
	.A(n_150),
	.B(n_195));
   NAND2X1 g6043__7410 (.Z(n_203),
	.A(n_193),
	.B(n_184));
   NAND2X1 g6044__6417 (.Z(n_202),
	.A(n_192),
	.B(n_186));
   NAND2X1 g6045__5477 (.Z(n_201),
	.A(n_193),
	.B(n_190));
   XOR2X1 g6046__2398 (.Z(n_200),
	.A(enable_7seg),
	.B(n_142));
   MUX2X1 g6047__5107 (.Z(n_199),
	.A(seconds_clk),
	.B(last_seconds_clk),
	.S(reset));
   NAND2X1 g6048__6260 (.Z(n_220),
	.A(n_169),
	.B(n_160));
   NOR2X1 g6049__4319 (.Z(n_219),
	.A(n_158),
	.B(n_172));
   NAND2X1 g6050__8428 (.Z(n_191),
	.A(n_150),
	.B(n_152));
   OR2X1 g6051__5526 (.Z(n_190),
	.A(n_131),
	.B(n_162));
   NAND3X1 g6052__6783 (.Z(n_189),
	.A(n_111),
	.B(n_104),
	.C(n_108));
   OR2X1 g6053__3680 (.Z(n_188),
	.A(n_135),
	.B(n_165));
   NAND2X1 g6054__1617 (.Z(n_187),
	.A(n_150),
	.B(n_153));
   OR2X1 g6055__2802 (.Z(n_186),
	.A(n_132),
	.B(n_166));
   NAND3X1 g6056__1705 (.Z(n_185),
	.A(n_137),
	.B(n_124),
	.C(n_136));
   OR2X1 g6057__5122 (.Z(n_184),
	.A(n_134),
	.B(n_164));
   NOR2X1 g6058__8246 (.Z(n_198),
	.A(bcdCurrSec[4]),
	.B(n_151));
   NOR2X1 g6059__7098 (.Z(n_197),
	.A(bcdCurrSec[0]),
	.B(n_163));
   NAND2X1 g6060__6131 (.Z(n_196),
	.A(n_163),
	.B(n_133));
   NAND2X1 g6061__1881 (.Z(n_195),
	.A(n_151),
	.B(n_126));
   NAND3X1 g6062__5115 (.Z(n_194),
	.A(n_138),
	.B(n_99),
	.C(n_140));
   AND2X1 g6063__7482 (.Z(n_193),
	.A(n_161),
	.B(n_128));
   AND2X1 g6064__4733 (.Z(n_192),
	.A(n_161),
	.B(n_70));
   INVX2 g6065 (.Z(n_181),
	.A(n_182));
   MUX2X1 g6066__6161 (.Z(n_180),
	.A(n_139),
	.B(n_123),
	.S(bcdCurrSec[0]));
   NAND3X1 g6067__9315 (.Z(n_179),
	.A(n_115),
	.B(n_101),
	.C(n_109));
   NAND3X1 g6068__9945 (.Z(n_178),
	.A(n_110),
	.B(n_100),
	.C(n_107));
   MUX2X1 g6069__2883 (.Z(n_177),
	.A(n_113),
	.B(n_130),
	.S(bcdCurrSec[4]));
   MUX2X1 g6070__2346 (.Z(n_176),
	.A(n_129),
	.B(n_115),
	.S(n_9));
   MUX2X1 g6071__1666 (.Z(n_175),
	.A(n_120),
	.B(n_137),
	.S(n_4));
   MUX2X1 g6072__7410 (.Z(n_174),
	.A(n_127),
	.B(n_110),
	.S(n_3));
   MUX2X1 g6073__6417 (.Z(n_173),
	.A(n_105),
	.B(n_111),
	.S(n_8));
   MUX2X1 g6074__5477 (.Z(n_172),
	.A(n_94),
	.B(n_139),
	.S(bcdCurrSec[0]));
   MUX2X1 g6075__2398 (.Z(n_171),
	.A(n_89),
	.B(n_115),
	.S(bcdCurrHour[4]));
   MUX2X1 g6076__5107 (.Z(n_170),
	.A(n_86),
	.B(n_110),
	.S(bcdCurrHour[0]));
   MUX2X1 g6077__6260 (.Z(n_169),
	.A(n_91),
	.B(n_114),
	.S(bcdCurrSec[4]));
   MUX2X1 g6078__4319 (.Z(n_168),
	.A(n_87),
	.B(n_137),
	.S(bcdCurrMin[0]));
   MUX2X1 g6079__8428 (.Z(n_167),
	.A(n_92),
	.B(n_111),
	.S(bcdCurrMin[4]));
   NAND3X1 g6080__5526 (.Z(n_183),
	.A(n_114),
	.B(n_102),
	.C(n_112));
   NAND3X1 g6081__6783 (.Z(n_182),
	.A(n_106),
	.B(n_125),
	.C(p2));
   INVX2 g6082 (.Z(n_160),
	.A(n_159));
   INVX2 g6083 (.Z(n_157),
	.A(n_158));
   AND2X1 g6084__3680 (.Z(n_156),
	.A(n_116),
	.B(n_33));
   AND2X1 g6085__1617 (.Z(n_155),
	.A(n_118),
	.B(n_34));
   NAND2X1 g6086__2802 (.Z(n_166),
	.A(n_107),
	.B(n_86));
   NAND2X1 g6087__1705 (.Z(n_165),
	.A(n_109),
	.B(n_89));
   NAND2X1 g6088__5122 (.Z(n_164),
	.A(n_136),
	.B(n_87));
   AND2X1 g6090__8246 (.Z(n_163),
	.A(n_140),
	.B(n_95));
   NAND2X1 g6091__7098 (.Z(n_162),
	.A(n_108),
	.B(n_92));
   NOR2X1 g6092__6131 (.Z(n_161),
	.A(reset),
	.B(n_103));
   NAND2X1 g6093__1881 (.Z(n_159),
	.A(n_98),
	.B(n_112));
   NAND2X1 g6094__5115 (.Z(n_158),
	.A(n_121),
	.B(n_140));
   INVX2 g6095 (.Z(n_149),
	.A(n_150));
   NAND3X1 g6096__7482 (.Z(n_148),
	.A(n_109),
	.B(n_85),
	.C(n_82));
   NAND3X1 g6097__4733 (.Z(n_147),
	.A(n_108),
	.B(n_90),
	.C(n_77));
   AND2X1 g6098__6161 (.Z(n_146),
	.A(n_141),
	.B(n_54));
   NAND3X1 g6099__9315 (.Z(n_145),
	.A(n_136),
	.B(n_88),
	.C(n_80));
   NAND3X1 g6100__9945 (.Z(n_144),
	.A(n_107),
	.B(n_93),
	.C(n_79));
   AND2X1 g6101__2883 (.Z(n_143),
	.A(n_117),
	.B(n_19));
   AND2X1 g6102__2346 (.Z(n_142),
	.A(n_119),
	.B(seconds_clk));
   NAND3X1 g6103__1666 (.Z(n_153),
	.A(n_140),
	.B(n_97),
	.C(n_78));
   NAND3X1 g6104__7410 (.Z(n_152),
	.A(n_112),
	.B(n_96),
	.C(n_81));
   AND2X1 g6105__6417 (.Z(n_151),
	.A(n_112),
	.B(n_91));
   NOR2X1 g6106__5477 (.Z(n_150),
	.A(reset),
	.B(n_122));
   INVX2 g6107 (.Z(n_138),
	.A(n_139));
   NOR2X1 g6108__2398 (.Z(n_135),
	.A(n_9),
	.B(n_85));
   NOR2X1 g6109__5107 (.Z(n_134),
	.A(n_4),
	.B(n_88));
   OR2X1 g6110__6260 (.Z(n_133),
	.A(n_1),
	.B(n_97));
   NOR2X1 g6111__4319 (.Z(n_132),
	.A(n_3),
	.B(n_93));
   NOR2X1 g6112__8428 (.Z(n_131),
	.A(n_8),
	.B(n_90));
   NAND2X1 g6113__5526 (.Z(n_130),
	.A(n_91),
	.B(n_67));
   AND2X1 g6114__6783 (.Z(n_129),
	.A(n_89),
	.B(n_64));
   NAND3X1 g6115__3680 (.Z(n_128),
	.A(state[1]),
	.B(n_13),
	.C(p1));
   AND2X1 g6116__1617 (.Z(n_127),
	.A(n_86),
	.B(n_71));
   OR2X1 g6117__2802 (.Z(n_126),
	.A(n_2),
	.B(n_96));
   NAND2X1 g6118__1705 (.Z(n_125),
	.A(n_68),
	.B(state[1]));
   OR2X1 g6119__5122 (.Z(n_124),
	.A(bcdCurrMin[0]),
	.B(n_88));
   OR2X1 g6120__8246 (.Z(n_123),
	.A(n_52),
	.B(n_94));
   NOR2X1 g6121__7098 (.Z(n_122),
	.A(n_83),
	.B(n_56));
   OR2X1 g6122__6131 (.Z(n_121),
	.A(bcdCurrSec[2]),
	.B(n_95));
   AND2X1 g6123__1881 (.Z(n_120),
	.A(n_87),
	.B(n_36));
   OR2X1 g6124__5115 (.Z(n_141),
	.A(bcdCurrHour[2]),
	.B(n_86));
   NAND2X1 g6125__7482 (.Z(n_140),
	.A(n_43),
	.B(bcdCurrSec[3]));
   NOR2X1 g6126__4733 (.Z(n_139),
	.A(bcdCurrSec[1]),
	.B(n_97));
   OR2X1 g6127__6161 (.Z(n_137),
	.A(bcdCurrMin[1]),
	.B(n_88));
   NAND2X1 g6128__9315 (.Z(n_136),
	.A(n_53),
	.B(bcdCurrMin[3]));
   INVX2 g6129 (.Z(n_114),
	.A(n_113));
   XOR2X1 g6130__9945 (.Z(n_106),
	.A(state[1]),
	.B(state[2]));
   AND2X1 g6131__2883 (.Z(n_105),
	.A(n_92),
	.B(n_26));
   OR2X1 g6132__2346 (.Z(n_104),
	.A(bcdCurrMin[4]),
	.B(n_90));
   MUX2X1 g6133__1666 (.Z(n_103),
	.A(state[2]),
	.B(state[0]),
	.S(state[1]));
   OR2X1 g6134__7410 (.Z(n_102),
	.A(bcdCurrSec[4]),
	.B(n_96));
   OR2X1 g6135__6417 (.Z(n_101),
	.A(bcdCurrHour[4]),
	.B(n_85));
   OR2X1 g6136__5477 (.Z(n_100),
	.A(bcdCurrHour[0]),
	.B(n_93));
   OR2X1 g6137__2398 (.Z(n_99),
	.A(bcdCurrSec[0]),
	.B(n_97));
   OR2X1 g6138__5107 (.Z(n_98),
	.A(bcdCurrSec[6]),
	.B(n_91));
   OR2X1 g6140__6260 (.Z(n_118),
	.A(bcdCurrMin[6]),
	.B(n_92));
   OR2X1 g6141__4319 (.Z(n_117),
	.A(bcdCurrHour[6]),
	.B(n_89));
   OR2X1 g6142__8428 (.Z(n_116),
	.A(bcdCurrMin[2]),
	.B(n_87));
   OR2X1 g6143__5526 (.Z(n_115),
	.A(bcdCurrHour[5]),
	.B(n_85));
   NOR2X1 g6144__6783 (.Z(n_113),
	.A(bcdCurrSec[5]),
	.B(n_96));
   NAND2X1 g6145__3680 (.Z(n_112),
	.A(n_57),
	.B(bcdCurrSec[7]));
   OR2X1 g6146__1617 (.Z(n_111),
	.A(bcdCurrMin[5]),
	.B(n_90));
   OR2X1 g6147__2802 (.Z(n_110),
	.A(bcdCurrHour[1]),
	.B(n_93));
   NAND2X1 g6148__1705 (.Z(n_109),
	.A(n_31),
	.B(bcdCurrHour[7]));
   NAND2X1 g6149__5122 (.Z(n_108),
	.A(n_32),
	.B(bcdCurrMin[7]));
   NAND2X1 g6150__8246 (.Z(n_107),
	.A(n_24),
	.B(bcdCurrHour[3]));
   INVX2 g6151 (.Z(n_94),
	.A(n_95));
   NAND2X1 g6152__7098 (.Z(n_84),
	.A(display_h2[3]),
	.B(reset));
   NOR2X1 g6153__6131 (.Z(n_83),
	.A(n_13),
	.B(state[2]));
   OR2X1 g6154__1881 (.Z(n_82),
	.A(bcdCurrHour[7]),
	.B(n_9));
   OR2X1 g6155__5115 (.Z(n_81),
	.A(bcdCurrSec[7]),
	.B(n_2));
   OR2X1 g6156__7482 (.Z(n_80),
	.A(bcdCurrMin[3]),
	.B(n_4));
   OR2X1 g6157__4733 (.Z(n_79),
	.A(bcdCurrHour[3]),
	.B(n_3));
   OR2X1 g6158__6161 (.Z(n_78),
	.A(bcdCurrSec[3]),
	.B(n_1));
   OR2X1 g6159__9315 (.Z(n_77),
	.A(bcdCurrMin[7]),
	.B(n_8));
   NAND2X1 g6160__9945 (.Z(n_76),
	.A(display_s1[4]),
	.B(reset));
   NAND2X1 g6161__2883 (.Z(n_75),
	.A(display_h1[0]),
	.B(reset));
   NAND2X1 g6162__2346 (.Z(n_74),
	.A(display_m2[3]),
	.B(reset));
   NAND2X1 g6163__1666 (.Z(n_73),
	.A(display_h2[4]),
	.B(reset));
   NAND2X1 g6164__7410 (.Z(n_72),
	.A(display_s2[0]),
	.B(reset));
   OR2X1 g6165__6417 (.Z(n_71),
	.A(bcdCurrHour[2]),
	.B(bcdCurrHour[3]));
   NAND2X1 g6166__5477 (.Z(n_70),
	.A(n_13),
	.B(state[0]));
   NAND2X1 g6167__2398 (.Z(n_69),
	.A(display_h2[1]),
	.B(reset));
   NAND2X1 g6168__5107 (.Z(n_68),
	.A(state[0]),
	.B(enable_7seg));
   OR2X1 g6169__6260 (.Z(n_67),
	.A(bcdCurrSec[6]),
	.B(bcdCurrSec[7]));
   NAND2X1 g6170__4319 (.Z(n_66),
	.A(display_h2[5]),
	.B(reset));
   NAND2X1 g6171__8428 (.Z(n_65),
	.A(display_h1[2]),
	.B(reset));
   OR2X1 g6172__5526 (.Z(n_64),
	.A(bcdCurrHour[6]),
	.B(bcdCurrHour[7]));
   NAND2X1 g6173__6783 (.Z(n_63),
	.A(display_s2[2]),
	.B(reset));
   NAND2X1 g6174__3680 (.Z(n_62),
	.A(display_m2[6]),
	.B(reset));
   NAND2X1 g6175__1617 (.Z(n_61),
	.A(display_m1[0]),
	.B(reset));
   NAND2X1 g6176__2802 (.Z(n_60),
	.A(display_m2[1]),
	.B(reset));
   NAND2X1 g6177__1705 (.Z(n_59),
	.A(display_h1[4]),
	.B(reset));
   NAND2X1 g6178__5122 (.Z(n_58),
	.A(display_m1[5]),
	.B(reset));
   NOR2X1 g6179__8246 (.Z(n_57),
	.A(bcdCurrSec[5]),
	.B(bcdCurrSec[6]));
   NAND2X1 g6180__7098 (.Z(n_56),
	.A(state[1]),
	.B(state[0]));
   NAND2X1 g6181__6131 (.Z(n_97),
	.A(n_5),
	.B(bcdCurrSec[2]));
   NAND2X1 g6182__1881 (.Z(n_96),
	.A(n_11),
	.B(bcdCurrSec[6]));
   NAND2X1 g6183__5115 (.Z(n_95),
	.A(n_5),
	.B(bcdCurrSec[1]));
   NAND2X1 g6184__7482 (.Z(n_93),
	.A(n_12),
	.B(bcdCurrHour[2]));
   NAND2X1 g6185__4733 (.Z(n_92),
	.A(n_14),
	.B(bcdCurrMin[5]));
   NAND2X1 g6186__6161 (.Z(n_91),
	.A(n_11),
	.B(bcdCurrSec[5]));
   NAND2X1 g6187__9315 (.Z(n_90),
	.A(n_14),
	.B(bcdCurrMin[6]));
   NAND2X1 g6188__9945 (.Z(n_89),
	.A(n_10),
	.B(bcdCurrHour[5]));
   NAND2X1 g6189__2883 (.Z(n_88),
	.A(n_6),
	.B(bcdCurrMin[2]));
   NAND2X1 g6190__2346 (.Z(n_87),
	.A(n_6),
	.B(bcdCurrMin[1]));
   NAND2X1 g6191__1666 (.Z(n_86),
	.A(n_12),
	.B(bcdCurrHour[1]));
   NAND2X1 g6192__7410 (.Z(n_85),
	.A(n_10),
	.B(bcdCurrHour[6]));
   NAND2X1 g6193__6417 (.Z(n_55),
	.A(display_h2[6]),
	.B(reset));
   NAND2X1 g6194__5477 (.Z(n_54),
	.A(n_3),
	.B(n_12));
   NOR2X1 g6195__2398 (.Z(n_53),
	.A(bcdCurrMin[1]),
	.B(bcdCurrMin[2]));
   NOR2X1 g6196__5107 (.Z(n_52),
	.A(bcdCurrSec[2]),
	.B(bcdCurrSec[3]));
   NAND2X1 g6197__6260 (.Z(n_51),
	.A(display_m1[1]),
	.B(reset));
   NAND2X1 g6198__4319 (.Z(n_50),
	.A(display_m1[6]),
	.B(reset));
   NAND2X1 g6199__8428 (.Z(n_49),
	.A(n_1),
	.B(n_5));
   NAND2X1 g6200__5526 (.Z(n_48),
	.A(display_m2[4]),
	.B(reset));
   NAND2X1 g6201__6783 (.Z(n_47),
	.A(n_2),
	.B(n_11));
   NAND2X1 g6202__3680 (.Z(n_46),
	.A(display_m1[2]),
	.B(reset));
   NAND2X1 g6203__1617 (.Z(n_45),
	.A(display_m1[4]),
	.B(reset));
   NAND2X1 g6204__2802 (.Z(n_44),
	.A(display_s1[2]),
	.B(reset));
   NOR2X1 g6205__1705 (.Z(n_43),
	.A(bcdCurrSec[1]),
	.B(bcdCurrSec[2]));
   NAND2X1 g6206__5122 (.Z(n_42),
	.A(display_m2[0]),
	.B(reset));
   NAND2X1 g6207__8246 (.Z(n_41),
	.A(display_s2[6]),
	.B(reset));
   NAND2X1 g6208__7098 (.Z(n_40),
	.A(display_s1[1]),
	.B(reset));
   NAND2X1 g6209__6131 (.Z(n_39),
	.A(display_h1[5]),
	.B(reset));
   NAND2X1 g6210__1881 (.Z(n_38),
	.A(display_m1[3]),
	.B(reset));
   NAND2X1 g6211__5115 (.Z(n_37),
	.A(display_s2[5]),
	.B(reset));
   OR2X1 g6212__7482 (.Z(n_36),
	.A(bcdCurrMin[2]),
	.B(bcdCurrMin[3]));
   NAND2X1 g6213__4733 (.Z(n_35),
	.A(display_s2[4]),
	.B(reset));
   NAND2X1 g6214__6161 (.Z(n_34),
	.A(n_8),
	.B(n_14));
   NAND2X1 g6215__9315 (.Z(n_33),
	.A(n_4),
	.B(n_6));
   NOR2X1 g6216__9945 (.Z(n_32),
	.A(bcdCurrMin[5]),
	.B(bcdCurrMin[6]));
   NOR2X1 g6217__2883 (.Z(n_31),
	.A(bcdCurrHour[5]),
	.B(bcdCurrHour[6]));
   NAND2X1 g6218__2346 (.Z(n_30),
	.A(display_h1[3]),
	.B(reset));
   NAND2X1 g6219__1666 (.Z(n_29),
	.A(display_s1[0]),
	.B(reset));
   NAND2X1 g6220__7410 (.Z(n_28),
	.A(display_s1[5]),
	.B(reset));
   NAND2X1 g6221__6417 (.Z(n_27),
	.A(display_m2[2]),
	.B(reset));
   OR2X1 g6222__5477 (.Z(n_26),
	.A(bcdCurrMin[6]),
	.B(bcdCurrMin[7]));
   NAND2X1 g6223__2398 (.Z(n_25),
	.A(display_h1[1]),
	.B(reset));
   NOR2X1 g6224__5107 (.Z(n_24),
	.A(bcdCurrHour[1]),
	.B(bcdCurrHour[2]));
   NAND2X1 g6225__6260 (.Z(n_23),
	.A(display_s2[3]),
	.B(reset));
   NAND2X1 g6226__4319 (.Z(n_22),
	.A(display_h2[2]),
	.B(reset));
   NAND2X1 g6227__8428 (.Z(n_21),
	.A(display_h1[6]),
	.B(reset));
   NAND2X1 g6228__5526 (.Z(n_20),
	.A(display_h2[0]),
	.B(reset));
   NAND2X1 g6229__6783 (.Z(n_19),
	.A(n_9),
	.B(n_10));
   NAND2X1 g6230__3680 (.Z(n_18),
	.A(display_s2[1]),
	.B(reset));
   NAND2X1 g6231__1617 (.Z(n_17),
	.A(display_s1[6]),
	.B(reset));
   NAND2X1 g6232__2802 (.Z(n_16),
	.A(display_s1[3]),
	.B(reset));
   NAND2X1 g6233__1705 (.Z(n_15),
	.A(display_m2[5]),
	.B(reset));
   INVX2 g6255 (.Z(n_14),
	.A(bcdCurrMin[7]));
   INVX2 g6256 (.Z(n_13),
	.A(enable_7seg));
   INVX2 g6257 (.Z(n_12),
	.A(bcdCurrHour[3]));
   INVX2 g6258 (.Z(n_11),
	.A(bcdCurrSec[7]));
   INVX2 g6259 (.Z(n_10),
	.A(bcdCurrHour[7]));
   INVX2 g6260 (.Z(n_9),
	.A(bcdCurrHour[4]));
   INVX2 g6261 (.Z(n_8),
	.A(bcdCurrMin[4]));
   INVX2 g6284 (.Z(n_6),
	.A(bcdCurrMin[3]));
   INVX2 g6285 (.Z(n_5),
	.A(bcdCurrSec[3]));
   INVX2 g6286 (.Z(n_4),
	.A(bcdCurrMin[0]));
   INVX2 g6287 (.Z(n_3),
	.A(bcdCurrHour[0]));
   INVX2 g6288 (.Z(n_2),
	.A(bcdCurrSec[4]));
   INVX2 g6289 (.Z(n_1),
	.A(bcdCurrSec[0]));
   INVX1 g6291 (.Z(n_119),
	.A(last_seconds_clk));
endmodule

module soc_top (
	clk, 
	reset, 
	btn_mode, 
	btn_set, 
	btn_inc, 
	btn_dec, 
	btn_light, 
	h1_6, 
	h1_5, 
	h1_4, 
	h1_3, 
	h1_2, 
	h1_1, 
	h1_0, 
	h0_6, 
	h0_5, 
	h0_4, 
	h0_3, 
	h0_2, 
	h0_1, 
	h0_0, 
	m1_6, 
	m1_5, 
	m1_4, 
	m1_3, 
	m1_2, 
	m1_1, 
	m1_0, 
	m0_6, 
	m0_5, 
	m0_4, 
	m0_3, 
	m0_2, 
	m0_1, 
	m0_0, 
	s1_6, 
	s1_5, 
	s1_4, 
	s1_3, 
	s1_2, 
	s1_1, 
	s1_0, 
	s0_6, 
	s0_5, 
	s0_4, 
	s0_3, 
	s0_2, 
	s0_1, 
	s0_0, 
	colon, 
	light);
   input clk;
   input reset;
   input btn_mode;
   input btn_set;
   input btn_inc;
   input btn_dec;
   input btn_light;
   output h1_6;
   output h1_5;
   output h1_4;
   output h1_3;
   output h1_2;
   output h1_1;
   output h1_0;
   output h0_6;
   output h0_5;
   output h0_4;
   output h0_3;
   output h0_2;
   output h0_1;
   output h0_0;
   output m1_6;
   output m1_5;
   output m1_4;
   output m1_3;
   output m1_2;
   output m1_1;
   output m1_0;
   output m0_6;
   output m0_5;
   output m0_4;
   output m0_3;
   output m0_2;
   output m0_1;
   output m0_0;
   output s1_6;
   output s1_5;
   output s1_4;
   output s1_3;
   output s1_2;
   output s1_1;
   output s1_0;
   output s0_6;
   output s0_5;
   output s0_4;
   output s0_3;
   output s0_2;
   output s0_1;
   output s0_0;
   output colon;
   output light;

   // Internal wires
   wire CTS_10;
   wire CTS_9;
   wire CTS_8;
   wire CTS_7;
   wire CTS_6;
   wire CTS_5;
   wire CTS_4;
   wire CTS_3;
   wire CTS_2;
   wire CTS_1;
   wire CTS_13;
   wire CTS_12;
   wire FE_DBTN1_reset_PAD;
   wire FE_DBTN0_chip_state_2;
   wire [2:0] chip_state;
   wire [5:0] chip_t_seconds;
   wire [5:0] chip_t_minutes;
   wire [5:0] chip_t_hours;
   wire [2:0] chip_fsm_next_state;
   wire [25:0] chip_cd_count;
   wire UNCONNECTED;
   wire UNCONNECTED_HIER_Z;
   wire UNCONNECTED_HIER_Z0;
   wire UNCONNECTED_HIER_Z1;
   wire UNCONNECTED_HIER_Z2;
   wire UNCONNECTED_HIER_Z3;
   wire UNCONNECTED_HIER_Z4;
   wire UNCONNECTED_HIER_Z5;
   wire UNCONNECTED_HIER_Z6;
   wire UNCONNECTED_HIER_Z7;
   wire UNCONNECTED_HIER_Z8;
   wire UNCONNECTED_HIER_Z9;
   wire UNCONNECTED_HIER_Z10;
   wire UNCONNECTED_HIER_Z11;
   wire UNCONNECTED_HIER_Z12;
   wire UNCONNECTED_HIER_Z13;
   wire UNCONNECTED_HIER_Z14;
   wire UNCONNECTED_HIER_Z15;
   wire UNCONNECTED_HIER_Z16;
   wire btn_dec_PAD;
   wire btn_inc_PAD;
   wire btn_light_PAD;
   wire btn_mode_PAD;
   wire btn_set_PAD;
   wire chip_backlight_light_mode;
   wire chip_cd_inc_add_23_19_n_269;
   wire chip_cd_inc_add_23_19_n_272;
   wire chip_cd_inc_add_23_19_n_278;
   wire chip_cd_inc_add_23_19_n_281;
   wire chip_cd_inc_add_23_19_n_284;
   wire chip_cd_inc_add_23_19_n_287;
   wire chip_cd_inc_add_23_19_n_291;
   wire chip_cd_inc_add_23_19_n_292;
   wire chip_cd_inc_add_23_19_n_295;
   wire chip_cd_inc_add_23_19_n_296;
   wire chip_cd_inc_add_23_19_n_301;
   wire chip_cd_inc_add_23_19_n_304;
   wire chip_cd_inc_add_23_19_n_305;
   wire chip_cd_inc_add_23_19_n_306;
   wire chip_cd_inc_add_23_19_n_311;
   wire chip_cd_inc_add_23_19_n_312;
   wire chip_cd_inc_add_23_19_n_315;
   wire chip_cd_inc_add_23_19_n_317;
   wire chip_cd_inc_add_23_19_n_319;
   wire chip_cd_inc_add_23_19_n_321;
   wire chip_cd_inc_add_23_19_n_325;
   wire chip_cd_inc_add_23_19_n_327;
   wire chip_cd_inc_add_23_19_n_328;
   wire chip_cd_inc_add_23_19_n_333;
   wire chip_cd_inc_add_23_19_n_336;
   wire chip_cd_inc_add_23_19_n_338;
   wire chip_cd_inc_add_23_19_n_340;
   wire chip_cd_inc_add_23_19_n_341;
   wire chip_cd_inc_add_23_19_n_345;
   wire chip_cd_inc_add_23_19_n_347;
   wire chip_cd_inc_add_23_19_n_349;
   wire chip_cd_inc_add_23_19_n_350;
   wire chip_cd_inc_add_23_19_n_351;
   wire chip_cd_inc_add_23_19_n_352;
   wire chip_cd_inc_add_23_19_n_355;
   wire chip_cd_inc_add_23_19_n_359;
   wire chip_cd_inc_add_23_19_n_361;
   wire chip_cd_inc_add_23_19_n_362;
   wire chip_cd_inc_add_23_19_n_364;
   wire chip_cd_inc_add_23_19_n_365;
   wire chip_cd_inc_add_23_19_n_367;
   wire chip_cd_inc_add_23_19_n_368;
   wire chip_cd_inc_add_23_19_n_370;
   wire chip_cd_inc_add_23_19_n_371;
   wire chip_cd_inc_add_23_19_n_373;
   wire chip_cd_inc_add_23_19_n_375;
   wire chip_cd_inc_add_23_19_n_397;
   wire chip_cd_n_73;
   wire chip_cd_n_74;
   wire chip_cd_n_75;
   wire chip_cd_n_76;
   wire chip_cd_n_77;
   wire chip_cd_n_78;
   wire chip_cd_n_79;
   wire chip_cd_n_80;
   wire chip_cd_n_81;
   wire chip_cd_n_82;
   wire chip_cd_n_83;
   wire chip_cd_n_84;
   wire chip_cd_n_85;
   wire chip_cd_n_86;
   wire chip_cd_n_87;
   wire chip_cd_n_88;
   wire chip_cd_n_89;
   wire chip_cd_n_90;
   wire chip_cd_n_91;
   wire chip_cd_n_92;
   wire chip_cd_n_93;
   wire chip_cd_n_94;
   wire chip_cd_n_95;
   wire chip_cd_n_96;
   wire chip_cd_n_97;
   wire chip_clk_seconds;
   wire chip_clock_old_clk_1sec;
   wire chip_fsm_n_514;
   wire chip_fsm_n_522;
   wire chip_fsm_n_543;
   wire chip_fsm_swFF_Q_9;
   wire clk_PAD;
   wire h0_PAD_0;
   wire h0_PAD_1;
   wire h0_PAD_2;
   wire h0_PAD_3;
   wire h0_PAD_4;
   wire h0_PAD_5;
   wire h0_PAD_6;
   wire h1_PAD_0;
   wire h1_PAD_1;
   wire h1_PAD_2;
   wire h1_PAD_3;
   wire h1_PAD_4;
   wire h1_PAD_5;
   wire h1_PAD_6;
   wire m0_PAD_0;
   wire m0_PAD_1;
   wire m0_PAD_2;
   wire m0_PAD_3;
   wire m0_PAD_4;
   wire m0_PAD_5;
   wire m0_PAD_6;
   wire m1_PAD_0;
   wire m1_PAD_1;
   wire m1_PAD_2;
   wire m1_PAD_3;
   wire m1_PAD_4;
   wire m1_PAD_5;
   wire m1_PAD_6;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_166;
   wire n_178;
   wire n_179;
   wire n_184;
   wire n_185;
   wire n_187;
   wire n_188;
   wire n_192;
   wire n_193;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_212;
   wire n_213;
   wire n_214;
   wire n_215;
   wire n_216;
   wire n_217;
   wire n_218;
   wire n_219;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_223;
   wire n_224;
   wire n_225;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_230;
   wire n_231;
   wire n_232;
   wire n_233;
   wire n_234;
   wire n_235;
   wire n_236;
   wire n_237;
   wire n_238;
   wire n_239;
   wire n_240;
   wire n_241;
   wire n_242;
   wire n_243;
   wire n_244;
   wire n_245;
   wire n_246;
   wire n_247;
   wire n_248;
   wire n_249;
   wire n_250;
   wire reset_PAD;
   wire s0_PAD_0;
   wire s0_PAD_1;
   wire s0_PAD_2;
   wire s0_PAD_3;
   wire s0_PAD_4;
   wire s0_PAD_5;
   wire s0_PAD_6;
   wire s1_PAD_0;
   wire s1_PAD_1;
   wire s1_PAD_2;
   wire s1_PAD_3;
   wire s1_PAD_4;
   wire s1_PAD_5;
   wire s1_PAD_6;

   assign chip_backlight_light_mode = 1'b0 ;
   assign chip_fsm_next_state[2] = 1'b0 ;
   assign chip_fsm_next_state[1] = 1'b0 ;
   assign chip_fsm_next_state[0] = 1'b0 ;

   ANTENNA DIODE_10 (.A(FE_DBTN1_reset_PAD));
   ANTENNA DIODE_9 (.A(FE_DBTN1_reset_PAD));
   BUFX1 CTS_ccl_a_buf_00012 (.Z(CTS_10),
	.A(clk_PAD));
   BUFX1 CTS_ccl_a_buf_00011 (.Z(CTS_9),
	.A(clk_PAD));
   BUFX1 CTS_ccl_a_buf_00010 (.Z(CTS_8),
	.A(clk_PAD));
   BUFX1 CTS_ccl_a_buf_00009 (.Z(CTS_7),
	.A(clk_PAD));
   BUFX1 CTS_ccl_a_buf_00008 (.Z(CTS_6),
	.A(clk_PAD));
   BUFX1 CTS_ccl_a_buf_00007 (.Z(CTS_5),
	.A(clk_PAD));
   BUFX1 CTS_ccl_a_buf_00006 (.Z(CTS_4),
	.A(clk_PAD));
   BUFX1 CTS_ccl_a_buf_00005 (.Z(CTS_3),
	.A(clk_PAD));
   BUFX1 CTS_ccl_a_buf_00004 (.Z(CTS_2),
	.A(clk_PAD));
   BUFX1 CTS_ccl_a_buf_00003 (.Z(CTS_1),
	.A(clk_PAD));
   BUFX1 CTS_ccl_a_buf_00002 (.Z(CTS_13),
	.A(clk_PAD));
   BUFX1 CTS_ccl_a_buf_00001 (.Z(CTS_12),
	.A(clk_PAD));
   INVX2 FE_DBTC1_reset_PAD (.Z(FE_DBTN1_reset_PAD),
	.A(reset_PAD));
   INVX2 FE_DBTC0_chip_state_2 (.Z(FE_DBTN0_chip_state_2),
	.A(chip_state[2]));
   Seg7Display chip_displayer (.clk(clk_PAD),
	.reset(reset_PAD),
	.seconds_clk(chip_clk_seconds),
	.state(chip_state),
	.current_s(chip_t_seconds),
	.current_m(chip_t_minutes),
	.current_h(chip_t_hours),
	.stopwatch_s({ UNCONNECTED_HIER_Z4,
		UNCONNECTED_HIER_Z3,
		UNCONNECTED_HIER_Z2,
		UNCONNECTED_HIER_Z1,
		UNCONNECTED_HIER_Z0,
		UNCONNECTED_HIER_Z }),
	.stopwatch_m({ UNCONNECTED_HIER_Z10,
		UNCONNECTED_HIER_Z9,
		UNCONNECTED_HIER_Z8,
		UNCONNECTED_HIER_Z7,
		UNCONNECTED_HIER_Z6,
		UNCONNECTED_HIER_Z5 }),
	.stopwatch_h({ UNCONNECTED_HIER_Z16,
		UNCONNECTED_HIER_Z15,
		UNCONNECTED_HIER_Z14,
		UNCONNECTED_HIER_Z13,
		UNCONNECTED_HIER_Z12,
		UNCONNECTED_HIER_Z11 }),
	.display_s1({ s0_PAD_6,
		s0_PAD_5,
		s0_PAD_4,
		s0_PAD_3,
		s0_PAD_2,
		s0_PAD_1,
		s0_PAD_0 }),
	.display_m1({ m0_PAD_6,
		m0_PAD_5,
		m0_PAD_4,
		m0_PAD_3,
		m0_PAD_2,
		m0_PAD_1,
		m0_PAD_0 }),
	.display_h1({ h0_PAD_6,
		h0_PAD_5,
		h0_PAD_4,
		h0_PAD_3,
		h0_PAD_2,
		h0_PAD_1,
		h0_PAD_0 }),
	.display_s2({ s1_PAD_6,
		s1_PAD_5,
		s1_PAD_4,
		s1_PAD_3,
		s1_PAD_2,
		s1_PAD_1,
		s1_PAD_0 }),
	.display_m2({ m1_PAD_6,
		m1_PAD_5,
		m1_PAD_4,
		m1_PAD_3,
		m1_PAD_2,
		m1_PAD_1,
		m1_PAD_0 }),
	.display_h2({ h1_PAD_6,
		h1_PAD_5,
		h1_PAD_4,
		h1_PAD_3,
		h1_PAD_2,
		h1_PAD_1,
		h1_PAD_0 }),
	.second(UNCONNECTED),
	.p1(FE_DBTN0_chip_state_2),
	.p2(FE_DBTN1_reset_PAD),
	.clk_clone3(CTS_2),
	.clk_clone2(CTS_9),
	.clk_clone1(CTS_10));
   pad_in btn_dec_pad (.DataIn(btn_dec_PAD),
	.pad(btn_dec));
   pad_in btn_inc_pad (.DataIn(btn_inc_PAD),
	.pad(btn_inc));
   pad_in btn_light_pad (.DataIn(btn_light_PAD),
	.pad(btn_light));
   pad_in btn_mode_pad (.DataIn(btn_mode_PAD),
	.pad(btn_mode));
   pad_in btn_set_pad (.DataIn(btn_set_PAD),
	.pad(btn_set));
   pad_in clk_pad (.DataIn(clk_PAD),
	.pad(clk));
   pad_out colon_pad (.pad(colon),
	.DataOut(1'b0));
   pad_out h0_pad_0 (.pad(h0_0),
	.DataOut(h0_PAD_0));
   pad_out h0_pad_1 (.pad(h0_1),
	.DataOut(h0_PAD_1));
   pad_out h0_pad_2 (.pad(h0_2),
	.DataOut(h0_PAD_2));
   pad_out h0_pad_3 (.pad(h0_3),
	.DataOut(h0_PAD_3));
   pad_out h0_pad_4 (.pad(h0_4),
	.DataOut(h0_PAD_4));
   pad_out h0_pad_5 (.pad(h0_5),
	.DataOut(h0_PAD_5));
   pad_out h0_pad_6 (.pad(h0_6),
	.DataOut(h0_PAD_6));
   pad_out h1_pad_0 (.pad(h1_0),
	.DataOut(h1_PAD_0));
   pad_out h1_pad_1 (.pad(h1_1),
	.DataOut(h1_PAD_1));
   pad_out h1_pad_2 (.pad(h1_2),
	.DataOut(h1_PAD_2));
   pad_out h1_pad_3 (.pad(h1_3),
	.DataOut(h1_PAD_3));
   pad_out h1_pad_4 (.pad(h1_4),
	.DataOut(h1_PAD_4));
   pad_out h1_pad_5 (.pad(h1_5),
	.DataOut(h1_PAD_5));
   pad_out h1_pad_6 (.pad(h1_6),
	.DataOut(h1_PAD_6));
   pad_out light_pad (.pad(light),
	.DataOut(n_204));
   pad_out m0_pad_0 (.pad(m0_0),
	.DataOut(m0_PAD_0));
   pad_out m0_pad_1 (.pad(m0_1),
	.DataOut(m0_PAD_1));
   pad_out m0_pad_2 (.pad(m0_2),
	.DataOut(m0_PAD_2));
   pad_out m0_pad_3 (.pad(m0_3),
	.DataOut(m0_PAD_3));
   pad_out m0_pad_4 (.pad(m0_4),
	.DataOut(m0_PAD_4));
   pad_out m0_pad_5 (.pad(m0_5),
	.DataOut(m0_PAD_5));
   pad_out m0_pad_6 (.pad(m0_6),
	.DataOut(m0_PAD_6));
   pad_out m1_pad_0 (.pad(m1_0),
	.DataOut(m1_PAD_0));
   pad_out m1_pad_1 (.pad(m1_1),
	.DataOut(m1_PAD_1));
   pad_out m1_pad_2 (.pad(m1_2),
	.DataOut(m1_PAD_2));
   pad_out m1_pad_3 (.pad(m1_3),
	.DataOut(m1_PAD_3));
   pad_out m1_pad_4 (.pad(m1_4),
	.DataOut(m1_PAD_4));
   pad_out m1_pad_5 (.pad(m1_5),
	.DataOut(m1_PAD_5));
   pad_out m1_pad_6 (.pad(m1_6),
	.DataOut(m1_PAD_6));
   pad_in reset_pad (.DataIn(reset_PAD),
	.pad(reset));
   pad_out s0_pad_0 (.pad(s0_0),
	.DataOut(s0_PAD_0));
   pad_out s0_pad_1 (.pad(s0_1),
	.DataOut(s0_PAD_1));
   pad_out s0_pad_2 (.pad(s0_2),
	.DataOut(s0_PAD_2));
   pad_out s0_pad_3 (.pad(s0_3),
	.DataOut(s0_PAD_3));
   pad_out s0_pad_4 (.pad(s0_4),
	.DataOut(s0_PAD_4));
   pad_out s0_pad_5 (.pad(s0_5),
	.DataOut(s0_PAD_5));
   pad_out s0_pad_6 (.pad(s0_6),
	.DataOut(s0_PAD_6));
   pad_out s1_pad_0 (.pad(s1_0),
	.DataOut(s1_PAD_0));
   pad_out s1_pad_1 (.pad(s1_1),
	.DataOut(s1_PAD_1));
   pad_out s1_pad_2 (.pad(s1_2),
	.DataOut(s1_PAD_2));
   pad_out s1_pad_3 (.pad(s1_3),
	.DataOut(s1_PAD_3));
   pad_out s1_pad_4 (.pad(s1_4),
	.DataOut(s1_PAD_4));
   pad_out s1_pad_5 (.pad(s1_5),
	.DataOut(s1_PAD_5));
   pad_out s1_pad_6 (.pad(s1_6),
	.DataOut(s1_PAD_6));
   DFFQX1 \chip_fsm_next_state_reg[0]  (.Q(chip_fsm_next_state[0]),
	.CLK(CTS_5),
	.D(n_250));
   DFFQX1 \chip_fsm_next_state_reg[1]  (.Q(chip_fsm_next_state[1]),
	.CLK(CTS_12),
	.D(n_249));
   DFFQX1 \chip_fsm_next_state_reg[2]  (.Q(chip_fsm_next_state[2]),
	.CLK(CTS_5),
	.D(n_248));
   NAND3X1 g2224__5122 (.Z(n_250),
	.A(n_246),
	.B(n_223),
	.C(n_227));
   NAND3X1 g2225__8246 (.Z(n_249),
	.A(n_247),
	.B(n_228),
	.C(n_226));
   NAND3X1 g2226__7098 (.Z(n_248),
	.A(n_242),
	.B(n_235),
	.C(n_234));
   NOR2X1 g2227__6131 (.Z(n_247),
	.A(n_213),
	.B(n_244));
   NOR2X1 g2228__1881 (.Z(n_246),
	.A(n_237),
	.B(n_245));
   OR2X1 g2229__5115 (.Z(n_245),
	.A(n_231),
	.B(n_243));
   NAND3X1 g2230__7482 (.Z(n_244),
	.A(n_241),
	.B(n_236),
	.C(n_233));
   NOR2X1 g2231__4733 (.Z(n_243),
	.A(chip_state[1]),
	.B(n_239));
   AND2X1 g2232__6161 (.Z(n_242),
	.A(n_240),
	.B(n_230));
   NAND2X1 g2233__9315 (.Z(n_241),
	.A(n_238),
	.B(n_202));
   OR2X1 g2234__9945 (.Z(n_240),
	.A(chip_fsm_n_514),
	.B(n_232));
   AND2X1 g2235__2883 (.Z(n_239),
	.A(n_229),
	.B(n_218));
   OR2X1 g2236__2346 (.Z(n_238),
	.A(n_200),
	.B(n_225));
   NOR2X1 g2237__1666 (.Z(n_237),
	.A(btn_inc_PAD),
	.B(n_235));
   OR2X1 g2238__7410 (.Z(n_236),
	.A(btn_inc_PAD),
	.B(n_224));
   NAND2X1 g2239__6417 (.Z(n_234),
	.A(n_217),
	.B(btn_inc_PAD));
   OR2X1 g2240__5477 (.Z(n_233),
	.A(btn_mode_PAD),
	.B(n_212));
   AND2X1 g2241__2398 (.Z(n_232),
	.A(n_221),
	.B(n_219));
   NOR2X1 g2242__5107 (.Z(n_231),
	.A(n_220),
	.B(n_207));
   NAND3X1 g2243__6260 (.Z(n_230),
	.A(n_206),
	.B(n_21),
	.C(n_12));
   NAND2X1 g2244__4319 (.Z(n_235),
	.A(n_217),
	.B(btn_dec_PAD));
   XOR2X1 g2245__8428 (.Z(n_229),
	.A(chip_state[0]),
	.B(n_208));
   NAND2X1 g2246__5526 (.Z(n_228),
	.A(n_216),
	.B(chip_fsm_swFF_Q_9));
   OR2X1 g2247__6783 (.Z(n_227),
	.A(chip_fsm_n_522),
	.B(n_215));
   OR2X1 g2248__3680 (.Z(n_226),
	.A(chip_state[1]),
	.B(n_214));
   NOR2X1 g2249__1617 (.Z(n_225),
	.A(btn_dec_PAD),
	.B(n_215));
   OR2X1 g2250__2802 (.Z(n_224),
	.A(btn_dec_PAD),
	.B(n_222));
   NAND3X1 g2251__1705 (.Z(n_223),
	.A(n_201),
	.B(chip_state[2]),
	.C(n_211));
   OR2X1 g2252__5122 (.Z(n_222),
	.A(n_210),
	.B(chip_fsm_n_522));
   NAND2X1 g2253__8246 (.Z(n_221),
	.A(n_209),
	.B(chip_fsm_swFF_Q_9));
   AND2X1 g2254__7098 (.Z(n_220),
	.A(n_203),
	.B(n_12));
   OR2X1 g2255__6131 (.Z(n_219),
	.A(n_211),
	.B(FE_DBTN0_chip_state_2));
   NAND2X1 g2256__1881 (.Z(n_218),
	.A(n_202),
	.B(btn_mode_PAD));
   INVX2 g2257 (.Z(chip_fsm_n_543),
	.A(n_216));
   OR2X1 g2258__5115 (.Z(n_214),
	.A(n_199),
	.B(n_202));
   NOR2X1 g2259__7482 (.Z(n_213),
	.A(n_12),
	.B(n_207));
   OR2X1 g2260__4733 (.Z(n_212),
	.A(btn_set_PAD),
	.B(chip_fsm_n_514));
   NOR2X1 g2261__6161 (.Z(n_217),
	.A(n_198),
	.B(chip_fsm_n_522));
   NOR2X1 g2262__9315 (.Z(n_216),
	.A(chip_state[2]),
	.B(chip_fsm_n_514));
   NAND3X1 g2263__9945 (.Z(n_215),
	.A(chip_state[1]),
	.B(n_193),
	.C(n_12));
   INVX2 g2264 (.Z(n_211),
	.A(n_210));
   INVX2 g2265 (.Z(n_209),
	.A(n_208));
   INVX2 g2266 (.Z(n_206),
	.A(n_207));
   DFFQSRX1 chip_backlight_light_reg (.Q(n_204),
	.CLK(CTS_5),
	.D(chip_backlight_light_mode),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   NAND2X1 g2270__2883 (.Z(n_203),
	.A(n_193),
	.B(btn_dec_PAD));
   NAND2X1 g2271__2346 (.Z(n_210),
	.A(n_193),
	.B(btn_set_PAD));
   NAND2X1 g2272__1666 (.Z(n_208),
	.A(FE_DBTN0_chip_state_2),
	.B(btn_set_PAD));
   NAND2X1 g2273__7410 (.Z(n_207),
	.A(chip_state[2]),
	.B(n_198));
   INVX2 g2274 (.Z(n_201),
	.A(chip_fsm_n_514));
   NOR2X1 g2275__6417 (.Z(n_200),
	.A(n_193),
	.B(chip_state[0]));
   NOR2X1 g2276__5477 (.Z(n_199),
	.A(btn_mode_PAD),
	.B(chip_state[0]));
   NOR2X1 g2277__2398 (.Z(n_202),
	.A(btn_set_PAD),
	.B(chip_state[2]));
   NAND2X1 g2278__5107 (.Z(chip_fsm_n_522),
	.A(chip_state[0]),
	.B(FE_DBTN0_chip_state_2));
   NAND2X1 g2279__6260 (.Z(chip_fsm_n_514),
	.A(n_21),
	.B(chip_state[1]));
   INVX2 g2280 (.Z(n_198),
	.A(chip_state[1]));
   INVX2 g2281 (.Z(n_21),
	.A(chip_state[0]));
   INVX2 g2284 (.Z(n_12),
	.A(btn_inc_PAD));
   INVX2 g2285 (.Z(n_193),
	.A(btn_mode_PAD));
   DFFQSRX1 chip_backlight_light_mode_reg (.Q(chip_backlight_light_mode),
	.CLK(CTS_6),
	.D(n_36),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 chip_cd_clk_seconds_reg (.Q(chip_clk_seconds),
	.CLK(CTS_2),
	.D(n_192),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[0]  (.Q(chip_cd_count[0]),
	.CLK(CTS_2),
	.D(n_166),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[1]  (.Q(chip_cd_count[1]),
	.CLK(CTS_2),
	.D(chip_cd_n_73),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[2]  (.Q(chip_cd_count[2]),
	.CLK(CTS_10),
	.D(chip_cd_n_74),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[3]  (.Q(chip_cd_count[3]),
	.CLK(CTS_9),
	.D(n_187),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[4]  (.Q(chip_cd_count[4]),
	.CLK(CTS_9),
	.D(chip_cd_n_76),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[5]  (.Q(chip_cd_count[5]),
	.CLK(CTS_9),
	.D(n_188),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[6]  (.Q(chip_cd_count[6]),
	.CLK(CTS_9),
	.D(chip_cd_n_78),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[7]  (.Q(chip_cd_count[7]),
	.CLK(CTS_9),
	.D(n_185),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[8]  (.Q(chip_cd_count[8]),
	.CLK(CTS_7),
	.D(n_184),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[9]  (.Q(chip_cd_count[9]),
	.CLK(CTS_7),
	.D(chip_cd_n_81),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[10]  (.Q(chip_cd_count[10]),
	.CLK(CTS_7),
	.D(chip_cd_n_82),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[11]  (.Q(chip_cd_count[11]),
	.CLK(CTS_7),
	.D(chip_cd_n_83),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[12]  (.Q(chip_cd_count[12]),
	.CLK(CTS_8),
	.D(chip_cd_n_84),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[13]  (.Q(chip_cd_count[13]),
	.CLK(CTS_1),
	.D(n_179),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[14]  (.Q(chip_cd_count[14]),
	.CLK(CTS_8),
	.D(n_178),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[15]  (.Q(chip_cd_count[15]),
	.CLK(CTS_8),
	.D(chip_cd_n_87),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[16]  (.Q(chip_cd_count[16]),
	.CLK(CTS_8),
	.D(chip_cd_n_88),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[17]  (.Q(chip_cd_count[17]),
	.CLK(CTS_6),
	.D(chip_cd_n_89),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[18]  (.Q(chip_cd_count[18]),
	.CLK(CTS_6),
	.D(chip_cd_n_90),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[19]  (.Q(chip_cd_count[19]),
	.CLK(CTS_8),
	.D(chip_cd_n_91),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[20]  (.Q(chip_cd_count[20]),
	.CLK(CTS_8),
	.D(chip_cd_n_92),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[21]  (.Q(chip_cd_count[21]),
	.CLK(CTS_8),
	.D(chip_cd_n_93),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[22]  (.Q(chip_cd_count[22]),
	.CLK(CTS_7),
	.D(chip_cd_n_94),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[23]  (.Q(chip_cd_count[23]),
	.CLK(CTS_6),
	.D(chip_cd_n_95),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[24]  (.Q(chip_cd_count[24]),
	.CLK(CTS_6),
	.D(chip_cd_n_96),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_cd_count_reg[25]  (.Q(chip_cd_count[25]),
	.CLK(CTS_6),
	.D(chip_cd_n_97),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_clock_hours_reg[0]  (.Q(chip_t_hours[0]),
	.CLK(CTS_4),
	.D(n_139),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQX1 \chip_clock_hours_reg[0]47  (.Q(chip_t_hours[0]),
	.CLK(n_128),
	.D(n_8));
   DFFQX1 \chip_clock_hours_reg[0]53  (.Q(chip_t_hours[0]),
	.CLK(n_117),
	.D(n_8));
   DFFQSRX1 \chip_clock_hours_reg[1]  (.Q(chip_t_hours[1]),
	.CLK(CTS_4),
	.D(n_146),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQX1 \chip_clock_hours_reg[1]48  (.Q(chip_t_hours[1]),
	.CLK(n_128),
	.D(n_44));
   DFFQX1 \chip_clock_hours_reg[1]54  (.Q(chip_t_hours[1]),
	.CLK(n_117),
	.D(n_43));
   DFFQSRX1 \chip_clock_hours_reg[2]  (.Q(chip_t_hours[2]),
	.CLK(CTS_4),
	.D(n_141),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQX1 \chip_clock_hours_reg[2]49  (.Q(chip_t_hours[2]),
	.CLK(n_128),
	.D(n_67));
   DFFQX1 \chip_clock_hours_reg[2]55  (.Q(chip_t_hours[2]),
	.CLK(n_117),
	.D(n_61));
   DFFQSRX1 \chip_clock_hours_reg[3]  (.Q(chip_t_hours[3]),
	.CLK(CTS_5),
	.D(n_144),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQX1 \chip_clock_hours_reg[3]50  (.Q(chip_t_hours[3]),
	.CLK(n_128),
	.D(n_1));
   DFFQX1 \chip_clock_hours_reg[3]56  (.Q(chip_t_hours[3]),
	.CLK(n_117),
	.D(n_103));
   DFFQSRX1 \chip_clock_hours_reg[4]  (.Q(chip_t_hours[4]),
	.CLK(CTS_3),
	.D(n_143),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQX1 \chip_clock_hours_reg[4]51  (.Q(chip_t_hours[4]),
	.CLK(n_128),
	.D(n_0));
   DFFQX1 \chip_clock_hours_reg[4]57  (.Q(chip_t_hours[4]),
	.CLK(n_117),
	.D(n_92));
   DFFQSRX1 \chip_clock_hours_reg[5]  (.Q(chip_t_hours[5]),
	.CLK(CTS_4),
	.D(n_140),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQX1 \chip_clock_hours_reg[5]52  (.Q(chip_t_hours[5]),
	.CLK(n_128),
	.D(n_114));
   DFFQX1 \chip_clock_hours_reg[5]58  (.Q(chip_t_hours[5]),
	.CLK(n_117),
	.D(n_102));
   DFFQSRX1 \chip_clock_minutes_reg[0]  (.Q(chip_t_minutes[0]),
	.CLK(CTS_3),
	.D(n_130),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQX1 \chip_clock_minutes_reg[0]35  (.Q(chip_t_minutes[0]),
	.CLK(n_127),
	.D(n_10));
   DFFQX1 \chip_clock_minutes_reg[0]41  (.Q(chip_t_minutes[0]),
	.CLK(n_116),
	.D(n_10));
   DFFQSRX1 \chip_clock_minutes_reg[1]  (.Q(chip_t_minutes[1]),
	.CLK(CTS_3),
	.D(n_134),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQX1 \chip_clock_minutes_reg[1]36  (.Q(chip_t_minutes[1]),
	.CLK(n_127),
	.D(n_46));
   DFFQX1 \chip_clock_minutes_reg[1]42  (.Q(chip_t_minutes[1]),
	.CLK(n_116),
	.D(n_45));
   DFFQSRX1 \chip_clock_minutes_reg[2]  (.Q(chip_t_minutes[2]),
	.CLK(CTS_3),
	.D(n_148),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQX1 \chip_clock_minutes_reg[2]37  (.Q(chip_t_minutes[2]),
	.CLK(n_127),
	.D(n_98));
   DFFQX1 \chip_clock_minutes_reg[2]43  (.Q(chip_t_minutes[2]),
	.CLK(n_116),
	.D(n_78));
   DFFQSRX1 \chip_clock_minutes_reg[3]  (.Q(chip_t_minutes[3]),
	.CLK(CTS_1),
	.D(n_147),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQX1 \chip_clock_minutes_reg[3]38  (.Q(chip_t_minutes[3]),
	.CLK(n_127),
	.D(n_97));
   DFFQX1 \chip_clock_minutes_reg[3]44  (.Q(chip_t_minutes[3]),
	.CLK(n_116),
	.D(n_79));
   DFFQSRX1 \chip_clock_minutes_reg[4]  (.Q(chip_t_minutes[4]),
	.CLK(CTS_13),
	.D(n_150),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQX1 \chip_clock_minutes_reg[4]39  (.Q(chip_t_minutes[4]),
	.CLK(n_127),
	.D(n_108));
   DFFQX1 \chip_clock_minutes_reg[4]45  (.Q(chip_t_minutes[4]),
	.CLK(n_116),
	.D(n_91));
   DFFQSRX1 \chip_clock_minutes_reg[5]  (.Q(chip_t_minutes[5]),
	.CLK(CTS_12),
	.D(n_142),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQX1 \chip_clock_minutes_reg[5]40  (.Q(chip_t_minutes[5]),
	.CLK(n_127),
	.D(n_107));
   DFFQX1 \chip_clock_minutes_reg[5]46  (.Q(chip_t_minutes[5]),
	.CLK(n_116),
	.D(n_109));
   DFFQSRX1 chip_clock_old_clk_1sec_reg (.Q(chip_clock_old_clk_1sec),
	.CLK(CTS_2),
	.D(chip_clk_seconds),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_clock_seconds_reg[0]  (.Q(chip_t_seconds[0]),
	.CLK(CTS_2),
	.D(n_57),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_clock_seconds_reg[1]  (.Q(chip_t_seconds[1]),
	.CLK(CTS_2),
	.D(n_80),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_clock_seconds_reg[2]  (.Q(chip_t_seconds[2]),
	.CLK(CTS_13),
	.D(n_106),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_clock_seconds_reg[3]  (.Q(chip_t_seconds[3]),
	.CLK(CTS_1),
	.D(n_120),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_clock_seconds_reg[4]  (.Q(chip_t_seconds[4]),
	.CLK(CTS_1),
	.D(n_131),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_clock_seconds_reg[5]  (.Q(chip_t_seconds[5]),
	.CLK(CTS_1),
	.D(n_145),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_fsm_state_reg[0]  (.Q(chip_state[0]),
	.CLK(CTS_13),
	.D(chip_fsm_next_state[0]),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_fsm_state_reg[1]  (.Q(chip_state[1]),
	.CLK(CTS_13),
	.D(chip_fsm_next_state[1]),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQSRX1 \chip_fsm_state_reg[2]  (.Q(chip_state[2]),
	.CLK(CTS_12),
	.D(chip_fsm_next_state[2]),
	.RESETB(1'b1),
	.SETB(FE_DBTN1_reset_PAD));
   DFFQX1 chip_fsm_swFF_Q_reg (.Q(chip_fsm_swFF_Q_9),
	.CLK(CTS_12),
	.D(n_77));
   XOR2X1 g3791__4319 (.Z(n_192),
	.A(chip_clk_seconds),
	.B(n_3));
   AND2X1 g3808__8428 (.Z(n_188),
	.A(n_2),
	.B(chip_cd_n_77));
   AND2X1 g3809__5526 (.Z(n_187),
	.A(n_2),
	.B(chip_cd_n_75));
   AND2X1 g3811__6783 (.Z(n_185),
	.A(n_2),
	.B(chip_cd_n_79));
   AND2X1 g3812__3680 (.Z(n_184),
	.A(n_2),
	.B(chip_cd_n_80));
   AND2X1 g3817__1617 (.Z(n_179),
	.A(n_2),
	.B(chip_cd_n_85));
   AND2X1 g3818__2802 (.Z(n_178),
	.A(n_2),
	.B(chip_cd_n_86));
   NOR2X1 g3830__1705 (.Z(n_166),
	.A(chip_cd_count[0]),
	.B(n_3));
   OR2X1 g3832__5122 (.Z(n_2),
	.A(chip_cd_count[16]),
	.B(n_164));
   OR2X1 g3833__8246 (.Z(n_164),
	.A(chip_cd_count[15]),
	.B(n_163));
   OR2X1 g3834__7098 (.Z(n_163),
	.A(chip_cd_count[18]),
	.B(n_162));
   OR2X1 g3835__6131 (.Z(n_162),
	.A(chip_cd_count[17]),
	.B(n_161));
   OR2X1 g3836__1881 (.Z(n_161),
	.A(chip_cd_count[20]),
	.B(n_160));
   OR2X1 g3837__5115 (.Z(n_160),
	.A(chip_cd_count[19]),
	.B(n_159));
   OR2X1 g3838__7482 (.Z(n_159),
	.A(chip_cd_count[21]),
	.B(n_158));
   OR2X1 g3839__4733 (.Z(n_158),
	.A(chip_cd_count[0]),
	.B(n_157));
   NAND3X1 g3840__6161 (.Z(n_157),
	.A(n_156),
	.B(chip_cd_count[14]),
	.C(chip_cd_count[13]));
   NOR2X1 g3841__9315 (.Z(n_156),
	.A(chip_cd_count[12]),
	.B(n_155));
   OR2X1 g3842__9945 (.Z(n_155),
	.A(chip_cd_count[11]),
	.B(n_154));
   OR2X1 g3843__2883 (.Z(n_154),
	.A(chip_cd_count[10]),
	.B(n_153));
   OR2X1 g3844__2346 (.Z(n_153),
	.A(chip_cd_count[25]),
	.B(n_152));
   OR2X1 g3845__1666 (.Z(n_152),
	.A(chip_cd_count[24]),
	.B(n_151));
   OR2X1 g3854__7410 (.Z(n_151),
	.A(chip_cd_count[23]),
	.B(n_149));
   NAND2X1 g3858__6417 (.Z(n_150),
	.A(n_135),
	.B(n_118));
   OR2X1 g3861__5477 (.Z(n_149),
	.A(chip_cd_count[9]),
	.B(n_133));
   NAND2X1 g3862__2398 (.Z(n_148),
	.A(n_137),
	.B(n_121));
   NAND2X1 g3863__5107 (.Z(n_147),
	.A(n_138),
	.B(n_123));
   MUX2X1 g3865__6260 (.Z(n_146),
	.A(n_44),
	.B(chip_t_hours[1]),
	.S(n_125));
   NAND2X1 g3866__4319 (.Z(n_145),
	.A(n_132),
	.B(n_129));
   MUX2X1 g3867__8428 (.Z(n_144),
	.A(n_1),
	.B(chip_t_hours[3]),
	.S(n_125));
   MUX2X1 g3868__5526 (.Z(n_143),
	.A(n_0),
	.B(chip_t_hours[4]),
	.S(n_125));
   NAND2X1 g3869__6783 (.Z(n_142),
	.A(n_136),
	.B(n_122));
   MUX2X1 g3870__3680 (.Z(n_141),
	.A(n_67),
	.B(chip_t_hours[2]),
	.S(n_125));
   MUX2X1 g3871__1617 (.Z(n_140),
	.A(n_114),
	.B(chip_t_hours[5]),
	.S(n_125));
   XOR2X1 g3872__2802 (.Z(n_139),
	.A(chip_t_hours[0]),
	.B(n_124));
   NAND2X1 g3873__1705 (.Z(n_138),
	.A(n_126),
	.B(n_82));
   NAND2X1 g3874__5122 (.Z(n_137),
	.A(n_126),
	.B(n_68));
   NAND2X1 g3875__8246 (.Z(n_136),
	.A(n_104),
	.B(n_126));
   NAND2X1 g3876__7098 (.Z(n_135),
	.A(n_126),
	.B(n_100));
   MUX2X1 g3878__6131 (.Z(n_134),
	.A(n_46),
	.B(chip_t_minutes[1]),
	.S(n_112));
   NAND3X1 g3879__1881 (.Z(n_133),
	.A(n_110),
	.B(chip_cd_count[8]),
	.C(chip_cd_count[7]));
   NAND2X1 g3880__5115 (.Z(n_132),
	.A(n_119),
	.B(chip_t_seconds[5]));
   MUX2X1 g3881__7482 (.Z(n_131),
	.A(n_113),
	.B(n_115),
	.S(chip_t_seconds[4]));
   XOR2X1 g3882__4733 (.Z(n_130),
	.A(chip_t_minutes[0]),
	.B(n_111));
   NAND2X1 g3883__6161 (.Z(n_129),
	.A(n_113),
	.B(chip_t_seconds[4]));
   INVX2 g3890 (.Z(n_124),
	.A(n_125));
   NAND2X1 g3891__9315 (.Z(n_123),
	.A(n_112),
	.B(chip_t_minutes[3]));
   NAND2X1 g3892__9945 (.Z(n_122),
	.A(n_112),
	.B(chip_t_minutes[5]));
   NAND2X1 g3893__2883 (.Z(n_121),
	.A(n_112),
	.B(chip_t_minutes[2]));
   NAND2X1 g3894__2346 (.Z(n_120),
	.A(n_105),
	.B(n_64));
   OR2X1 g3895__1666 (.Z(n_119),
	.A(n_17),
	.B(n_115));
   NAND2X1 g3896__7410 (.Z(n_118),
	.A(n_112),
	.B(chip_t_minutes[4]));
   NOR2X1 g3897__6417 (.Z(n_126),
	.A(n_87),
	.B(n_112));
   NAND3X1 g3898__5477 (.Z(n_125),
	.A(n_111),
	.B(n_87),
	.C(n_7));
   INVX2 g3908 (.Z(n_111),
	.A(n_112));
   NOR2X1 g3909__2398 (.Z(n_110),
	.A(chip_cd_count[22]),
	.B(n_94));
   XOR2X1 g3910__5107 (.Z(n_109),
	.A(chip_t_minutes[5]),
	.B(n_75));
   AND2X1 g3911__6260 (.Z(n_108),
	.A(n_100),
	.B(n_88));
   AND2X1 g3912__4319 (.Z(n_107),
	.A(n_104),
	.B(n_88));
   NAND2X1 g3913__8428 (.Z(n_106),
	.A(n_96),
	.B(n_60));
   NAND2X1 g3914__5526 (.Z(n_105),
	.A(n_93),
	.B(n_89));
   NAND2X1 g3915__6783 (.Z(n_115),
	.A(n_95),
	.B(n_37));
   XOR2X1 g3916__3680 (.Z(n_114),
	.A(chip_t_hours[5]),
	.B(n_84));
   AND2X1 g3917__1617 (.Z(n_113),
	.A(n_101),
	.B(n_37));
   NAND3X1 g3918__2802 (.Z(n_112),
	.A(n_90),
	.B(n_37),
	.C(n_15));
   NOR2X1 g3919__1705 (.Z(n_103),
	.A(n_41),
	.B(n_76));
   AND2X1 g3923__5122 (.Z(n_102),
	.A(n_85),
	.B(chip_t_hours[5]));
   NOR2X1 g3924__8246 (.Z(n_101),
	.A(n_66),
	.B(n_90));
   OR2X1 g3926__7098 (.Z(n_104),
	.A(chip_t_minutes[5]),
	.B(n_86));
   AND2X1 g3929__6131 (.Z(n_98),
	.A(n_88),
	.B(n_68));
   AND2X1 g3930__1881 (.Z(n_97),
	.A(n_82),
	.B(n_88));
   NAND3X1 g3931__5115 (.Z(n_96),
	.A(n_89),
	.B(n_42),
	.C(n_15));
   NAND2X1 g3932__7482 (.Z(n_95),
	.A(n_89),
	.B(n_66));
   NAND3X1 g3933__4733 (.Z(n_94),
	.A(n_59),
	.B(n_19),
	.C(chip_cd_count[5]));
   MUX2X1 g3934__6161 (.Z(n_93),
	.A(n_63),
	.B(chip_t_seconds[3]),
	.S(n_15));
   XOR2X1 g3935__9315 (.Z(n_92),
	.A(chip_t_hours[4]),
	.B(n_72));
   XOR2X1 g3936__9945 (.Z(n_91),
	.A(chip_t_minutes[4]),
	.B(n_74));
   XOR2X1 g3937__2883 (.Z(n_100),
	.A(chip_t_minutes[4]),
	.B(n_71));
   XOR2X1 g3938__2346 (.Z(n_99),
	.A(chip_t_hours[4]),
	.B(n_73));
   INVX2 g3939 (.Z(n_89),
	.A(n_90));
   INVX2 g3940 (.Z(n_87),
	.A(n_88));
   AND2X1 g3941__1666 (.Z(n_86),
	.A(n_71),
	.B(chip_t_minutes[4]));
   NAND2X1 g3944__7410 (.Z(n_85),
	.A(n_72),
	.B(n_6));
   AND2X1 g3945__6417 (.Z(n_84),
	.A(n_73),
	.B(chip_t_hours[4]));
   NOR2X1 g3947__5477 (.Z(n_90),
	.A(n_17),
	.B(n_58));
   NAND3X1 g3948__2398 (.Z(n_88),
	.A(n_48),
	.B(chip_t_minutes[4]),
	.C(chip_t_minutes[3]));
   XOR2X1 g3949__5107 (.Z(n_80),
	.A(chip_t_seconds[1]),
	.B(n_38));
   XOR2X1 g3950__6260 (.Z(n_79),
	.A(chip_t_minutes[3]),
	.B(n_54));
   AND2X1 g3951__4319 (.Z(n_78),
	.A(n_56),
	.B(n_65));
   NAND2X1 g3952__8428 (.Z(n_77),
	.A(n_62),
	.B(n_34));
   NOR2X1 g3953__5526 (.Z(n_76),
	.A(n_69),
	.B(n_72));
   NOR2X1 g3954__6783 (.Z(n_83),
	.A(n_70),
	.B(n_73));
   NOR2X1 g3955__3680 (.Z(n_82),
	.A(n_55),
	.B(n_71));
   AND2X1 g3956__1617 (.Z(n_75),
	.A(n_74),
	.B(n_5));
   NAND3X1 g3957__2802 (.Z(n_81),
	.A(n_52),
	.B(chip_t_hours[4]),
	.C(n_11));
   NOR2X1 g3965__1705 (.Z(n_70),
	.A(chip_t_hours[3]),
	.B(n_52));
   AND2X1 g3966__5122 (.Z(n_69),
	.A(n_47),
	.B(chip_t_hours[3]));
   AND2X1 g3967__8246 (.Z(n_74),
	.A(n_54),
	.B(n_14));
   AND2X1 g3968__7098 (.Z(n_73),
	.A(n_52),
	.B(chip_t_hours[3]));
   NOR2X1 g3969__6131 (.Z(n_72),
	.A(chip_t_hours[3]),
	.B(n_47));
   AND2X1 g3970__1881 (.Z(n_71),
	.A(n_53),
	.B(chip_t_minutes[3]));
   NAND3X1 g3971__5115 (.Z(n_65),
	.A(n_22),
	.B(n_7),
	.C(n_14));
   OR2X1 g3972__7482 (.Z(n_64),
	.A(n_16),
	.B(n_42));
   AND2X1 g3973__4733 (.Z(n_63),
	.A(n_42),
	.B(n_16));
   NAND2X1 g3974__6161 (.Z(n_62),
	.A(n_51),
	.B(chip_fsm_swFF_Q_9));
   NAND2X1 g3975__9315 (.Z(n_61),
	.A(n_47),
	.B(n_50));
   OR2X1 g3976__9945 (.Z(n_60),
	.A(n_15),
	.B(n_42));
   NOR2X1 g3977__2883 (.Z(n_59),
	.A(chip_cd_count[4]),
	.B(n_40));
   NAND3X1 g3978__2346 (.Z(n_58),
	.A(n_29),
	.B(chip_t_seconds[3]),
	.C(chip_t_seconds[5]));
   XOR2X1 g3979__1666 (.Z(n_57),
	.A(chip_t_seconds[0]),
	.B(n_37));
   XOR2X1 g3980__7410 (.Z(n_56),
	.A(chip_t_minutes[2]),
	.B(n_31));
   NOR2X1 g3981__6417 (.Z(n_55),
	.A(chip_t_minutes[3]),
	.B(n_53));
   XOR2X1 g3982__5477 (.Z(n_68),
	.A(n_7),
	.B(n_26));
   NOR2X1 g3983__2398 (.Z(n_67),
	.A(n_49),
	.B(n_52));
   NAND3X1 g3984__5107 (.Z(n_66),
	.A(n_29),
	.B(chip_t_seconds[2]),
	.C(chip_t_seconds[3]));
   NAND2X1 g3987__6260 (.Z(n_51),
	.A(n_27),
	.B(chip_fsm_n_514));
   NAND2X1 g3988__4319 (.Z(n_50),
	.A(n_33),
	.B(chip_t_hours[2]));
   NOR2X1 g3989__8428 (.Z(n_49),
	.A(chip_t_hours[2]),
	.B(n_30));
   NOR2X1 g3990__5526 (.Z(n_48),
	.A(n_9),
	.B(n_26));
   AND2X1 g3992__6783 (.Z(n_54),
	.A(n_31),
	.B(n_7));
   NOR2X1 g3993__3680 (.Z(n_53),
	.A(n_7),
	.B(n_26));
   AND2X1 g3994__1617 (.Z(n_52),
	.A(n_30),
	.B(chip_t_hours[2]));
   INVX2 g3995 (.Z(n_45),
	.A(n_46));
   INVX2 g3996 (.Z(n_43),
	.A(n_44));
   AND2X1 g3997__2802 (.Z(n_41),
	.A(n_23),
	.B(n_6));
   NAND2X1 g3998__1705 (.Z(n_40),
	.A(n_24),
	.B(chip_cd_count[3]));
   NAND2X1 g4000__5122 (.Z(n_47),
	.A(n_35),
	.B(n_8));
   NOR2X1 g4001__8246 (.Z(n_46),
	.A(n_25),
	.B(n_31));
   AND2X1 g4002__7098 (.Z(n_38),
	.A(n_37),
	.B(chip_t_seconds[0]));
   NOR2X1 g4003__6131 (.Z(n_44),
	.A(n_30),
	.B(n_32));
   AND2X1 g4004__1881 (.Z(n_42),
	.A(n_37),
	.B(n_29));
   AND2X1 g4005__5115 (.Z(n_128),
	.A(n_28),
	.B(btn_inc_PAD));
   AND2X1 g4006__7482 (.Z(n_117),
	.A(n_28),
	.B(btn_dec_PAD));
   OR2X1 g4007__4733 (.Z(n_36),
	.A(btn_light_PAD),
	.B(chip_backlight_light_mode));
   NOR2X1 g4008__6161 (.Z(n_35),
	.A(chip_t_hours[2]),
	.B(chip_t_hours[1]));
   NAND2X1 g4009__9315 (.Z(n_34),
	.A(n_21),
	.B(chip_state[2]));
   NOR2X1 g4013__9945 (.Z(n_116),
	.A(n_20),
	.B(chip_fsm_n_543));
   NOR2X1 g4014__2883 (.Z(n_127),
	.A(n_12),
	.B(chip_fsm_n_543));
   NOR2X1 g4015__2346 (.Z(n_37),
	.A(chip_clock_old_clk_1sec),
	.B(n_18));
   INVX2 g4016 (.Z(n_33),
	.A(n_32));
   INVX2 g4017 (.Z(n_27),
	.A(n_28));
   INVX2 g4018 (.Z(n_25),
	.A(n_26));
   NOR2X1 g4019__1666 (.Z(n_24),
	.A(chip_cd_count[2]),
	.B(chip_cd_count[1]));
   NOR2X1 g4020__7410 (.Z(n_23),
	.A(chip_t_hours[5]),
	.B(chip_t_hours[3]));
   NOR2X1 g4021__6417 (.Z(n_22),
	.A(chip_t_minutes[5]),
	.B(chip_t_minutes[4]));
   NOR2X1 g4022__5477 (.Z(n_32),
	.A(chip_t_hours[1]),
	.B(chip_t_hours[0]));
   NOR2X1 g4023__2398 (.Z(n_31),
	.A(chip_t_minutes[1]),
	.B(chip_t_minutes[0]));
   AND2X1 g4024__5107 (.Z(n_30),
	.A(chip_t_hours[1]),
	.B(chip_t_hours[0]));
   AND2X1 g4025__6260 (.Z(n_29),
	.A(chip_t_seconds[0]),
	.B(chip_t_seconds[1]));
   NOR2X1 g4026__4319 (.Z(n_28),
	.A(chip_state[1]),
	.B(chip_fsm_n_522));
   NAND2X1 g4027__8428 (.Z(n_26),
	.A(chip_t_minutes[1]),
	.B(chip_t_minutes[0]));
   INVX2 g4029 (.Z(n_20),
	.A(btn_dec_PAD));
   INVX2 g4030 (.Z(n_19),
	.A(chip_cd_count[6]));
   INVX2 g4034 (.Z(n_18),
	.A(chip_clk_seconds));
   INVX2 g4036 (.Z(n_17),
	.A(chip_t_seconds[4]));
   INVX2 g4037 (.Z(n_16),
	.A(chip_t_seconds[3]));
   INVX2 g4038 (.Z(n_15),
	.A(chip_t_seconds[2]));
   INVX2 g4039 (.Z(n_14),
	.A(chip_t_minutes[3]));
   INVX2 g4042 (.Z(n_11),
	.A(chip_t_hours[5]));
   INVX2 g4043 (.Z(n_10),
	.A(chip_t_minutes[0]));
   INVX2 g4044 (.Z(n_9),
	.A(chip_t_minutes[5]));
   INVX2 g4045 (.Z(n_8),
	.A(chip_t_hours[0]));
   INVX2 g4046 (.Z(n_7),
	.A(chip_t_minutes[2]));
   INVX2 g4047 (.Z(n_6),
	.A(chip_t_hours[4]));
   INVX2 g4048 (.Z(n_5),
	.A(chip_t_minutes[4]));
   INVX2 drc_bufs4055 (.Z(n_3),
	.A(n_2));
   AND2X1 g4056__5526 (.Z(n_1),
	.A(n_83),
	.B(n_81));
   AND2X1 g4057__6783 (.Z(n_0),
	.A(n_99),
	.B(n_81));
   XOR2X1 chip_cd_inc_add_23_19_g393__3680 (.Z(chip_cd_n_95),
	.A(chip_cd_count[23]),
	.B(chip_cd_inc_add_23_19_n_272));
   XOR2X1 chip_cd_inc_add_23_19_g394__1617 (.Z(chip_cd_n_91),
	.A(chip_cd_count[19]),
	.B(chip_cd_inc_add_23_19_n_269));
   XOR2X1 chip_cd_inc_add_23_19_g395__2802 (.Z(chip_cd_n_90),
	.A(chip_cd_count[18]),
	.B(chip_cd_inc_add_23_19_n_278));
   XOR2X1 chip_cd_inc_add_23_19_g396__1705 (.Z(chip_cd_n_94),
	.A(chip_cd_count[22]),
	.B(chip_cd_inc_add_23_19_n_287));
   XOR2X1 chip_cd_inc_add_23_19_g397__5122 (.Z(chip_cd_n_93),
	.A(chip_cd_count[21]),
	.B(chip_cd_inc_add_23_19_n_284));
   XOR2X1 chip_cd_inc_add_23_19_g398__8246 (.Z(chip_cd_n_97),
	.A(chip_cd_count[25]),
	.B(chip_cd_inc_add_23_19_n_281));
   AND2X1 chip_cd_inc_add_23_19_g399__7098 (.Z(chip_cd_inc_add_23_19_n_269),
	.A(chip_cd_inc_add_23_19_n_278),
	.B(chip_cd_count[18]));
   AND2X1 chip_cd_inc_add_23_19_g400__6131 (.Z(chip_cd_inc_add_23_19_n_272),
	.A(chip_cd_inc_add_23_19_n_287),
	.B(chip_cd_count[22]));
   XOR2X1 chip_cd_inc_add_23_19_g401__1881 (.Z(chip_cd_n_92),
	.A(chip_cd_count[20]),
	.B(chip_cd_inc_add_23_19_n_296));
   XOR2X1 chip_cd_inc_add_23_19_g402__5115 (.Z(chip_cd_n_96),
	.A(chip_cd_count[24]),
	.B(chip_cd_inc_add_23_19_n_295));
   XOR2X1 chip_cd_inc_add_23_19_g403__7482 (.Z(chip_cd_n_89),
	.A(chip_cd_count[17]),
	.B(chip_cd_inc_add_23_19_n_291));
   AND2X1 chip_cd_inc_add_23_19_g404__4733 (.Z(chip_cd_inc_add_23_19_n_278),
	.A(chip_cd_inc_add_23_19_n_291),
	.B(chip_cd_count[17]));
   AND2X1 chip_cd_inc_add_23_19_g405__6161 (.Z(chip_cd_inc_add_23_19_n_281),
	.A(chip_cd_inc_add_23_19_n_295),
	.B(chip_cd_count[24]));
   AND2X1 chip_cd_inc_add_23_19_g406__9315 (.Z(chip_cd_inc_add_23_19_n_284),
	.A(chip_cd_inc_add_23_19_n_296),
	.B(chip_cd_count[20]));
   AND2X1 chip_cd_inc_add_23_19_g407__9945 (.Z(chip_cd_inc_add_23_19_n_287),
	.A(chip_cd_inc_add_23_19_n_296),
	.B(chip_cd_inc_add_23_19_n_370));
   NOR2X1 chip_cd_inc_add_23_19_g408__2883 (.Z(chip_cd_n_88),
	.A(chip_cd_inc_add_23_19_n_292),
	.B(chip_cd_inc_add_23_19_n_291));
   XOR2X1 chip_cd_inc_add_23_19_g409__2346 (.Z(chip_cd_n_87),
	.A(chip_cd_count[15]),
	.B(chip_cd_inc_add_23_19_n_306));
   XOR2X1 chip_cd_inc_add_23_19_g410__1666 (.Z(chip_cd_n_83),
	.A(chip_cd_count[11]),
	.B(chip_cd_inc_add_23_19_n_301));
   AND2X1 chip_cd_inc_add_23_19_g411__7410 (.Z(chip_cd_inc_add_23_19_n_291),
	.A(chip_cd_inc_add_23_19_n_304),
	.B(chip_cd_count[16]));
   NOR2X1 chip_cd_inc_add_23_19_g412__6417 (.Z(chip_cd_inc_add_23_19_n_292),
	.A(chip_cd_count[16]),
	.B(chip_cd_inc_add_23_19_n_304));
   NOR2X1 chip_cd_inc_add_23_19_g413__5477 (.Z(chip_cd_inc_add_23_19_n_295),
	.A(chip_cd_inc_add_23_19_n_321),
	.B(chip_cd_inc_add_23_19_n_305));
   NOR2X1 chip_cd_inc_add_23_19_g414__2398 (.Z(chip_cd_inc_add_23_19_n_296),
	.A(chip_cd_inc_add_23_19_n_349),
	.B(chip_cd_inc_add_23_19_n_305));
   XOR2X1 chip_cd_inc_add_23_19_g415__5107 (.Z(chip_cd_n_86),
	.A(chip_cd_count[14]),
	.B(chip_cd_inc_add_23_19_n_315));
   XOR2X1 chip_cd_inc_add_23_19_g416__6260 (.Z(chip_cd_n_82),
	.A(chip_cd_count[10]),
	.B(chip_cd_inc_add_23_19_n_311));
   XOR2X1 chip_cd_inc_add_23_19_g417__4319 (.Z(chip_cd_n_85),
	.A(chip_cd_count[13]),
	.B(chip_cd_inc_add_23_19_n_317));
   AND2X1 chip_cd_inc_add_23_19_g418__8428 (.Z(chip_cd_inc_add_23_19_n_301),
	.A(chip_cd_inc_add_23_19_n_311),
	.B(chip_cd_count[10]));
   INVX2 chip_cd_inc_add_23_19_g419 (.Z(chip_cd_inc_add_23_19_n_305),
	.A(chip_cd_inc_add_23_19_n_304));
   NOR2X1 chip_cd_inc_add_23_19_g420__5526 (.Z(chip_cd_inc_add_23_19_n_304),
	.A(chip_cd_inc_add_23_19_n_341),
	.B(chip_cd_inc_add_23_19_n_319));
   AND2X1 chip_cd_inc_add_23_19_g421__6783 (.Z(chip_cd_inc_add_23_19_n_306),
	.A(chip_cd_inc_add_23_19_n_315),
	.B(chip_cd_count[14]));
   XOR2X1 chip_cd_inc_add_23_19_g422__3680 (.Z(chip_cd_n_84),
	.A(chip_cd_count[12]),
	.B(chip_cd_inc_add_23_19_n_325));
   NOR2X1 chip_cd_inc_add_23_19_g423__1617 (.Z(chip_cd_n_81),
	.A(chip_cd_inc_add_23_19_n_312),
	.B(chip_cd_inc_add_23_19_n_311));
   AND2X1 chip_cd_inc_add_23_19_g424__2802 (.Z(chip_cd_inc_add_23_19_n_311),
	.A(chip_cd_inc_add_23_19_n_327),
	.B(chip_cd_count[9]));
   NOR2X1 chip_cd_inc_add_23_19_g425__1705 (.Z(chip_cd_inc_add_23_19_n_312),
	.A(chip_cd_count[9]),
	.B(chip_cd_inc_add_23_19_n_327));
   AND2X1 chip_cd_inc_add_23_19_g426__5122 (.Z(chip_cd_inc_add_23_19_n_315),
	.A(chip_cd_inc_add_23_19_n_325),
	.B(chip_cd_inc_add_23_19_n_367));
   AND2X1 chip_cd_inc_add_23_19_g427__8246 (.Z(chip_cd_inc_add_23_19_n_317),
	.A(chip_cd_inc_add_23_19_n_325),
	.B(chip_cd_count[12]));
   NAND3X1 chip_cd_inc_add_23_19_g428__7098 (.Z(chip_cd_inc_add_23_19_n_319),
	.A(chip_cd_inc_add_23_19_n_336),
	.B(chip_cd_count[15]),
	.C(chip_cd_count[14]));
   NAND3X1 chip_cd_inc_add_23_19_g429__6131 (.Z(chip_cd_inc_add_23_19_n_321),
	.A(chip_cd_inc_add_23_19_n_338),
	.B(chip_cd_count[23]),
	.C(chip_cd_count[22]));
   NOR2X1 chip_cd_inc_add_23_19_g430__1881 (.Z(chip_cd_n_80),
	.A(chip_cd_inc_add_23_19_n_328),
	.B(chip_cd_inc_add_23_19_n_327));
   XOR2X1 chip_cd_inc_add_23_19_g431__5115 (.Z(chip_cd_n_79),
	.A(chip_cd_count[7]),
	.B(chip_cd_inc_add_23_19_n_333));
   NOR2X1 chip_cd_inc_add_23_19_g432__7482 (.Z(chip_cd_inc_add_23_19_n_325),
	.A(chip_cd_inc_add_23_19_n_350),
	.B(chip_cd_inc_add_23_19_n_341));
   AND2X1 chip_cd_inc_add_23_19_g433__4733 (.Z(chip_cd_inc_add_23_19_n_327),
	.A(chip_cd_inc_add_23_19_n_340),
	.B(chip_cd_count[8]));
   NOR2X1 chip_cd_inc_add_23_19_g434__6161 (.Z(chip_cd_inc_add_23_19_n_328),
	.A(chip_cd_count[8]),
	.B(chip_cd_inc_add_23_19_n_340));
   XOR2X1 chip_cd_inc_add_23_19_g435__9315 (.Z(chip_cd_n_78),
	.A(chip_cd_count[6]),
	.B(chip_cd_inc_add_23_19_n_351));
   XOR2X1 chip_cd_inc_add_23_19_g436__9945 (.Z(chip_cd_n_77),
	.A(chip_cd_count[5]),
	.B(chip_cd_inc_add_23_19_n_345));
   AND2X1 chip_cd_inc_add_23_19_g437__2883 (.Z(chip_cd_inc_add_23_19_n_333),
	.A(chip_cd_inc_add_23_19_n_351),
	.B(chip_cd_count[6]));
   NOR2X1 chip_cd_inc_add_23_19_g438__2346 (.Z(chip_cd_inc_add_23_19_n_336),
	.A(chip_cd_inc_add_23_19_n_368),
	.B(chip_cd_inc_add_23_19_n_350));
   NOR2X1 chip_cd_inc_add_23_19_g439__1666 (.Z(chip_cd_inc_add_23_19_n_338),
	.A(chip_cd_inc_add_23_19_n_371),
	.B(chip_cd_inc_add_23_19_n_349));
   INVX2 chip_cd_inc_add_23_19_g440 (.Z(chip_cd_inc_add_23_19_n_341),
	.A(chip_cd_inc_add_23_19_n_340));
   NOR2X1 chip_cd_inc_add_23_19_g441__7410 (.Z(chip_cd_inc_add_23_19_n_340),
	.A(chip_cd_inc_add_23_19_n_359),
	.B(chip_cd_inc_add_23_19_n_352));
   NOR2X1 chip_cd_inc_add_23_19_g442__6417 (.Z(chip_cd_n_76),
	.A(chip_cd_inc_add_23_19_n_347),
	.B(chip_cd_inc_add_23_19_n_345));
   XOR2X1 chip_cd_inc_add_23_19_g443__5477 (.Z(chip_cd_n_75),
	.A(chip_cd_count[3]),
	.B(chip_cd_inc_add_23_19_n_355));
   NOR2X1 chip_cd_inc_add_23_19_g444__2398 (.Z(chip_cd_inc_add_23_19_n_345),
	.A(chip_cd_inc_add_23_19_n_397),
	.B(chip_cd_inc_add_23_19_n_359));
   AND2X1 chip_cd_inc_add_23_19_g445__5107 (.Z(chip_cd_inc_add_23_19_n_347),
	.A(chip_cd_inc_add_23_19_n_359),
	.B(chip_cd_inc_add_23_19_n_397));
   NAND3X1 chip_cd_inc_add_23_19_g446__6260 (.Z(chip_cd_inc_add_23_19_n_349),
	.A(chip_cd_inc_add_23_19_n_362),
	.B(chip_cd_count[16]),
	.C(chip_cd_count[17]));
   NAND3X1 chip_cd_inc_add_23_19_g447__4319 (.Z(chip_cd_inc_add_23_19_n_350),
	.A(chip_cd_inc_add_23_19_n_373),
	.B(chip_cd_count[8]),
	.C(chip_cd_count[9]));
   NOR2X1 chip_cd_inc_add_23_19_g448__8428 (.Z(chip_cd_inc_add_23_19_n_351),
	.A(chip_cd_inc_add_23_19_n_365),
	.B(chip_cd_inc_add_23_19_n_359));
   NAND3X1 chip_cd_inc_add_23_19_g449__5526 (.Z(chip_cd_inc_add_23_19_n_352),
	.A(chip_cd_inc_add_23_19_n_364),
	.B(chip_cd_count[7]),
	.C(chip_cd_count[6]));
   XOR2X1 chip_cd_inc_add_23_19_g450__6783 (.Z(chip_cd_n_74),
	.A(chip_cd_count[2]),
	.B(chip_cd_inc_add_23_19_n_361));
   AND2X1 chip_cd_inc_add_23_19_g451__3680 (.Z(chip_cd_inc_add_23_19_n_355),
	.A(chip_cd_inc_add_23_19_n_361),
	.B(chip_cd_count[2]));
   NOR2X1 chip_cd_inc_add_23_19_g452__1617 (.Z(chip_cd_n_73),
	.A(chip_cd_inc_add_23_19_n_375),
	.B(chip_cd_inc_add_23_19_n_361));
   NAND3X1 chip_cd_inc_add_23_19_g453__2802 (.Z(chip_cd_inc_add_23_19_n_359),
	.A(chip_cd_inc_add_23_19_n_361),
	.B(chip_cd_count[2]),
	.C(chip_cd_count[3]));
   AND2X1 chip_cd_inc_add_23_19_g454__1705 (.Z(chip_cd_inc_add_23_19_n_361),
	.A(chip_cd_count[0]),
	.B(chip_cd_count[1]));
   AND2X1 chip_cd_inc_add_23_19_g455__5122 (.Z(chip_cd_inc_add_23_19_n_362),
	.A(chip_cd_count[18]),
	.B(chip_cd_count[19]));
   INVX2 chip_cd_inc_add_23_19_g456 (.Z(chip_cd_inc_add_23_19_n_364),
	.A(chip_cd_inc_add_23_19_n_365));
   NAND2X1 chip_cd_inc_add_23_19_g457__8246 (.Z(chip_cd_inc_add_23_19_n_365),
	.A(chip_cd_count[4]),
	.B(chip_cd_count[5]));
   INVX2 chip_cd_inc_add_23_19_g458 (.Z(chip_cd_inc_add_23_19_n_367),
	.A(chip_cd_inc_add_23_19_n_368));
   NAND2X1 chip_cd_inc_add_23_19_g459__7098 (.Z(chip_cd_inc_add_23_19_n_368),
	.A(chip_cd_count[12]),
	.B(chip_cd_count[13]));
   INVX2 chip_cd_inc_add_23_19_g460 (.Z(chip_cd_inc_add_23_19_n_370),
	.A(chip_cd_inc_add_23_19_n_371));
   NAND2X1 chip_cd_inc_add_23_19_g461__6131 (.Z(chip_cd_inc_add_23_19_n_371),
	.A(chip_cd_count[20]),
	.B(chip_cd_count[21]));
   AND2X1 chip_cd_inc_add_23_19_g462__1881 (.Z(chip_cd_inc_add_23_19_n_373),
	.A(chip_cd_count[10]),
	.B(chip_cd_count[11]));
   NOR2X1 chip_cd_inc_add_23_19_g463__5115 (.Z(chip_cd_inc_add_23_19_n_375),
	.A(chip_cd_count[1]),
	.B(chip_cd_count[0]));
   INVX2 chip_cd_inc_add_23_19_g464 (.Z(chip_cd_inc_add_23_19_n_397),
	.A(chip_cd_count[4]));
endmodule

