/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID lab1-3.eng.utah.edu)
#  Generated on:      Wed Nov 29 21:25:11 2023
#  Design:            soc_top
#  Command:           saveNetlist -excludeLeafCell ../HDL/PLACED/soc_top_placed_modelsim.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Nov 28 2023 17:45:53 MST (Nov 29 2023 00:45:53 UTC)
// Verification Directory fv/soc_top 
module soc_top (
	clk, 
	reset, 
	btn_mode, 
	btn_set, 
	btn_inc, 
	btn_dec, 
	btn_light, 
	h1_6, 
	h1_5, 
	h1_4, 
	h1_3, 
	h1_2, 
	h1_1, 
	h1_0, 
	h0_6, 
	h0_5, 
	h0_4, 
	h0_3, 
	h0_2, 
	h0_1, 
	h0_0, 
	m1_6, 
	m1_5, 
	m1_4, 
	m1_3, 
	m1_2, 
	m1_1, 
	m1_0, 
	m0_6, 
	m0_5, 
	m0_4, 
	m0_3, 
	m0_2, 
	m0_1, 
	m0_0, 
	s1_6, 
	s1_5, 
	s1_4, 
	s1_3, 
	s1_2, 
	s1_1, 
	s1_0, 
	s0_6, 
	s0_5, 
	s0_4, 
	s0_3, 
	s0_2, 
	s0_1, 
	s0_0, 
	colon, 
	light);
   input clk;
   input reset;
   input btn_mode;
   input btn_set;
   input btn_inc;
   input btn_dec;
   input btn_light;
   output h1_6;
   output h1_5;
   output h1_4;
   output h1_3;
   output h1_2;
   output h1_1;
   output h1_0;
   output h0_6;
   output h0_5;
   output h0_4;
   output h0_3;
   output h0_2;
   output h0_1;
   output h0_0;
   output m1_6;
   output m1_5;
   output m1_4;
   output m1_3;
   output m1_2;
   output m1_1;
   output m1_0;
   output m0_6;
   output m0_5;
   output m0_4;
   output m0_3;
   output m0_2;
   output m0_1;
   output m0_0;
   output s1_6;
   output s1_5;
   output s1_4;
   output s1_3;
   output s1_2;
   output s1_1;
   output s1_0;
   output s0_6;
   output s0_5;
   output s0_4;
   output s0_3;
   output s0_2;
   output s0_1;
   output s0_0;
   output colon;
   output light;

   // Internal wires
   wire [2:0] chip_fsm_next_state;
   wire [2:0] chip_state;
   wire [2:0] chip_backlight_current_count;
   wire [25:0] chip_backlight_seconds_clk_count;
   wire [25:0] chip_cd_count;
   wire btn_dec_PAD;
   wire btn_inc_PAD;
   wire btn_light_PAD;
   wire btn_mode_PAD;
   wire btn_set_PAD;
   wire chip_backlight_light_clk;
   wire chip_backlight_light_mode;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_269;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_272;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_278;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_281;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_284;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_287;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_291;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_292;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_295;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_296;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_301;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_304;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_305;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_306;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_311;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_312;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_315;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_317;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_319;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_321;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_325;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_327;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_328;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_333;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_336;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_338;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_340;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_341;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_345;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_347;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_349;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_350;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_351;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_352;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_355;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_359;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_361;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_362;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_364;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_365;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_367;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_368;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_370;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_371;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_373;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_375;
   wire chip_backlight_seconds_clk_inc_add_23_19_n_397;
   wire chip_backlight_seconds_clk_n_73;
   wire chip_backlight_seconds_clk_n_74;
   wire chip_backlight_seconds_clk_n_75;
   wire chip_backlight_seconds_clk_n_76;
   wire chip_backlight_seconds_clk_n_77;
   wire chip_backlight_seconds_clk_n_78;
   wire chip_backlight_seconds_clk_n_79;
   wire chip_backlight_seconds_clk_n_80;
   wire chip_backlight_seconds_clk_n_81;
   wire chip_backlight_seconds_clk_n_82;
   wire chip_backlight_seconds_clk_n_83;
   wire chip_backlight_seconds_clk_n_84;
   wire chip_backlight_seconds_clk_n_85;
   wire chip_backlight_seconds_clk_n_86;
   wire chip_backlight_seconds_clk_n_87;
   wire chip_backlight_seconds_clk_n_88;
   wire chip_backlight_seconds_clk_n_89;
   wire chip_backlight_seconds_clk_n_90;
   wire chip_backlight_seconds_clk_n_91;
   wire chip_backlight_seconds_clk_n_92;
   wire chip_backlight_seconds_clk_n_93;
   wire chip_backlight_seconds_clk_n_94;
   wire chip_backlight_seconds_clk_n_95;
   wire chip_backlight_seconds_clk_n_96;
   wire chip_backlight_seconds_clk_n_97;
   wire chip_backlight_start_counter;
   wire chip_cd_inc_add_23_19_n_269;
   wire chip_cd_inc_add_23_19_n_272;
   wire chip_cd_inc_add_23_19_n_278;
   wire chip_cd_inc_add_23_19_n_281;
   wire chip_cd_inc_add_23_19_n_284;
   wire chip_cd_inc_add_23_19_n_287;
   wire chip_cd_inc_add_23_19_n_291;
   wire chip_cd_inc_add_23_19_n_292;
   wire chip_cd_inc_add_23_19_n_295;
   wire chip_cd_inc_add_23_19_n_296;
   wire chip_cd_inc_add_23_19_n_301;
   wire chip_cd_inc_add_23_19_n_304;
   wire chip_cd_inc_add_23_19_n_305;
   wire chip_cd_inc_add_23_19_n_306;
   wire chip_cd_inc_add_23_19_n_311;
   wire chip_cd_inc_add_23_19_n_312;
   wire chip_cd_inc_add_23_19_n_315;
   wire chip_cd_inc_add_23_19_n_317;
   wire chip_cd_inc_add_23_19_n_319;
   wire chip_cd_inc_add_23_19_n_321;
   wire chip_cd_inc_add_23_19_n_325;
   wire chip_cd_inc_add_23_19_n_327;
   wire chip_cd_inc_add_23_19_n_328;
   wire chip_cd_inc_add_23_19_n_333;
   wire chip_cd_inc_add_23_19_n_336;
   wire chip_cd_inc_add_23_19_n_338;
   wire chip_cd_inc_add_23_19_n_340;
   wire chip_cd_inc_add_23_19_n_341;
   wire chip_cd_inc_add_23_19_n_345;
   wire chip_cd_inc_add_23_19_n_347;
   wire chip_cd_inc_add_23_19_n_349;
   wire chip_cd_inc_add_23_19_n_350;
   wire chip_cd_inc_add_23_19_n_351;
   wire chip_cd_inc_add_23_19_n_352;
   wire chip_cd_inc_add_23_19_n_355;
   wire chip_cd_inc_add_23_19_n_359;
   wire chip_cd_inc_add_23_19_n_361;
   wire chip_cd_inc_add_23_19_n_362;
   wire chip_cd_inc_add_23_19_n_364;
   wire chip_cd_inc_add_23_19_n_365;
   wire chip_cd_inc_add_23_19_n_367;
   wire chip_cd_inc_add_23_19_n_368;
   wire chip_cd_inc_add_23_19_n_370;
   wire chip_cd_inc_add_23_19_n_371;
   wire chip_cd_inc_add_23_19_n_373;
   wire chip_cd_inc_add_23_19_n_375;
   wire chip_cd_inc_add_23_19_n_397;
   wire chip_cd_n_73;
   wire chip_cd_n_74;
   wire chip_cd_n_75;
   wire chip_cd_n_76;
   wire chip_cd_n_77;
   wire chip_cd_n_78;
   wire chip_cd_n_79;
   wire chip_cd_n_80;
   wire chip_cd_n_81;
   wire chip_cd_n_82;
   wire chip_cd_n_83;
   wire chip_cd_n_84;
   wire chip_cd_n_85;
   wire chip_cd_n_86;
   wire chip_cd_n_87;
   wire chip_cd_n_88;
   wire chip_cd_n_89;
   wire chip_cd_n_90;
   wire chip_cd_n_91;
   wire chip_cd_n_92;
   wire chip_cd_n_93;
   wire chip_cd_n_94;
   wire chip_cd_n_95;
   wire chip_cd_n_96;
   wire chip_cd_n_97;
   wire chip_clk_seconds;
   wire chip_displayer_enable_7seg;
   wire chip_displayer_last_seconds_clk;
   wire chip_fsm_n_490;
   wire chip_fsm_n_496;
   wire chip_fsm_swFF_Q_9;
   wire clk_PAD;
   wire h0_PAD_0;
   wire m0_PAD_0;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_43;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_87;
   wire n_88;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_104;
   wire n_108;
   wire n_109;
   wire n_114;
   wire n_115;
   wire n_119;
   wire n_133;
   wire n_134;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_144;
   wire n_145;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_282;
   wire n_283;
   wire n_284;
   wire n_285;
   wire reset_PAD;
   wire s0_PAD_0;

   pad_corner corner0 ();
   pad_corner corner1 ();
   pad_corner corner2 ();
   pad_corner corner3 ();
   pad_vdd vdd0 ();
   pad_gnd vss0 ();
   pad_in btn_dec_pad (.DataIn(btn_dec_PAD),
	.pad(btn_dec));
   pad_in btn_inc_pad (.DataIn(btn_inc_PAD),
	.pad(btn_inc));
   pad_in btn_light_pad (.DataIn(btn_light_PAD),
	.pad(btn_light));
   pad_in btn_mode_pad (.DataIn(btn_mode_PAD),
	.pad(btn_mode));
   pad_in btn_set_pad (.DataIn(btn_set_PAD),
	.pad(btn_set));
   pad_in clk_pad (.DataIn(clk_PAD),
	.pad(clk));
   pad_out colon_pad (.pad(colon),
	.DataOut(1'b0));
   pad_out h0_pad_0 (.pad(h0_0),
	.DataOut(h0_PAD_0));
   pad_out h0_pad_1 (.pad(h0_1),
	.DataOut(1'b0));
   pad_out h0_pad_2 (.pad(h0_2),
	.DataOut(1'b0));
   pad_out h0_pad_3 (.pad(h0_3),
	.DataOut(1'b0));
   pad_out h0_pad_4 (.pad(h0_4),
	.DataOut(1'b0));
   pad_out h0_pad_5 (.pad(h0_5),
	.DataOut(1'b0));
   pad_out h0_pad_6 (.pad(h0_6),
	.DataOut(1'b0));
   pad_out h1_pad_0 (.pad(h1_0),
	.DataOut(h0_PAD_0));
   pad_out h1_pad_1 (.pad(h1_1),
	.DataOut(1'b0));
   pad_out h1_pad_2 (.pad(h1_2),
	.DataOut(1'b0));
   pad_out h1_pad_3 (.pad(h1_3),
	.DataOut(1'b0));
   pad_out h1_pad_4 (.pad(h1_4),
	.DataOut(1'b0));
   pad_out h1_pad_5 (.pad(h1_5),
	.DataOut(1'b0));
   pad_out h1_pad_6 (.pad(h1_6),
	.DataOut(1'b0));
   pad_out light_pad (.pad(light),
	.DataOut(n_162));
   pad_out m0_pad_0 (.pad(m0_0),
	.DataOut(m0_PAD_0));
   pad_out m0_pad_1 (.pad(m0_1),
	.DataOut(1'b0));
   pad_out m0_pad_2 (.pad(m0_2),
	.DataOut(1'b0));
   pad_out m0_pad_3 (.pad(m0_3),
	.DataOut(1'b0));
   pad_out m0_pad_4 (.pad(m0_4),
	.DataOut(1'b0));
   pad_out m0_pad_5 (.pad(m0_5),
	.DataOut(1'b0));
   pad_out m0_pad_6 (.pad(m0_6),
	.DataOut(1'b0));
   pad_out m1_pad_0 (.pad(m1_0),
	.DataOut(m0_PAD_0));
   pad_out m1_pad_1 (.pad(m1_1),
	.DataOut(1'b0));
   pad_out m1_pad_2 (.pad(m1_2),
	.DataOut(1'b0));
   pad_out m1_pad_3 (.pad(m1_3),
	.DataOut(1'b0));
   pad_out m1_pad_4 (.pad(m1_4),
	.DataOut(1'b0));
   pad_out m1_pad_5 (.pad(m1_5),
	.DataOut(1'b0));
   pad_out m1_pad_6 (.pad(m1_6),
	.DataOut(1'b0));
   pad_in reset_pad (.DataIn(reset_PAD),
	.pad(reset));
   pad_out s0_pad_0 (.pad(s0_0),
	.DataOut(s0_PAD_0));
   pad_out s0_pad_1 (.pad(s0_1),
	.DataOut(1'b0));
   pad_out s0_pad_2 (.pad(s0_2),
	.DataOut(1'b0));
   pad_out s0_pad_3 (.pad(s0_3),
	.DataOut(1'b0));
   pad_out s0_pad_4 (.pad(s0_4),
	.DataOut(1'b0));
   pad_out s0_pad_5 (.pad(s0_5),
	.DataOut(1'b0));
   pad_out s0_pad_6 (.pad(s0_6),
	.DataOut(1'b0));
   pad_out s1_pad_0 (.pad(s1_0),
	.DataOut(s0_PAD_0));
   pad_out s1_pad_1 (.pad(s1_1),
	.DataOut(1'b0));
   pad_out s1_pad_2 (.pad(s1_2),
	.DataOut(1'b0));
   pad_out s1_pad_3 (.pad(s1_3),
	.DataOut(1'b0));
   pad_out s1_pad_4 (.pad(s1_4),
	.DataOut(1'b0));
   pad_out s1_pad_5 (.pad(s1_5),
	.DataOut(1'b0));
   pad_out s1_pad_6 (.pad(s1_6),
	.DataOut(1'b0));
   INVX2 g1936 (.Z(n_205),
	.A(chip_fsm_n_496));
   DFFQX1 \chip_fsm_next_state_reg[1]  (.Q(chip_fsm_next_state[1]),
	.CLK(clk_PAD),
	.D(n_204));
   NAND3X1 g2393__2398 (.Z(n_204),
	.A(n_203),
	.B(n_185),
	.C(n_170));
   NOR2X1 g2394__5107 (.Z(n_203),
	.A(n_190),
	.B(n_202));
   DFFQX1 \chip_fsm_next_state_reg[0]  (.Q(chip_fsm_next_state[0]),
	.CLK(clk_PAD),
	.D(n_201));
   NAND3X1 g2396__6260 (.Z(n_202),
	.A(n_199),
	.B(n_177),
	.C(n_181));
   DFFQX1 \chip_fsm_next_state_reg[2]  (.Q(chip_fsm_next_state[2]),
	.CLK(clk_PAD),
	.D(n_200));
   NAND3X1 g2398__4319 (.Z(n_201),
	.A(n_197),
	.B(n_198),
	.C(n_187));
   NAND3X1 g2399__8428 (.Z(n_200),
	.A(n_184),
	.B(n_193),
	.C(n_179));
   OR2X1 g2400__5526 (.Z(n_199),
	.A(btn_dec_PAD),
	.B(n_196));
   NOR2X1 g2401__6783 (.Z(n_198),
	.A(n_194),
	.B(n_191));
   NOR2X1 g2402__3680 (.Z(n_197),
	.A(n_182),
	.B(n_192));
   AND2X1 g2403__1617 (.Z(n_196),
	.A(n_195),
	.B(n_180));
   NAND3X1 g2404__2802 (.Z(n_195),
	.A(n_169),
	.B(chip_state[0]),
	.C(n_150));
   NOR2X1 g2405__1705 (.Z(n_194),
	.A(chip_state[1]),
	.B(n_189));
   AND2X1 g2406__5122 (.Z(n_193),
	.A(n_178),
	.B(n_188));
   NOR2X1 g2407__8246 (.Z(n_192),
	.A(btn_mode_PAD),
	.B(n_183));
   NOR2X1 g2408__7098 (.Z(n_191),
	.A(chip_fsm_n_496),
	.B(n_186));
   NOR2X1 g2409__6131 (.Z(n_190),
	.A(chip_state[0]),
	.B(n_173));
   NOR2X1 g2410__1881 (.Z(n_189),
	.A(n_171),
	.B(n_172));
   NAND3X1 g2411__5115 (.Z(n_188),
	.A(n_161),
	.B(n_149),
	.C(n_154));
   NAND3X1 g2412__7482 (.Z(n_187),
	.A(n_166),
	.B(chip_state[0]),
	.C(n_8));
   NOR2X1 g2413__4733 (.Z(n_186),
	.A(n_168),
	.B(n_176));
   OR2X1 g2414__6161 (.Z(n_185),
	.A(chip_state[2]),
	.B(chip_fsm_n_490));
   OR2X1 g2415__9315 (.Z(n_184),
	.A(n_166),
	.B(chip_fsm_n_490));
   NAND3X1 g2416__9945 (.Z(n_183),
	.A(n_158),
	.B(chip_state[2]),
	.C(btn_set_PAD));
   AND2X1 g2417__2883 (.Z(n_182),
	.A(n_161),
	.B(n_175));
   NAND3X1 g2418__2346 (.Z(n_181),
	.A(n_160),
	.B(n_156),
	.C(n_8));
   NAND2X1 g2419__1666 (.Z(n_180),
	.A(n_176),
	.B(n_159));
   NAND2X1 g2420__7410 (.Z(n_179),
	.A(n_174),
	.B(chip_state[1]));
   NAND3X1 g2421__6417 (.Z(n_178),
	.A(n_158),
	.B(chip_state[2]),
	.C(n_165));
   NAND3X1 g2422__5477 (.Z(n_177),
	.A(n_158),
	.B(n_150),
	.C(n_151));
   NAND2X1 g2423__2398 (.Z(n_175),
	.A(n_164),
	.B(n_154));
   NOR2X1 g2424__5107 (.Z(n_174),
	.A(n_157),
	.B(chip_fsm_n_496));
   NOR2X1 g2425__6260 (.Z(n_176),
	.A(btn_mode_PAD),
	.B(n_167));
   NAND2X1 g2426__4319 (.Z(chip_fsm_n_490),
	.A(n_158),
	.B(chip_fsm_swFF_Q_9));
   INVX2 g2427 (.Z(n_173),
	.A(n_172));
   NOR2X1 g2428__8428 (.Z(n_171),
	.A(chip_state[0]),
	.B(n_166));
   NAND2X1 g2429__5526 (.Z(n_170),
	.A(n_161),
	.B(btn_inc_PAD));
   NOR2X1 g2430__6783 (.Z(n_169),
	.A(btn_inc_PAD),
	.B(n_166));
   NOR2X1 g2431__3680 (.Z(n_168),
	.A(n_155),
	.B(n_167));
   NOR2X1 g2432__1617 (.Z(n_172),
	.A(n_150),
	.B(n_160));
   NAND2X1 g2433__2802 (.Z(n_165),
	.A(n_150),
	.B(btn_set_PAD));
   NAND2X1 g2434__1705 (.Z(n_164),
	.A(n_150),
	.B(btn_dec_PAD));
   DFFQSRX1 chip_backlight_light_reg (.Q(n_162),
	.CLK(clk_PAD),
	.D(chip_backlight_light_mode),
	.RESETB(1'b1),
	.SETB(n_5));
   NAND2X1 g2438__5122 (.Z(n_167),
	.A(chip_state[1]),
	.B(n_154));
   OR2X1 g2439__8246 (.Z(n_166),
	.A(n_151),
	.B(chip_state[2]));
   INVX2 g2440 (.Z(n_160),
	.A(n_159));
   NOR2X1 g2441__7098 (.Z(n_157),
	.A(btn_inc_PAD),
	.B(btn_dec_PAD));
   NAND2X1 g2442__6131 (.Z(n_156),
	.A(n_149),
	.B(n_150));
   OR2X1 g2443__1881 (.Z(chip_fsm_n_496),
	.A(chip_state[2]),
	.B(n_149));
   AND2X1 g2444__5115 (.Z(n_161),
	.A(n_8),
	.B(chip_state[2]));
   NOR2X1 g2445__7482 (.Z(n_159),
	.A(btn_set_PAD),
	.B(chip_state[2]));
   NOR2X1 g2446__4733 (.Z(n_158),
	.A(n_8),
	.B(chip_state[0]));
   INVX2 g2447 (.Z(n_155),
	.A(btn_dec_PAD));
   INVX2 g2448 (.Z(n_154),
	.A(btn_inc_PAD));
   INVX2 g2449 (.Z(n_8),
	.A(chip_state[1]));
   INVX2 g2451 (.Z(n_151),
	.A(btn_set_PAD));
   INVX2 g2452 (.Z(n_150),
	.A(btn_mode_PAD));
   INVX2 g2453 (.Z(n_149),
	.A(chip_state[0]));
   DFFQX1 \chip_backlight_current_count_reg[0]  (.Q(chip_backlight_current_count[0]),
	.CLK(n_10),
	.D(n_7));
   DFFQX1 \chip_backlight_current_count_reg[1]  (.Q(chip_backlight_current_count[1]),
	.CLK(n_10),
	.D(n_33));
   DFFQX1 \chip_backlight_current_count_reg[2]  (.Q(chip_backlight_current_count[2]),
	.CLK(n_10),
	.D(n_39));
   DFFQX1 chip_backlight_light_mode_reg (.Q(chip_backlight_light_mode),
	.CLK(n_10),
	.D(n_36));
   DFFQSRX1 chip_backlight_seconds_clk_clk_seconds_reg (.Q(chip_backlight_light_clk),
	.CLK(clk_PAD),
	.D(n_144),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[0]  (.Q(chip_backlight_seconds_clk_count[0]),
	.CLK(clk_PAD),
	.D(n_93),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[1]  (.Q(chip_backlight_seconds_clk_count[1]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_73),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[2]  (.Q(chip_backlight_seconds_clk_count[2]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_74),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[3]  (.Q(chip_backlight_seconds_clk_count[3]),
	.CLK(clk_PAD),
	.D(n_119),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[4]  (.Q(chip_backlight_seconds_clk_count[4]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_76),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[5]  (.Q(chip_backlight_seconds_clk_count[5]),
	.CLK(clk_PAD),
	.D(n_104),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[6]  (.Q(chip_backlight_seconds_clk_count[6]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_78),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[7]  (.Q(chip_backlight_seconds_clk_count[7]),
	.CLK(clk_PAD),
	.D(n_115),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[8]  (.Q(chip_backlight_seconds_clk_count[8]),
	.CLK(clk_PAD),
	.D(n_114),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[9]  (.Q(chip_backlight_seconds_clk_count[9]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_81),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[10]  (.Q(chip_backlight_seconds_clk_count[10]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_82),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[11]  (.Q(chip_backlight_seconds_clk_count[11]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_83),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[12]  (.Q(chip_backlight_seconds_clk_count[12]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_84),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[13]  (.Q(chip_backlight_seconds_clk_count[13]),
	.CLK(clk_PAD),
	.D(n_109),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[14]  (.Q(chip_backlight_seconds_clk_count[14]),
	.CLK(clk_PAD),
	.D(n_108),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[15]  (.Q(chip_backlight_seconds_clk_count[15]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_87),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[16]  (.Q(chip_backlight_seconds_clk_count[16]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_88),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[17]  (.Q(chip_backlight_seconds_clk_count[17]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_89),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[18]  (.Q(chip_backlight_seconds_clk_count[18]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_90),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[19]  (.Q(chip_backlight_seconds_clk_count[19]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_91),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[20]  (.Q(chip_backlight_seconds_clk_count[20]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_92),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[21]  (.Q(chip_backlight_seconds_clk_count[21]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_93),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[22]  (.Q(chip_backlight_seconds_clk_count[22]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_94),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[23]  (.Q(chip_backlight_seconds_clk_count[23]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_95),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[24]  (.Q(chip_backlight_seconds_clk_count[24]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_96),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 \chip_backlight_seconds_clk_count_reg[25]  (.Q(chip_backlight_seconds_clk_count[25]),
	.CLK(clk_PAD),
	.D(chip_backlight_seconds_clk_n_97),
	.RESETB(1'b1),
	.SETB(n_9));
   DFFQSRX1 chip_backlight_start_counter_reg (.Q(chip_backlight_start_counter),
	.CLK(clk_PAD),
	.D(btn_light_PAD),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 chip_cd_clk_seconds_reg (.Q(chip_clk_seconds),
	.CLK(clk_PAD),
	.D(n_145),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[0]  (.Q(chip_cd_count[0]),
	.CLK(clk_PAD),
	.D(n_92),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[1]  (.Q(chip_cd_count[1]),
	.CLK(clk_PAD),
	.D(chip_cd_n_73),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[2]  (.Q(chip_cd_count[2]),
	.CLK(clk_PAD),
	.D(chip_cd_n_74),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[3]  (.Q(chip_cd_count[3]),
	.CLK(clk_PAD),
	.D(n_94),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[4]  (.Q(chip_cd_count[4]),
	.CLK(clk_PAD),
	.D(chip_cd_n_76),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[5]  (.Q(chip_cd_count[5]),
	.CLK(clk_PAD),
	.D(n_141),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[6]  (.Q(chip_cd_count[6]),
	.CLK(clk_PAD),
	.D(chip_cd_n_78),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[7]  (.Q(chip_cd_count[7]),
	.CLK(clk_PAD),
	.D(n_140),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[8]  (.Q(chip_cd_count[8]),
	.CLK(clk_PAD),
	.D(n_139),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[9]  (.Q(chip_cd_count[9]),
	.CLK(clk_PAD),
	.D(chip_cd_n_81),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[10]  (.Q(chip_cd_count[10]),
	.CLK(clk_PAD),
	.D(chip_cd_n_82),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[11]  (.Q(chip_cd_count[11]),
	.CLK(clk_PAD),
	.D(chip_cd_n_83),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[12]  (.Q(chip_cd_count[12]),
	.CLK(clk_PAD),
	.D(chip_cd_n_84),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[13]  (.Q(chip_cd_count[13]),
	.CLK(clk_PAD),
	.D(n_134),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[14]  (.Q(chip_cd_count[14]),
	.CLK(clk_PAD),
	.D(n_133),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[15]  (.Q(chip_cd_count[15]),
	.CLK(clk_PAD),
	.D(chip_cd_n_87),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[16]  (.Q(chip_cd_count[16]),
	.CLK(clk_PAD),
	.D(chip_cd_n_88),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[17]  (.Q(chip_cd_count[17]),
	.CLK(clk_PAD),
	.D(chip_cd_n_89),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[18]  (.Q(chip_cd_count[18]),
	.CLK(clk_PAD),
	.D(chip_cd_n_90),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[19]  (.Q(chip_cd_count[19]),
	.CLK(clk_PAD),
	.D(chip_cd_n_91),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[20]  (.Q(chip_cd_count[20]),
	.CLK(clk_PAD),
	.D(chip_cd_n_92),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[21]  (.Q(chip_cd_count[21]),
	.CLK(clk_PAD),
	.D(chip_cd_n_93),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[22]  (.Q(chip_cd_count[22]),
	.CLK(clk_PAD),
	.D(chip_cd_n_94),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[23]  (.Q(chip_cd_count[23]),
	.CLK(clk_PAD),
	.D(chip_cd_n_95),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[24]  (.Q(chip_cd_count[24]),
	.CLK(clk_PAD),
	.D(chip_cd_n_96),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQSRX1 \chip_cd_count_reg[25]  (.Q(chip_cd_count[25]),
	.CLK(clk_PAD),
	.D(chip_cd_n_97),
	.RESETB(1'b1),
	.SETB(n_5));
   DFFQX1 \chip_displayer_display_h1_reg[0]  (.Q(h0_PAD_0),
	.CLK(clk_PAD),
	.D(n_53));
   DFFQX1 \chip_displayer_display_m1_reg[0]  (.Q(m0_PAD_0),
	.CLK(clk_PAD),
	.D(n_55));
   DFFQX1 \chip_displayer_display_s1_reg[0]  (.Q(s0_PAD_0),
	.CLK(clk_PAD),
	.D(n_54));
   DFFQSRX1 chip_displayer_enable_7seg_reg (.Q(chip_displayer_enable_7seg),
	.CLK(clk_PAD),
	.D(n_40),
	.RESETB(n_5),
	.SETB(1'b1));
   DFFQX1 chip_displayer_last_seconds_clk_reg (.Q(chip_displayer_last_seconds_clk),
	.CLK(clk_PAD),
	.D(n_51));
   DFFQX1 \chip_fsm_state_reg[0]  (.Q(chip_state[0]),
	.CLK(clk_PAD),
	.D(n_28));
   DFFQX1 \chip_fsm_state_reg[1]  (.Q(chip_state[1]),
	.CLK(clk_PAD),
	.D(n_27));
   DFFQX1 \chip_fsm_state_reg[2]  (.Q(chip_state[2]),
	.CLK(clk_PAD),
	.D(n_17));
   DFFQX1 chip_fsm_swFF_Q_reg (.Q(chip_fsm_swFF_Q_9),
	.CLK(clk_PAD),
	.D(n_41));
   XOR2X1 g4037__6161 (.Z(n_145),
	.A(chip_clk_seconds),
	.B(n_2));
   XOR2X1 g4038__9315 (.Z(n_144),
	.A(chip_backlight_light_clk),
	.B(n_3));
   AND2X1 g4066__9945 (.Z(n_141),
	.A(n_0),
	.B(chip_cd_n_77));
   AND2X1 g4067__2883 (.Z(n_140),
	.A(n_0),
	.B(chip_cd_n_79));
   AND2X1 g4068__2346 (.Z(n_139),
	.A(n_0),
	.B(chip_cd_n_80));
   AND2X1 g4073__1666 (.Z(n_134),
	.A(n_0),
	.B(chip_cd_n_85));
   AND2X1 g4074__7410 (.Z(n_133),
	.A(n_0),
	.B(chip_cd_n_86));
   AND2X1 g4088__6417 (.Z(n_119),
	.A(n_1),
	.B(chip_backlight_seconds_clk_n_75));
   AND2X1 g4092__5477 (.Z(n_115),
	.A(n_1),
	.B(chip_backlight_seconds_clk_n_79));
   AND2X1 g4093__2398 (.Z(n_114),
	.A(n_1),
	.B(chip_backlight_seconds_clk_n_80));
   AND2X1 g4098__5107 (.Z(n_109),
	.A(n_1),
	.B(chip_backlight_seconds_clk_n_85));
   AND2X1 g4099__6260 (.Z(n_108),
	.A(n_1),
	.B(chip_backlight_seconds_clk_n_86));
   AND2X1 g4103__4319 (.Z(n_104),
	.A(n_1),
	.B(chip_backlight_seconds_clk_n_77));
   AND2X1 g4113__8428 (.Z(n_94),
	.A(n_0),
	.B(chip_cd_n_75));
   NOR2X1 g4114__5526 (.Z(n_93),
	.A(chip_backlight_seconds_clk_count[0]),
	.B(n_3));
   NOR2X1 g4115__6783 (.Z(n_92),
	.A(chip_cd_count[0]),
	.B(n_2));
   OR2X1 g4117__3680 (.Z(n_1),
	.A(chip_backlight_seconds_clk_count[0]),
	.B(n_283));
   OR2X1 g4119__1617 (.Z(n_0),
	.A(chip_cd_count[0]),
	.B(n_88));
   OR2X1 g4121__1705 (.Z(n_88),
	.A(chip_cd_count[15]),
	.B(n_87));
   NAND3X1 g4122__5122 (.Z(n_87),
	.A(n_85),
	.B(chip_cd_count[14]),
	.C(chip_cd_count[13]));
   NOR2X1 g4124__7098 (.Z(n_85),
	.A(chip_cd_count[22]),
	.B(n_83));
   NOR2X1 g4125__6131 (.Z(n_84),
	.A(chip_backlight_seconds_clk_count[6]),
	.B(n_82));
   OR2X1 g4126__1881 (.Z(n_83),
	.A(chip_cd_count[23]),
	.B(n_81));
   NAND2X1 g4127__5115 (.Z(n_82),
	.A(n_80),
	.B(chip_backlight_seconds_clk_count[5]));
   OR2X1 g4128__7482 (.Z(n_81),
	.A(chip_cd_count[21]),
	.B(n_79));
   NOR2X1 g4129__4733 (.Z(n_80),
	.A(chip_backlight_seconds_clk_count[4]),
	.B(n_78));
   OR2X1 g4130__6161 (.Z(n_79),
	.A(chip_cd_count[20]),
	.B(n_77));
   NAND3X1 g4131__9315 (.Z(n_78),
	.A(n_76),
	.B(n_14),
	.C(chip_backlight_seconds_clk_count[3]));
   OR2X1 g4132__9945 (.Z(n_77),
	.A(chip_cd_count[18]),
	.B(n_75));
   NOR2X1 g4133__2883 (.Z(n_76),
	.A(chip_backlight_seconds_clk_count[1]),
	.B(n_74));
   OR2X1 g4134__2346 (.Z(n_75),
	.A(chip_cd_count[19]),
	.B(n_73));
   OR2X1 g4135__1666 (.Z(n_74),
	.A(chip_backlight_seconds_clk_count[21]),
	.B(n_72));
   OR2X1 g4136__7410 (.Z(n_73),
	.A(chip_cd_count[17]),
	.B(n_71));
   OR2X1 g4137__6417 (.Z(n_72),
	.A(chip_backlight_seconds_clk_count[20]),
	.B(n_69));
   OR2X1 g4138__5477 (.Z(n_71),
	.A(chip_cd_count[16]),
	.B(n_70));
   OR2X1 g4139__2398 (.Z(n_70),
	.A(chip_cd_count[12]),
	.B(n_67));
   OR2X1 g4140__5107 (.Z(n_69),
	.A(chip_backlight_seconds_clk_count[19]),
	.B(n_68));
   OR2X1 g4141__6260 (.Z(n_68),
	.A(chip_backlight_seconds_clk_count[18]),
	.B(n_65));
   OR2X1 g4142__4319 (.Z(n_67),
	.A(chip_cd_count[25]),
	.B(n_66));
   OR2X1 g4143__8428 (.Z(n_66),
	.A(chip_cd_count[24]),
	.B(n_63));
   OR2X1 g4144__5526 (.Z(n_65),
	.A(chip_backlight_seconds_clk_count[17]),
	.B(n_64));
   OR2X1 g4145__6783 (.Z(n_64),
	.A(chip_backlight_seconds_clk_count[16]),
	.B(n_62));
   OR2X1 g4146__3680 (.Z(n_63),
	.A(chip_cd_count[11]),
	.B(n_61));
   OR2X1 g4147__1617 (.Z(n_62),
	.A(chip_backlight_seconds_clk_count[23]),
	.B(n_60));
   OR2X1 g4148__2802 (.Z(n_61),
	.A(chip_cd_count[10]),
	.B(n_59));
   OR2X1 g4149__1705 (.Z(n_60),
	.A(chip_backlight_seconds_clk_count[22]),
	.B(n_58));
   OR2X1 g4150__5122 (.Z(n_59),
	.A(chip_cd_count[9]),
	.B(n_57));
   OR2X1 g4151__8246 (.Z(n_58),
	.A(chip_backlight_seconds_clk_count[15]),
	.B(n_56));
   NAND3X1 g4152__7098 (.Z(n_57),
	.A(n_52),
	.B(chip_cd_count[8]),
	.C(chip_cd_count[7]));
   NAND3X1 g4155__6131 (.Z(n_56),
	.A(n_48),
	.B(chip_backlight_seconds_clk_count[14]),
	.C(chip_backlight_seconds_clk_count[13]));
   OR2X1 g4158__1881 (.Z(n_55),
	.A(n_22),
	.B(n_50));
   OR2X1 g4159__5115 (.Z(n_54),
	.A(n_21),
	.B(n_47));
   NAND3X1 g4160__7482 (.Z(n_53),
	.A(n_43),
	.B(n_20),
	.C(n_16));
   NOR2X1 g4161__4733 (.Z(n_52),
	.A(chip_cd_count[6]),
	.B(n_285));
   MUX2X1 g4162__6161 (.Z(n_51),
	.A(chip_clk_seconds),
	.B(chip_displayer_last_seconds_clk),
	.S(reset_PAD));
   NAND3X1 g4166__9315 (.Z(n_50),
	.A(n_43),
	.B(n_38),
	.C(n_18));
   NOR2X1 g4168__2883 (.Z(n_48),
	.A(chip_backlight_seconds_clk_count[12]),
	.B(n_45));
   OR2X1 g4169__2346 (.Z(n_47),
	.A(n_22),
	.B(n_46));
   MUX2X1 g4170__1666 (.Z(n_46),
	.A(s0_PAD_0),
	.B(n_29),
	.S(n_5));
   OR2X1 g4172__7410 (.Z(n_45),
	.A(chip_backlight_seconds_clk_count[11]),
	.B(n_34));
   NAND3X1 g4176__5477 (.Z(n_41),
	.A(chip_fsm_n_490),
	.B(n_32),
	.C(n_26));
   XOR2X1 g4177__2398 (.Z(n_40),
	.A(chip_displayer_enable_7seg),
	.B(n_25));
   XOR2X1 g4178__5107 (.Z(n_39),
	.A(chip_backlight_current_count[2]),
	.B(n_24));
   AND2X1 g4179__6260 (.Z(n_43),
	.A(n_30),
	.B(n_37));
   NAND2X1 g4180__4319 (.Z(n_38),
	.A(n_21),
	.B(chip_state[2]));
   NAND2X1 g4181__8428 (.Z(n_37),
	.A(n_22),
	.B(chip_state[2]));
   OR2X1 g4182__5526 (.Z(n_36),
	.A(chip_backlight_current_count[2]),
	.B(n_23));
   NAND3X1 g4187__3680 (.Z(n_34),
	.A(n_12),
	.B(n_15),
	.C(chip_backlight_seconds_clk_count[8]));
   XOR2X1 g4188__1617 (.Z(n_33),
	.A(chip_backlight_current_count[0]),
	.B(chip_backlight_current_count[1]));
   NAND3X1 g4189__2802 (.Z(n_32),
	.A(n_205),
	.B(n_8),
	.C(chip_fsm_swFF_Q_9));
   NAND2X1 g4191__1705 (.Z(n_30),
	.A(n_29),
	.B(n_5));
   AND2X1 g4192__5122 (.Z(n_28),
	.A(n_5),
	.B(chip_fsm_next_state[0]));
   AND2X1 g4193__8246 (.Z(n_27),
	.A(n_5),
	.B(chip_fsm_next_state[1]));
   AND2X1 g4194__7098 (.Z(n_29),
	.A(chip_displayer_enable_7seg),
	.B(n_6));
   OR2X1 g4195__6131 (.Z(n_26),
	.A(chip_state[0]),
	.B(n_6));
   NOR2X1 g4196__1881 (.Z(n_25),
	.A(chip_displayer_last_seconds_clk),
	.B(n_11));
   INVX2 g4199 (.Z(n_24),
	.A(n_23));
   INVX2 g4200 (.Z(n_20),
	.A(n_21));
   NOR2X1 g4201__5115 (.Z(n_19),
	.A(chip_cd_count[2]),
	.B(chip_cd_count[1]));
   NAND2X1 g4202__7482 (.Z(n_18),
	.A(m0_PAD_0),
	.B(reset_PAD));
   AND2X1 g4203__4733 (.Z(n_17),
	.A(n_5),
	.B(chip_fsm_next_state[2]));
   NAND2X1 g4204__6161 (.Z(n_16),
	.A(h0_PAD_0),
	.B(reset_PAD));
   NAND2X1 g4205__9315 (.Z(n_23),
	.A(chip_backlight_current_count[1]),
	.B(chip_backlight_current_count[0]));
   NOR2X1 g4206__9945 (.Z(n_22),
	.A(reset_PAD),
	.B(chip_state[1]));
   NOR2X1 g4207__2883 (.Z(n_21),
	.A(reset_PAD),
	.B(chip_state[0]));
   INVX2 g4208 (.Z(n_15),
	.A(chip_backlight_seconds_clk_count[10]));
   INVX2 g4209 (.Z(n_14),
	.A(chip_backlight_seconds_clk_count[2]));
   INVX2 g4211 (.Z(n_12),
	.A(chip_backlight_seconds_clk_count[9]));
   INVX2 g4216 (.Z(n_11),
	.A(chip_clk_seconds));
   INVX2 g4217 (.Z(n_10),
	.A(chip_backlight_light_clk));
   INVX1 g4218 (.Z(n_9),
	.A(chip_backlight_start_counter));
   INVX2 g4225 (.Z(n_7),
	.A(chip_backlight_current_count[0]));
   INVX2 g4226 (.Z(n_6),
	.A(chip_state[2]));
   INVX2 g4231 (.Z(n_5),
	.A(reset_PAD));
   INVX2 drc_bufs4238 (.Z(n_3),
	.A(n_1));
   INVX2 drc_bufs4245 (.Z(n_2),
	.A(n_0));
   XOR2X1 chip_cd_inc_add_23_19_g393__2346 (.Z(chip_cd_n_95),
	.A(chip_cd_count[23]),
	.B(chip_cd_inc_add_23_19_n_272));
   XOR2X1 chip_cd_inc_add_23_19_g394__1666 (.Z(chip_cd_n_91),
	.A(chip_cd_count[19]),
	.B(chip_cd_inc_add_23_19_n_269));
   XOR2X1 chip_cd_inc_add_23_19_g395__7410 (.Z(chip_cd_n_90),
	.A(chip_cd_count[18]),
	.B(chip_cd_inc_add_23_19_n_278));
   XOR2X1 chip_cd_inc_add_23_19_g396__6417 (.Z(chip_cd_n_94),
	.A(chip_cd_count[22]),
	.B(chip_cd_inc_add_23_19_n_287));
   XOR2X1 chip_cd_inc_add_23_19_g397__5477 (.Z(chip_cd_n_93),
	.A(chip_cd_count[21]),
	.B(chip_cd_inc_add_23_19_n_284));
   XOR2X1 chip_cd_inc_add_23_19_g398__2398 (.Z(chip_cd_n_97),
	.A(chip_cd_count[25]),
	.B(chip_cd_inc_add_23_19_n_281));
   AND2X1 chip_cd_inc_add_23_19_g399__5107 (.Z(chip_cd_inc_add_23_19_n_269),
	.A(chip_cd_inc_add_23_19_n_278),
	.B(chip_cd_count[18]));
   AND2X1 chip_cd_inc_add_23_19_g400__6260 (.Z(chip_cd_inc_add_23_19_n_272),
	.A(chip_cd_inc_add_23_19_n_287),
	.B(chip_cd_count[22]));
   XOR2X1 chip_cd_inc_add_23_19_g401__4319 (.Z(chip_cd_n_92),
	.A(chip_cd_count[20]),
	.B(chip_cd_inc_add_23_19_n_296));
   XOR2X1 chip_cd_inc_add_23_19_g402__8428 (.Z(chip_cd_n_96),
	.A(chip_cd_count[24]),
	.B(chip_cd_inc_add_23_19_n_295));
   XOR2X1 chip_cd_inc_add_23_19_g403__5526 (.Z(chip_cd_n_89),
	.A(chip_cd_count[17]),
	.B(chip_cd_inc_add_23_19_n_291));
   AND2X1 chip_cd_inc_add_23_19_g404__6783 (.Z(chip_cd_inc_add_23_19_n_278),
	.A(chip_cd_inc_add_23_19_n_291),
	.B(chip_cd_count[17]));
   AND2X1 chip_cd_inc_add_23_19_g405__3680 (.Z(chip_cd_inc_add_23_19_n_281),
	.A(chip_cd_inc_add_23_19_n_295),
	.B(chip_cd_count[24]));
   AND2X1 chip_cd_inc_add_23_19_g406__1617 (.Z(chip_cd_inc_add_23_19_n_284),
	.A(chip_cd_inc_add_23_19_n_296),
	.B(chip_cd_count[20]));
   AND2X1 chip_cd_inc_add_23_19_g407__2802 (.Z(chip_cd_inc_add_23_19_n_287),
	.A(chip_cd_inc_add_23_19_n_296),
	.B(chip_cd_inc_add_23_19_n_370));
   NOR2X1 chip_cd_inc_add_23_19_g408__1705 (.Z(chip_cd_n_88),
	.A(chip_cd_inc_add_23_19_n_292),
	.B(chip_cd_inc_add_23_19_n_291));
   XOR2X1 chip_cd_inc_add_23_19_g409__5122 (.Z(chip_cd_n_87),
	.A(chip_cd_count[15]),
	.B(chip_cd_inc_add_23_19_n_306));
   XOR2X1 chip_cd_inc_add_23_19_g410__8246 (.Z(chip_cd_n_83),
	.A(chip_cd_count[11]),
	.B(chip_cd_inc_add_23_19_n_301));
   AND2X1 chip_cd_inc_add_23_19_g411__7098 (.Z(chip_cd_inc_add_23_19_n_291),
	.A(chip_cd_inc_add_23_19_n_304),
	.B(chip_cd_count[16]));
   NOR2X1 chip_cd_inc_add_23_19_g412__6131 (.Z(chip_cd_inc_add_23_19_n_292),
	.A(chip_cd_count[16]),
	.B(chip_cd_inc_add_23_19_n_304));
   NOR2X1 chip_cd_inc_add_23_19_g413__1881 (.Z(chip_cd_inc_add_23_19_n_295),
	.A(chip_cd_inc_add_23_19_n_321),
	.B(chip_cd_inc_add_23_19_n_305));
   NOR2X1 chip_cd_inc_add_23_19_g414__5115 (.Z(chip_cd_inc_add_23_19_n_296),
	.A(chip_cd_inc_add_23_19_n_349),
	.B(chip_cd_inc_add_23_19_n_305));
   XOR2X1 chip_cd_inc_add_23_19_g415__7482 (.Z(chip_cd_n_86),
	.A(chip_cd_count[14]),
	.B(chip_cd_inc_add_23_19_n_315));
   XOR2X1 chip_cd_inc_add_23_19_g416__4733 (.Z(chip_cd_n_82),
	.A(chip_cd_count[10]),
	.B(chip_cd_inc_add_23_19_n_311));
   XOR2X1 chip_cd_inc_add_23_19_g417__6161 (.Z(chip_cd_n_85),
	.A(chip_cd_count[13]),
	.B(chip_cd_inc_add_23_19_n_317));
   AND2X1 chip_cd_inc_add_23_19_g418__9315 (.Z(chip_cd_inc_add_23_19_n_301),
	.A(chip_cd_inc_add_23_19_n_311),
	.B(chip_cd_count[10]));
   INVX2 chip_cd_inc_add_23_19_g419 (.Z(chip_cd_inc_add_23_19_n_305),
	.A(chip_cd_inc_add_23_19_n_304));
   NOR2X1 chip_cd_inc_add_23_19_g420__9945 (.Z(chip_cd_inc_add_23_19_n_304),
	.A(chip_cd_inc_add_23_19_n_341),
	.B(chip_cd_inc_add_23_19_n_319));
   AND2X1 chip_cd_inc_add_23_19_g421__2883 (.Z(chip_cd_inc_add_23_19_n_306),
	.A(chip_cd_inc_add_23_19_n_315),
	.B(chip_cd_count[14]));
   XOR2X1 chip_cd_inc_add_23_19_g422__2346 (.Z(chip_cd_n_84),
	.A(chip_cd_count[12]),
	.B(chip_cd_inc_add_23_19_n_325));
   NOR2X1 chip_cd_inc_add_23_19_g423__1666 (.Z(chip_cd_n_81),
	.A(chip_cd_inc_add_23_19_n_312),
	.B(chip_cd_inc_add_23_19_n_311));
   AND2X1 chip_cd_inc_add_23_19_g424__7410 (.Z(chip_cd_inc_add_23_19_n_311),
	.A(chip_cd_inc_add_23_19_n_327),
	.B(chip_cd_count[9]));
   NOR2X1 chip_cd_inc_add_23_19_g425__6417 (.Z(chip_cd_inc_add_23_19_n_312),
	.A(chip_cd_count[9]),
	.B(chip_cd_inc_add_23_19_n_327));
   AND2X1 chip_cd_inc_add_23_19_g426__5477 (.Z(chip_cd_inc_add_23_19_n_315),
	.A(chip_cd_inc_add_23_19_n_325),
	.B(chip_cd_inc_add_23_19_n_367));
   AND2X1 chip_cd_inc_add_23_19_g427__2398 (.Z(chip_cd_inc_add_23_19_n_317),
	.A(chip_cd_inc_add_23_19_n_325),
	.B(chip_cd_count[12]));
   NAND3X1 chip_cd_inc_add_23_19_g428__5107 (.Z(chip_cd_inc_add_23_19_n_319),
	.A(chip_cd_inc_add_23_19_n_336),
	.B(chip_cd_count[15]),
	.C(chip_cd_count[14]));
   NAND3X1 chip_cd_inc_add_23_19_g429__6260 (.Z(chip_cd_inc_add_23_19_n_321),
	.A(chip_cd_inc_add_23_19_n_338),
	.B(chip_cd_count[23]),
	.C(chip_cd_count[22]));
   NOR2X1 chip_cd_inc_add_23_19_g430__4319 (.Z(chip_cd_n_80),
	.A(chip_cd_inc_add_23_19_n_328),
	.B(chip_cd_inc_add_23_19_n_327));
   XOR2X1 chip_cd_inc_add_23_19_g431__8428 (.Z(chip_cd_n_79),
	.A(chip_cd_count[7]),
	.B(chip_cd_inc_add_23_19_n_333));
   NOR2X1 chip_cd_inc_add_23_19_g432__5526 (.Z(chip_cd_inc_add_23_19_n_325),
	.A(chip_cd_inc_add_23_19_n_350),
	.B(chip_cd_inc_add_23_19_n_341));
   AND2X1 chip_cd_inc_add_23_19_g433__6783 (.Z(chip_cd_inc_add_23_19_n_327),
	.A(chip_cd_inc_add_23_19_n_340),
	.B(chip_cd_count[8]));
   NOR2X1 chip_cd_inc_add_23_19_g434__3680 (.Z(chip_cd_inc_add_23_19_n_328),
	.A(chip_cd_count[8]),
	.B(chip_cd_inc_add_23_19_n_340));
   XOR2X1 chip_cd_inc_add_23_19_g435__1617 (.Z(chip_cd_n_78),
	.A(chip_cd_count[6]),
	.B(chip_cd_inc_add_23_19_n_351));
   XOR2X1 chip_cd_inc_add_23_19_g436__2802 (.Z(chip_cd_n_77),
	.A(chip_cd_count[5]),
	.B(chip_cd_inc_add_23_19_n_345));
   AND2X1 chip_cd_inc_add_23_19_g437__1705 (.Z(chip_cd_inc_add_23_19_n_333),
	.A(chip_cd_inc_add_23_19_n_351),
	.B(chip_cd_count[6]));
   NOR2X1 chip_cd_inc_add_23_19_g438__5122 (.Z(chip_cd_inc_add_23_19_n_336),
	.A(chip_cd_inc_add_23_19_n_368),
	.B(chip_cd_inc_add_23_19_n_350));
   NOR2X1 chip_cd_inc_add_23_19_g439__8246 (.Z(chip_cd_inc_add_23_19_n_338),
	.A(chip_cd_inc_add_23_19_n_371),
	.B(chip_cd_inc_add_23_19_n_349));
   INVX2 chip_cd_inc_add_23_19_g440 (.Z(chip_cd_inc_add_23_19_n_341),
	.A(chip_cd_inc_add_23_19_n_340));
   NOR2X1 chip_cd_inc_add_23_19_g441__7098 (.Z(chip_cd_inc_add_23_19_n_340),
	.A(chip_cd_inc_add_23_19_n_359),
	.B(chip_cd_inc_add_23_19_n_352));
   NOR2X1 chip_cd_inc_add_23_19_g442__6131 (.Z(chip_cd_n_76),
	.A(chip_cd_inc_add_23_19_n_347),
	.B(chip_cd_inc_add_23_19_n_345));
   XOR2X1 chip_cd_inc_add_23_19_g443__1881 (.Z(chip_cd_n_75),
	.A(chip_cd_count[3]),
	.B(chip_cd_inc_add_23_19_n_355));
   NOR2X1 chip_cd_inc_add_23_19_g444__5115 (.Z(chip_cd_inc_add_23_19_n_345),
	.A(chip_cd_inc_add_23_19_n_397),
	.B(chip_cd_inc_add_23_19_n_359));
   AND2X1 chip_cd_inc_add_23_19_g445__7482 (.Z(chip_cd_inc_add_23_19_n_347),
	.A(chip_cd_inc_add_23_19_n_359),
	.B(chip_cd_inc_add_23_19_n_397));
   NAND3X1 chip_cd_inc_add_23_19_g446__4733 (.Z(chip_cd_inc_add_23_19_n_349),
	.A(chip_cd_inc_add_23_19_n_362),
	.B(chip_cd_count[16]),
	.C(chip_cd_count[17]));
   NAND3X1 chip_cd_inc_add_23_19_g447__6161 (.Z(chip_cd_inc_add_23_19_n_350),
	.A(chip_cd_inc_add_23_19_n_373),
	.B(chip_cd_count[8]),
	.C(chip_cd_count[9]));
   NOR2X1 chip_cd_inc_add_23_19_g448__9315 (.Z(chip_cd_inc_add_23_19_n_351),
	.A(chip_cd_inc_add_23_19_n_365),
	.B(chip_cd_inc_add_23_19_n_359));
   NAND3X1 chip_cd_inc_add_23_19_g449__9945 (.Z(chip_cd_inc_add_23_19_n_352),
	.A(chip_cd_inc_add_23_19_n_364),
	.B(chip_cd_count[7]),
	.C(chip_cd_count[6]));
   XOR2X1 chip_cd_inc_add_23_19_g450__2883 (.Z(chip_cd_n_74),
	.A(chip_cd_count[2]),
	.B(chip_cd_inc_add_23_19_n_361));
   AND2X1 chip_cd_inc_add_23_19_g451__2346 (.Z(chip_cd_inc_add_23_19_n_355),
	.A(chip_cd_inc_add_23_19_n_361),
	.B(chip_cd_count[2]));
   NOR2X1 chip_cd_inc_add_23_19_g452__1666 (.Z(chip_cd_n_73),
	.A(chip_cd_inc_add_23_19_n_375),
	.B(chip_cd_inc_add_23_19_n_361));
   NAND3X1 chip_cd_inc_add_23_19_g453__7410 (.Z(chip_cd_inc_add_23_19_n_359),
	.A(chip_cd_inc_add_23_19_n_361),
	.B(chip_cd_count[2]),
	.C(chip_cd_count[3]));
   AND2X1 chip_cd_inc_add_23_19_g454__6417 (.Z(chip_cd_inc_add_23_19_n_361),
	.A(chip_cd_count[0]),
	.B(chip_cd_count[1]));
   AND2X1 chip_cd_inc_add_23_19_g455__5477 (.Z(chip_cd_inc_add_23_19_n_362),
	.A(chip_cd_count[18]),
	.B(chip_cd_count[19]));
   INVX2 chip_cd_inc_add_23_19_g456 (.Z(chip_cd_inc_add_23_19_n_364),
	.A(chip_cd_inc_add_23_19_n_365));
   NAND2X1 chip_cd_inc_add_23_19_g457__2398 (.Z(chip_cd_inc_add_23_19_n_365),
	.A(chip_cd_count[4]),
	.B(chip_cd_count[5]));
   INVX2 chip_cd_inc_add_23_19_g458 (.Z(chip_cd_inc_add_23_19_n_367),
	.A(chip_cd_inc_add_23_19_n_368));
   NAND2X1 chip_cd_inc_add_23_19_g459__5107 (.Z(chip_cd_inc_add_23_19_n_368),
	.A(chip_cd_count[12]),
	.B(chip_cd_count[13]));
   INVX2 chip_cd_inc_add_23_19_g460 (.Z(chip_cd_inc_add_23_19_n_370),
	.A(chip_cd_inc_add_23_19_n_371));
   NAND2X1 chip_cd_inc_add_23_19_g461__6260 (.Z(chip_cd_inc_add_23_19_n_371),
	.A(chip_cd_count[20]),
	.B(chip_cd_count[21]));
   AND2X1 chip_cd_inc_add_23_19_g462__4319 (.Z(chip_cd_inc_add_23_19_n_373),
	.A(chip_cd_count[10]),
	.B(chip_cd_count[11]));
   NOR2X1 chip_cd_inc_add_23_19_g463__8428 (.Z(chip_cd_inc_add_23_19_n_375),
	.A(chip_cd_count[1]),
	.B(chip_cd_count[0]));
   INVX2 chip_cd_inc_add_23_19_g464 (.Z(chip_cd_inc_add_23_19_n_397),
	.A(chip_cd_count[4]));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g393__5526 (.Z(chip_backlight_seconds_clk_n_95),
	.A(chip_backlight_seconds_clk_count[23]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_272));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g394__6783 (.Z(chip_backlight_seconds_clk_n_91),
	.A(chip_backlight_seconds_clk_count[19]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_269));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g395__3680 (.Z(chip_backlight_seconds_clk_n_90),
	.A(chip_backlight_seconds_clk_count[18]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_278));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g396__1617 (.Z(chip_backlight_seconds_clk_n_94),
	.A(chip_backlight_seconds_clk_count[22]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_287));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g397__2802 (.Z(chip_backlight_seconds_clk_n_93),
	.A(chip_backlight_seconds_clk_count[21]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_284));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g398__1705 (.Z(chip_backlight_seconds_clk_n_97),
	.A(chip_backlight_seconds_clk_count[25]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_281));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g399__5122 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_269),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_278),
	.B(chip_backlight_seconds_clk_count[18]));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g400__8246 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_272),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_287),
	.B(chip_backlight_seconds_clk_count[22]));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g401__7098 (.Z(chip_backlight_seconds_clk_n_92),
	.A(chip_backlight_seconds_clk_count[20]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_296));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g402__6131 (.Z(chip_backlight_seconds_clk_n_96),
	.A(chip_backlight_seconds_clk_count[24]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_295));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g403__1881 (.Z(chip_backlight_seconds_clk_n_89),
	.A(chip_backlight_seconds_clk_count[17]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_291));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g404__5115 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_278),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_291),
	.B(chip_backlight_seconds_clk_count[17]));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g405__7482 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_281),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_295),
	.B(chip_backlight_seconds_clk_count[24]));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g406__4733 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_284),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_296),
	.B(chip_backlight_seconds_clk_count[20]));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g407__6161 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_287),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_296),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_370));
   NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g408__9315 (.Z(chip_backlight_seconds_clk_n_88),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_292),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_291));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g409__9945 (.Z(chip_backlight_seconds_clk_n_87),
	.A(chip_backlight_seconds_clk_count[15]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_306));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g410__2883 (.Z(chip_backlight_seconds_clk_n_83),
	.A(chip_backlight_seconds_clk_count[11]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_301));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g411__2346 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_291),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_304),
	.B(chip_backlight_seconds_clk_count[16]));
   NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g412__1666 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_292),
	.A(chip_backlight_seconds_clk_count[16]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_304));
   NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g413__7410 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_295),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_321),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_305));
   NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g414__6417 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_296),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_349),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_305));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g415__5477 (.Z(chip_backlight_seconds_clk_n_86),
	.A(chip_backlight_seconds_clk_count[14]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_315));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g416__2398 (.Z(chip_backlight_seconds_clk_n_82),
	.A(chip_backlight_seconds_clk_count[10]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_311));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g417__5107 (.Z(chip_backlight_seconds_clk_n_85),
	.A(chip_backlight_seconds_clk_count[13]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_317));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g418__6260 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_301),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_311),
	.B(chip_backlight_seconds_clk_count[10]));
   INVX2 chip_backlight_seconds_clk_inc_add_23_19_g419 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_305),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_304));
   NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g420__4319 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_304),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_341),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_319));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g421__8428 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_306),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_315),
	.B(chip_backlight_seconds_clk_count[14]));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g422__5526 (.Z(chip_backlight_seconds_clk_n_84),
	.A(chip_backlight_seconds_clk_count[12]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_325));
   NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g423__6783 (.Z(chip_backlight_seconds_clk_n_81),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_312),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_311));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g424__3680 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_311),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_327),
	.B(chip_backlight_seconds_clk_count[9]));
   NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g425__1617 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_312),
	.A(chip_backlight_seconds_clk_count[9]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_327));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g426__2802 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_315),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_325),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_367));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g427__1705 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_317),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_325),
	.B(chip_backlight_seconds_clk_count[12]));
   NAND3X1 chip_backlight_seconds_clk_inc_add_23_19_g428__5122 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_319),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_336),
	.B(chip_backlight_seconds_clk_count[15]),
	.C(chip_backlight_seconds_clk_count[14]));
   NAND3X1 chip_backlight_seconds_clk_inc_add_23_19_g429__8246 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_321),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_338),
	.B(chip_backlight_seconds_clk_count[23]),
	.C(chip_backlight_seconds_clk_count[22]));
   NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g430__7098 (.Z(chip_backlight_seconds_clk_n_80),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_328),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_327));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g431__6131 (.Z(chip_backlight_seconds_clk_n_79),
	.A(chip_backlight_seconds_clk_count[7]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_333));
   NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g432__1881 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_325),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_350),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_341));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g433__5115 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_327),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_340),
	.B(chip_backlight_seconds_clk_count[8]));
   NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g434__7482 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_328),
	.A(chip_backlight_seconds_clk_count[8]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_340));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g435__4733 (.Z(chip_backlight_seconds_clk_n_78),
	.A(chip_backlight_seconds_clk_count[6]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_351));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g436__6161 (.Z(chip_backlight_seconds_clk_n_77),
	.A(chip_backlight_seconds_clk_count[5]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_345));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g437__9315 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_333),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_351),
	.B(chip_backlight_seconds_clk_count[6]));
   NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g438__9945 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_336),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_368),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_350));
   NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g439__2883 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_338),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_371),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_349));
   INVX2 chip_backlight_seconds_clk_inc_add_23_19_g440 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_341),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_340));
   NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g441__2346 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_340),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_359),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_352));
   NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g442__1666 (.Z(chip_backlight_seconds_clk_n_76),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_347),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_345));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g443__7410 (.Z(chip_backlight_seconds_clk_n_75),
	.A(chip_backlight_seconds_clk_count[3]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_355));
   NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g444__6417 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_345),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_397),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_359));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g445__5477 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_347),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_359),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_397));
   NAND3X1 chip_backlight_seconds_clk_inc_add_23_19_g446__2398 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_349),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_362),
	.B(chip_backlight_seconds_clk_count[16]),
	.C(chip_backlight_seconds_clk_count[17]));
   NAND3X1 chip_backlight_seconds_clk_inc_add_23_19_g447__5107 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_350),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_373),
	.B(chip_backlight_seconds_clk_count[8]),
	.C(chip_backlight_seconds_clk_count[9]));
   NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g448__6260 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_351),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_365),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_359));
   NAND3X1 chip_backlight_seconds_clk_inc_add_23_19_g449__4319 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_352),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_364),
	.B(chip_backlight_seconds_clk_count[7]),
	.C(chip_backlight_seconds_clk_count[6]));
   XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g450__8428 (.Z(chip_backlight_seconds_clk_n_74),
	.A(chip_backlight_seconds_clk_count[2]),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_361));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g451__5526 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_355),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_361),
	.B(chip_backlight_seconds_clk_count[2]));
   NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g452__6783 (.Z(chip_backlight_seconds_clk_n_73),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_375),
	.B(chip_backlight_seconds_clk_inc_add_23_19_n_361));
   NAND3X1 chip_backlight_seconds_clk_inc_add_23_19_g453__3680 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_359),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_361),
	.B(chip_backlight_seconds_clk_count[2]),
	.C(chip_backlight_seconds_clk_count[3]));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g454__1617 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_361),
	.A(chip_backlight_seconds_clk_count[0]),
	.B(chip_backlight_seconds_clk_count[1]));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g455__2802 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_362),
	.A(chip_backlight_seconds_clk_count[18]),
	.B(chip_backlight_seconds_clk_count[19]));
   INVX2 chip_backlight_seconds_clk_inc_add_23_19_g456 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_364),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_365));
   NAND2X1 chip_backlight_seconds_clk_inc_add_23_19_g457__1705 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_365),
	.A(chip_backlight_seconds_clk_count[4]),
	.B(chip_backlight_seconds_clk_count[5]));
   INVX2 chip_backlight_seconds_clk_inc_add_23_19_g458 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_367),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_368));
   NAND2X1 chip_backlight_seconds_clk_inc_add_23_19_g459__5122 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_368),
	.A(chip_backlight_seconds_clk_count[12]),
	.B(chip_backlight_seconds_clk_count[13]));
   INVX2 chip_backlight_seconds_clk_inc_add_23_19_g460 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_370),
	.A(chip_backlight_seconds_clk_inc_add_23_19_n_371));
   NAND2X1 chip_backlight_seconds_clk_inc_add_23_19_g461__8246 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_371),
	.A(chip_backlight_seconds_clk_count[20]),
	.B(chip_backlight_seconds_clk_count[21]));
   AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g462__7098 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_373),
	.A(chip_backlight_seconds_clk_count[10]),
	.B(chip_backlight_seconds_clk_count[11]));
   NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g463__6131 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_375),
	.A(chip_backlight_seconds_clk_count[1]),
	.B(chip_backlight_seconds_clk_count[0]));
   INVX2 chip_backlight_seconds_clk_inc_add_23_19_g464 (.Z(chip_backlight_seconds_clk_inc_add_23_19_n_397),
	.A(chip_backlight_seconds_clk_count[4]));
   NAND3X1 g2 (.Z(n_283),
	.A(n_282),
	.B(n_84),
	.C(chip_backlight_seconds_clk_count[7]));
   NOR2X1 g3 (.Z(n_282),
	.A(chip_backlight_seconds_clk_count[24]),
	.B(chip_backlight_seconds_clk_count[25]));
   OR2X1 g4302 (.Z(n_285),
	.A(n_284),
	.B(chip_cd_count[4]));
   NAND3X1 g4303 (.Z(n_284),
	.A(n_19),
	.B(chip_cd_count[3]),
	.C(chip_cd_count[5]));
endmodule

