
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Nov 28 2023 17:45:53 MST (Nov 29 2023 00:45:53 UTC)

// Verification Directory fv/soc_top 

module soc_top(clk, reset, btn_mode, btn_set, btn_inc, btn_dec,
     btn_light, h1_6, h1_5, h1_4, h1_3, h1_2, h1_1, h1_0, h0_6, h0_5,
     h0_4, h0_3, h0_2, h0_1, h0_0, m1_6, m1_5, m1_4, m1_3, m1_2, m1_1,
     m1_0, m0_6, m0_5, m0_4, m0_3, m0_2, m0_1, m0_0, s1_6, s1_5, s1_4,
     s1_3, s1_2, s1_1, s1_0, s0_6, s0_5, s0_4, s0_3, s0_2, s0_1, s0_0,
     colon, light);
  input clk, reset, btn_mode, btn_set, btn_inc, btn_dec, btn_light;
  output h1_6, h1_5, h1_4, h1_3, h1_2, h1_1, h1_0, h0_6, h0_5, h0_4,
       h0_3, h0_2, h0_1, h0_0, m1_6, m1_5, m1_4, m1_3, m1_2, m1_1,
       m1_0, m0_6, m0_5, m0_4, m0_3, m0_2, m0_1, m0_0, s1_6, s1_5,
       s1_4, s1_3, s1_2, s1_1, s1_0, s0_6, s0_5, s0_4, s0_3, s0_2,
       s0_1, s0_0, colon, light;
  wire clk, reset, btn_mode, btn_set, btn_inc, btn_dec, btn_light;
  wire h1_6, h1_5, h1_4, h1_3, h1_2, h1_1, h1_0, h0_6, h0_5, h0_4,
       h0_3, h0_2, h0_1, h0_0, m1_6, m1_5, m1_4, m1_3, m1_2, m1_1,
       m1_0, m0_6, m0_5, m0_4, m0_3, m0_2, m0_1, m0_0, s1_6, s1_5,
       s1_4, s1_3, s1_2, s1_1, s1_0, s0_6, s0_5, s0_4, s0_3, s0_2,
       s0_1, s0_0, colon, light;
  wire [2:0] chip_fsm_next_state;
  wire [2:0] chip_state;
  wire [2:0] chip_backlight_current_count;
  wire [25:0] chip_backlight_seconds_clk_count;
  wire [25:0] chip_cd_count;
  wire btn_dec_PAD, btn_inc_PAD, btn_light_PAD, btn_mode_PAD,
       btn_set_PAD, chip_backlight_light_clk,
       chip_backlight_light_mode,
       chip_backlight_seconds_clk_inc_add_23_19_n_269;
  wire chip_backlight_seconds_clk_inc_add_23_19_n_272,
       chip_backlight_seconds_clk_inc_add_23_19_n_278,
       chip_backlight_seconds_clk_inc_add_23_19_n_281,
       chip_backlight_seconds_clk_inc_add_23_19_n_284,
       chip_backlight_seconds_clk_inc_add_23_19_n_287,
       chip_backlight_seconds_clk_inc_add_23_19_n_291,
       chip_backlight_seconds_clk_inc_add_23_19_n_292,
       chip_backlight_seconds_clk_inc_add_23_19_n_295;
  wire chip_backlight_seconds_clk_inc_add_23_19_n_296,
       chip_backlight_seconds_clk_inc_add_23_19_n_301,
       chip_backlight_seconds_clk_inc_add_23_19_n_304,
       chip_backlight_seconds_clk_inc_add_23_19_n_305,
       chip_backlight_seconds_clk_inc_add_23_19_n_306,
       chip_backlight_seconds_clk_inc_add_23_19_n_311,
       chip_backlight_seconds_clk_inc_add_23_19_n_312,
       chip_backlight_seconds_clk_inc_add_23_19_n_315;
  wire chip_backlight_seconds_clk_inc_add_23_19_n_317,
       chip_backlight_seconds_clk_inc_add_23_19_n_319,
       chip_backlight_seconds_clk_inc_add_23_19_n_321,
       chip_backlight_seconds_clk_inc_add_23_19_n_325,
       chip_backlight_seconds_clk_inc_add_23_19_n_327,
       chip_backlight_seconds_clk_inc_add_23_19_n_328,
       chip_backlight_seconds_clk_inc_add_23_19_n_333,
       chip_backlight_seconds_clk_inc_add_23_19_n_336;
  wire chip_backlight_seconds_clk_inc_add_23_19_n_338,
       chip_backlight_seconds_clk_inc_add_23_19_n_340,
       chip_backlight_seconds_clk_inc_add_23_19_n_341,
       chip_backlight_seconds_clk_inc_add_23_19_n_345,
       chip_backlight_seconds_clk_inc_add_23_19_n_347,
       chip_backlight_seconds_clk_inc_add_23_19_n_349,
       chip_backlight_seconds_clk_inc_add_23_19_n_350,
       chip_backlight_seconds_clk_inc_add_23_19_n_351;
  wire chip_backlight_seconds_clk_inc_add_23_19_n_352,
       chip_backlight_seconds_clk_inc_add_23_19_n_355,
       chip_backlight_seconds_clk_inc_add_23_19_n_359,
       chip_backlight_seconds_clk_inc_add_23_19_n_361,
       chip_backlight_seconds_clk_inc_add_23_19_n_362,
       chip_backlight_seconds_clk_inc_add_23_19_n_364,
       chip_backlight_seconds_clk_inc_add_23_19_n_365,
       chip_backlight_seconds_clk_inc_add_23_19_n_367;
  wire chip_backlight_seconds_clk_inc_add_23_19_n_368,
       chip_backlight_seconds_clk_inc_add_23_19_n_370,
       chip_backlight_seconds_clk_inc_add_23_19_n_371,
       chip_backlight_seconds_clk_inc_add_23_19_n_373,
       chip_backlight_seconds_clk_inc_add_23_19_n_375,
       chip_backlight_seconds_clk_inc_add_23_19_n_397,
       chip_backlight_seconds_clk_n_73, chip_backlight_seconds_clk_n_74;
  wire chip_backlight_seconds_clk_n_75,
       chip_backlight_seconds_clk_n_76,
       chip_backlight_seconds_clk_n_77,
       chip_backlight_seconds_clk_n_78,
       chip_backlight_seconds_clk_n_79,
       chip_backlight_seconds_clk_n_80,
       chip_backlight_seconds_clk_n_81, chip_backlight_seconds_clk_n_82;
  wire chip_backlight_seconds_clk_n_83,
       chip_backlight_seconds_clk_n_84,
       chip_backlight_seconds_clk_n_85,
       chip_backlight_seconds_clk_n_86,
       chip_backlight_seconds_clk_n_87,
       chip_backlight_seconds_clk_n_88,
       chip_backlight_seconds_clk_n_89, chip_backlight_seconds_clk_n_90;
  wire chip_backlight_seconds_clk_n_91,
       chip_backlight_seconds_clk_n_92,
       chip_backlight_seconds_clk_n_93,
       chip_backlight_seconds_clk_n_94,
       chip_backlight_seconds_clk_n_95,
       chip_backlight_seconds_clk_n_96,
       chip_backlight_seconds_clk_n_97, chip_backlight_start_counter;
  wire chip_cd_inc_add_23_19_n_269, chip_cd_inc_add_23_19_n_272,
       chip_cd_inc_add_23_19_n_278, chip_cd_inc_add_23_19_n_281,
       chip_cd_inc_add_23_19_n_284, chip_cd_inc_add_23_19_n_287,
       chip_cd_inc_add_23_19_n_291, chip_cd_inc_add_23_19_n_292;
  wire chip_cd_inc_add_23_19_n_295, chip_cd_inc_add_23_19_n_296,
       chip_cd_inc_add_23_19_n_301, chip_cd_inc_add_23_19_n_304,
       chip_cd_inc_add_23_19_n_305, chip_cd_inc_add_23_19_n_306,
       chip_cd_inc_add_23_19_n_311, chip_cd_inc_add_23_19_n_312;
  wire chip_cd_inc_add_23_19_n_315, chip_cd_inc_add_23_19_n_317,
       chip_cd_inc_add_23_19_n_319, chip_cd_inc_add_23_19_n_321,
       chip_cd_inc_add_23_19_n_325, chip_cd_inc_add_23_19_n_327,
       chip_cd_inc_add_23_19_n_328, chip_cd_inc_add_23_19_n_333;
  wire chip_cd_inc_add_23_19_n_336, chip_cd_inc_add_23_19_n_338,
       chip_cd_inc_add_23_19_n_340, chip_cd_inc_add_23_19_n_341,
       chip_cd_inc_add_23_19_n_345, chip_cd_inc_add_23_19_n_347,
       chip_cd_inc_add_23_19_n_349, chip_cd_inc_add_23_19_n_350;
  wire chip_cd_inc_add_23_19_n_351, chip_cd_inc_add_23_19_n_352,
       chip_cd_inc_add_23_19_n_355, chip_cd_inc_add_23_19_n_359,
       chip_cd_inc_add_23_19_n_361, chip_cd_inc_add_23_19_n_362,
       chip_cd_inc_add_23_19_n_364, chip_cd_inc_add_23_19_n_365;
  wire chip_cd_inc_add_23_19_n_367, chip_cd_inc_add_23_19_n_368,
       chip_cd_inc_add_23_19_n_370, chip_cd_inc_add_23_19_n_371,
       chip_cd_inc_add_23_19_n_373, chip_cd_inc_add_23_19_n_375,
       chip_cd_inc_add_23_19_n_397, chip_cd_n_73;
  wire chip_cd_n_74, chip_cd_n_75, chip_cd_n_76, chip_cd_n_77,
       chip_cd_n_78, chip_cd_n_79, chip_cd_n_80, chip_cd_n_81;
  wire chip_cd_n_82, chip_cd_n_83, chip_cd_n_84, chip_cd_n_85,
       chip_cd_n_86, chip_cd_n_87, chip_cd_n_88, chip_cd_n_89;
  wire chip_cd_n_90, chip_cd_n_91, chip_cd_n_92, chip_cd_n_93,
       chip_cd_n_94, chip_cd_n_95, chip_cd_n_96, chip_cd_n_97;
  wire chip_clk_seconds, chip_displayer_enable_7seg,
       chip_displayer_last_seconds_clk, chip_fsm_n_490, chip_fsm_n_496,
       chip_fsm_swFF_Q_9, clk_PAD, h0_PAD_0;
  wire light_PAD, m0_PAD_0, n_0, n_1, n_2, n_3, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_32;
  wire n_33, n_34, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_43, n_45, n_46, n_47, n_48, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_87, n_88, n_92, n_93, n_94, n_104, n_108;
  wire n_109, n_114, n_115, n_119, n_133, n_134, n_139, n_140;
  wire n_141, n_144, n_145, n_149, n_150, n_151, n_154, n_155;
  wire n_156, n_157, n_158, n_159, n_160, n_161, n_162, n_163;
  wire n_164, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177, n_178, n_179;
  wire n_180, n_181, n_182, n_183, n_184, n_185, n_186, n_187;
  wire n_188, n_189, n_190, n_191, n_192, n_193, n_194, n_195;
  wire n_196, n_197, n_198, n_199, n_200, n_201, n_202, n_203;
  wire n_204, n_205, n_258, n_259, n_260, n_266, n_267, n_268;
  wire n_274, n_275, n_276, n_282, n_283, n_284, n_285, reset_PAD;
  wire s0_PAD_0;

  pad_corner corner0 ();
  pad_corner corner1 ();
  pad_corner corner2 ();
  pad_corner corner3 ();
  pad_vdd vdd0 ();
  pad_gnd vss0 ();

  pad_in btn_dec_pad(.pad (btn_dec), .DataIn (btn_dec_PAD));
  pad_in btn_inc_pad(.pad (btn_inc), .DataIn (btn_inc_PAD));
  pad_in btn_light_pad(.pad (btn_light), .DataIn (btn_light_PAD));
  pad_in btn_mode_pad(.pad (btn_mode), .DataIn (btn_mode_PAD));
  pad_in btn_set_pad(.pad (btn_set), .DataIn (btn_set_PAD));
  pad_in clk_pad(.pad (clk), .DataIn (clk_PAD));
  pad_out colon_pad(.DataOut (1'b0), .pad (colon));
  pad_out h0_pad_0(.DataOut (n_259), .pad (h0_0));
  pad_out h0_pad_1(.DataOut (1'b0), .pad (h0_1));
  pad_out h0_pad_2(.DataOut (1'b0), .pad (h0_2));
  pad_out h0_pad_3(.DataOut (1'b0), .pad (h0_3));
  pad_out h0_pad_4(.DataOut (1'b0), .pad (h0_4));
  pad_out h0_pad_5(.DataOut (1'b0), .pad (h0_5));
  pad_out h0_pad_6(.DataOut (1'b0), .pad (h0_6));
  pad_out h1_pad_0(.DataOut (n_258), .pad (h1_0));
  pad_out h1_pad_1(.DataOut (1'b0), .pad (h1_1));
  pad_out h1_pad_2(.DataOut (1'b0), .pad (h1_2));
  pad_out h1_pad_3(.DataOut (1'b0), .pad (h1_3));
  pad_out h1_pad_4(.DataOut (1'b0), .pad (h1_4));
  pad_out h1_pad_5(.DataOut (1'b0), .pad (h1_5));
  pad_out h1_pad_6(.DataOut (1'b0), .pad (h1_6));
  pad_out light_pad(.DataOut (light_PAD), .pad (light));
  pad_out m0_pad_0(.DataOut (n_275), .pad (m0_0));
  pad_out m0_pad_1(.DataOut (1'b0), .pad (m0_1));
  pad_out m0_pad_2(.DataOut (1'b0), .pad (m0_2));
  pad_out m0_pad_3(.DataOut (1'b0), .pad (m0_3));
  pad_out m0_pad_4(.DataOut (1'b0), .pad (m0_4));
  pad_out m0_pad_5(.DataOut (1'b0), .pad (m0_5));
  pad_out m0_pad_6(.DataOut (1'b0), .pad (m0_6));
  pad_out m1_pad_0(.DataOut (n_274), .pad (m1_0));
  pad_out m1_pad_1(.DataOut (1'b0), .pad (m1_1));
  pad_out m1_pad_2(.DataOut (1'b0), .pad (m1_2));
  pad_out m1_pad_3(.DataOut (1'b0), .pad (m1_3));
  pad_out m1_pad_4(.DataOut (1'b0), .pad (m1_4));
  pad_out m1_pad_5(.DataOut (1'b0), .pad (m1_5));
  pad_out m1_pad_6(.DataOut (1'b0), .pad (m1_6));
  pad_in reset_pad(.pad (reset), .DataIn (reset_PAD));
  pad_out s0_pad_0(.DataOut (n_267), .pad (s0_0));
  pad_out s0_pad_1(.DataOut (1'b0), .pad (s0_1));
  pad_out s0_pad_2(.DataOut (1'b0), .pad (s0_2));
  pad_out s0_pad_3(.DataOut (1'b0), .pad (s0_3));
  pad_out s0_pad_4(.DataOut (1'b0), .pad (s0_4));
  pad_out s0_pad_5(.DataOut (1'b0), .pad (s0_5));
  pad_out s0_pad_6(.DataOut (1'b0), .pad (s0_6));
  pad_out s1_pad_0(.DataOut (n_266), .pad (s1_0));
  pad_out s1_pad_1(.DataOut (1'b0), .pad (s1_1));
  pad_out s1_pad_2(.DataOut (1'b0), .pad (s1_2));
  pad_out s1_pad_3(.DataOut (1'b0), .pad (s1_3));
  pad_out s1_pad_4(.DataOut (1'b0), .pad (s1_4));
  pad_out s1_pad_5(.DataOut (1'b0), .pad (s1_5));
  pad_out s1_pad_6(.DataOut (1'b0), .pad (s1_6));
  INVX2 g1936(.A (chip_fsm_n_496), .Z (n_205));
  DFFQX1 \chip_fsm_next_state_reg[1] (.CLK (clk_PAD), .D (n_204), .Q
       (chip_fsm_next_state[1]));
  NAND3X1 g2393__2398(.A (n_203), .B (n_185), .C (n_170), .Z (n_204));
  NOR2X1 g2394__5107(.A (n_190), .B (n_202), .Z (n_203));
  DFFQX1 \chip_fsm_next_state_reg[0] (.CLK (clk_PAD), .D (n_201), .Q
       (chip_fsm_next_state[0]));
  NAND3X1 g2396__6260(.A (n_199), .B (n_177), .C (n_181), .Z (n_202));
  DFFQX1 \chip_fsm_next_state_reg[2] (.CLK (clk_PAD), .D (n_200), .Q
       (chip_fsm_next_state[2]));
  NAND3X1 g2398__4319(.A (n_197), .B (n_198), .C (n_187), .Z (n_201));
  NAND3X1 g2399__8428(.A (n_184), .B (n_193), .C (n_179), .Z (n_200));
  OR2X1 g2400__5526(.A (btn_dec_PAD), .B (n_196), .Z (n_199));
  NOR2X1 g2401__6783(.A (n_194), .B (n_191), .Z (n_198));
  NOR2X1 g2402__3680(.A (n_182), .B (n_192), .Z (n_197));
  AND2X1 g2403__1617(.A (n_195), .B (n_180), .Z (n_196));
  NAND3X1 g2404__2802(.A (n_169), .B (chip_state[0]), .C (n_150), .Z
       (n_195));
  NOR2X1 g2405__1705(.A (chip_state[1]), .B (n_189), .Z (n_194));
  AND2X1 g2406__5122(.A (n_178), .B (n_188), .Z (n_193));
  NOR2X1 g2407__8246(.A (btn_mode_PAD), .B (n_183), .Z (n_192));
  NOR2X1 g2408__7098(.A (chip_fsm_n_496), .B (n_186), .Z (n_191));
  NOR2X1 g2409__6131(.A (chip_state[0]), .B (n_173), .Z (n_190));
  NOR2X1 g2410__1881(.A (n_171), .B (n_172), .Z (n_189));
  NAND3X1 g2411__5115(.A (n_161), .B (n_149), .C (n_154), .Z (n_188));
  NAND3X1 g2412__7482(.A (n_166), .B (chip_state[0]), .C (n_8), .Z
       (n_187));
  NOR2X1 g2413__4733(.A (n_168), .B (n_176), .Z (n_186));
  OR2X1 g2414__6161(.A (chip_state[2]), .B (chip_fsm_n_490), .Z
       (n_185));
  OR2X1 g2415__9315(.A (n_166), .B (chip_fsm_n_490), .Z (n_184));
  NAND3X1 g2416__9945(.A (n_158), .B (chip_state[2]), .C (btn_set_PAD),
       .Z (n_183));
  AND2X1 g2417__2883(.A (n_161), .B (n_175), .Z (n_182));
  NAND3X1 g2418__2346(.A (n_160), .B (n_156), .C (n_8), .Z (n_181));
  NAND2X1 g2419__1666(.A (n_176), .B (n_159), .Z (n_180));
  NAND2X1 g2420__7410(.A (n_174), .B (chip_state[1]), .Z (n_179));
  NAND3X1 g2421__6417(.A (n_158), .B (chip_state[2]), .C (n_165), .Z
       (n_178));
  NAND3X1 g2422__5477(.A (n_158), .B (n_150), .C (n_151), .Z (n_177));
  NAND2X1 g2423__2398(.A (n_164), .B (n_154), .Z (n_175));
  NOR2X1 g2424__5107(.A (n_157), .B (chip_fsm_n_496), .Z (n_174));
  NOR2X1 g2425__6260(.A (btn_mode_PAD), .B (n_167), .Z (n_176));
  NAND2X1 g2426__4319(.A (n_158), .B (chip_fsm_swFF_Q_9), .Z
       (chip_fsm_n_490));
  INVX2 g2427(.A (n_172), .Z (n_173));
  NOR2X1 g2428__8428(.A (chip_state[0]), .B (n_166), .Z (n_171));
  NAND2X1 g2429__5526(.A (n_161), .B (btn_inc_PAD), .Z (n_170));
  NOR2X1 g2430__6783(.A (btn_inc_PAD), .B (n_166), .Z (n_169));
  NOR2X1 g2431__3680(.A (n_155), .B (n_167), .Z (n_168));
  NOR2X1 g2432__1617(.A (n_150), .B (n_160), .Z (n_172));
  NAND2X1 g2433__2802(.A (n_150), .B (btn_set_PAD), .Z (n_165));
  NAND2X1 g2434__1705(.A (n_150), .B (btn_dec_PAD), .Z (n_164));
  DFFQSRX1 chip_backlight_light_reg(.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_backlight_light_mode), .Q (n_162));
  INVX4 g2436(.A (n_163), .Z (light_PAD));
  INVX2 g2437(.A (n_162), .Z (n_163));
  NAND2X1 g2438__5122(.A (chip_state[1]), .B (n_154), .Z (n_167));
  OR2X1 g2439__8246(.A (n_151), .B (chip_state[2]), .Z (n_166));
  INVX2 g2440(.A (n_159), .Z (n_160));
  NOR2X1 g2441__7098(.A (btn_inc_PAD), .B (btn_dec_PAD), .Z (n_157));
  NAND2X1 g2442__6131(.A (n_149), .B (n_150), .Z (n_156));
  OR2X1 g2443__1881(.A (chip_state[2]), .B (n_149), .Z
       (chip_fsm_n_496));
  AND2X1 g2444__5115(.A (n_8), .B (chip_state[2]), .Z (n_161));
  NOR2X1 g2445__7482(.A (btn_set_PAD), .B (chip_state[2]), .Z (n_159));
  NOR2X1 g2446__4733(.A (n_8), .B (chip_state[0]), .Z (n_158));
  INVX2 g2447(.A (btn_dec_PAD), .Z (n_155));
  INVX2 g2448(.A (btn_inc_PAD), .Z (n_154));
  INVX2 g2449(.A (chip_state[1]), .Z (n_8));
  INVX2 g2451(.A (btn_set_PAD), .Z (n_151));
  INVX2 g2452(.A (btn_mode_PAD), .Z (n_150));
  INVX2 g2453(.A (chip_state[0]), .Z (n_149));
  DFFQX1 \chip_backlight_current_count_reg[0] (.CLK (n_10), .D (n_7),
       .Q (chip_backlight_current_count[0]));
  DFFQX1 \chip_backlight_current_count_reg[1] (.CLK (n_10), .D (n_33),
       .Q (chip_backlight_current_count[1]));
  DFFQX1 \chip_backlight_current_count_reg[2] (.CLK (n_10), .D (n_39),
       .Q (chip_backlight_current_count[2]));
  DFFQX1 chip_backlight_light_mode_reg(.CLK (n_10), .D (n_36), .Q
       (chip_backlight_light_mode));
  DFFQSRX1 chip_backlight_seconds_clk_clk_seconds_reg(.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D (n_144), .Q
       (chip_backlight_light_clk));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[0] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D (n_93), .Q
       (chip_backlight_seconds_clk_count[0]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[1] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_73), .Q
       (chip_backlight_seconds_clk_count[1]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[2] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_74), .Q
       (chip_backlight_seconds_clk_count[2]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[3] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D (n_119), .Q
       (chip_backlight_seconds_clk_count[3]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[4] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_76), .Q
       (chip_backlight_seconds_clk_count[4]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[5] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D (n_104), .Q
       (chip_backlight_seconds_clk_count[5]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[6] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_78), .Q
       (chip_backlight_seconds_clk_count[6]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[7] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D (n_115), .Q
       (chip_backlight_seconds_clk_count[7]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[8] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D (n_114), .Q
       (chip_backlight_seconds_clk_count[8]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[9] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_81), .Q
       (chip_backlight_seconds_clk_count[9]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[10] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_82), .Q
       (chip_backlight_seconds_clk_count[10]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[11] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_83), .Q
       (chip_backlight_seconds_clk_count[11]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[12] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_84), .Q
       (chip_backlight_seconds_clk_count[12]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[13] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D (n_109), .Q
       (chip_backlight_seconds_clk_count[13]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[14] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D (n_108), .Q
       (chip_backlight_seconds_clk_count[14]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[15] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_87), .Q
       (chip_backlight_seconds_clk_count[15]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[16] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_88), .Q
       (chip_backlight_seconds_clk_count[16]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[17] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_89), .Q
       (chip_backlight_seconds_clk_count[17]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[18] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_90), .Q
       (chip_backlight_seconds_clk_count[18]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[19] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_91), .Q
       (chip_backlight_seconds_clk_count[19]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[20] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_92), .Q
       (chip_backlight_seconds_clk_count[20]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[21] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_93), .Q
       (chip_backlight_seconds_clk_count[21]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[22] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_94), .Q
       (chip_backlight_seconds_clk_count[22]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[23] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_95), .Q
       (chip_backlight_seconds_clk_count[23]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[24] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_96), .Q
       (chip_backlight_seconds_clk_count[24]));
  DFFQSRX1 \chip_backlight_seconds_clk_count_reg[25] (.SETB (n_9),
       .RESETB (1'b1), .CLK (clk_PAD), .D
       (chip_backlight_seconds_clk_n_97), .Q
       (chip_backlight_seconds_clk_count[25]));
  DFFQSRX1 chip_backlight_start_counter_reg(.SETB (n_5), .RESETB
       (1'b1), .CLK (clk_PAD), .D (btn_light_PAD), .Q
       (chip_backlight_start_counter));
  DFFQSRX1 chip_cd_clk_seconds_reg(.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_145), .Q (chip_clk_seconds));
  DFFQSRX1 \chip_cd_count_reg[0] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_92), .Q (chip_cd_count[0]));
  DFFQSRX1 \chip_cd_count_reg[1] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_73), .Q (chip_cd_count[1]));
  DFFQSRX1 \chip_cd_count_reg[2] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_74), .Q (chip_cd_count[2]));
  DFFQSRX1 \chip_cd_count_reg[3] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_94), .Q (chip_cd_count[3]));
  DFFQSRX1 \chip_cd_count_reg[4] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_76), .Q (chip_cd_count[4]));
  DFFQSRX1 \chip_cd_count_reg[5] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_141), .Q (chip_cd_count[5]));
  DFFQSRX1 \chip_cd_count_reg[6] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_78), .Q (chip_cd_count[6]));
  DFFQSRX1 \chip_cd_count_reg[7] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_140), .Q (chip_cd_count[7]));
  DFFQSRX1 \chip_cd_count_reg[8] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_139), .Q (chip_cd_count[8]));
  DFFQSRX1 \chip_cd_count_reg[9] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_81), .Q (chip_cd_count[9]));
  DFFQSRX1 \chip_cd_count_reg[10] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_82), .Q (chip_cd_count[10]));
  DFFQSRX1 \chip_cd_count_reg[11] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_83), .Q (chip_cd_count[11]));
  DFFQSRX1 \chip_cd_count_reg[12] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_84), .Q (chip_cd_count[12]));
  DFFQSRX1 \chip_cd_count_reg[13] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_134), .Q (chip_cd_count[13]));
  DFFQSRX1 \chip_cd_count_reg[14] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_133), .Q (chip_cd_count[14]));
  DFFQSRX1 \chip_cd_count_reg[15] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_87), .Q (chip_cd_count[15]));
  DFFQSRX1 \chip_cd_count_reg[16] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_88), .Q (chip_cd_count[16]));
  DFFQSRX1 \chip_cd_count_reg[17] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_89), .Q (chip_cd_count[17]));
  DFFQSRX1 \chip_cd_count_reg[18] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_90), .Q (chip_cd_count[18]));
  DFFQSRX1 \chip_cd_count_reg[19] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_91), .Q (chip_cd_count[19]));
  DFFQSRX1 \chip_cd_count_reg[20] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_92), .Q (chip_cd_count[20]));
  DFFQSRX1 \chip_cd_count_reg[21] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_93), .Q (chip_cd_count[21]));
  DFFQSRX1 \chip_cd_count_reg[22] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_94), .Q (chip_cd_count[22]));
  DFFQSRX1 \chip_cd_count_reg[23] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_95), .Q (chip_cd_count[23]));
  DFFQSRX1 \chip_cd_count_reg[24] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_96), .Q (chip_cd_count[24]));
  DFFQSRX1 \chip_cd_count_reg[25] (.SETB (n_5), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_97), .Q (chip_cd_count[25]));
  DFFQX1 \chip_displayer_display_h1_reg[0] (.CLK (clk_PAD), .D (n_53),
       .Q (h0_PAD_0));
  DFFQX1 \chip_displayer_display_m1_reg[0] (.CLK (clk_PAD), .D (n_55),
       .Q (m0_PAD_0));
  DFFQX1 \chip_displayer_display_s1_reg[0] (.CLK (clk_PAD), .D (n_54),
       .Q (s0_PAD_0));
  DFFQSRX1 chip_displayer_enable_7seg_reg(.SETB (1'b1), .RESETB (n_5),
       .CLK (clk_PAD), .D (n_40), .Q (chip_displayer_enable_7seg));
  DFFQX1 chip_displayer_last_seconds_clk_reg(.CLK (clk_PAD), .D (n_51),
       .Q (chip_displayer_last_seconds_clk));
  DFFQX1 \chip_fsm_state_reg[0] (.CLK (clk_PAD), .D (n_28), .Q
       (chip_state[0]));
  DFFQX1 \chip_fsm_state_reg[1] (.CLK (clk_PAD), .D (n_27), .Q
       (chip_state[1]));
  DFFQX1 \chip_fsm_state_reg[2] (.CLK (clk_PAD), .D (n_17), .Q
       (chip_state[2]));
  DFFQX1 chip_fsm_swFF_Q_reg(.CLK (clk_PAD), .D (n_41), .Q
       (chip_fsm_swFF_Q_9));
  XOR2X1 g4037__6161(.A (chip_clk_seconds), .B (n_2), .Z (n_145));
  XOR2X1 g4038__9315(.A (chip_backlight_light_clk), .B (n_3), .Z
       (n_144));
  AND2X1 g4066__9945(.A (n_0), .B (chip_cd_n_77), .Z (n_141));
  AND2X1 g4067__2883(.A (n_0), .B (chip_cd_n_79), .Z (n_140));
  AND2X1 g4068__2346(.A (n_0), .B (chip_cd_n_80), .Z (n_139));
  AND2X1 g4073__1666(.A (n_0), .B (chip_cd_n_85), .Z (n_134));
  AND2X1 g4074__7410(.A (n_0), .B (chip_cd_n_86), .Z (n_133));
  AND2X1 g4088__6417(.A (n_1), .B (chip_backlight_seconds_clk_n_75), .Z
       (n_119));
  AND2X1 g4092__5477(.A (n_1), .B (chip_backlight_seconds_clk_n_79), .Z
       (n_115));
  AND2X1 g4093__2398(.A (n_1), .B (chip_backlight_seconds_clk_n_80), .Z
       (n_114));
  AND2X1 g4098__5107(.A (n_1), .B (chip_backlight_seconds_clk_n_85), .Z
       (n_109));
  AND2X1 g4099__6260(.A (n_1), .B (chip_backlight_seconds_clk_n_86), .Z
       (n_108));
  AND2X1 g4103__4319(.A (n_1), .B (chip_backlight_seconds_clk_n_77), .Z
       (n_104));
  AND2X1 g4113__8428(.A (n_0), .B (chip_cd_n_75), .Z (n_94));
  NOR2X1 g4114__5526(.A (chip_backlight_seconds_clk_count[0]), .B
       (n_3), .Z (n_93));
  NOR2X1 g4115__6783(.A (chip_cd_count[0]), .B (n_2), .Z (n_92));
  OR2X1 g4117__3680(.A (chip_backlight_seconds_clk_count[0]), .B
       (n_283), .Z (n_1));
  OR2X1 g4119__1617(.A (chip_cd_count[0]), .B (n_88), .Z (n_0));
  OR2X1 g4121__1705(.A (chip_cd_count[15]), .B (n_87), .Z (n_88));
  NAND3X1 g4122__5122(.A (n_85), .B (chip_cd_count[14]), .C
       (chip_cd_count[13]), .Z (n_87));
  NOR2X1 g4124__7098(.A (chip_cd_count[22]), .B (n_83), .Z (n_85));
  NOR2X1 g4125__6131(.A (chip_backlight_seconds_clk_count[6]), .B
       (n_82), .Z (n_84));
  OR2X1 g4126__1881(.A (chip_cd_count[23]), .B (n_81), .Z (n_83));
  NAND2X1 g4127__5115(.A (n_80), .B
       (chip_backlight_seconds_clk_count[5]), .Z (n_82));
  OR2X1 g4128__7482(.A (chip_cd_count[21]), .B (n_79), .Z (n_81));
  NOR2X1 g4129__4733(.A (chip_backlight_seconds_clk_count[4]), .B
       (n_78), .Z (n_80));
  OR2X1 g4130__6161(.A (chip_cd_count[20]), .B (n_77), .Z (n_79));
  NAND3X1 g4131__9315(.A (n_76), .B (n_14), .C
       (chip_backlight_seconds_clk_count[3]), .Z (n_78));
  OR2X1 g4132__9945(.A (chip_cd_count[18]), .B (n_75), .Z (n_77));
  NOR2X1 g4133__2883(.A (chip_backlight_seconds_clk_count[1]), .B
       (n_74), .Z (n_76));
  OR2X1 g4134__2346(.A (chip_cd_count[19]), .B (n_73), .Z (n_75));
  OR2X1 g4135__1666(.A (chip_backlight_seconds_clk_count[21]), .B
       (n_72), .Z (n_74));
  OR2X1 g4136__7410(.A (chip_cd_count[17]), .B (n_71), .Z (n_73));
  OR2X1 g4137__6417(.A (chip_backlight_seconds_clk_count[20]), .B
       (n_69), .Z (n_72));
  OR2X1 g4138__5477(.A (chip_cd_count[16]), .B (n_70), .Z (n_71));
  OR2X1 g4139__2398(.A (chip_cd_count[12]), .B (n_67), .Z (n_70));
  OR2X1 g4140__5107(.A (chip_backlight_seconds_clk_count[19]), .B
       (n_68), .Z (n_69));
  OR2X1 g4141__6260(.A (chip_backlight_seconds_clk_count[18]), .B
       (n_65), .Z (n_68));
  OR2X1 g4142__4319(.A (chip_cd_count[25]), .B (n_66), .Z (n_67));
  OR2X1 g4143__8428(.A (chip_cd_count[24]), .B (n_63), .Z (n_66));
  OR2X1 g4144__5526(.A (chip_backlight_seconds_clk_count[17]), .B
       (n_64), .Z (n_65));
  OR2X1 g4145__6783(.A (chip_backlight_seconds_clk_count[16]), .B
       (n_62), .Z (n_64));
  OR2X1 g4146__3680(.A (chip_cd_count[11]), .B (n_61), .Z (n_63));
  OR2X1 g4147__1617(.A (chip_backlight_seconds_clk_count[23]), .B
       (n_60), .Z (n_62));
  OR2X1 g4148__2802(.A (chip_cd_count[10]), .B (n_59), .Z (n_61));
  OR2X1 g4149__1705(.A (chip_backlight_seconds_clk_count[22]), .B
       (n_58), .Z (n_60));
  OR2X1 g4150__5122(.A (chip_cd_count[9]), .B (n_57), .Z (n_59));
  OR2X1 g4151__8246(.A (chip_backlight_seconds_clk_count[15]), .B
       (n_56), .Z (n_58));
  NAND3X1 g4152__7098(.A (n_52), .B (chip_cd_count[8]), .C
       (chip_cd_count[7]), .Z (n_57));
  NAND3X1 g4155__6131(.A (n_48), .B
       (chip_backlight_seconds_clk_count[14]), .C
       (chip_backlight_seconds_clk_count[13]), .Z (n_56));
  OR2X1 g4158__1881(.A (n_22), .B (n_50), .Z (n_55));
  OR2X1 g4159__5115(.A (n_21), .B (n_47), .Z (n_54));
  NAND3X1 g4160__7482(.A (n_43), .B (n_20), .C (n_16), .Z (n_53));
  NOR2X1 g4161__4733(.A (chip_cd_count[6]), .B (n_285), .Z (n_52));
  MUX2X1 g4162__6161(.A (chip_clk_seconds), .B
       (chip_displayer_last_seconds_clk), .S (reset_PAD), .Z (n_51));
  NAND3X1 g4166__9315(.A (n_43), .B (n_38), .C (n_18), .Z (n_50));
  NOR2X1 g4168__2883(.A (chip_backlight_seconds_clk_count[12]), .B
       (n_45), .Z (n_48));
  OR2X1 g4169__2346(.A (n_22), .B (n_46), .Z (n_47));
  MUX2X1 g4170__1666(.A (s0_PAD_0), .B (n_29), .S (n_5), .Z (n_46));
  OR2X1 g4172__7410(.A (chip_backlight_seconds_clk_count[11]), .B
       (n_34), .Z (n_45));
  NAND3X1 g4176__5477(.A (chip_fsm_n_490), .B (n_32), .C (n_26), .Z
       (n_41));
  XOR2X1 g4177__2398(.A (chip_displayer_enable_7seg), .B (n_25), .Z
       (n_40));
  XOR2X1 g4178__5107(.A (chip_backlight_current_count[2]), .B (n_24),
       .Z (n_39));
  AND2X1 g4179__6260(.A (n_30), .B (n_37), .Z (n_43));
  NAND2X1 g4180__4319(.A (n_21), .B (chip_state[2]), .Z (n_38));
  NAND2X1 g4181__8428(.A (n_22), .B (chip_state[2]), .Z (n_37));
  OR2X1 g4182__5526(.A (chip_backlight_current_count[2]), .B (n_23), .Z
       (n_36));
  NAND3X1 g4187__3680(.A (n_12), .B (n_15), .C
       (chip_backlight_seconds_clk_count[8]), .Z (n_34));
  XOR2X1 g4188__1617(.A (chip_backlight_current_count[0]), .B
       (chip_backlight_current_count[1]), .Z (n_33));
  NAND3X1 g4189__2802(.A (n_205), .B (n_8), .C (chip_fsm_swFF_Q_9), .Z
       (n_32));
  NAND2X1 g4191__1705(.A (n_29), .B (n_5), .Z (n_30));
  AND2X1 g4192__5122(.A (n_5), .B (chip_fsm_next_state[0]), .Z (n_28));
  AND2X1 g4193__8246(.A (n_5), .B (chip_fsm_next_state[1]), .Z (n_27));
  AND2X1 g4194__7098(.A (chip_displayer_enable_7seg), .B (n_6), .Z
       (n_29));
  OR2X1 g4195__6131(.A (chip_state[0]), .B (n_6), .Z (n_26));
  NOR2X1 g4196__1881(.A (chip_displayer_last_seconds_clk), .B (n_11),
       .Z (n_25));
  INVX2 g4199(.A (n_23), .Z (n_24));
  INVX2 g4200(.A (n_21), .Z (n_20));
  NOR2X1 g4201__5115(.A (chip_cd_count[2]), .B (chip_cd_count[1]), .Z
       (n_19));
  NAND2X1 g4202__7482(.A (m0_PAD_0), .B (reset_PAD), .Z (n_18));
  AND2X1 g4203__4733(.A (n_5), .B (chip_fsm_next_state[2]), .Z (n_17));
  NAND2X1 g4204__6161(.A (h0_PAD_0), .B (reset_PAD), .Z (n_16));
  NAND2X1 g4205__9315(.A (chip_backlight_current_count[1]), .B
       (chip_backlight_current_count[0]), .Z (n_23));
  NOR2X1 g4206__9945(.A (reset_PAD), .B (chip_state[1]), .Z (n_22));
  NOR2X1 g4207__2883(.A (reset_PAD), .B (chip_state[0]), .Z (n_21));
  INVX2 g4208(.A (chip_backlight_seconds_clk_count[10]), .Z (n_15));
  INVX2 g4209(.A (chip_backlight_seconds_clk_count[2]), .Z (n_14));
  INVX2 g4211(.A (chip_backlight_seconds_clk_count[9]), .Z (n_12));
  INVX2 g4216(.A (chip_clk_seconds), .Z (n_11));
  INVX2 g4217(.A (chip_backlight_light_clk), .Z (n_10));
  INVX1 g4218(.A (chip_backlight_start_counter), .Z (n_9));
  INVX2 g4225(.A (chip_backlight_current_count[0]), .Z (n_7));
  INVX2 g4226(.A (chip_state[2]), .Z (n_6));
  INVX2 g4231(.A (reset_PAD), .Z (n_5));
  INVX2 drc_bufs4238(.A (n_1), .Z (n_3));
  INVX2 drc_bufs4245(.A (n_0), .Z (n_2));
  XOR2X1 chip_cd_inc_add_23_19_g393__2346(.A (chip_cd_count[23]), .B
       (chip_cd_inc_add_23_19_n_272), .Z (chip_cd_n_95));
  XOR2X1 chip_cd_inc_add_23_19_g394__1666(.A (chip_cd_count[19]), .B
       (chip_cd_inc_add_23_19_n_269), .Z (chip_cd_n_91));
  XOR2X1 chip_cd_inc_add_23_19_g395__7410(.A (chip_cd_count[18]), .B
       (chip_cd_inc_add_23_19_n_278), .Z (chip_cd_n_90));
  XOR2X1 chip_cd_inc_add_23_19_g396__6417(.A (chip_cd_count[22]), .B
       (chip_cd_inc_add_23_19_n_287), .Z (chip_cd_n_94));
  XOR2X1 chip_cd_inc_add_23_19_g397__5477(.A (chip_cd_count[21]), .B
       (chip_cd_inc_add_23_19_n_284), .Z (chip_cd_n_93));
  XOR2X1 chip_cd_inc_add_23_19_g398__2398(.A (chip_cd_count[25]), .B
       (chip_cd_inc_add_23_19_n_281), .Z (chip_cd_n_97));
  AND2X1 chip_cd_inc_add_23_19_g399__5107(.A
       (chip_cd_inc_add_23_19_n_278), .B (chip_cd_count[18]), .Z
       (chip_cd_inc_add_23_19_n_269));
  AND2X1 chip_cd_inc_add_23_19_g400__6260(.A
       (chip_cd_inc_add_23_19_n_287), .B (chip_cd_count[22]), .Z
       (chip_cd_inc_add_23_19_n_272));
  XOR2X1 chip_cd_inc_add_23_19_g401__4319(.A (chip_cd_count[20]), .B
       (chip_cd_inc_add_23_19_n_296), .Z (chip_cd_n_92));
  XOR2X1 chip_cd_inc_add_23_19_g402__8428(.A (chip_cd_count[24]), .B
       (chip_cd_inc_add_23_19_n_295), .Z (chip_cd_n_96));
  XOR2X1 chip_cd_inc_add_23_19_g403__5526(.A (chip_cd_count[17]), .B
       (chip_cd_inc_add_23_19_n_291), .Z (chip_cd_n_89));
  AND2X1 chip_cd_inc_add_23_19_g404__6783(.A
       (chip_cd_inc_add_23_19_n_291), .B (chip_cd_count[17]), .Z
       (chip_cd_inc_add_23_19_n_278));
  AND2X1 chip_cd_inc_add_23_19_g405__3680(.A
       (chip_cd_inc_add_23_19_n_295), .B (chip_cd_count[24]), .Z
       (chip_cd_inc_add_23_19_n_281));
  AND2X1 chip_cd_inc_add_23_19_g406__1617(.A
       (chip_cd_inc_add_23_19_n_296), .B (chip_cd_count[20]), .Z
       (chip_cd_inc_add_23_19_n_284));
  AND2X1 chip_cd_inc_add_23_19_g407__2802(.A
       (chip_cd_inc_add_23_19_n_296), .B (chip_cd_inc_add_23_19_n_370),
       .Z (chip_cd_inc_add_23_19_n_287));
  NOR2X1 chip_cd_inc_add_23_19_g408__1705(.A
       (chip_cd_inc_add_23_19_n_292), .B (chip_cd_inc_add_23_19_n_291),
       .Z (chip_cd_n_88));
  XOR2X1 chip_cd_inc_add_23_19_g409__5122(.A (chip_cd_count[15]), .B
       (chip_cd_inc_add_23_19_n_306), .Z (chip_cd_n_87));
  XOR2X1 chip_cd_inc_add_23_19_g410__8246(.A (chip_cd_count[11]), .B
       (chip_cd_inc_add_23_19_n_301), .Z (chip_cd_n_83));
  AND2X1 chip_cd_inc_add_23_19_g411__7098(.A
       (chip_cd_inc_add_23_19_n_304), .B (chip_cd_count[16]), .Z
       (chip_cd_inc_add_23_19_n_291));
  NOR2X1 chip_cd_inc_add_23_19_g412__6131(.A (chip_cd_count[16]), .B
       (chip_cd_inc_add_23_19_n_304), .Z (chip_cd_inc_add_23_19_n_292));
  NOR2X1 chip_cd_inc_add_23_19_g413__1881(.A
       (chip_cd_inc_add_23_19_n_321), .B (chip_cd_inc_add_23_19_n_305),
       .Z (chip_cd_inc_add_23_19_n_295));
  NOR2X1 chip_cd_inc_add_23_19_g414__5115(.A
       (chip_cd_inc_add_23_19_n_349), .B (chip_cd_inc_add_23_19_n_305),
       .Z (chip_cd_inc_add_23_19_n_296));
  XOR2X1 chip_cd_inc_add_23_19_g415__7482(.A (chip_cd_count[14]), .B
       (chip_cd_inc_add_23_19_n_315), .Z (chip_cd_n_86));
  XOR2X1 chip_cd_inc_add_23_19_g416__4733(.A (chip_cd_count[10]), .B
       (chip_cd_inc_add_23_19_n_311), .Z (chip_cd_n_82));
  XOR2X1 chip_cd_inc_add_23_19_g417__6161(.A (chip_cd_count[13]), .B
       (chip_cd_inc_add_23_19_n_317), .Z (chip_cd_n_85));
  AND2X1 chip_cd_inc_add_23_19_g418__9315(.A
       (chip_cd_inc_add_23_19_n_311), .B (chip_cd_count[10]), .Z
       (chip_cd_inc_add_23_19_n_301));
  INVX2 chip_cd_inc_add_23_19_g419(.A (chip_cd_inc_add_23_19_n_304), .Z
       (chip_cd_inc_add_23_19_n_305));
  NOR2X1 chip_cd_inc_add_23_19_g420__9945(.A
       (chip_cd_inc_add_23_19_n_341), .B (chip_cd_inc_add_23_19_n_319),
       .Z (chip_cd_inc_add_23_19_n_304));
  AND2X1 chip_cd_inc_add_23_19_g421__2883(.A
       (chip_cd_inc_add_23_19_n_315), .B (chip_cd_count[14]), .Z
       (chip_cd_inc_add_23_19_n_306));
  XOR2X1 chip_cd_inc_add_23_19_g422__2346(.A (chip_cd_count[12]), .B
       (chip_cd_inc_add_23_19_n_325), .Z (chip_cd_n_84));
  NOR2X1 chip_cd_inc_add_23_19_g423__1666(.A
       (chip_cd_inc_add_23_19_n_312), .B (chip_cd_inc_add_23_19_n_311),
       .Z (chip_cd_n_81));
  AND2X1 chip_cd_inc_add_23_19_g424__7410(.A
       (chip_cd_inc_add_23_19_n_327), .B (chip_cd_count[9]), .Z
       (chip_cd_inc_add_23_19_n_311));
  NOR2X1 chip_cd_inc_add_23_19_g425__6417(.A (chip_cd_count[9]), .B
       (chip_cd_inc_add_23_19_n_327), .Z (chip_cd_inc_add_23_19_n_312));
  AND2X1 chip_cd_inc_add_23_19_g426__5477(.A
       (chip_cd_inc_add_23_19_n_325), .B (chip_cd_inc_add_23_19_n_367),
       .Z (chip_cd_inc_add_23_19_n_315));
  AND2X1 chip_cd_inc_add_23_19_g427__2398(.A
       (chip_cd_inc_add_23_19_n_325), .B (chip_cd_count[12]), .Z
       (chip_cd_inc_add_23_19_n_317));
  NAND3X1 chip_cd_inc_add_23_19_g428__5107(.A
       (chip_cd_inc_add_23_19_n_336), .B (chip_cd_count[15]), .C
       (chip_cd_count[14]), .Z (chip_cd_inc_add_23_19_n_319));
  NAND3X1 chip_cd_inc_add_23_19_g429__6260(.A
       (chip_cd_inc_add_23_19_n_338), .B (chip_cd_count[23]), .C
       (chip_cd_count[22]), .Z (chip_cd_inc_add_23_19_n_321));
  NOR2X1 chip_cd_inc_add_23_19_g430__4319(.A
       (chip_cd_inc_add_23_19_n_328), .B (chip_cd_inc_add_23_19_n_327),
       .Z (chip_cd_n_80));
  XOR2X1 chip_cd_inc_add_23_19_g431__8428(.A (chip_cd_count[7]), .B
       (chip_cd_inc_add_23_19_n_333), .Z (chip_cd_n_79));
  NOR2X1 chip_cd_inc_add_23_19_g432__5526(.A
       (chip_cd_inc_add_23_19_n_350), .B (chip_cd_inc_add_23_19_n_341),
       .Z (chip_cd_inc_add_23_19_n_325));
  AND2X1 chip_cd_inc_add_23_19_g433__6783(.A
       (chip_cd_inc_add_23_19_n_340), .B (chip_cd_count[8]), .Z
       (chip_cd_inc_add_23_19_n_327));
  NOR2X1 chip_cd_inc_add_23_19_g434__3680(.A (chip_cd_count[8]), .B
       (chip_cd_inc_add_23_19_n_340), .Z (chip_cd_inc_add_23_19_n_328));
  XOR2X1 chip_cd_inc_add_23_19_g435__1617(.A (chip_cd_count[6]), .B
       (chip_cd_inc_add_23_19_n_351), .Z (chip_cd_n_78));
  XOR2X1 chip_cd_inc_add_23_19_g436__2802(.A (chip_cd_count[5]), .B
       (chip_cd_inc_add_23_19_n_345), .Z (chip_cd_n_77));
  AND2X1 chip_cd_inc_add_23_19_g437__1705(.A
       (chip_cd_inc_add_23_19_n_351), .B (chip_cd_count[6]), .Z
       (chip_cd_inc_add_23_19_n_333));
  NOR2X1 chip_cd_inc_add_23_19_g438__5122(.A
       (chip_cd_inc_add_23_19_n_368), .B (chip_cd_inc_add_23_19_n_350),
       .Z (chip_cd_inc_add_23_19_n_336));
  NOR2X1 chip_cd_inc_add_23_19_g439__8246(.A
       (chip_cd_inc_add_23_19_n_371), .B (chip_cd_inc_add_23_19_n_349),
       .Z (chip_cd_inc_add_23_19_n_338));
  INVX2 chip_cd_inc_add_23_19_g440(.A (chip_cd_inc_add_23_19_n_340), .Z
       (chip_cd_inc_add_23_19_n_341));
  NOR2X1 chip_cd_inc_add_23_19_g441__7098(.A
       (chip_cd_inc_add_23_19_n_359), .B (chip_cd_inc_add_23_19_n_352),
       .Z (chip_cd_inc_add_23_19_n_340));
  NOR2X1 chip_cd_inc_add_23_19_g442__6131(.A
       (chip_cd_inc_add_23_19_n_347), .B (chip_cd_inc_add_23_19_n_345),
       .Z (chip_cd_n_76));
  XOR2X1 chip_cd_inc_add_23_19_g443__1881(.A (chip_cd_count[3]), .B
       (chip_cd_inc_add_23_19_n_355), .Z (chip_cd_n_75));
  NOR2X1 chip_cd_inc_add_23_19_g444__5115(.A
       (chip_cd_inc_add_23_19_n_397), .B (chip_cd_inc_add_23_19_n_359),
       .Z (chip_cd_inc_add_23_19_n_345));
  AND2X1 chip_cd_inc_add_23_19_g445__7482(.A
       (chip_cd_inc_add_23_19_n_359), .B (chip_cd_inc_add_23_19_n_397),
       .Z (chip_cd_inc_add_23_19_n_347));
  NAND3X1 chip_cd_inc_add_23_19_g446__4733(.A
       (chip_cd_inc_add_23_19_n_362), .B (chip_cd_count[16]), .C
       (chip_cd_count[17]), .Z (chip_cd_inc_add_23_19_n_349));
  NAND3X1 chip_cd_inc_add_23_19_g447__6161(.A
       (chip_cd_inc_add_23_19_n_373), .B (chip_cd_count[8]), .C
       (chip_cd_count[9]), .Z (chip_cd_inc_add_23_19_n_350));
  NOR2X1 chip_cd_inc_add_23_19_g448__9315(.A
       (chip_cd_inc_add_23_19_n_365), .B (chip_cd_inc_add_23_19_n_359),
       .Z (chip_cd_inc_add_23_19_n_351));
  NAND3X1 chip_cd_inc_add_23_19_g449__9945(.A
       (chip_cd_inc_add_23_19_n_364), .B (chip_cd_count[7]), .C
       (chip_cd_count[6]), .Z (chip_cd_inc_add_23_19_n_352));
  XOR2X1 chip_cd_inc_add_23_19_g450__2883(.A (chip_cd_count[2]), .B
       (chip_cd_inc_add_23_19_n_361), .Z (chip_cd_n_74));
  AND2X1 chip_cd_inc_add_23_19_g451__2346(.A
       (chip_cd_inc_add_23_19_n_361), .B (chip_cd_count[2]), .Z
       (chip_cd_inc_add_23_19_n_355));
  NOR2X1 chip_cd_inc_add_23_19_g452__1666(.A
       (chip_cd_inc_add_23_19_n_375), .B (chip_cd_inc_add_23_19_n_361),
       .Z (chip_cd_n_73));
  NAND3X1 chip_cd_inc_add_23_19_g453__7410(.A
       (chip_cd_inc_add_23_19_n_361), .B (chip_cd_count[2]), .C
       (chip_cd_count[3]), .Z (chip_cd_inc_add_23_19_n_359));
  AND2X1 chip_cd_inc_add_23_19_g454__6417(.A (chip_cd_count[0]), .B
       (chip_cd_count[1]), .Z (chip_cd_inc_add_23_19_n_361));
  AND2X1 chip_cd_inc_add_23_19_g455__5477(.A (chip_cd_count[18]), .B
       (chip_cd_count[19]), .Z (chip_cd_inc_add_23_19_n_362));
  INVX2 chip_cd_inc_add_23_19_g456(.A (chip_cd_inc_add_23_19_n_365), .Z
       (chip_cd_inc_add_23_19_n_364));
  NAND2X1 chip_cd_inc_add_23_19_g457__2398(.A (chip_cd_count[4]), .B
       (chip_cd_count[5]), .Z (chip_cd_inc_add_23_19_n_365));
  INVX2 chip_cd_inc_add_23_19_g458(.A (chip_cd_inc_add_23_19_n_368), .Z
       (chip_cd_inc_add_23_19_n_367));
  NAND2X1 chip_cd_inc_add_23_19_g459__5107(.A (chip_cd_count[12]), .B
       (chip_cd_count[13]), .Z (chip_cd_inc_add_23_19_n_368));
  INVX2 chip_cd_inc_add_23_19_g460(.A (chip_cd_inc_add_23_19_n_371), .Z
       (chip_cd_inc_add_23_19_n_370));
  NAND2X1 chip_cd_inc_add_23_19_g461__6260(.A (chip_cd_count[20]), .B
       (chip_cd_count[21]), .Z (chip_cd_inc_add_23_19_n_371));
  AND2X1 chip_cd_inc_add_23_19_g462__4319(.A (chip_cd_count[10]), .B
       (chip_cd_count[11]), .Z (chip_cd_inc_add_23_19_n_373));
  NOR2X1 chip_cd_inc_add_23_19_g463__8428(.A (chip_cd_count[1]), .B
       (chip_cd_count[0]), .Z (chip_cd_inc_add_23_19_n_375));
  INVX2 chip_cd_inc_add_23_19_g464(.A (chip_cd_count[4]), .Z
       (chip_cd_inc_add_23_19_n_397));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g393__5526(.A
       (chip_backlight_seconds_clk_count[23]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_272), .Z
       (chip_backlight_seconds_clk_n_95));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g394__6783(.A
       (chip_backlight_seconds_clk_count[19]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_269), .Z
       (chip_backlight_seconds_clk_n_91));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g395__3680(.A
       (chip_backlight_seconds_clk_count[18]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_278), .Z
       (chip_backlight_seconds_clk_n_90));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g396__1617(.A
       (chip_backlight_seconds_clk_count[22]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_287), .Z
       (chip_backlight_seconds_clk_n_94));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g397__2802(.A
       (chip_backlight_seconds_clk_count[21]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_284), .Z
       (chip_backlight_seconds_clk_n_93));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g398__1705(.A
       (chip_backlight_seconds_clk_count[25]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_281), .Z
       (chip_backlight_seconds_clk_n_97));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g399__5122(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_278), .B
       (chip_backlight_seconds_clk_count[18]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_269));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g400__8246(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_287), .B
       (chip_backlight_seconds_clk_count[22]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_272));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g401__7098(.A
       (chip_backlight_seconds_clk_count[20]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_296), .Z
       (chip_backlight_seconds_clk_n_92));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g402__6131(.A
       (chip_backlight_seconds_clk_count[24]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_295), .Z
       (chip_backlight_seconds_clk_n_96));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g403__1881(.A
       (chip_backlight_seconds_clk_count[17]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_291), .Z
       (chip_backlight_seconds_clk_n_89));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g404__5115(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_291), .B
       (chip_backlight_seconds_clk_count[17]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_278));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g405__7482(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_295), .B
       (chip_backlight_seconds_clk_count[24]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_281));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g406__4733(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_296), .B
       (chip_backlight_seconds_clk_count[20]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_284));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g407__6161(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_296), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_370), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_287));
  NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g408__9315(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_292), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_291), .Z
       (chip_backlight_seconds_clk_n_88));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g409__9945(.A
       (chip_backlight_seconds_clk_count[15]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_306), .Z
       (chip_backlight_seconds_clk_n_87));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g410__2883(.A
       (chip_backlight_seconds_clk_count[11]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_301), .Z
       (chip_backlight_seconds_clk_n_83));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g411__2346(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_304), .B
       (chip_backlight_seconds_clk_count[16]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_291));
  NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g412__1666(.A
       (chip_backlight_seconds_clk_count[16]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_304), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_292));
  NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g413__7410(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_321), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_305), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_295));
  NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g414__6417(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_349), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_305), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_296));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g415__5477(.A
       (chip_backlight_seconds_clk_count[14]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_315), .Z
       (chip_backlight_seconds_clk_n_86));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g416__2398(.A
       (chip_backlight_seconds_clk_count[10]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_311), .Z
       (chip_backlight_seconds_clk_n_82));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g417__5107(.A
       (chip_backlight_seconds_clk_count[13]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_317), .Z
       (chip_backlight_seconds_clk_n_85));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g418__6260(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_311), .B
       (chip_backlight_seconds_clk_count[10]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_301));
  INVX2 chip_backlight_seconds_clk_inc_add_23_19_g419(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_304), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_305));
  NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g420__4319(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_341), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_319), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_304));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g421__8428(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_315), .B
       (chip_backlight_seconds_clk_count[14]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_306));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g422__5526(.A
       (chip_backlight_seconds_clk_count[12]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_325), .Z
       (chip_backlight_seconds_clk_n_84));
  NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g423__6783(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_312), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_311), .Z
       (chip_backlight_seconds_clk_n_81));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g424__3680(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_327), .B
       (chip_backlight_seconds_clk_count[9]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_311));
  NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g425__1617(.A
       (chip_backlight_seconds_clk_count[9]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_327), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_312));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g426__2802(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_325), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_367), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_315));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g427__1705(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_325), .B
       (chip_backlight_seconds_clk_count[12]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_317));
  NAND3X1 chip_backlight_seconds_clk_inc_add_23_19_g428__5122(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_336), .B
       (chip_backlight_seconds_clk_count[15]), .C
       (chip_backlight_seconds_clk_count[14]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_319));
  NAND3X1 chip_backlight_seconds_clk_inc_add_23_19_g429__8246(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_338), .B
       (chip_backlight_seconds_clk_count[23]), .C
       (chip_backlight_seconds_clk_count[22]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_321));
  NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g430__7098(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_328), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_327), .Z
       (chip_backlight_seconds_clk_n_80));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g431__6131(.A
       (chip_backlight_seconds_clk_count[7]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_333), .Z
       (chip_backlight_seconds_clk_n_79));
  NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g432__1881(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_350), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_341), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_325));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g433__5115(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_340), .B
       (chip_backlight_seconds_clk_count[8]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_327));
  NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g434__7482(.A
       (chip_backlight_seconds_clk_count[8]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_340), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_328));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g435__4733(.A
       (chip_backlight_seconds_clk_count[6]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_351), .Z
       (chip_backlight_seconds_clk_n_78));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g436__6161(.A
       (chip_backlight_seconds_clk_count[5]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_345), .Z
       (chip_backlight_seconds_clk_n_77));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g437__9315(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_351), .B
       (chip_backlight_seconds_clk_count[6]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_333));
  NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g438__9945(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_368), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_350), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_336));
  NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g439__2883(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_371), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_349), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_338));
  INVX2 chip_backlight_seconds_clk_inc_add_23_19_g440(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_340), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_341));
  NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g441__2346(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_359), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_352), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_340));
  NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g442__1666(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_347), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_345), .Z
       (chip_backlight_seconds_clk_n_76));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g443__7410(.A
       (chip_backlight_seconds_clk_count[3]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_355), .Z
       (chip_backlight_seconds_clk_n_75));
  NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g444__6417(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_397), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_359), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_345));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g445__5477(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_359), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_397), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_347));
  NAND3X1 chip_backlight_seconds_clk_inc_add_23_19_g446__2398(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_362), .B
       (chip_backlight_seconds_clk_count[16]), .C
       (chip_backlight_seconds_clk_count[17]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_349));
  NAND3X1 chip_backlight_seconds_clk_inc_add_23_19_g447__5107(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_373), .B
       (chip_backlight_seconds_clk_count[8]), .C
       (chip_backlight_seconds_clk_count[9]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_350));
  NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g448__6260(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_365), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_359), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_351));
  NAND3X1 chip_backlight_seconds_clk_inc_add_23_19_g449__4319(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_364), .B
       (chip_backlight_seconds_clk_count[7]), .C
       (chip_backlight_seconds_clk_count[6]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_352));
  XOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g450__8428(.A
       (chip_backlight_seconds_clk_count[2]), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_361), .Z
       (chip_backlight_seconds_clk_n_74));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g451__5526(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_361), .B
       (chip_backlight_seconds_clk_count[2]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_355));
  NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g452__6783(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_375), .B
       (chip_backlight_seconds_clk_inc_add_23_19_n_361), .Z
       (chip_backlight_seconds_clk_n_73));
  NAND3X1 chip_backlight_seconds_clk_inc_add_23_19_g453__3680(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_361), .B
       (chip_backlight_seconds_clk_count[2]), .C
       (chip_backlight_seconds_clk_count[3]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_359));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g454__1617(.A
       (chip_backlight_seconds_clk_count[0]), .B
       (chip_backlight_seconds_clk_count[1]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_361));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g455__2802(.A
       (chip_backlight_seconds_clk_count[18]), .B
       (chip_backlight_seconds_clk_count[19]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_362));
  INVX2 chip_backlight_seconds_clk_inc_add_23_19_g456(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_365), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_364));
  NAND2X1 chip_backlight_seconds_clk_inc_add_23_19_g457__1705(.A
       (chip_backlight_seconds_clk_count[4]), .B
       (chip_backlight_seconds_clk_count[5]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_365));
  INVX2 chip_backlight_seconds_clk_inc_add_23_19_g458(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_368), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_367));
  NAND2X1 chip_backlight_seconds_clk_inc_add_23_19_g459__5122(.A
       (chip_backlight_seconds_clk_count[12]), .B
       (chip_backlight_seconds_clk_count[13]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_368));
  INVX2 chip_backlight_seconds_clk_inc_add_23_19_g460(.A
       (chip_backlight_seconds_clk_inc_add_23_19_n_371), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_370));
  NAND2X1 chip_backlight_seconds_clk_inc_add_23_19_g461__8246(.A
       (chip_backlight_seconds_clk_count[20]), .B
       (chip_backlight_seconds_clk_count[21]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_371));
  AND2X1 chip_backlight_seconds_clk_inc_add_23_19_g462__7098(.A
       (chip_backlight_seconds_clk_count[10]), .B
       (chip_backlight_seconds_clk_count[11]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_373));
  NOR2X1 chip_backlight_seconds_clk_inc_add_23_19_g463__6131(.A
       (chip_backlight_seconds_clk_count[1]), .B
       (chip_backlight_seconds_clk_count[0]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_375));
  INVX2 chip_backlight_seconds_clk_inc_add_23_19_g464(.A
       (chip_backlight_seconds_clk_count[4]), .Z
       (chip_backlight_seconds_clk_inc_add_23_19_n_397));
  INVX4 drc_bufs(.A (n_260), .Z (n_258));
  INVX4 drc_bufs4285(.A (n_260), .Z (n_259));
  INVX2 drc_bufs4286(.A (h0_PAD_0), .Z (n_260));
  INVX4 drc_bufs4290(.A (n_268), .Z (n_266));
  INVX4 drc_bufs4291(.A (n_268), .Z (n_267));
  INVX2 drc_bufs4292(.A (s0_PAD_0), .Z (n_268));
  INVX4 drc_bufs4296(.A (n_276), .Z (n_274));
  INVX4 drc_bufs4297(.A (n_276), .Z (n_275));
  INVX2 drc_bufs4298(.A (m0_PAD_0), .Z (n_276));
  NAND3X1 g2(.A (n_282), .B (n_84), .C
       (chip_backlight_seconds_clk_count[7]), .Z (n_283));
  NOR2X1 g3(.A (chip_backlight_seconds_clk_count[24]), .B
       (chip_backlight_seconds_clk_count[25]), .Z (n_282));
  OR2X1 g4302(.A (n_284), .B (chip_cd_count[4]), .Z (n_285));
  NAND3X1 g4303(.A (n_19), .B (chip_cd_count[3]), .C
       (chip_cd_count[5]), .Z (n_284));
endmodule

