
// Generated by Cadence Genus(TM) Synthesis Solution 21.15-s080_1
// Generated on: Nov 27 2023 18:23:33 MST (Nov 28 2023 01:23:33 UTC)

// Verification Directory fv/soc_top 

module binToBCD(clk, rst, bin, BCD);
  input clk, rst;
  input [5:0] bin;
  output [7:0] BCD;
  wire clk, rst;
  wire [5:0] bin;
  wire [7:0] BCD;
endmodule

module Seg7Display(clk, reset, seconds_clk, state, current_s,
     current_m, current_h, stopwatch_s, stopwatch_m, stopwatch_h,
     display_s1, display_m1, display_h1, display_s2, display_m2,
     display_h2, second);
  input clk, reset, seconds_clk;
  input [2:0] state;
  input [5:0] current_s, current_m, current_h, stopwatch_s,
       stopwatch_m, stopwatch_h;
  output [6:0] display_s1, display_m1, display_h1, display_s2,
       display_m2, display_h2;
  output second;
  wire clk, reset, seconds_clk;
  wire [2:0] state;
  wire [5:0] current_s, current_m, current_h, stopwatch_s, stopwatch_m,
       stopwatch_h;
  wire [6:0] display_s1, display_m1, display_h1, display_s2,
       display_m2, display_h2;
  wire second;
  wire [7:0] bcdCurrHour;
  wire [7:0] bcdCurrMin;
  wire [7:0] bcdCurrSec;
  wire \display_h1[0]_420 , \display_h1[1]_421 , \display_h1[2]_422 ,
       \display_h1[3]_423 , \display_h1[4]_424 , \display_h1[5]_425 ,
       \display_h1[6]_426 , \display_h2[0]_441 ;
  wire \display_h2[1]_442 , \display_h2[2]_443 , \display_h2[3]_444 ,
       \display_h2[4]_445 , \display_h2[5]_446 , \display_h2[6]_447 ,
       \display_m1[0]_413 , \display_m1[1]_414 ;
  wire \display_m1[2]_415 , \display_m1[3]_416 , \display_m1[4]_417 ,
       \display_m1[5]_418 , \display_m1[6]_419 , \display_m2[0]_434 ,
       \display_m2[1]_435 , \display_m2[2]_436 ;
  wire \display_m2[3]_437 , \display_m2[4]_438 , \display_m2[5]_439 ,
       \display_m2[6]_440 , \display_s1[0]_406 , \display_s1[1]_407 ,
       \display_s1[2]_408 , \display_s1[3]_409 ;
  wire \display_s1[4]_410 , \display_s1[5]_411 , \display_s1[6]_412 ,
       \display_s2[0]_427 , \display_s2[1]_428 , \display_s2[2]_429 ,
       \display_s2[3]_430 , \display_s2[4]_431 ;
  wire \display_s2[5]_432 , \display_s2[6]_433 , enable_7seg,
       last_seconds_clk, n_0, n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_61, n_62, n_63, n_64, n_65, n_66, n_67;
  wire n_68, n_69, n_70, n_71, n_72, n_73, n_74, n_75;
  wire n_76, n_77, n_78, n_79, n_80, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_137, n_138, n_139;
  wire n_140, n_141, n_142, n_143, n_144, n_145, n_146, n_147;
  wire n_148, n_149, n_150, n_151, n_152, n_153, n_155, n_156;
  wire n_157, n_158, n_159, n_160, n_161, n_162, n_163, n_164;
  wire n_165, n_166, n_167, n_168, n_169, n_170, n_171, n_172;
  wire n_173, n_174, n_175, n_176, n_177, n_178, n_179, n_180;
  wire n_181, n_182, n_183, n_184, n_185, n_186, n_187, n_188;
  wire n_189, n_190, n_191, n_192, n_193, n_194, n_195, n_196;
  wire n_197, n_198, n_199, n_200, n_201, n_202, n_203, n_204;
  wire n_205, n_206, n_207, n_208, n_209, n_210, n_211, n_212;
  wire n_213, n_214, n_215, n_216, n_217, n_218, n_219, n_220;
  wire n_221, n_222, n_223, n_224, n_225, n_226, n_227, n_228;
  wire n_229, n_230, n_231, n_232, n_233, n_234, n_235, n_236;
  wire n_237, n_238, n_239, n_240, n_241, n_242, n_243, n_244;
  wire n_245, n_246, n_247, n_248, n_249, n_250, n_251, n_252;
  wire n_253, n_254, n_255, n_256, n_257, n_258, n_259, n_260;
  wire n_261, n_262, n_263, n_264, n_265, n_266, n_267, n_268;
  wire n_269, n_270, n_271, n_272, n_273, n_274, n_275, n_276;
  wire n_277, n_278, n_279, n_280, n_281, n_282, n_283, n_284;
  wire n_285, n_286, n_287, n_288, n_289, n_290, n_291, n_292;
  wire n_293, n_294, n_295, n_296, n_297, n_298, n_299, n_300;
  wire n_301, n_302, n_303, n_304, n_305, n_306, n_307, n_308;
  wire n_309, n_310, n_311, n_312, n_313, n_314, n_403, n_408;
  wire n_413, n_418, n_423, n_428, n_433, n_438, n_443, n_448;
  wire n_453, n_458, n_463, n_468, n_473, n_478, n_483, n_488;
  wire n_493, n_498, n_503, n_508, n_513, n_518, n_523, n_528;
  wire n_533, n_538, n_543, n_548, n_553, n_558, n_563, n_568;
  wire n_573, n_578, n_583, n_588, n_593, n_598, n_603, n_608;
  binToBCD bcdCurrH(.clk (clk), .rst (reset), .bin (current_h), .BCD
       (bcdCurrHour));
  binToBCD bcdCurrM(.clk (clk), .rst (reset), .bin (current_m), .BCD
       (bcdCurrMin));
  binToBCD bcdCurrS(.clk (clk), .rst (reset), .bin (current_s), .BCD
       (bcdCurrSec));
  DFFQX1 \display_h1_reg[0] (.CLK (clk), .D (n_303), .Q
       (\display_h1[0]_420 ));
  DFFQX1 \display_h1_reg[1] (.CLK (clk), .D (n_275), .Q
       (\display_h1[1]_421 ));
  DFFQX1 \display_h1_reg[2] (.CLK (clk), .D (n_274), .Q
       (\display_h1[2]_422 ));
  DFFQX1 \display_h1_reg[3] (.CLK (clk), .D (n_314), .Q
       (\display_h1[3]_423 ));
  DFFQX1 \display_h1_reg[4] (.CLK (clk), .D (n_287), .Q
       (\display_h1[4]_424 ));
  DFFQX1 \display_h1_reg[5] (.CLK (clk), .D (n_310), .Q
       (\display_h1[5]_425 ));
  DFFQX1 \display_h1_reg[6] (.CLK (clk), .D (n_283), .Q
       (\display_h1[6]_426 ));
  DFFQX1 \display_h2_reg[0] (.CLK (clk), .D (n_306), .Q
       (\display_h2[0]_441 ));
  DFFQX1 \display_h2_reg[1] (.CLK (clk), .D (n_277), .Q
       (\display_h2[1]_442 ));
  DFFQX1 \display_h2_reg[2] (.CLK (clk), .D (n_276), .Q
       (\display_h2[2]_443 ));
  DFFQX1 \display_h2_reg[3] (.CLK (clk), .D (n_307), .Q
       (\display_h2[3]_444 ));
  DFFQX1 \display_h2_reg[4] (.CLK (clk), .D (n_273), .Q
       (\display_h2[4]_445 ));
  DFFQX1 \display_h2_reg[5] (.CLK (clk), .D (n_313), .Q
       (\display_h2[5]_446 ));
  DFFQX1 \display_h2_reg[6] (.CLK (clk), .D (n_288), .Q
       (\display_h2[6]_447 ));
  DFFQX1 \display_m1_reg[0] (.CLK (clk), .D (n_304), .Q
       (\display_m1[0]_413 ));
  DFFQX1 \display_m1_reg[1] (.CLK (clk), .D (n_286), .Q
       (\display_m1[1]_414 ));
  DFFQX1 \display_m1_reg[2] (.CLK (clk), .D (n_285), .Q
       (\display_m1[2]_415 ));
  DFFQX1 \display_m1_reg[3] (.CLK (clk), .D (n_312), .Q
       (\display_m1[3]_416 ));
  DFFQX1 \display_m1_reg[4] (.CLK (clk), .D (n_284), .Q
       (\display_m1[4]_417 ));
  DFFQX1 \display_m1_reg[5] (.CLK (clk), .D (n_311), .Q
       (\display_m1[5]_418 ));
  DFFQX1 \display_m1_reg[6] (.CLK (clk), .D (n_282), .Q
       (\display_m1[6]_419 ));
  DFFQX1 \display_m2_reg[0] (.CLK (clk), .D (n_305), .Q
       (\display_m2[0]_434 ));
  DFFQX1 \display_m2_reg[1] (.CLK (clk), .D (n_290), .Q
       (\display_m2[1]_435 ));
  DFFQX1 \display_m2_reg[2] (.CLK (clk), .D (n_280), .Q
       (\display_m2[2]_436 ));
  DFFQX1 \display_m2_reg[3] (.CLK (clk), .D (n_309), .Q
       (\display_m2[3]_437 ));
  DFFQX1 \display_m2_reg[4] (.CLK (clk), .D (n_279), .Q
       (\display_m2[4]_438 ));
  DFFQX1 \display_m2_reg[5] (.CLK (clk), .D (n_308), .Q
       (\display_m2[5]_439 ));
  DFFQX1 \display_m2_reg[6] (.CLK (clk), .D (n_278), .Q
       (\display_m2[6]_440 ));
  DFFQX1 \display_s1_reg[0] (.CLK (clk), .D (n_298), .Q
       (\display_s1[0]_406 ));
  DFFQX1 \display_s1_reg[1] (.CLK (clk), .D (n_254), .Q
       (\display_s1[1]_407 ));
  DFFQX1 \display_s1_reg[2] (.CLK (clk), .D (n_253), .Q
       (\display_s1[2]_408 ));
  DFFQX1 \display_s1_reg[3] (.CLK (clk), .D (n_299), .Q
       (\display_s1[3]_409 ));
  DFFQX1 \display_s1_reg[4] (.CLK (clk), .D (n_214), .Q
       (\display_s1[4]_410 ));
  DFFQX1 \display_s1_reg[5] (.CLK (clk), .D (n_300), .Q
       (\display_s1[5]_411 ));
  DFFQX1 \display_s1_reg[6] (.CLK (clk), .D (n_251), .Q
       (\display_s1[6]_412 ));
  DFFQX1 \display_s2_reg[0] (.CLK (clk), .D (n_301), .Q
       (\display_s2[0]_427 ));
  DFFQX1 \display_s2_reg[1] (.CLK (clk), .D (n_249), .Q
       (\display_s2[1]_428 ));
  DFFQX1 \display_s2_reg[2] (.CLK (clk), .D (n_248), .Q
       (\display_s2[2]_429 ));
  DFFQX1 \display_s2_reg[3] (.CLK (clk), .D (n_281), .Q
       (\display_s2[3]_430 ));
  DFFQX1 \display_s2_reg[4] (.CLK (clk), .D (n_211), .Q
       (\display_s2[4]_431 ));
  DFFQX1 \display_s2_reg[5] (.CLK (clk), .D (n_289), .Q
       (\display_s2[5]_432 ));
  DFFQX1 \display_s2_reg[6] (.CLK (clk), .D (n_245), .Q
       (\display_s2[6]_433 ));
  DFFQSRX1 enable_7seg_reg(.SETB (1'b1), .RESETB (n_0), .CLK (clk), .D
       (n_200), .Q (enable_7seg));
  DFFQX1 last_seconds_clk_reg(.CLK (clk), .D (n_199), .Q
       (last_seconds_clk));
  NAND3X1 g5898__2398(.A (n_30), .B (n_271), .C (n_295), .Z (n_314));
  NAND3X1 g5899__5107(.A (n_66), .B (n_296), .C (n_268), .Z (n_313));
  NAND3X1 g5904__6260(.A (n_38), .B (n_271), .C (n_294), .Z (n_312));
  NAND3X1 g5905__4319(.A (n_58), .B (n_292), .C (n_272), .Z (n_311));
  NAND3X1 g5906__8428(.A (n_39), .B (n_302), .C (n_272), .Z (n_310));
  NAND3X1 g5907__5526(.A (n_74), .B (n_259), .C (n_291), .Z (n_309));
  NAND3X1 g5908__6783(.A (n_15), .B (n_293), .C (n_268), .Z (n_308));
  NAND3X1 g5909__3680(.A (n_84), .B (n_259), .C (n_297), .Z (n_307));
  NAND3X1 g5923__1617(.A (n_20), .B (n_270), .C (n_263), .Z (n_306));
  NAND3X1 g5924__2802(.A (n_42), .B (n_270), .C (n_260), .Z (n_305));
  NAND3X1 g5925__1705(.A (n_61), .B (n_269), .C (n_262), .Z (n_304));
  NAND3X1 g5926__5122(.A (n_75), .B (n_269), .C (n_261), .Z (n_303));
  NAND2X1 g5936__8246(.A (n_192), .B (n_267), .Z (n_302));
  NAND2X1 g5937__7098(.A (n_72), .B (n_250), .Z (n_301));
  NAND2X1 g5938__6131(.A (n_28), .B (n_252), .Z (n_300));
  NAND2X1 g5939__1881(.A (n_16), .B (n_247), .Z (n_299));
  NAND2X1 g5940__5115(.A (n_29), .B (n_255), .Z (n_298));
  NAND2X1 g5941__7482(.A (n_192), .B (n_244), .Z (n_297));
  NAND2X1 g5942__4733(.A (n_192), .B (n_264), .Z (n_296));
  NAND2X1 g5943__6161(.A (n_192), .B (n_265), .Z (n_295));
  NAND2X1 g5944__9315(.A (n_193), .B (n_266), .Z (n_294));
  NAND2X1 g5945__9945(.A (n_193), .B (n_256), .Z (n_293));
  NAND2X1 g5946__2883(.A (n_193), .B (n_258), .Z (n_292));
  NAND2X1 g5947__2346(.A (n_193), .B (n_257), .Z (n_291));
  NAND3X1 g5954__1666(.A (n_60), .B (n_242), .C (n_225), .Z (n_290));
  NAND2X1 g5955__7410(.A (n_37), .B (n_246), .Z (n_289));
  NAND3X1 g5956__6417(.A (n_55), .B (n_237), .C (n_206), .Z (n_288));
  NAND3X1 g5957__5477(.A (n_59), .B (n_231), .C (n_223), .Z (n_287));
  NAND3X1 g5958__2398(.A (n_51), .B (n_239), .C (n_222), .Z (n_286));
  NAND3X1 g5959__5107(.A (n_46), .B (n_241), .C (n_229), .Z (n_285));
  NAND3X1 g5960__6260(.A (n_45), .B (n_231), .C (n_221), .Z (n_284));
  NAND3X1 g5961__4319(.A (n_21), .B (n_234), .C (n_202), .Z (n_283));
  NAND3X1 g5962__8428(.A (n_50), .B (n_234), .C (n_203), .Z (n_282));
  NAND2X1 g5963__5526(.A (n_23), .B (n_243), .Z (n_281));
  NAND3X1 g5964__6783(.A (n_27), .B (n_240), .C (n_207), .Z (n_280));
  NAND3X1 g5965__3680(.A (n_48), .B (n_236), .C (n_230), .Z (n_279));
  NAND3X1 g5966__1617(.A (n_62), .B (n_237), .C (n_201), .Z (n_278));
  NAND3X1 g5967__2802(.A (n_69), .B (n_242), .C (n_226), .Z (n_277));
  NAND3X1 g5968__1705(.A (n_22), .B (n_240), .C (n_213), .Z (n_276));
  NAND3X1 g5969__5122(.A (n_25), .B (n_239), .C (n_227), .Z (n_275));
  NAND3X1 g5970__8246(.A (n_65), .B (n_241), .C (n_228), .Z (n_274));
  NAND3X1 g5971__7098(.A (n_73), .B (n_236), .C (n_224), .Z (n_273));
  NAND3X1 g5972__6131(.A (n_174), .B (n_141), .C (n_107), .Z (n_267));
  NAND3X1 g5973__1881(.A (n_168), .B (n_116), .C (n_136), .Z (n_266));
  NAND3X1 g5974__5115(.A (n_170), .B (n_141), .C (n_107), .Z (n_265));
  NAND3X1 g5975__7482(.A (n_176), .B (n_117), .C (n_109), .Z (n_264));
  NAND2X1 g5976__4733(.A (n_192), .B (n_208), .Z (n_263));
  NAND2X1 g5977__6161(.A (n_193), .B (n_210), .Z (n_262));
  NAND2X1 g5978__9315(.A (n_192), .B (n_218), .Z (n_261));
  NAND2X1 g5979__9945(.A (n_193), .B (n_209), .Z (n_260));
  OR2X1 g5980__2883(.A (n_235), .B (n_182), .Z (n_272));
  OR2X1 g5981__2346(.A (n_219), .B (n_182), .Z (n_271));
  NAND2X1 g5982__1666(.A (n_181), .B (n_232), .Z (n_270));
  NAND2X1 g5983__7410(.A (n_181), .B (n_233), .Z (n_269));
  OR2X1 g5984__6417(.A (n_238), .B (n_182), .Z (n_268));
  NAND3X1 g5989__5477(.A (n_175), .B (n_116), .C (n_136), .Z (n_258));
  NAND3X1 g5990__2398(.A (n_167), .B (n_118), .C (n_108), .Z (n_257));
  NAND3X1 g5991__5107(.A (n_173), .B (n_118), .C (n_108), .Z (n_256));
  NAND2X1 g5992__6260(.A (n_150), .B (n_233), .Z (n_255));
  NAND2X1 g5993__4319(.A (n_40), .B (n_216), .Z (n_254));
  NAND2X1 g5994__8428(.A (n_44), .B (n_217), .Z (n_253));
  OR2X1 g5995__5526(.A (n_235), .B (n_149), .Z (n_252));
  NAND2X1 g5996__6783(.A (n_17), .B (n_205), .Z (n_251));
  NAND2X1 g5997__3680(.A (n_150), .B (n_232), .Z (n_250));
  NAND2X1 g5998__1617(.A (n_18), .B (n_212), .Z (n_249));
  NAND2X1 g5999__2802(.A (n_63), .B (n_215), .Z (n_248));
  OR2X1 g6000__1705(.A (n_219), .B (n_149), .Z (n_247));
  OR2X1 g6001__5122(.A (n_238), .B (n_149), .Z (n_246));
  NAND2X1 g6002__8246(.A (n_41), .B (n_204), .Z (n_245));
  NAND3X1 g6003__7098(.A (n_171), .B (n_117), .C (n_109), .Z (n_244));
  NAND2X1 g6004__6131(.A (n_150), .B (n_220), .Z (n_243));
  NAND2X1 g6005__1881(.A (n_181), .B (n_220), .Z (n_259));
  NAND2X1 g6006__5115(.A (n_193), .B (n_147), .Z (n_230));
  NAND3X1 g6007__7482(.A (n_193), .B (n_164), .C (n_4), .Z (n_229));
  NAND3X1 g6008__4733(.A (n_192), .B (n_166), .C (n_3), .Z (n_228));
  NAND2X1 g6009__6161(.A (n_192), .B (n_178), .Z (n_227));
  NAND2X1 g6010__9315(.A (n_192), .B (n_179), .Z (n_226));
  NAND2X1 g6011__9945(.A (n_193), .B (n_189), .Z (n_225));
  NAND2X1 g6012__2883(.A (n_192), .B (n_148), .Z (n_224));
  NAND2X1 g6013__2346(.A (n_192), .B (n_144), .Z (n_223));
  NAND2X1 g6014__1666(.A (n_193), .B (n_185), .Z (n_222));
  NAND2X1 g6015__7410(.A (n_193), .B (n_145), .Z (n_221));
  NAND2X1 g6016__6417(.A (n_181), .B (n_183), .Z (n_242));
  NAND2X1 g6017__5477(.A (n_181), .B (n_197), .Z (n_241));
  NAND2X1 g6018__2398(.A (n_181), .B (n_198), .Z (n_240));
  NAND2X1 g6019__5107(.A (n_181), .B (n_194), .Z (n_239));
  NOR2X1 g6020__6260(.A (n_159), .B (n_177), .Z (n_238));
  NAND2X1 g6021__4319(.A (n_181), .B (n_195), .Z (n_237));
  NAND2X1 g6022__8428(.A (n_181), .B (n_152), .Z (n_236));
  NOR2X1 g6023__5526(.A (n_158), .B (n_180), .Z (n_235));
  NAND2X1 g6024__6783(.A (n_181), .B (n_196), .Z (n_234));
  NAND3X1 g6025__3680(.A (n_157), .B (n_138), .C (n_49), .Z (n_233));
  NAND3X1 g6026__1617(.A (n_160), .B (n_114), .C (n_47), .Z (n_232));
  NAND2X1 g6027__2802(.A (n_181), .B (n_153), .Z (n_231));
  NAND3X1 g6028__1705(.A (n_146), .B (n_110), .C (n_107), .Z (n_218));
  NAND2X1 g6029__5122(.A (n_150), .B (n_197), .Z (n_217));
  NAND2X1 g6030__8246(.A (n_150), .B (n_194), .Z (n_216));
  NAND2X1 g6031__7098(.A (n_150), .B (n_198), .Z (n_215));
  NAND2X1 g6032__6131(.A (n_76), .B (n_187), .Z (n_214));
  NAND3X1 g6033__1881(.A (n_192), .B (n_165), .C (n_9), .Z (n_213));
  NAND2X1 g6034__5115(.A (n_150), .B (n_183), .Z (n_212));
  NAND2X1 g6035__7482(.A (n_35), .B (n_191), .Z (n_211));
  NAND3X1 g6036__4733(.A (n_156), .B (n_137), .C (n_136), .Z (n_210));
  NAND3X1 g6037__6161(.A (n_155), .B (n_111), .C (n_108), .Z (n_209));
  NAND3X1 g6038__9315(.A (n_143), .B (n_115), .C (n_109), .Z (n_208));
  NAND3X1 g6039__9945(.A (n_193), .B (n_162), .C (n_8), .Z (n_207));
  NAND2X1 g6040__2883(.A (n_192), .B (n_188), .Z (n_206));
  NAND2X1 g6041__2346(.A (n_150), .B (n_196), .Z (n_205));
  NAND2X1 g6042__1666(.A (n_150), .B (n_195), .Z (n_204));
  NAND2X1 g6043__7410(.A (n_193), .B (n_184), .Z (n_203));
  NAND2X1 g6044__6417(.A (n_192), .B (n_186), .Z (n_202));
  NAND2X1 g6045__5477(.A (n_193), .B (n_190), .Z (n_201));
  XOR2X1 g6046__2398(.A (enable_7seg), .B (n_142), .Z (n_200));
  MUX2X1 g6047__5107(.A (seconds_clk), .B (last_seconds_clk), .S
       (reset), .Z (n_199));
  NAND2X1 g6048__6260(.A (n_169), .B (n_160), .Z (n_220));
  NOR2X1 g6049__4319(.A (n_158), .B (n_172), .Z (n_219));
  NAND2X1 g6050__8428(.A (n_150), .B (n_152), .Z (n_191));
  OR2X1 g6051__5526(.A (n_131), .B (n_162), .Z (n_190));
  NAND3X1 g6052__6783(.A (n_111), .B (n_104), .C (n_108), .Z (n_189));
  OR2X1 g6053__3680(.A (n_135), .B (n_165), .Z (n_188));
  NAND2X1 g6054__1617(.A (n_150), .B (n_153), .Z (n_187));
  OR2X1 g6055__2802(.A (n_132), .B (n_166), .Z (n_186));
  NAND3X1 g6056__1705(.A (n_137), .B (n_124), .C (n_136), .Z (n_185));
  OR2X1 g6057__5122(.A (n_134), .B (n_164), .Z (n_184));
  NOR2X1 g6058__8246(.A (bcdCurrSec[4]), .B (n_151), .Z (n_198));
  NOR2X1 g6059__7098(.A (bcdCurrSec[0]), .B (n_163), .Z (n_197));
  NAND2X1 g6060__6131(.A (n_163), .B (n_133), .Z (n_196));
  NAND2X1 g6061__1881(.A (n_151), .B (n_126), .Z (n_195));
  NAND3X1 g6062__5115(.A (n_138), .B (n_99), .C (n_140), .Z (n_194));
  AND2X1 g6063__7482(.A (n_161), .B (n_128), .Z (n_193));
  AND2X1 g6064__4733(.A (n_161), .B (n_70), .Z (n_192));
  INVX2 g6065(.A (n_182), .Z (n_181));
  MUX2X1 g6066__6161(.A (n_139), .B (n_123), .S (bcdCurrSec[0]), .Z
       (n_180));
  NAND3X1 g6067__9315(.A (n_115), .B (n_101), .C (n_109), .Z (n_179));
  NAND3X1 g6068__9945(.A (n_110), .B (n_100), .C (n_107), .Z (n_178));
  MUX2X1 g6069__2883(.A (n_113), .B (n_130), .S (bcdCurrSec[4]), .Z
       (n_177));
  MUX2X1 g6070__2346(.A (n_129), .B (n_115), .S (n_9), .Z (n_176));
  MUX2X1 g6071__1666(.A (n_120), .B (n_137), .S (n_4), .Z (n_175));
  MUX2X1 g6072__7410(.A (n_127), .B (n_110), .S (n_3), .Z (n_174));
  MUX2X1 g6073__6417(.A (n_105), .B (n_111), .S (n_8), .Z (n_173));
  MUX2X1 g6074__5477(.A (n_94), .B (n_139), .S (bcdCurrSec[0]), .Z
       (n_172));
  MUX2X1 g6075__2398(.A (n_89), .B (n_115), .S (bcdCurrHour[4]), .Z
       (n_171));
  MUX2X1 g6076__5107(.A (n_86), .B (n_110), .S (bcdCurrHour[0]), .Z
       (n_170));
  MUX2X1 g6077__6260(.A (n_91), .B (n_114), .S (bcdCurrSec[4]), .Z
       (n_169));
  MUX2X1 g6078__4319(.A (n_87), .B (n_137), .S (bcdCurrMin[0]), .Z
       (n_168));
  MUX2X1 g6079__8428(.A (n_92), .B (n_111), .S (bcdCurrMin[4]), .Z
       (n_167));
  NAND3X1 g6080__5526(.A (n_114), .B (n_102), .C (n_112), .Z (n_183));
  NAND3X1 g6081__6783(.A (n_106), .B (n_125), .C (n_0), .Z (n_182));
  INVX2 g6082(.A (n_159), .Z (n_160));
  INVX2 g6083(.A (n_158), .Z (n_157));
  AND2X1 g6084__3680(.A (n_116), .B (n_33), .Z (n_156));
  AND2X1 g6085__1617(.A (n_118), .B (n_34), .Z (n_155));
  NAND2X1 g6086__2802(.A (n_107), .B (n_86), .Z (n_166));
  NAND2X1 g6087__1705(.A (n_109), .B (n_89), .Z (n_165));
  NAND2X1 g6088__5122(.A (n_136), .B (n_87), .Z (n_164));
  AND2X1 g6090__8246(.A (n_140), .B (n_95), .Z (n_163));
  NAND2X1 g6091__7098(.A (n_108), .B (n_92), .Z (n_162));
  NOR2X1 g6092__6131(.A (reset), .B (n_103), .Z (n_161));
  NAND2X1 g6093__1881(.A (n_98), .B (n_112), .Z (n_159));
  NAND2X1 g6094__5115(.A (n_121), .B (n_140), .Z (n_158));
  INVX2 g6095(.A (n_150), .Z (n_149));
  NAND3X1 g6096__7482(.A (n_109), .B (n_85), .C (n_82), .Z (n_148));
  NAND3X1 g6097__4733(.A (n_108), .B (n_90), .C (n_77), .Z (n_147));
  AND2X1 g6098__6161(.A (n_141), .B (n_54), .Z (n_146));
  NAND3X1 g6099__9315(.A (n_136), .B (n_88), .C (n_80), .Z (n_145));
  NAND3X1 g6100__9945(.A (n_107), .B (n_93), .C (n_79), .Z (n_144));
  AND2X1 g6101__2883(.A (n_117), .B (n_19), .Z (n_143));
  AND2X1 g6102__2346(.A (n_119), .B (seconds_clk), .Z (n_142));
  NAND3X1 g6103__1666(.A (n_140), .B (n_97), .C (n_78), .Z (n_153));
  NAND3X1 g6104__7410(.A (n_112), .B (n_96), .C (n_81), .Z (n_152));
  AND2X1 g6105__6417(.A (n_112), .B (n_91), .Z (n_151));
  NOR2X1 g6106__5477(.A (reset), .B (n_122), .Z (n_150));
  INVX2 g6107(.A (n_139), .Z (n_138));
  NOR2X1 g6108__2398(.A (n_9), .B (n_85), .Z (n_135));
  NOR2X1 g6109__5107(.A (n_4), .B (n_88), .Z (n_134));
  OR2X1 g6110__6260(.A (n_1), .B (n_97), .Z (n_133));
  NOR2X1 g6111__4319(.A (n_3), .B (n_93), .Z (n_132));
  NOR2X1 g6112__8428(.A (n_8), .B (n_90), .Z (n_131));
  NAND2X1 g6113__5526(.A (n_91), .B (n_67), .Z (n_130));
  AND2X1 g6114__6783(.A (n_89), .B (n_64), .Z (n_129));
  NAND3X1 g6115__3680(.A (state[1]), .B (n_13), .C (n_7), .Z (n_128));
  AND2X1 g6116__1617(.A (n_86), .B (n_71), .Z (n_127));
  OR2X1 g6117__2802(.A (n_2), .B (n_96), .Z (n_126));
  NAND2X1 g6118__1705(.A (n_68), .B (state[1]), .Z (n_125));
  OR2X1 g6119__5122(.A (bcdCurrMin[0]), .B (n_88), .Z (n_124));
  OR2X1 g6120__8246(.A (n_52), .B (n_94), .Z (n_123));
  NOR2X1 g6121__7098(.A (n_83), .B (n_56), .Z (n_122));
  OR2X1 g6122__6131(.A (bcdCurrSec[2]), .B (n_95), .Z (n_121));
  AND2X1 g6123__1881(.A (n_87), .B (n_36), .Z (n_120));
  OR2X1 g6124__5115(.A (bcdCurrHour[2]), .B (n_86), .Z (n_141));
  NAND2X1 g6125__7482(.A (n_43), .B (bcdCurrSec[3]), .Z (n_140));
  NOR2X1 g6126__4733(.A (bcdCurrSec[1]), .B (n_97), .Z (n_139));
  OR2X1 g6127__6161(.A (bcdCurrMin[1]), .B (n_88), .Z (n_137));
  NAND2X1 g6128__9315(.A (n_53), .B (bcdCurrMin[3]), .Z (n_136));
  INVX2 g6129(.A (n_113), .Z (n_114));
  XOR2X1 g6130__9945(.A (state[1]), .B (state[2]), .Z (n_106));
  AND2X1 g6131__2883(.A (n_92), .B (n_26), .Z (n_105));
  OR2X1 g6132__2346(.A (bcdCurrMin[4]), .B (n_90), .Z (n_104));
  MUX2X1 g6133__1666(.A (state[2]), .B (state[0]), .S (state[1]), .Z
       (n_103));
  OR2X1 g6134__7410(.A (bcdCurrSec[4]), .B (n_96), .Z (n_102));
  OR2X1 g6135__6417(.A (bcdCurrHour[4]), .B (n_85), .Z (n_101));
  OR2X1 g6136__5477(.A (bcdCurrHour[0]), .B (n_93), .Z (n_100));
  OR2X1 g6137__2398(.A (bcdCurrSec[0]), .B (n_97), .Z (n_99));
  OR2X1 g6138__5107(.A (bcdCurrSec[6]), .B (n_91), .Z (n_98));
  OR2X1 g6140__6260(.A (bcdCurrMin[6]), .B (n_92), .Z (n_118));
  OR2X1 g6141__4319(.A (bcdCurrHour[6]), .B (n_89), .Z (n_117));
  OR2X1 g6142__8428(.A (bcdCurrMin[2]), .B (n_87), .Z (n_116));
  OR2X1 g6143__5526(.A (bcdCurrHour[5]), .B (n_85), .Z (n_115));
  NOR2X1 g6144__6783(.A (bcdCurrSec[5]), .B (n_96), .Z (n_113));
  NAND2X1 g6145__3680(.A (n_57), .B (bcdCurrSec[7]), .Z (n_112));
  OR2X1 g6146__1617(.A (bcdCurrMin[5]), .B (n_90), .Z (n_111));
  OR2X1 g6147__2802(.A (bcdCurrHour[1]), .B (n_93), .Z (n_110));
  NAND2X1 g6148__1705(.A (n_31), .B (bcdCurrHour[7]), .Z (n_109));
  NAND2X1 g6149__5122(.A (n_32), .B (bcdCurrMin[7]), .Z (n_108));
  NAND2X1 g6150__8246(.A (n_24), .B (bcdCurrHour[3]), .Z (n_107));
  INVX2 g6151(.A (n_95), .Z (n_94));
  NAND2X1 g6152__7098(.A (\display_h2[3]_444 ), .B (reset), .Z (n_84));
  NOR2X1 g6153__6131(.A (n_13), .B (state[2]), .Z (n_83));
  OR2X1 g6154__1881(.A (bcdCurrHour[7]), .B (n_9), .Z (n_82));
  OR2X1 g6155__5115(.A (bcdCurrSec[7]), .B (n_2), .Z (n_81));
  OR2X1 g6156__7482(.A (bcdCurrMin[3]), .B (n_4), .Z (n_80));
  OR2X1 g6157__4733(.A (bcdCurrHour[3]), .B (n_3), .Z (n_79));
  OR2X1 g6158__6161(.A (bcdCurrSec[3]), .B (n_1), .Z (n_78));
  OR2X1 g6159__9315(.A (bcdCurrMin[7]), .B (n_8), .Z (n_77));
  NAND2X1 g6160__9945(.A (\display_s1[4]_410 ), .B (reset), .Z (n_76));
  NAND2X1 g6161__2883(.A (\display_h1[0]_420 ), .B (reset), .Z (n_75));
  NAND2X1 g6162__2346(.A (\display_m2[3]_437 ), .B (reset), .Z (n_74));
  NAND2X1 g6163__1666(.A (\display_h2[4]_445 ), .B (reset), .Z (n_73));
  NAND2X1 g6164__7410(.A (\display_s2[0]_427 ), .B (reset), .Z (n_72));
  OR2X1 g6165__6417(.A (bcdCurrHour[2]), .B (bcdCurrHour[3]), .Z
       (n_71));
  NAND2X1 g6166__5477(.A (n_13), .B (state[0]), .Z (n_70));
  NAND2X1 g6167__2398(.A (\display_h2[1]_442 ), .B (reset), .Z (n_69));
  NAND2X1 g6168__5107(.A (state[0]), .B (enable_7seg), .Z (n_68));
  OR2X1 g6169__6260(.A (bcdCurrSec[6]), .B (bcdCurrSec[7]), .Z (n_67));
  NAND2X1 g6170__4319(.A (\display_h2[5]_446 ), .B (reset), .Z (n_66));
  NAND2X1 g6171__8428(.A (\display_h1[2]_422 ), .B (reset), .Z (n_65));
  OR2X1 g6172__5526(.A (bcdCurrHour[6]), .B (bcdCurrHour[7]), .Z
       (n_64));
  NAND2X1 g6173__6783(.A (\display_s2[2]_429 ), .B (reset), .Z (n_63));
  NAND2X1 g6174__3680(.A (\display_m2[6]_440 ), .B (reset), .Z (n_62));
  NAND2X1 g6175__1617(.A (\display_m1[0]_413 ), .B (reset), .Z (n_61));
  NAND2X1 g6176__2802(.A (\display_m2[1]_435 ), .B (reset), .Z (n_60));
  NAND2X1 g6177__1705(.A (\display_h1[4]_424 ), .B (reset), .Z (n_59));
  NAND2X1 g6178__5122(.A (\display_m1[5]_418 ), .B (reset), .Z (n_58));
  NOR2X1 g6179__8246(.A (bcdCurrSec[5]), .B (bcdCurrSec[6]), .Z (n_57));
  NAND2X1 g6180__7098(.A (state[1]), .B (state[0]), .Z (n_56));
  NAND2X1 g6181__6131(.A (n_5), .B (bcdCurrSec[2]), .Z (n_97));
  NAND2X1 g6182__1881(.A (n_11), .B (bcdCurrSec[6]), .Z (n_96));
  NAND2X1 g6183__5115(.A (n_5), .B (bcdCurrSec[1]), .Z (n_95));
  NAND2X1 g6184__7482(.A (n_12), .B (bcdCurrHour[2]), .Z (n_93));
  NAND2X1 g6185__4733(.A (n_14), .B (bcdCurrMin[5]), .Z (n_92));
  NAND2X1 g6186__6161(.A (n_11), .B (bcdCurrSec[5]), .Z (n_91));
  NAND2X1 g6187__9315(.A (n_14), .B (bcdCurrMin[6]), .Z (n_90));
  NAND2X1 g6188__9945(.A (n_10), .B (bcdCurrHour[5]), .Z (n_89));
  NAND2X1 g6189__2883(.A (n_6), .B (bcdCurrMin[2]), .Z (n_88));
  NAND2X1 g6190__2346(.A (n_6), .B (bcdCurrMin[1]), .Z (n_87));
  NAND2X1 g6191__1666(.A (n_12), .B (bcdCurrHour[1]), .Z (n_86));
  NAND2X1 g6192__7410(.A (n_10), .B (bcdCurrHour[6]), .Z (n_85));
  NAND2X1 g6193__6417(.A (\display_h2[6]_447 ), .B (reset), .Z (n_55));
  NAND2X1 g6194__5477(.A (n_3), .B (n_12), .Z (n_54));
  NOR2X1 g6195__2398(.A (bcdCurrMin[1]), .B (bcdCurrMin[2]), .Z (n_53));
  NOR2X1 g6196__5107(.A (bcdCurrSec[2]), .B (bcdCurrSec[3]), .Z (n_52));
  NAND2X1 g6197__6260(.A (\display_m1[1]_414 ), .B (reset), .Z (n_51));
  NAND2X1 g6198__4319(.A (\display_m1[6]_419 ), .B (reset), .Z (n_50));
  NAND2X1 g6199__8428(.A (n_1), .B (n_5), .Z (n_49));
  NAND2X1 g6200__5526(.A (\display_m2[4]_438 ), .B (reset), .Z (n_48));
  NAND2X1 g6201__6783(.A (n_2), .B (n_11), .Z (n_47));
  NAND2X1 g6202__3680(.A (\display_m1[2]_415 ), .B (reset), .Z (n_46));
  NAND2X1 g6203__1617(.A (\display_m1[4]_417 ), .B (reset), .Z (n_45));
  NAND2X1 g6204__2802(.A (\display_s1[2]_408 ), .B (reset), .Z (n_44));
  NOR2X1 g6205__1705(.A (bcdCurrSec[1]), .B (bcdCurrSec[2]), .Z (n_43));
  NAND2X1 g6206__5122(.A (\display_m2[0]_434 ), .B (reset), .Z (n_42));
  NAND2X1 g6207__8246(.A (\display_s2[6]_433 ), .B (reset), .Z (n_41));
  NAND2X1 g6208__7098(.A (\display_s1[1]_407 ), .B (reset), .Z (n_40));
  NAND2X1 g6209__6131(.A (\display_h1[5]_425 ), .B (reset), .Z (n_39));
  NAND2X1 g6210__1881(.A (\display_m1[3]_416 ), .B (reset), .Z (n_38));
  NAND2X1 g6211__5115(.A (\display_s2[5]_432 ), .B (reset), .Z (n_37));
  OR2X1 g6212__7482(.A (bcdCurrMin[2]), .B (bcdCurrMin[3]), .Z (n_36));
  NAND2X1 g6213__4733(.A (\display_s2[4]_431 ), .B (reset), .Z (n_35));
  NAND2X1 g6214__6161(.A (n_8), .B (n_14), .Z (n_34));
  NAND2X1 g6215__9315(.A (n_4), .B (n_6), .Z (n_33));
  NOR2X1 g6216__9945(.A (bcdCurrMin[5]), .B (bcdCurrMin[6]), .Z (n_32));
  NOR2X1 g6217__2883(.A (bcdCurrHour[5]), .B (bcdCurrHour[6]), .Z
       (n_31));
  NAND2X1 g6218__2346(.A (\display_h1[3]_423 ), .B (reset), .Z (n_30));
  NAND2X1 g6219__1666(.A (\display_s1[0]_406 ), .B (reset), .Z (n_29));
  NAND2X1 g6220__7410(.A (\display_s1[5]_411 ), .B (reset), .Z (n_28));
  NAND2X1 g6221__6417(.A (\display_m2[2]_436 ), .B (reset), .Z (n_27));
  OR2X1 g6222__5477(.A (bcdCurrMin[6]), .B (bcdCurrMin[7]), .Z (n_26));
  NAND2X1 g6223__2398(.A (\display_h1[1]_421 ), .B (reset), .Z (n_25));
  NOR2X1 g6224__5107(.A (bcdCurrHour[1]), .B (bcdCurrHour[2]), .Z
       (n_24));
  NAND2X1 g6225__6260(.A (\display_s2[3]_430 ), .B (reset), .Z (n_23));
  NAND2X1 g6226__4319(.A (\display_h2[2]_443 ), .B (reset), .Z (n_22));
  NAND2X1 g6227__8428(.A (\display_h1[6]_426 ), .B (reset), .Z (n_21));
  NAND2X1 g6228__5526(.A (\display_h2[0]_441 ), .B (reset), .Z (n_20));
  NAND2X1 g6229__6783(.A (n_9), .B (n_10), .Z (n_19));
  NAND2X1 g6230__3680(.A (\display_s2[1]_428 ), .B (reset), .Z (n_18));
  NAND2X1 g6231__1617(.A (\display_s1[6]_412 ), .B (reset), .Z (n_17));
  NAND2X1 g6232__2802(.A (\display_s1[3]_409 ), .B (reset), .Z (n_16));
  NAND2X1 g6233__1705(.A (\display_m2[5]_439 ), .B (reset), .Z (n_15));
  INVX2 g6255(.A (bcdCurrMin[7]), .Z (n_14));
  INVX2 g6256(.A (enable_7seg), .Z (n_13));
  INVX2 g6257(.A (bcdCurrHour[3]), .Z (n_12));
  INVX2 g6258(.A (bcdCurrSec[7]), .Z (n_11));
  INVX2 g6259(.A (bcdCurrHour[7]), .Z (n_10));
  INVX2 g6260(.A (bcdCurrHour[4]), .Z (n_9));
  INVX2 g6261(.A (bcdCurrMin[4]), .Z (n_8));
  INVX2 g6283(.A (state[2]), .Z (n_7));
  INVX2 g6284(.A (bcdCurrMin[3]), .Z (n_6));
  INVX2 g6285(.A (bcdCurrSec[3]), .Z (n_5));
  INVX2 g6286(.A (bcdCurrMin[0]), .Z (n_4));
  INVX2 g6287(.A (bcdCurrHour[0]), .Z (n_3));
  INVX2 g6288(.A (bcdCurrSec[4]), .Z (n_2));
  INVX2 g6289(.A (bcdCurrSec[0]), .Z (n_1));
  INVX2 g6290(.A (reset), .Z (n_0));
  INVX1 g6291(.A (last_seconds_clk), .Z (n_119));
  INVX4 drc_bufs6293(.A (n_403), .Z (display_h1[0]));
  INVX2 drc_bufs6294(.A (\display_h1[0]_420 ), .Z (n_403));
  INVX4 drc_bufs6295(.A (n_408), .Z (display_s2[6]));
  INVX2 drc_bufs6296(.A (\display_s2[6]_433 ), .Z (n_408));
  INVX4 drc_bufs6297(.A (n_413), .Z (display_s2[5]));
  INVX2 drc_bufs6298(.A (\display_s2[5]_432 ), .Z (n_413));
  INVX4 drc_bufs6299(.A (n_418), .Z (display_s2[4]));
  INVX2 drc_bufs6300(.A (\display_s2[4]_431 ), .Z (n_418));
  INVX4 drc_bufs6301(.A (n_423), .Z (display_s2[3]));
  INVX2 drc_bufs6302(.A (\display_s2[3]_430 ), .Z (n_423));
  INVX4 drc_bufs6303(.A (n_428), .Z (display_s2[2]));
  INVX2 drc_bufs6304(.A (\display_s2[2]_429 ), .Z (n_428));
  INVX4 drc_bufs6305(.A (n_433), .Z (display_s2[1]));
  INVX2 drc_bufs6306(.A (\display_s2[1]_428 ), .Z (n_433));
  INVX4 drc_bufs6307(.A (n_438), .Z (display_s2[0]));
  INVX2 drc_bufs6308(.A (\display_s2[0]_427 ), .Z (n_438));
  INVX4 drc_bufs6309(.A (n_443), .Z (display_s1[6]));
  INVX2 drc_bufs6310(.A (\display_s1[6]_412 ), .Z (n_443));
  INVX4 drc_bufs6311(.A (n_448), .Z (display_s1[5]));
  INVX2 drc_bufs6312(.A (\display_s1[5]_411 ), .Z (n_448));
  INVX4 drc_bufs6313(.A (n_453), .Z (display_s1[4]));
  INVX2 drc_bufs6314(.A (\display_s1[4]_410 ), .Z (n_453));
  INVX4 drc_bufs6315(.A (n_458), .Z (display_s1[3]));
  INVX2 drc_bufs6316(.A (\display_s1[3]_409 ), .Z (n_458));
  INVX4 drc_bufs6317(.A (n_463), .Z (display_s1[2]));
  INVX2 drc_bufs6318(.A (\display_s1[2]_408 ), .Z (n_463));
  INVX4 drc_bufs6319(.A (n_468), .Z (display_s1[1]));
  INVX2 drc_bufs6320(.A (\display_s1[1]_407 ), .Z (n_468));
  INVX4 drc_bufs6321(.A (n_473), .Z (display_s1[0]));
  INVX2 drc_bufs6322(.A (\display_s1[0]_406 ), .Z (n_473));
  INVX4 drc_bufs6323(.A (n_478), .Z (display_m2[6]));
  INVX2 drc_bufs6324(.A (\display_m2[6]_440 ), .Z (n_478));
  INVX4 drc_bufs6325(.A (n_483), .Z (display_m2[5]));
  INVX2 drc_bufs6326(.A (\display_m2[5]_439 ), .Z (n_483));
  INVX4 drc_bufs6327(.A (n_488), .Z (display_m2[4]));
  INVX2 drc_bufs6328(.A (\display_m2[4]_438 ), .Z (n_488));
  INVX4 drc_bufs6329(.A (n_493), .Z (display_m2[3]));
  INVX2 drc_bufs6330(.A (\display_m2[3]_437 ), .Z (n_493));
  INVX4 drc_bufs6331(.A (n_498), .Z (display_m2[2]));
  INVX2 drc_bufs6332(.A (\display_m2[2]_436 ), .Z (n_498));
  INVX4 drc_bufs6333(.A (n_503), .Z (display_m2[1]));
  INVX2 drc_bufs6334(.A (\display_m2[1]_435 ), .Z (n_503));
  INVX4 drc_bufs6335(.A (n_508), .Z (display_m2[0]));
  INVX2 drc_bufs6336(.A (\display_m2[0]_434 ), .Z (n_508));
  INVX4 drc_bufs6337(.A (n_513), .Z (display_m1[6]));
  INVX2 drc_bufs6338(.A (\display_m1[6]_419 ), .Z (n_513));
  INVX4 drc_bufs6339(.A (n_518), .Z (display_m1[5]));
  INVX2 drc_bufs6340(.A (\display_m1[5]_418 ), .Z (n_518));
  INVX4 drc_bufs6341(.A (n_523), .Z (display_m1[4]));
  INVX2 drc_bufs6342(.A (\display_m1[4]_417 ), .Z (n_523));
  INVX4 drc_bufs6343(.A (n_528), .Z (display_m1[3]));
  INVX2 drc_bufs6344(.A (\display_m1[3]_416 ), .Z (n_528));
  INVX4 drc_bufs6345(.A (n_533), .Z (display_m1[2]));
  INVX2 drc_bufs6346(.A (\display_m1[2]_415 ), .Z (n_533));
  INVX4 drc_bufs6347(.A (n_538), .Z (display_m1[1]));
  INVX2 drc_bufs6348(.A (\display_m1[1]_414 ), .Z (n_538));
  INVX4 drc_bufs6349(.A (n_543), .Z (display_m1[0]));
  INVX2 drc_bufs6350(.A (\display_m1[0]_413 ), .Z (n_543));
  INVX4 drc_bufs6351(.A (n_548), .Z (display_h2[6]));
  INVX2 drc_bufs6352(.A (\display_h2[6]_447 ), .Z (n_548));
  INVX4 drc_bufs6353(.A (n_553), .Z (display_h2[5]));
  INVX2 drc_bufs6354(.A (\display_h2[5]_446 ), .Z (n_553));
  INVX4 drc_bufs6355(.A (n_558), .Z (display_h2[4]));
  INVX2 drc_bufs6356(.A (\display_h2[4]_445 ), .Z (n_558));
  INVX4 drc_bufs6357(.A (n_563), .Z (display_h2[3]));
  INVX2 drc_bufs6358(.A (\display_h2[3]_444 ), .Z (n_563));
  INVX4 drc_bufs6359(.A (n_568), .Z (display_h2[2]));
  INVX2 drc_bufs6360(.A (\display_h2[2]_443 ), .Z (n_568));
  INVX4 drc_bufs6361(.A (n_573), .Z (display_h2[1]));
  INVX2 drc_bufs6362(.A (\display_h2[1]_442 ), .Z (n_573));
  INVX4 drc_bufs6363(.A (n_578), .Z (display_h2[0]));
  INVX2 drc_bufs6364(.A (\display_h2[0]_441 ), .Z (n_578));
  INVX4 drc_bufs6365(.A (n_583), .Z (display_h1[6]));
  INVX2 drc_bufs6366(.A (\display_h1[6]_426 ), .Z (n_583));
  INVX4 drc_bufs6367(.A (n_588), .Z (display_h1[5]));
  INVX2 drc_bufs6368(.A (\display_h1[5]_425 ), .Z (n_588));
  INVX4 drc_bufs6369(.A (n_593), .Z (display_h1[4]));
  INVX2 drc_bufs6370(.A (\display_h1[4]_424 ), .Z (n_593));
  INVX4 drc_bufs6371(.A (n_598), .Z (display_h1[3]));
  INVX2 drc_bufs6372(.A (\display_h1[3]_423 ), .Z (n_598));
  INVX4 drc_bufs6373(.A (n_603), .Z (display_h1[2]));
  INVX2 drc_bufs6374(.A (\display_h1[2]_422 ), .Z (n_603));
  INVX4 drc_bufs6375(.A (n_608), .Z (display_h1[1]));
  INVX2 drc_bufs6376(.A (\display_h1[1]_421 ), .Z (n_608));
endmodule

module soc_top(clk, reset, btn_mode, btn_set, btn_inc, btn_dec,
     btn_light, h1_6, h1_5, h1_4, h1_3, h1_2, h1_1, h1_0, h0_6, h0_5,
     h0_4, h0_3, h0_2, h0_1, h0_0, m1_6, m1_5, m1_4, m1_3, m1_2, m1_1,
     m1_0, m0_6, m0_5, m0_4, m0_3, m0_2, m0_1, m0_0, s1_6, s1_5, s1_4,
     s1_3, s1_2, s1_1, s1_0, s0_6, s0_5, s0_4, s0_3, s0_2, s0_1, s0_0,
     colon, light);
  input clk, reset, btn_mode, btn_set, btn_inc, btn_dec, btn_light;
  output h1_6, h1_5, h1_4, h1_3, h1_2, h1_1, h1_0, h0_6, h0_5, h0_4,
       h0_3, h0_2, h0_1, h0_0, m1_6, m1_5, m1_4, m1_3, m1_2, m1_1,
       m1_0, m0_6, m0_5, m0_4, m0_3, m0_2, m0_1, m0_0, s1_6, s1_5,
       s1_4, s1_3, s1_2, s1_1, s1_0, s0_6, s0_5, s0_4, s0_3, s0_2,
       s0_1, s0_0, colon, light;
  wire clk, reset, btn_mode, btn_set, btn_inc, btn_dec, btn_light;
  wire h1_6, h1_5, h1_4, h1_3, h1_2, h1_1, h1_0, h0_6, h0_5, h0_4,
       h0_3, h0_2, h0_1, h0_0, m1_6, m1_5, m1_4, m1_3, m1_2, m1_1,
       m1_0, m0_6, m0_5, m0_4, m0_3, m0_2, m0_1, m0_0, s1_6, s1_5,
       s1_4, s1_3, s1_2, s1_1, s1_0, s0_6, s0_5, s0_4, s0_3, s0_2,
       s0_1, s0_0, colon, light;
  wire [2:0] chip_state;
  wire [5:0] chip_t_seconds;
  wire [5:0] chip_t_minutes;
  wire [5:0] chip_t_hours;
  wire [2:0] chip_fsm_next_state;
  wire [25:0] chip_cd_count;
  wire UNCONNECTED, UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0,
       UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z3,
       UNCONNECTED_HIER_Z4, UNCONNECTED_HIER_Z5;
  wire UNCONNECTED_HIER_Z6, UNCONNECTED_HIER_Z7, UNCONNECTED_HIER_Z8,
       UNCONNECTED_HIER_Z9, UNCONNECTED_HIER_Z10, UNCONNECTED_HIER_Z11,
       UNCONNECTED_HIER_Z12, UNCONNECTED_HIER_Z13;
  wire UNCONNECTED_HIER_Z14, UNCONNECTED_HIER_Z15,
       UNCONNECTED_HIER_Z16, btn_dec_PAD, btn_inc_PAD, btn_light_PAD,
       btn_mode_PAD, btn_set_PAD;
  wire chip_backlight_light_mode, chip_cd_inc_add_23_19_n_269,
       chip_cd_inc_add_23_19_n_272, chip_cd_inc_add_23_19_n_278,
       chip_cd_inc_add_23_19_n_281, chip_cd_inc_add_23_19_n_284,
       chip_cd_inc_add_23_19_n_287, chip_cd_inc_add_23_19_n_291;
  wire chip_cd_inc_add_23_19_n_292, chip_cd_inc_add_23_19_n_295,
       chip_cd_inc_add_23_19_n_296, chip_cd_inc_add_23_19_n_301,
       chip_cd_inc_add_23_19_n_304, chip_cd_inc_add_23_19_n_305,
       chip_cd_inc_add_23_19_n_306, chip_cd_inc_add_23_19_n_311;
  wire chip_cd_inc_add_23_19_n_312, chip_cd_inc_add_23_19_n_315,
       chip_cd_inc_add_23_19_n_317, chip_cd_inc_add_23_19_n_319,
       chip_cd_inc_add_23_19_n_321, chip_cd_inc_add_23_19_n_325,
       chip_cd_inc_add_23_19_n_327, chip_cd_inc_add_23_19_n_328;
  wire chip_cd_inc_add_23_19_n_333, chip_cd_inc_add_23_19_n_336,
       chip_cd_inc_add_23_19_n_338, chip_cd_inc_add_23_19_n_340,
       chip_cd_inc_add_23_19_n_341, chip_cd_inc_add_23_19_n_345,
       chip_cd_inc_add_23_19_n_347, chip_cd_inc_add_23_19_n_349;
  wire chip_cd_inc_add_23_19_n_350, chip_cd_inc_add_23_19_n_351,
       chip_cd_inc_add_23_19_n_352, chip_cd_inc_add_23_19_n_355,
       chip_cd_inc_add_23_19_n_359, chip_cd_inc_add_23_19_n_361,
       chip_cd_inc_add_23_19_n_362, chip_cd_inc_add_23_19_n_364;
  wire chip_cd_inc_add_23_19_n_365, chip_cd_inc_add_23_19_n_367,
       chip_cd_inc_add_23_19_n_368, chip_cd_inc_add_23_19_n_370,
       chip_cd_inc_add_23_19_n_371, chip_cd_inc_add_23_19_n_373,
       chip_cd_inc_add_23_19_n_375, chip_cd_inc_add_23_19_n_397;
  wire chip_cd_n_73, chip_cd_n_74, chip_cd_n_75, chip_cd_n_76,
       chip_cd_n_77, chip_cd_n_78, chip_cd_n_79, chip_cd_n_80;
  wire chip_cd_n_81, chip_cd_n_82, chip_cd_n_83, chip_cd_n_84,
       chip_cd_n_85, chip_cd_n_86, chip_cd_n_87, chip_cd_n_88;
  wire chip_cd_n_89, chip_cd_n_90, chip_cd_n_91, chip_cd_n_92,
       chip_cd_n_93, chip_cd_n_94, chip_cd_n_95, chip_cd_n_96;
  wire chip_cd_n_97, chip_clk_seconds, chip_clock_old_clk_1sec,
       chip_fsm_n_514, chip_fsm_n_522, chip_fsm_n_543,
       chip_fsm_swFF_Q_9, clk_PAD;
  wire h0_PAD_0, h0_PAD_1, h0_PAD_2, h0_PAD_3, h0_PAD_4, h0_PAD_5,
       h0_PAD_6, h1_PAD_0;
  wire h1_PAD_1, h1_PAD_2, h1_PAD_3, h1_PAD_4, h1_PAD_5, h1_PAD_6,
       light_PAD, m0_PAD_0;
  wire m0_PAD_1, m0_PAD_2, m0_PAD_3, m0_PAD_4, m0_PAD_5, m0_PAD_6,
       m1_PAD_0, m1_PAD_1;
  wire m1_PAD_2, m1_PAD_3, m1_PAD_4, m1_PAD_5, m1_PAD_6, n_0, n_1, n_2;
  wire n_3, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_154, n_155, n_156;
  wire n_157, n_158, n_159, n_160, n_161, n_162, n_163, n_164;
  wire n_166, n_178, n_179, n_184, n_185, n_187, n_188, n_192;
  wire n_193, n_196, n_198, n_199, n_200, n_201, n_202, n_203;
  wire n_204, n_205, n_206, n_207, n_208, n_209, n_210, n_211;
  wire n_212, n_213, n_214, n_215, n_216, n_217, n_218, n_219;
  wire n_220, n_221, n_222, n_223, n_224, n_225, n_226, n_227;
  wire n_228, n_229, n_230, n_231, n_232, n_233, n_234, n_235;
  wire n_236, n_237, n_238, n_239, n_240, n_241, n_242, n_243;
  wire n_244, n_245, n_246, n_247, n_248, n_249, n_250, reset_PAD;
  wire s0_PAD_0, s0_PAD_1, s0_PAD_2, s0_PAD_3, s0_PAD_4, s0_PAD_5,
       s0_PAD_6, s1_PAD_0;
  wire s1_PAD_1, s1_PAD_2, s1_PAD_3, s1_PAD_4, s1_PAD_5, s1_PAD_6;
  assign chip_backlight_light_mode = 1'b0;
  assign chip_fsm_next_state[2] = 1'b0;
  assign chip_fsm_next_state[1] = 1'b0;
  assign chip_fsm_next_state[0] = 1'b0;
  Seg7Display chip_displayer(.clk (clk_PAD), .reset (reset_PAD),
       .seconds_clk (chip_clk_seconds), .state (chip_state), .current_s
       (chip_t_seconds), .current_m (chip_t_minutes), .current_h
       (chip_t_hours), .stopwatch_s ({UNCONNECTED_HIER_Z4,
       UNCONNECTED_HIER_Z3, UNCONNECTED_HIER_Z2, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z}), .stopwatch_m
       ({UNCONNECTED_HIER_Z10, UNCONNECTED_HIER_Z9,
       UNCONNECTED_HIER_Z8, UNCONNECTED_HIER_Z7, UNCONNECTED_HIER_Z6,
       UNCONNECTED_HIER_Z5}), .stopwatch_h ({UNCONNECTED_HIER_Z16,
       UNCONNECTED_HIER_Z15, UNCONNECTED_HIER_Z14,
       UNCONNECTED_HIER_Z13, UNCONNECTED_HIER_Z12,
       UNCONNECTED_HIER_Z11}), .display_s1 ({s0_PAD_6, s0_PAD_5,
       s0_PAD_4, s0_PAD_3, s0_PAD_2, s0_PAD_1, s0_PAD_0}), .display_m1
       ({m0_PAD_6, m0_PAD_5, m0_PAD_4, m0_PAD_3, m0_PAD_2, m0_PAD_1,
       m0_PAD_0}), .display_h1 ({h0_PAD_6, h0_PAD_5, h0_PAD_4,
       h0_PAD_3, h0_PAD_2, h0_PAD_1, h0_PAD_0}), .display_s2
       ({s1_PAD_6, s1_PAD_5, s1_PAD_4, s1_PAD_3, s1_PAD_2, s1_PAD_1,
       s1_PAD_0}), .display_m2 ({m1_PAD_6, m1_PAD_5, m1_PAD_4,
       m1_PAD_3, m1_PAD_2, m1_PAD_1, m1_PAD_0}), .display_h2
       ({h1_PAD_6, h1_PAD_5, h1_PAD_4, h1_PAD_3, h1_PAD_2, h1_PAD_1,
       h1_PAD_0}), .second (UNCONNECTED));
  pad_in btn_dec_pad(.pad (btn_dec), .DataIn (btn_dec_PAD));
  pad_in btn_inc_pad(.pad (btn_inc), .DataIn (btn_inc_PAD));
  pad_in btn_light_pad(.pad (btn_light), .DataIn (btn_light_PAD));
  pad_in btn_mode_pad(.pad (btn_mode), .DataIn (btn_mode_PAD));
  pad_in btn_set_pad(.pad (btn_set), .DataIn (btn_set_PAD));
  pad_in clk_pad(.pad (clk), .DataIn (clk_PAD));
  pad_out colon_pad(.DataOut (1'b0), .pad (colon));
  pad_out h0_pad_0(.DataOut (h0_PAD_0), .pad (h0_0));
  pad_out h0_pad_1(.DataOut (h0_PAD_1), .pad (h0_1));
  pad_out h0_pad_2(.DataOut (h0_PAD_2), .pad (h0_2));
  pad_out h0_pad_3(.DataOut (h0_PAD_3), .pad (h0_3));
  pad_out h0_pad_4(.DataOut (h0_PAD_4), .pad (h0_4));
  pad_out h0_pad_5(.DataOut (h0_PAD_5), .pad (h0_5));
  pad_out h0_pad_6(.DataOut (h0_PAD_6), .pad (h0_6));
  pad_out h1_pad_0(.DataOut (h1_PAD_0), .pad (h1_0));
  pad_out h1_pad_1(.DataOut (h1_PAD_1), .pad (h1_1));
  pad_out h1_pad_2(.DataOut (h1_PAD_2), .pad (h1_2));
  pad_out h1_pad_3(.DataOut (h1_PAD_3), .pad (h1_3));
  pad_out h1_pad_4(.DataOut (h1_PAD_4), .pad (h1_4));
  pad_out h1_pad_5(.DataOut (h1_PAD_5), .pad (h1_5));
  pad_out h1_pad_6(.DataOut (h1_PAD_6), .pad (h1_6));
  pad_out light_pad(.DataOut (light_PAD), .pad (light));
  pad_out m0_pad_0(.DataOut (m0_PAD_0), .pad (m0_0));
  pad_out m0_pad_1(.DataOut (m0_PAD_1), .pad (m0_1));
  pad_out m0_pad_2(.DataOut (m0_PAD_2), .pad (m0_2));
  pad_out m0_pad_3(.DataOut (m0_PAD_3), .pad (m0_3));
  pad_out m0_pad_4(.DataOut (m0_PAD_4), .pad (m0_4));
  pad_out m0_pad_5(.DataOut (m0_PAD_5), .pad (m0_5));
  pad_out m0_pad_6(.DataOut (m0_PAD_6), .pad (m0_6));
  pad_out m1_pad_0(.DataOut (m1_PAD_0), .pad (m1_0));
  pad_out m1_pad_1(.DataOut (m1_PAD_1), .pad (m1_1));
  pad_out m1_pad_2(.DataOut (m1_PAD_2), .pad (m1_2));
  pad_out m1_pad_3(.DataOut (m1_PAD_3), .pad (m1_3));
  pad_out m1_pad_4(.DataOut (m1_PAD_4), .pad (m1_4));
  pad_out m1_pad_5(.DataOut (m1_PAD_5), .pad (m1_5));
  pad_out m1_pad_6(.DataOut (m1_PAD_6), .pad (m1_6));
  pad_in reset_pad(.pad (reset), .DataIn (reset_PAD));
  pad_out s0_pad_0(.DataOut (s0_PAD_0), .pad (s0_0));
  pad_out s0_pad_1(.DataOut (s0_PAD_1), .pad (s0_1));
  pad_out s0_pad_2(.DataOut (s0_PAD_2), .pad (s0_2));
  pad_out s0_pad_3(.DataOut (s0_PAD_3), .pad (s0_3));
  pad_out s0_pad_4(.DataOut (s0_PAD_4), .pad (s0_4));
  pad_out s0_pad_5(.DataOut (s0_PAD_5), .pad (s0_5));
  pad_out s0_pad_6(.DataOut (s0_PAD_6), .pad (s0_6));
  pad_out s1_pad_0(.DataOut (s1_PAD_0), .pad (s1_0));
  pad_out s1_pad_1(.DataOut (s1_PAD_1), .pad (s1_1));
  pad_out s1_pad_2(.DataOut (s1_PAD_2), .pad (s1_2));
  pad_out s1_pad_3(.DataOut (s1_PAD_3), .pad (s1_3));
  pad_out s1_pad_4(.DataOut (s1_PAD_4), .pad (s1_4));
  pad_out s1_pad_5(.DataOut (s1_PAD_5), .pad (s1_5));
  pad_out s1_pad_6(.DataOut (s1_PAD_6), .pad (s1_6));
  DFFQX1 \chip_fsm_next_state_reg[0] (.CLK (clk_PAD), .D (n_250), .Q
       (chip_fsm_next_state[0]));
  DFFQX1 \chip_fsm_next_state_reg[1] (.CLK (clk_PAD), .D (n_249), .Q
       (chip_fsm_next_state[1]));
  DFFQX1 \chip_fsm_next_state_reg[2] (.CLK (clk_PAD), .D (n_248), .Q
       (chip_fsm_next_state[2]));
  NAND3X1 g2224__5122(.A (n_246), .B (n_223), .C (n_227), .Z (n_250));
  NAND3X1 g2225__8246(.A (n_247), .B (n_228), .C (n_226), .Z (n_249));
  NAND3X1 g2226__7098(.A (n_242), .B (n_235), .C (n_234), .Z (n_248));
  NOR2X1 g2227__6131(.A (n_213), .B (n_244), .Z (n_247));
  NOR2X1 g2228__1881(.A (n_237), .B (n_245), .Z (n_246));
  OR2X1 g2229__5115(.A (n_231), .B (n_243), .Z (n_245));
  NAND3X1 g2230__7482(.A (n_241), .B (n_236), .C (n_233), .Z (n_244));
  NOR2X1 g2231__4733(.A (chip_state[1]), .B (n_239), .Z (n_243));
  AND2X1 g2232__6161(.A (n_240), .B (n_230), .Z (n_242));
  NAND2X1 g2233__9315(.A (n_238), .B (n_202), .Z (n_241));
  OR2X1 g2234__9945(.A (chip_fsm_n_514), .B (n_232), .Z (n_240));
  AND2X1 g2235__2883(.A (n_229), .B (n_218), .Z (n_239));
  OR2X1 g2236__2346(.A (n_200), .B (n_225), .Z (n_238));
  NOR2X1 g2237__1666(.A (btn_inc_PAD), .B (n_235), .Z (n_237));
  OR2X1 g2238__7410(.A (btn_inc_PAD), .B (n_224), .Z (n_236));
  NAND2X1 g2239__6417(.A (n_217), .B (btn_inc_PAD), .Z (n_234));
  OR2X1 g2240__5477(.A (btn_mode_PAD), .B (n_212), .Z (n_233));
  AND2X1 g2241__2398(.A (n_221), .B (n_219), .Z (n_232));
  NOR2X1 g2242__5107(.A (n_220), .B (n_207), .Z (n_231));
  NAND3X1 g2243__6260(.A (n_206), .B (n_21), .C (n_12), .Z (n_230));
  NAND2X1 g2244__4319(.A (n_217), .B (btn_dec_PAD), .Z (n_235));
  XOR2X1 g2245__8428(.A (chip_state[0]), .B (n_208), .Z (n_229));
  NAND2X1 g2246__5526(.A (n_216), .B (chip_fsm_swFF_Q_9), .Z (n_228));
  OR2X1 g2247__6783(.A (chip_fsm_n_522), .B (n_215), .Z (n_227));
  OR2X1 g2248__3680(.A (chip_state[1]), .B (n_214), .Z (n_226));
  NOR2X1 g2249__1617(.A (btn_dec_PAD), .B (n_215), .Z (n_225));
  OR2X1 g2250__2802(.A (btn_dec_PAD), .B (n_222), .Z (n_224));
  NAND3X1 g2251__1705(.A (n_201), .B (chip_state[2]), .C (n_211), .Z
       (n_223));
  OR2X1 g2252__5122(.A (n_210), .B (chip_fsm_n_522), .Z (n_222));
  NAND2X1 g2253__8246(.A (n_209), .B (chip_fsm_swFF_Q_9), .Z (n_221));
  AND2X1 g2254__7098(.A (n_203), .B (n_12), .Z (n_220));
  OR2X1 g2255__6131(.A (n_211), .B (n_196), .Z (n_219));
  NAND2X1 g2256__1881(.A (n_202), .B (btn_mode_PAD), .Z (n_218));
  INVX2 g2257(.A (n_216), .Z (chip_fsm_n_543));
  OR2X1 g2258__5115(.A (n_199), .B (n_202), .Z (n_214));
  NOR2X1 g2259__7482(.A (n_12), .B (n_207), .Z (n_213));
  OR2X1 g2260__4733(.A (btn_set_PAD), .B (chip_fsm_n_514), .Z (n_212));
  NOR2X1 g2261__6161(.A (n_198), .B (chip_fsm_n_522), .Z (n_217));
  NOR2X1 g2262__9315(.A (chip_state[2]), .B (chip_fsm_n_514), .Z
       (n_216));
  NAND3X1 g2263__9945(.A (chip_state[1]), .B (n_193), .C (n_12), .Z
       (n_215));
  INVX2 g2264(.A (n_210), .Z (n_211));
  INVX2 g2265(.A (n_208), .Z (n_209));
  INVX2 g2266(.A (n_207), .Z (n_206));
  DFFQSRX1 chip_backlight_light_reg(.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_backlight_light_mode), .Q (n_204));
  INVX4 g2268(.A (n_205), .Z (light_PAD));
  INVX2 g2269(.A (n_204), .Z (n_205));
  NAND2X1 g2270__2883(.A (n_193), .B (btn_dec_PAD), .Z (n_203));
  NAND2X1 g2271__2346(.A (n_193), .B (btn_set_PAD), .Z (n_210));
  NAND2X1 g2272__1666(.A (n_196), .B (btn_set_PAD), .Z (n_208));
  NAND2X1 g2273__7410(.A (chip_state[2]), .B (n_198), .Z (n_207));
  INVX2 g2274(.A (chip_fsm_n_514), .Z (n_201));
  NOR2X1 g2275__6417(.A (n_193), .B (chip_state[0]), .Z (n_200));
  NOR2X1 g2276__5477(.A (btn_mode_PAD), .B (chip_state[0]), .Z (n_199));
  NOR2X1 g2277__2398(.A (btn_set_PAD), .B (chip_state[2]), .Z (n_202));
  NAND2X1 g2278__5107(.A (chip_state[0]), .B (n_196), .Z
       (chip_fsm_n_522));
  NAND2X1 g2279__6260(.A (n_21), .B (chip_state[1]), .Z
       (chip_fsm_n_514));
  INVX2 g2280(.A (chip_state[1]), .Z (n_198));
  INVX2 g2281(.A (chip_state[0]), .Z (n_21));
  INVX2 g2282(.A (chip_state[2]), .Z (n_196));
  INVX2 g2283(.A (reset_PAD), .Z (n_13));
  INVX2 g2284(.A (btn_inc_PAD), .Z (n_12));
  INVX2 g2285(.A (btn_mode_PAD), .Z (n_193));
  DFFQSRX1 chip_backlight_light_mode_reg(.SETB (n_13), .RESETB (1'b1),
       .CLK (clk_PAD), .D (n_36), .Q (chip_backlight_light_mode));
  DFFQSRX1 chip_cd_clk_seconds_reg(.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_192), .Q (chip_clk_seconds));
  DFFQSRX1 \chip_cd_count_reg[0] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_166), .Q (chip_cd_count[0]));
  DFFQSRX1 \chip_cd_count_reg[1] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_73), .Q (chip_cd_count[1]));
  DFFQSRX1 \chip_cd_count_reg[2] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_74), .Q (chip_cd_count[2]));
  DFFQSRX1 \chip_cd_count_reg[3] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_187), .Q (chip_cd_count[3]));
  DFFQSRX1 \chip_cd_count_reg[4] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_76), .Q (chip_cd_count[4]));
  DFFQSRX1 \chip_cd_count_reg[5] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_188), .Q (chip_cd_count[5]));
  DFFQSRX1 \chip_cd_count_reg[6] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_78), .Q (chip_cd_count[6]));
  DFFQSRX1 \chip_cd_count_reg[7] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_185), .Q (chip_cd_count[7]));
  DFFQSRX1 \chip_cd_count_reg[8] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_184), .Q (chip_cd_count[8]));
  DFFQSRX1 \chip_cd_count_reg[9] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_81), .Q (chip_cd_count[9]));
  DFFQSRX1 \chip_cd_count_reg[10] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_82), .Q (chip_cd_count[10]));
  DFFQSRX1 \chip_cd_count_reg[11] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_83), .Q (chip_cd_count[11]));
  DFFQSRX1 \chip_cd_count_reg[12] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_84), .Q (chip_cd_count[12]));
  DFFQSRX1 \chip_cd_count_reg[13] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_179), .Q (chip_cd_count[13]));
  DFFQSRX1 \chip_cd_count_reg[14] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_178), .Q (chip_cd_count[14]));
  DFFQSRX1 \chip_cd_count_reg[15] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_87), .Q (chip_cd_count[15]));
  DFFQSRX1 \chip_cd_count_reg[16] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_88), .Q (chip_cd_count[16]));
  DFFQSRX1 \chip_cd_count_reg[17] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_89), .Q (chip_cd_count[17]));
  DFFQSRX1 \chip_cd_count_reg[18] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_90), .Q (chip_cd_count[18]));
  DFFQSRX1 \chip_cd_count_reg[19] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_91), .Q (chip_cd_count[19]));
  DFFQSRX1 \chip_cd_count_reg[20] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_92), .Q (chip_cd_count[20]));
  DFFQSRX1 \chip_cd_count_reg[21] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_93), .Q (chip_cd_count[21]));
  DFFQSRX1 \chip_cd_count_reg[22] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_94), .Q (chip_cd_count[22]));
  DFFQSRX1 \chip_cd_count_reg[23] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_95), .Q (chip_cd_count[23]));
  DFFQSRX1 \chip_cd_count_reg[24] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_96), .Q (chip_cd_count[24]));
  DFFQSRX1 \chip_cd_count_reg[25] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_cd_n_97), .Q (chip_cd_count[25]));
  DFFQSRX1 \chip_clock_hours_reg[0] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_139), .Q (chip_t_hours[0]));
  DFFQX1 \chip_clock_hours_reg[0]47 (.CLK (n_128), .D (n_8), .Q
       (chip_t_hours[0]));
  DFFQX1 \chip_clock_hours_reg[0]53 (.CLK (n_117), .D (n_8), .Q
       (chip_t_hours[0]));
  DFFQSRX1 \chip_clock_hours_reg[1] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_146), .Q (chip_t_hours[1]));
  DFFQX1 \chip_clock_hours_reg[1]48 (.CLK (n_128), .D (n_44), .Q
       (chip_t_hours[1]));
  DFFQX1 \chip_clock_hours_reg[1]54 (.CLK (n_117), .D (n_43), .Q
       (chip_t_hours[1]));
  DFFQSRX1 \chip_clock_hours_reg[2] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_141), .Q (chip_t_hours[2]));
  DFFQX1 \chip_clock_hours_reg[2]49 (.CLK (n_128), .D (n_67), .Q
       (chip_t_hours[2]));
  DFFQX1 \chip_clock_hours_reg[2]55 (.CLK (n_117), .D (n_61), .Q
       (chip_t_hours[2]));
  DFFQSRX1 \chip_clock_hours_reg[3] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_144), .Q (chip_t_hours[3]));
  DFFQX1 \chip_clock_hours_reg[3]50 (.CLK (n_128), .D (n_1), .Q
       (chip_t_hours[3]));
  DFFQX1 \chip_clock_hours_reg[3]56 (.CLK (n_117), .D (n_103), .Q
       (chip_t_hours[3]));
  DFFQSRX1 \chip_clock_hours_reg[4] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_143), .Q (chip_t_hours[4]));
  DFFQX1 \chip_clock_hours_reg[4]51 (.CLK (n_128), .D (n_0), .Q
       (chip_t_hours[4]));
  DFFQX1 \chip_clock_hours_reg[4]57 (.CLK (n_117), .D (n_92), .Q
       (chip_t_hours[4]));
  DFFQSRX1 \chip_clock_hours_reg[5] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (n_140), .Q (chip_t_hours[5]));
  DFFQX1 \chip_clock_hours_reg[5]52 (.CLK (n_128), .D (n_114), .Q
       (chip_t_hours[5]));
  DFFQX1 \chip_clock_hours_reg[5]58 (.CLK (n_117), .D (n_102), .Q
       (chip_t_hours[5]));
  DFFQSRX1 \chip_clock_minutes_reg[0] (.SETB (n_13), .RESETB (1'b1),
       .CLK (clk_PAD), .D (n_130), .Q (chip_t_minutes[0]));
  DFFQX1 \chip_clock_minutes_reg[0]35 (.CLK (n_127), .D (n_10), .Q
       (chip_t_minutes[0]));
  DFFQX1 \chip_clock_minutes_reg[0]41 (.CLK (n_116), .D (n_10), .Q
       (chip_t_minutes[0]));
  DFFQSRX1 \chip_clock_minutes_reg[1] (.SETB (n_13), .RESETB (1'b1),
       .CLK (clk_PAD), .D (n_134), .Q (chip_t_minutes[1]));
  DFFQX1 \chip_clock_minutes_reg[1]36 (.CLK (n_127), .D (n_46), .Q
       (chip_t_minutes[1]));
  DFFQX1 \chip_clock_minutes_reg[1]42 (.CLK (n_116), .D (n_45), .Q
       (chip_t_minutes[1]));
  DFFQSRX1 \chip_clock_minutes_reg[2] (.SETB (n_13), .RESETB (1'b1),
       .CLK (clk_PAD), .D (n_148), .Q (chip_t_minutes[2]));
  DFFQX1 \chip_clock_minutes_reg[2]37 (.CLK (n_127), .D (n_98), .Q
       (chip_t_minutes[2]));
  DFFQX1 \chip_clock_minutes_reg[2]43 (.CLK (n_116), .D (n_78), .Q
       (chip_t_minutes[2]));
  DFFQSRX1 \chip_clock_minutes_reg[3] (.SETB (n_13), .RESETB (1'b1),
       .CLK (clk_PAD), .D (n_147), .Q (chip_t_minutes[3]));
  DFFQX1 \chip_clock_minutes_reg[3]38 (.CLK (n_127), .D (n_97), .Q
       (chip_t_minutes[3]));
  DFFQX1 \chip_clock_minutes_reg[3]44 (.CLK (n_116), .D (n_79), .Q
       (chip_t_minutes[3]));
  DFFQSRX1 \chip_clock_minutes_reg[4] (.SETB (n_13), .RESETB (1'b1),
       .CLK (clk_PAD), .D (n_150), .Q (chip_t_minutes[4]));
  DFFQX1 \chip_clock_minutes_reg[4]39 (.CLK (n_127), .D (n_108), .Q
       (chip_t_minutes[4]));
  DFFQX1 \chip_clock_minutes_reg[4]45 (.CLK (n_116), .D (n_91), .Q
       (chip_t_minutes[4]));
  DFFQSRX1 \chip_clock_minutes_reg[5] (.SETB (n_13), .RESETB (1'b1),
       .CLK (clk_PAD), .D (n_142), .Q (chip_t_minutes[5]));
  DFFQX1 \chip_clock_minutes_reg[5]40 (.CLK (n_127), .D (n_107), .Q
       (chip_t_minutes[5]));
  DFFQX1 \chip_clock_minutes_reg[5]46 (.CLK (n_116), .D (n_109), .Q
       (chip_t_minutes[5]));
  DFFQSRX1 chip_clock_old_clk_1sec_reg(.SETB (n_13), .RESETB (1'b1),
       .CLK (clk_PAD), .D (chip_clk_seconds), .Q
       (chip_clock_old_clk_1sec));
  DFFQSRX1 \chip_clock_seconds_reg[0] (.SETB (n_13), .RESETB (1'b1),
       .CLK (clk_PAD), .D (n_57), .Q (chip_t_seconds[0]));
  DFFQSRX1 \chip_clock_seconds_reg[1] (.SETB (n_13), .RESETB (1'b1),
       .CLK (clk_PAD), .D (n_80), .Q (chip_t_seconds[1]));
  DFFQSRX1 \chip_clock_seconds_reg[2] (.SETB (n_13), .RESETB (1'b1),
       .CLK (clk_PAD), .D (n_106), .Q (chip_t_seconds[2]));
  DFFQSRX1 \chip_clock_seconds_reg[3] (.SETB (n_13), .RESETB (1'b1),
       .CLK (clk_PAD), .D (n_120), .Q (chip_t_seconds[3]));
  DFFQSRX1 \chip_clock_seconds_reg[4] (.SETB (n_13), .RESETB (1'b1),
       .CLK (clk_PAD), .D (n_131), .Q (chip_t_seconds[4]));
  DFFQSRX1 \chip_clock_seconds_reg[5] (.SETB (n_13), .RESETB (1'b1),
       .CLK (clk_PAD), .D (n_145), .Q (chip_t_seconds[5]));
  DFFQSRX1 \chip_fsm_state_reg[0] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_fsm_next_state[0]), .Q (chip_state[0]));
  DFFQSRX1 \chip_fsm_state_reg[1] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_fsm_next_state[1]), .Q (chip_state[1]));
  DFFQSRX1 \chip_fsm_state_reg[2] (.SETB (n_13), .RESETB (1'b1), .CLK
       (clk_PAD), .D (chip_fsm_next_state[2]), .Q (chip_state[2]));
  DFFQX1 chip_fsm_swFF_Q_reg(.CLK (clk_PAD), .D (n_77), .Q
       (chip_fsm_swFF_Q_9));
  XOR2X1 g3791__4319(.A (chip_clk_seconds), .B (n_3), .Z (n_192));
  AND2X1 g3808__8428(.A (n_2), .B (chip_cd_n_77), .Z (n_188));
  AND2X1 g3809__5526(.A (n_2), .B (chip_cd_n_75), .Z (n_187));
  AND2X1 g3811__6783(.A (n_2), .B (chip_cd_n_79), .Z (n_185));
  AND2X1 g3812__3680(.A (n_2), .B (chip_cd_n_80), .Z (n_184));
  AND2X1 g3817__1617(.A (n_2), .B (chip_cd_n_85), .Z (n_179));
  AND2X1 g3818__2802(.A (n_2), .B (chip_cd_n_86), .Z (n_178));
  NOR2X1 g3830__1705(.A (chip_cd_count[0]), .B (n_3), .Z (n_166));
  OR2X1 g3832__5122(.A (chip_cd_count[16]), .B (n_164), .Z (n_2));
  OR2X1 g3833__8246(.A (chip_cd_count[15]), .B (n_163), .Z (n_164));
  OR2X1 g3834__7098(.A (chip_cd_count[18]), .B (n_162), .Z (n_163));
  OR2X1 g3835__6131(.A (chip_cd_count[17]), .B (n_161), .Z (n_162));
  OR2X1 g3836__1881(.A (chip_cd_count[20]), .B (n_160), .Z (n_161));
  OR2X1 g3837__5115(.A (chip_cd_count[19]), .B (n_159), .Z (n_160));
  OR2X1 g3838__7482(.A (chip_cd_count[21]), .B (n_158), .Z (n_159));
  OR2X1 g3839__4733(.A (chip_cd_count[0]), .B (n_157), .Z (n_158));
  NAND3X1 g3840__6161(.A (n_156), .B (chip_cd_count[14]), .C
       (chip_cd_count[13]), .Z (n_157));
  NOR2X1 g3841__9315(.A (chip_cd_count[12]), .B (n_155), .Z (n_156));
  OR2X1 g3842__9945(.A (chip_cd_count[11]), .B (n_154), .Z (n_155));
  OR2X1 g3843__2883(.A (chip_cd_count[10]), .B (n_153), .Z (n_154));
  OR2X1 g3844__2346(.A (chip_cd_count[25]), .B (n_152), .Z (n_153));
  OR2X1 g3845__1666(.A (chip_cd_count[24]), .B (n_151), .Z (n_152));
  OR2X1 g3854__7410(.A (chip_cd_count[23]), .B (n_149), .Z (n_151));
  NAND2X1 g3858__6417(.A (n_135), .B (n_118), .Z (n_150));
  OR2X1 g3861__5477(.A (chip_cd_count[9]), .B (n_133), .Z (n_149));
  NAND2X1 g3862__2398(.A (n_137), .B (n_121), .Z (n_148));
  NAND2X1 g3863__5107(.A (n_138), .B (n_123), .Z (n_147));
  MUX2X1 g3865__6260(.A (n_44), .B (chip_t_hours[1]), .S (n_125), .Z
       (n_146));
  NAND2X1 g3866__4319(.A (n_132), .B (n_129), .Z (n_145));
  MUX2X1 g3867__8428(.A (n_1), .B (chip_t_hours[3]), .S (n_125), .Z
       (n_144));
  MUX2X1 g3868__5526(.A (n_0), .B (chip_t_hours[4]), .S (n_125), .Z
       (n_143));
  NAND2X1 g3869__6783(.A (n_136), .B (n_122), .Z (n_142));
  MUX2X1 g3870__3680(.A (n_67), .B (chip_t_hours[2]), .S (n_125), .Z
       (n_141));
  MUX2X1 g3871__1617(.A (n_114), .B (chip_t_hours[5]), .S (n_125), .Z
       (n_140));
  XOR2X1 g3872__2802(.A (chip_t_hours[0]), .B (n_124), .Z (n_139));
  NAND2X1 g3873__1705(.A (n_126), .B (n_82), .Z (n_138));
  NAND2X1 g3874__5122(.A (n_126), .B (n_68), .Z (n_137));
  NAND2X1 g3875__8246(.A (n_104), .B (n_126), .Z (n_136));
  NAND2X1 g3876__7098(.A (n_126), .B (n_100), .Z (n_135));
  MUX2X1 g3878__6131(.A (n_46), .B (chip_t_minutes[1]), .S (n_112), .Z
       (n_134));
  NAND3X1 g3879__1881(.A (n_110), .B (chip_cd_count[8]), .C
       (chip_cd_count[7]), .Z (n_133));
  NAND2X1 g3880__5115(.A (n_119), .B (chip_t_seconds[5]), .Z (n_132));
  MUX2X1 g3881__7482(.A (n_113), .B (n_115), .S (chip_t_seconds[4]), .Z
       (n_131));
  XOR2X1 g3882__4733(.A (chip_t_minutes[0]), .B (n_111), .Z (n_130));
  NAND2X1 g3883__6161(.A (n_113), .B (chip_t_seconds[4]), .Z (n_129));
  INVX2 g3890(.A (n_125), .Z (n_124));
  NAND2X1 g3891__9315(.A (n_112), .B (chip_t_minutes[3]), .Z (n_123));
  NAND2X1 g3892__9945(.A (n_112), .B (chip_t_minutes[5]), .Z (n_122));
  NAND2X1 g3893__2883(.A (n_112), .B (chip_t_minutes[2]), .Z (n_121));
  NAND2X1 g3894__2346(.A (n_105), .B (n_64), .Z (n_120));
  OR2X1 g3895__1666(.A (n_17), .B (n_115), .Z (n_119));
  NAND2X1 g3896__7410(.A (n_112), .B (chip_t_minutes[4]), .Z (n_118));
  NOR2X1 g3897__6417(.A (n_87), .B (n_112), .Z (n_126));
  NAND3X1 g3898__5477(.A (n_111), .B (n_87), .C (n_7), .Z (n_125));
  INVX2 g3908(.A (n_112), .Z (n_111));
  NOR2X1 g3909__2398(.A (chip_cd_count[22]), .B (n_94), .Z (n_110));
  XOR2X1 g3910__5107(.A (chip_t_minutes[5]), .B (n_75), .Z (n_109));
  AND2X1 g3911__6260(.A (n_100), .B (n_88), .Z (n_108));
  AND2X1 g3912__4319(.A (n_104), .B (n_88), .Z (n_107));
  NAND2X1 g3913__8428(.A (n_96), .B (n_60), .Z (n_106));
  NAND2X1 g3914__5526(.A (n_93), .B (n_89), .Z (n_105));
  NAND2X1 g3915__6783(.A (n_95), .B (n_37), .Z (n_115));
  XOR2X1 g3916__3680(.A (chip_t_hours[5]), .B (n_84), .Z (n_114));
  AND2X1 g3917__1617(.A (n_101), .B (n_37), .Z (n_113));
  NAND3X1 g3918__2802(.A (n_90), .B (n_37), .C (n_15), .Z (n_112));
  NOR2X1 g3919__1705(.A (n_41), .B (n_76), .Z (n_103));
  AND2X1 g3923__5122(.A (n_85), .B (chip_t_hours[5]), .Z (n_102));
  NOR2X1 g3924__8246(.A (n_66), .B (n_90), .Z (n_101));
  OR2X1 g3926__7098(.A (chip_t_minutes[5]), .B (n_86), .Z (n_104));
  AND2X1 g3929__6131(.A (n_88), .B (n_68), .Z (n_98));
  AND2X1 g3930__1881(.A (n_82), .B (n_88), .Z (n_97));
  NAND3X1 g3931__5115(.A (n_89), .B (n_42), .C (n_15), .Z (n_96));
  NAND2X1 g3932__7482(.A (n_89), .B (n_66), .Z (n_95));
  NAND3X1 g3933__4733(.A (n_59), .B (n_19), .C (chip_cd_count[5]), .Z
       (n_94));
  MUX2X1 g3934__6161(.A (n_63), .B (chip_t_seconds[3]), .S (n_15), .Z
       (n_93));
  XOR2X1 g3935__9315(.A (chip_t_hours[4]), .B (n_72), .Z (n_92));
  XOR2X1 g3936__9945(.A (chip_t_minutes[4]), .B (n_74), .Z (n_91));
  XOR2X1 g3937__2883(.A (chip_t_minutes[4]), .B (n_71), .Z (n_100));
  XOR2X1 g3938__2346(.A (chip_t_hours[4]), .B (n_73), .Z (n_99));
  INVX2 g3939(.A (n_90), .Z (n_89));
  INVX2 g3940(.A (n_88), .Z (n_87));
  AND2X1 g3941__1666(.A (n_71), .B (chip_t_minutes[4]), .Z (n_86));
  NAND2X1 g3944__7410(.A (n_72), .B (n_6), .Z (n_85));
  AND2X1 g3945__6417(.A (n_73), .B (chip_t_hours[4]), .Z (n_84));
  NOR2X1 g3947__5477(.A (n_17), .B (n_58), .Z (n_90));
  NAND3X1 g3948__2398(.A (n_48), .B (chip_t_minutes[4]), .C
       (chip_t_minutes[3]), .Z (n_88));
  XOR2X1 g3949__5107(.A (chip_t_seconds[1]), .B (n_38), .Z (n_80));
  XOR2X1 g3950__6260(.A (chip_t_minutes[3]), .B (n_54), .Z (n_79));
  AND2X1 g3951__4319(.A (n_56), .B (n_65), .Z (n_78));
  NAND2X1 g3952__8428(.A (n_62), .B (n_34), .Z (n_77));
  NOR2X1 g3953__5526(.A (n_69), .B (n_72), .Z (n_76));
  NOR2X1 g3954__6783(.A (n_70), .B (n_73), .Z (n_83));
  NOR2X1 g3955__3680(.A (n_55), .B (n_71), .Z (n_82));
  AND2X1 g3956__1617(.A (n_74), .B (n_5), .Z (n_75));
  NAND3X1 g3957__2802(.A (n_52), .B (chip_t_hours[4]), .C (n_11), .Z
       (n_81));
  NOR2X1 g3965__1705(.A (chip_t_hours[3]), .B (n_52), .Z (n_70));
  AND2X1 g3966__5122(.A (n_47), .B (chip_t_hours[3]), .Z (n_69));
  AND2X1 g3967__8246(.A (n_54), .B (n_14), .Z (n_74));
  AND2X1 g3968__7098(.A (n_52), .B (chip_t_hours[3]), .Z (n_73));
  NOR2X1 g3969__6131(.A (chip_t_hours[3]), .B (n_47), .Z (n_72));
  AND2X1 g3970__1881(.A (n_53), .B (chip_t_minutes[3]), .Z (n_71));
  NAND3X1 g3971__5115(.A (n_22), .B (n_7), .C (n_14), .Z (n_65));
  OR2X1 g3972__7482(.A (n_16), .B (n_42), .Z (n_64));
  AND2X1 g3973__4733(.A (n_42), .B (n_16), .Z (n_63));
  NAND2X1 g3974__6161(.A (n_51), .B (chip_fsm_swFF_Q_9), .Z (n_62));
  NAND2X1 g3975__9315(.A (n_47), .B (n_50), .Z (n_61));
  OR2X1 g3976__9945(.A (n_15), .B (n_42), .Z (n_60));
  NOR2X1 g3977__2883(.A (chip_cd_count[4]), .B (n_40), .Z (n_59));
  NAND3X1 g3978__2346(.A (n_29), .B (chip_t_seconds[3]), .C
       (chip_t_seconds[5]), .Z (n_58));
  XOR2X1 g3979__1666(.A (chip_t_seconds[0]), .B (n_37), .Z (n_57));
  XOR2X1 g3980__7410(.A (chip_t_minutes[2]), .B (n_31), .Z (n_56));
  NOR2X1 g3981__6417(.A (chip_t_minutes[3]), .B (n_53), .Z (n_55));
  XOR2X1 g3982__5477(.A (n_7), .B (n_26), .Z (n_68));
  NOR2X1 g3983__2398(.A (n_49), .B (n_52), .Z (n_67));
  NAND3X1 g3984__5107(.A (n_29), .B (chip_t_seconds[2]), .C
       (chip_t_seconds[3]), .Z (n_66));
  NAND2X1 g3987__6260(.A (n_27), .B (chip_fsm_n_514), .Z (n_51));
  NAND2X1 g3988__4319(.A (n_33), .B (chip_t_hours[2]), .Z (n_50));
  NOR2X1 g3989__8428(.A (chip_t_hours[2]), .B (n_30), .Z (n_49));
  NOR2X1 g3990__5526(.A (n_9), .B (n_26), .Z (n_48));
  AND2X1 g3992__6783(.A (n_31), .B (n_7), .Z (n_54));
  NOR2X1 g3993__3680(.A (n_7), .B (n_26), .Z (n_53));
  AND2X1 g3994__1617(.A (n_30), .B (chip_t_hours[2]), .Z (n_52));
  INVX2 g3995(.A (n_46), .Z (n_45));
  INVX2 g3996(.A (n_44), .Z (n_43));
  AND2X1 g3997__2802(.A (n_23), .B (n_6), .Z (n_41));
  NAND2X1 g3998__1705(.A (n_24), .B (chip_cd_count[3]), .Z (n_40));
  NAND2X1 g4000__5122(.A (n_35), .B (n_8), .Z (n_47));
  NOR2X1 g4001__8246(.A (n_25), .B (n_31), .Z (n_46));
  AND2X1 g4002__7098(.A (n_37), .B (chip_t_seconds[0]), .Z (n_38));
  NOR2X1 g4003__6131(.A (n_30), .B (n_32), .Z (n_44));
  AND2X1 g4004__1881(.A (n_37), .B (n_29), .Z (n_42));
  AND2X1 g4005__5115(.A (n_28), .B (btn_inc_PAD), .Z (n_128));
  AND2X1 g4006__7482(.A (n_28), .B (btn_dec_PAD), .Z (n_117));
  OR2X1 g4007__4733(.A (btn_light_PAD), .B (chip_backlight_light_mode),
       .Z (n_36));
  NOR2X1 g4008__6161(.A (chip_t_hours[2]), .B (chip_t_hours[1]), .Z
       (n_35));
  NAND2X1 g4009__9315(.A (n_21), .B (chip_state[2]), .Z (n_34));
  NOR2X1 g4013__9945(.A (n_20), .B (chip_fsm_n_543), .Z (n_116));
  NOR2X1 g4014__2883(.A (n_12), .B (chip_fsm_n_543), .Z (n_127));
  NOR2X1 g4015__2346(.A (chip_clock_old_clk_1sec), .B (n_18), .Z
       (n_37));
  INVX2 g4016(.A (n_32), .Z (n_33));
  INVX2 g4017(.A (n_28), .Z (n_27));
  INVX2 g4018(.A (n_26), .Z (n_25));
  NOR2X1 g4019__1666(.A (chip_cd_count[2]), .B (chip_cd_count[1]), .Z
       (n_24));
  NOR2X1 g4020__7410(.A (chip_t_hours[5]), .B (chip_t_hours[3]), .Z
       (n_23));
  NOR2X1 g4021__6417(.A (chip_t_minutes[5]), .B (chip_t_minutes[4]), .Z
       (n_22));
  NOR2X1 g4022__5477(.A (chip_t_hours[1]), .B (chip_t_hours[0]), .Z
       (n_32));
  NOR2X1 g4023__2398(.A (chip_t_minutes[1]), .B (chip_t_minutes[0]), .Z
       (n_31));
  AND2X1 g4024__5107(.A (chip_t_hours[1]), .B (chip_t_hours[0]), .Z
       (n_30));
  AND2X1 g4025__6260(.A (chip_t_seconds[0]), .B (chip_t_seconds[1]), .Z
       (n_29));
  NOR2X1 g4026__4319(.A (chip_state[1]), .B (chip_fsm_n_522), .Z
       (n_28));
  NAND2X1 g4027__8428(.A (chip_t_minutes[1]), .B (chip_t_minutes[0]),
       .Z (n_26));
  INVX2 g4029(.A (btn_dec_PAD), .Z (n_20));
  INVX2 g4030(.A (chip_cd_count[6]), .Z (n_19));
  INVX2 g4034(.A (chip_clk_seconds), .Z (n_18));
  INVX2 g4036(.A (chip_t_seconds[4]), .Z (n_17));
  INVX2 g4037(.A (chip_t_seconds[3]), .Z (n_16));
  INVX2 g4038(.A (chip_t_seconds[2]), .Z (n_15));
  INVX2 g4039(.A (chip_t_minutes[3]), .Z (n_14));
  INVX2 g4042(.A (chip_t_hours[5]), .Z (n_11));
  INVX2 g4043(.A (chip_t_minutes[0]), .Z (n_10));
  INVX2 g4044(.A (chip_t_minutes[5]), .Z (n_9));
  INVX2 g4045(.A (chip_t_hours[0]), .Z (n_8));
  INVX2 g4046(.A (chip_t_minutes[2]), .Z (n_7));
  INVX2 g4047(.A (chip_t_hours[4]), .Z (n_6));
  INVX2 g4048(.A (chip_t_minutes[4]), .Z (n_5));
  INVX2 drc_bufs4055(.A (n_2), .Z (n_3));
  AND2X1 g4056__5526(.A (n_83), .B (n_81), .Z (n_1));
  AND2X1 g4057__6783(.A (n_99), .B (n_81), .Z (n_0));
  XOR2X1 chip_cd_inc_add_23_19_g393__3680(.A (chip_cd_count[23]), .B
       (chip_cd_inc_add_23_19_n_272), .Z (chip_cd_n_95));
  XOR2X1 chip_cd_inc_add_23_19_g394__1617(.A (chip_cd_count[19]), .B
       (chip_cd_inc_add_23_19_n_269), .Z (chip_cd_n_91));
  XOR2X1 chip_cd_inc_add_23_19_g395__2802(.A (chip_cd_count[18]), .B
       (chip_cd_inc_add_23_19_n_278), .Z (chip_cd_n_90));
  XOR2X1 chip_cd_inc_add_23_19_g396__1705(.A (chip_cd_count[22]), .B
       (chip_cd_inc_add_23_19_n_287), .Z (chip_cd_n_94));
  XOR2X1 chip_cd_inc_add_23_19_g397__5122(.A (chip_cd_count[21]), .B
       (chip_cd_inc_add_23_19_n_284), .Z (chip_cd_n_93));
  XOR2X1 chip_cd_inc_add_23_19_g398__8246(.A (chip_cd_count[25]), .B
       (chip_cd_inc_add_23_19_n_281), .Z (chip_cd_n_97));
  AND2X1 chip_cd_inc_add_23_19_g399__7098(.A
       (chip_cd_inc_add_23_19_n_278), .B (chip_cd_count[18]), .Z
       (chip_cd_inc_add_23_19_n_269));
  AND2X1 chip_cd_inc_add_23_19_g400__6131(.A
       (chip_cd_inc_add_23_19_n_287), .B (chip_cd_count[22]), .Z
       (chip_cd_inc_add_23_19_n_272));
  XOR2X1 chip_cd_inc_add_23_19_g401__1881(.A (chip_cd_count[20]), .B
       (chip_cd_inc_add_23_19_n_296), .Z (chip_cd_n_92));
  XOR2X1 chip_cd_inc_add_23_19_g402__5115(.A (chip_cd_count[24]), .B
       (chip_cd_inc_add_23_19_n_295), .Z (chip_cd_n_96));
  XOR2X1 chip_cd_inc_add_23_19_g403__7482(.A (chip_cd_count[17]), .B
       (chip_cd_inc_add_23_19_n_291), .Z (chip_cd_n_89));
  AND2X1 chip_cd_inc_add_23_19_g404__4733(.A
       (chip_cd_inc_add_23_19_n_291), .B (chip_cd_count[17]), .Z
       (chip_cd_inc_add_23_19_n_278));
  AND2X1 chip_cd_inc_add_23_19_g405__6161(.A
       (chip_cd_inc_add_23_19_n_295), .B (chip_cd_count[24]), .Z
       (chip_cd_inc_add_23_19_n_281));
  AND2X1 chip_cd_inc_add_23_19_g406__9315(.A
       (chip_cd_inc_add_23_19_n_296), .B (chip_cd_count[20]), .Z
       (chip_cd_inc_add_23_19_n_284));
  AND2X1 chip_cd_inc_add_23_19_g407__9945(.A
       (chip_cd_inc_add_23_19_n_296), .B (chip_cd_inc_add_23_19_n_370),
       .Z (chip_cd_inc_add_23_19_n_287));
  NOR2X1 chip_cd_inc_add_23_19_g408__2883(.A
       (chip_cd_inc_add_23_19_n_292), .B (chip_cd_inc_add_23_19_n_291),
       .Z (chip_cd_n_88));
  XOR2X1 chip_cd_inc_add_23_19_g409__2346(.A (chip_cd_count[15]), .B
       (chip_cd_inc_add_23_19_n_306), .Z (chip_cd_n_87));
  XOR2X1 chip_cd_inc_add_23_19_g410__1666(.A (chip_cd_count[11]), .B
       (chip_cd_inc_add_23_19_n_301), .Z (chip_cd_n_83));
  AND2X1 chip_cd_inc_add_23_19_g411__7410(.A
       (chip_cd_inc_add_23_19_n_304), .B (chip_cd_count[16]), .Z
       (chip_cd_inc_add_23_19_n_291));
  NOR2X1 chip_cd_inc_add_23_19_g412__6417(.A (chip_cd_count[16]), .B
       (chip_cd_inc_add_23_19_n_304), .Z (chip_cd_inc_add_23_19_n_292));
  NOR2X1 chip_cd_inc_add_23_19_g413__5477(.A
       (chip_cd_inc_add_23_19_n_321), .B (chip_cd_inc_add_23_19_n_305),
       .Z (chip_cd_inc_add_23_19_n_295));
  NOR2X1 chip_cd_inc_add_23_19_g414__2398(.A
       (chip_cd_inc_add_23_19_n_349), .B (chip_cd_inc_add_23_19_n_305),
       .Z (chip_cd_inc_add_23_19_n_296));
  XOR2X1 chip_cd_inc_add_23_19_g415__5107(.A (chip_cd_count[14]), .B
       (chip_cd_inc_add_23_19_n_315), .Z (chip_cd_n_86));
  XOR2X1 chip_cd_inc_add_23_19_g416__6260(.A (chip_cd_count[10]), .B
       (chip_cd_inc_add_23_19_n_311), .Z (chip_cd_n_82));
  XOR2X1 chip_cd_inc_add_23_19_g417__4319(.A (chip_cd_count[13]), .B
       (chip_cd_inc_add_23_19_n_317), .Z (chip_cd_n_85));
  AND2X1 chip_cd_inc_add_23_19_g418__8428(.A
       (chip_cd_inc_add_23_19_n_311), .B (chip_cd_count[10]), .Z
       (chip_cd_inc_add_23_19_n_301));
  INVX2 chip_cd_inc_add_23_19_g419(.A (chip_cd_inc_add_23_19_n_304), .Z
       (chip_cd_inc_add_23_19_n_305));
  NOR2X1 chip_cd_inc_add_23_19_g420__5526(.A
       (chip_cd_inc_add_23_19_n_341), .B (chip_cd_inc_add_23_19_n_319),
       .Z (chip_cd_inc_add_23_19_n_304));
  AND2X1 chip_cd_inc_add_23_19_g421__6783(.A
       (chip_cd_inc_add_23_19_n_315), .B (chip_cd_count[14]), .Z
       (chip_cd_inc_add_23_19_n_306));
  XOR2X1 chip_cd_inc_add_23_19_g422__3680(.A (chip_cd_count[12]), .B
       (chip_cd_inc_add_23_19_n_325), .Z (chip_cd_n_84));
  NOR2X1 chip_cd_inc_add_23_19_g423__1617(.A
       (chip_cd_inc_add_23_19_n_312), .B (chip_cd_inc_add_23_19_n_311),
       .Z (chip_cd_n_81));
  AND2X1 chip_cd_inc_add_23_19_g424__2802(.A
       (chip_cd_inc_add_23_19_n_327), .B (chip_cd_count[9]), .Z
       (chip_cd_inc_add_23_19_n_311));
  NOR2X1 chip_cd_inc_add_23_19_g425__1705(.A (chip_cd_count[9]), .B
       (chip_cd_inc_add_23_19_n_327), .Z (chip_cd_inc_add_23_19_n_312));
  AND2X1 chip_cd_inc_add_23_19_g426__5122(.A
       (chip_cd_inc_add_23_19_n_325), .B (chip_cd_inc_add_23_19_n_367),
       .Z (chip_cd_inc_add_23_19_n_315));
  AND2X1 chip_cd_inc_add_23_19_g427__8246(.A
       (chip_cd_inc_add_23_19_n_325), .B (chip_cd_count[12]), .Z
       (chip_cd_inc_add_23_19_n_317));
  NAND3X1 chip_cd_inc_add_23_19_g428__7098(.A
       (chip_cd_inc_add_23_19_n_336), .B (chip_cd_count[15]), .C
       (chip_cd_count[14]), .Z (chip_cd_inc_add_23_19_n_319));
  NAND3X1 chip_cd_inc_add_23_19_g429__6131(.A
       (chip_cd_inc_add_23_19_n_338), .B (chip_cd_count[23]), .C
       (chip_cd_count[22]), .Z (chip_cd_inc_add_23_19_n_321));
  NOR2X1 chip_cd_inc_add_23_19_g430__1881(.A
       (chip_cd_inc_add_23_19_n_328), .B (chip_cd_inc_add_23_19_n_327),
       .Z (chip_cd_n_80));
  XOR2X1 chip_cd_inc_add_23_19_g431__5115(.A (chip_cd_count[7]), .B
       (chip_cd_inc_add_23_19_n_333), .Z (chip_cd_n_79));
  NOR2X1 chip_cd_inc_add_23_19_g432__7482(.A
       (chip_cd_inc_add_23_19_n_350), .B (chip_cd_inc_add_23_19_n_341),
       .Z (chip_cd_inc_add_23_19_n_325));
  AND2X1 chip_cd_inc_add_23_19_g433__4733(.A
       (chip_cd_inc_add_23_19_n_340), .B (chip_cd_count[8]), .Z
       (chip_cd_inc_add_23_19_n_327));
  NOR2X1 chip_cd_inc_add_23_19_g434__6161(.A (chip_cd_count[8]), .B
       (chip_cd_inc_add_23_19_n_340), .Z (chip_cd_inc_add_23_19_n_328));
  XOR2X1 chip_cd_inc_add_23_19_g435__9315(.A (chip_cd_count[6]), .B
       (chip_cd_inc_add_23_19_n_351), .Z (chip_cd_n_78));
  XOR2X1 chip_cd_inc_add_23_19_g436__9945(.A (chip_cd_count[5]), .B
       (chip_cd_inc_add_23_19_n_345), .Z (chip_cd_n_77));
  AND2X1 chip_cd_inc_add_23_19_g437__2883(.A
       (chip_cd_inc_add_23_19_n_351), .B (chip_cd_count[6]), .Z
       (chip_cd_inc_add_23_19_n_333));
  NOR2X1 chip_cd_inc_add_23_19_g438__2346(.A
       (chip_cd_inc_add_23_19_n_368), .B (chip_cd_inc_add_23_19_n_350),
       .Z (chip_cd_inc_add_23_19_n_336));
  NOR2X1 chip_cd_inc_add_23_19_g439__1666(.A
       (chip_cd_inc_add_23_19_n_371), .B (chip_cd_inc_add_23_19_n_349),
       .Z (chip_cd_inc_add_23_19_n_338));
  INVX2 chip_cd_inc_add_23_19_g440(.A (chip_cd_inc_add_23_19_n_340), .Z
       (chip_cd_inc_add_23_19_n_341));
  NOR2X1 chip_cd_inc_add_23_19_g441__7410(.A
       (chip_cd_inc_add_23_19_n_359), .B (chip_cd_inc_add_23_19_n_352),
       .Z (chip_cd_inc_add_23_19_n_340));
  NOR2X1 chip_cd_inc_add_23_19_g442__6417(.A
       (chip_cd_inc_add_23_19_n_347), .B (chip_cd_inc_add_23_19_n_345),
       .Z (chip_cd_n_76));
  XOR2X1 chip_cd_inc_add_23_19_g443__5477(.A (chip_cd_count[3]), .B
       (chip_cd_inc_add_23_19_n_355), .Z (chip_cd_n_75));
  NOR2X1 chip_cd_inc_add_23_19_g444__2398(.A
       (chip_cd_inc_add_23_19_n_397), .B (chip_cd_inc_add_23_19_n_359),
       .Z (chip_cd_inc_add_23_19_n_345));
  AND2X1 chip_cd_inc_add_23_19_g445__5107(.A
       (chip_cd_inc_add_23_19_n_359), .B (chip_cd_inc_add_23_19_n_397),
       .Z (chip_cd_inc_add_23_19_n_347));
  NAND3X1 chip_cd_inc_add_23_19_g446__6260(.A
       (chip_cd_inc_add_23_19_n_362), .B (chip_cd_count[16]), .C
       (chip_cd_count[17]), .Z (chip_cd_inc_add_23_19_n_349));
  NAND3X1 chip_cd_inc_add_23_19_g447__4319(.A
       (chip_cd_inc_add_23_19_n_373), .B (chip_cd_count[8]), .C
       (chip_cd_count[9]), .Z (chip_cd_inc_add_23_19_n_350));
  NOR2X1 chip_cd_inc_add_23_19_g448__8428(.A
       (chip_cd_inc_add_23_19_n_365), .B (chip_cd_inc_add_23_19_n_359),
       .Z (chip_cd_inc_add_23_19_n_351));
  NAND3X1 chip_cd_inc_add_23_19_g449__5526(.A
       (chip_cd_inc_add_23_19_n_364), .B (chip_cd_count[7]), .C
       (chip_cd_count[6]), .Z (chip_cd_inc_add_23_19_n_352));
  XOR2X1 chip_cd_inc_add_23_19_g450__6783(.A (chip_cd_count[2]), .B
       (chip_cd_inc_add_23_19_n_361), .Z (chip_cd_n_74));
  AND2X1 chip_cd_inc_add_23_19_g451__3680(.A
       (chip_cd_inc_add_23_19_n_361), .B (chip_cd_count[2]), .Z
       (chip_cd_inc_add_23_19_n_355));
  NOR2X1 chip_cd_inc_add_23_19_g452__1617(.A
       (chip_cd_inc_add_23_19_n_375), .B (chip_cd_inc_add_23_19_n_361),
       .Z (chip_cd_n_73));
  NAND3X1 chip_cd_inc_add_23_19_g453__2802(.A
       (chip_cd_inc_add_23_19_n_361), .B (chip_cd_count[2]), .C
       (chip_cd_count[3]), .Z (chip_cd_inc_add_23_19_n_359));
  AND2X1 chip_cd_inc_add_23_19_g454__1705(.A (chip_cd_count[0]), .B
       (chip_cd_count[1]), .Z (chip_cd_inc_add_23_19_n_361));
  AND2X1 chip_cd_inc_add_23_19_g455__5122(.A (chip_cd_count[18]), .B
       (chip_cd_count[19]), .Z (chip_cd_inc_add_23_19_n_362));
  INVX2 chip_cd_inc_add_23_19_g456(.A (chip_cd_inc_add_23_19_n_365), .Z
       (chip_cd_inc_add_23_19_n_364));
  NAND2X1 chip_cd_inc_add_23_19_g457__8246(.A (chip_cd_count[4]), .B
       (chip_cd_count[5]), .Z (chip_cd_inc_add_23_19_n_365));
  INVX2 chip_cd_inc_add_23_19_g458(.A (chip_cd_inc_add_23_19_n_368), .Z
       (chip_cd_inc_add_23_19_n_367));
  NAND2X1 chip_cd_inc_add_23_19_g459__7098(.A (chip_cd_count[12]), .B
       (chip_cd_count[13]), .Z (chip_cd_inc_add_23_19_n_368));
  INVX2 chip_cd_inc_add_23_19_g460(.A (chip_cd_inc_add_23_19_n_371), .Z
       (chip_cd_inc_add_23_19_n_370));
  NAND2X1 chip_cd_inc_add_23_19_g461__6131(.A (chip_cd_count[20]), .B
       (chip_cd_count[21]), .Z (chip_cd_inc_add_23_19_n_371));
  AND2X1 chip_cd_inc_add_23_19_g462__1881(.A (chip_cd_count[10]), .B
       (chip_cd_count[11]), .Z (chip_cd_inc_add_23_19_n_373));
  NOR2X1 chip_cd_inc_add_23_19_g463__5115(.A (chip_cd_count[1]), .B
       (chip_cd_count[0]), .Z (chip_cd_inc_add_23_19_n_375));
  INVX2 chip_cd_inc_add_23_19_g464(.A (chip_cd_count[4]), .Z
       (chip_cd_inc_add_23_19_n_397));
endmodule

