$ Spice netlist generated by v2lvs
$ v2021.2_37.20    Tue Jun 1 14:42:15 PDT 2021
*.BUSDELIMITER [ 

.SUBCKT soc_top VDD VSS clk reset btn_mode btn_set btn_inc btn_dec btn_light 
+ h1_6 h1_5 h1_4 h1_3 h1_2 h1_1 h1_0 h0_6 h0_5 h0_4 h0_3 h0_2 h0_1 h0_0 m1_6 
+ m1_5 m1_4 m1_3 m1_2 m1_1 m1_0 m0_6 m0_5 m0_4 m0_3 m0_2 m0_1 m0_0 s1_6 s1_5 
+ s1_4 s1_3 s1_2 s1_1 s1_0 s0_6 s0_5 s0_4 s0_3 s0_2 s0_1 s0_0 colon light 
Xcorner0 pad_corner $PINS VSS=VSS VDD=VDD 
Xcorner1 pad_corner $PINS VSS=VSS VDD=VDD 
Xcorner2 pad_corner $PINS VSS=VSS VDD=VDD 
Xcorner3 pad_corner $PINS VSS=VSS VDD=VDD 
Xvdd0 pad_vdd $PINS VSS=VSS VDD=VDD 
Xvss0 pad_gnd $PINS VSS=VSS VDD=VDD 
Xbtn_dec_pad pad_in $PINS DataIn=btn_dec_PAD pad=btn_dec VSS=VSS VDD=VDD 
Xbtn_inc_pad pad_in $PINS DataIn=btn_inc_PAD pad=btn_inc VSS=VSS VDD=VDD 
Xbtn_light_pad pad_in $PINS DataIn=btn_light_PAD pad=btn_light VSS=VSS VDD=VDD 
Xbtn_mode_pad pad_in $PINS DataIn=btn_mode_PAD pad=btn_mode VSS=VSS VDD=VDD 
Xbtn_set_pad pad_in $PINS DataIn=btn_set_PAD pad=btn_set VSS=VSS VDD=VDD 
Xclk_pad pad_in $PINS DataIn=clk_PAD pad=clk VSS=VSS VDD=VDD 
Xcolon_pad pad_out $PINS pad=colon DataOut=VSS VSS=VSS VDD=VDD 
Xh0_pad_0 pad_out $PINS pad=h0_0 DataOut=h0_PAD_0 VSS=VSS VDD=VDD 
Xh0_pad_1 pad_out $PINS pad=h0_1 DataOut=VSS VSS=VSS VDD=VDD 
Xh0_pad_2 pad_out $PINS pad=h0_2 DataOut=VSS VSS=VSS VDD=VDD 
Xh0_pad_3 pad_out $PINS pad=h0_3 DataOut=VSS VSS=VSS VDD=VDD 
Xh0_pad_4 pad_out $PINS pad=h0_4 DataOut=VSS VSS=VSS VDD=VDD 
Xh0_pad_5 pad_out $PINS pad=h0_5 DataOut=VSS VSS=VSS VDD=VDD 
Xh0_pad_6 pad_out $PINS pad=h0_6 DataOut=VSS VSS=VSS VDD=VDD 
Xh1_pad_0 pad_out $PINS pad=h1_0 DataOut=h0_PAD_0 VSS=VSS VDD=VDD 
Xh1_pad_1 pad_out $PINS pad=h1_1 DataOut=VSS VSS=VSS VDD=VDD 
Xh1_pad_2 pad_out $PINS pad=h1_2 DataOut=VSS VSS=VSS VDD=VDD 
Xh1_pad_3 pad_out $PINS pad=h1_3 DataOut=VSS VSS=VSS VDD=VDD 
Xh1_pad_4 pad_out $PINS pad=h1_4 DataOut=VSS VSS=VSS VDD=VDD 
Xh1_pad_5 pad_out $PINS pad=h1_5 DataOut=VSS VSS=VSS VDD=VDD 
Xh1_pad_6 pad_out $PINS pad=h1_6 DataOut=VSS VSS=VSS VDD=VDD 
Xlight_pad pad_out $PINS pad=light DataOut=n_162 VSS=VSS VDD=VDD 
Xm0_pad_0 pad_out $PINS pad=m0_0 DataOut=m0_PAD_0 VSS=VSS VDD=VDD 
Xm0_pad_1 pad_out $PINS pad=m0_1 DataOut=VSS VSS=VSS VDD=VDD 
Xm0_pad_2 pad_out $PINS pad=m0_2 DataOut=VSS VSS=VSS VDD=VDD 
Xm0_pad_3 pad_out $PINS pad=m0_3 DataOut=VSS VSS=VSS VDD=VDD 
Xm0_pad_4 pad_out $PINS pad=m0_4 DataOut=VSS VSS=VSS VDD=VDD 
Xm0_pad_5 pad_out $PINS pad=m0_5 DataOut=VSS VSS=VSS VDD=VDD 
Xm0_pad_6 pad_out $PINS pad=m0_6 DataOut=VSS VSS=VSS VDD=VDD 
Xm1_pad_0 pad_out $PINS pad=m1_0 DataOut=m0_PAD_0 VSS=VSS VDD=VDD 
Xm1_pad_1 pad_out $PINS pad=m1_1 DataOut=VSS VSS=VSS VDD=VDD 
Xm1_pad_2 pad_out $PINS pad=m1_2 DataOut=VSS VSS=VSS VDD=VDD 
Xm1_pad_3 pad_out $PINS pad=m1_3 DataOut=VSS VSS=VSS VDD=VDD 
Xm1_pad_4 pad_out $PINS pad=m1_4 DataOut=VSS VSS=VSS VDD=VDD 
Xm1_pad_5 pad_out $PINS pad=m1_5 DataOut=VSS VSS=VSS VDD=VDD 
Xm1_pad_6 pad_out $PINS pad=m1_6 DataOut=VSS VSS=VSS VDD=VDD 
Xreset_pad pad_in $PINS DataIn=reset_PAD pad=reset VSS=VSS VDD=VDD 
Xs0_pad_0 pad_out $PINS pad=s0_0 DataOut=s0_PAD_0 VSS=VSS VDD=VDD 
Xs0_pad_1 pad_out $PINS pad=s0_1 DataOut=VSS VSS=VSS VDD=VDD 
Xs0_pad_2 pad_out $PINS pad=s0_2 DataOut=VSS VSS=VSS VDD=VDD 
Xs0_pad_3 pad_out $PINS pad=s0_3 DataOut=VSS VSS=VSS VDD=VDD 
Xs0_pad_4 pad_out $PINS pad=s0_4 DataOut=VSS VSS=VSS VDD=VDD 
Xs0_pad_5 pad_out $PINS pad=s0_5 DataOut=VSS VSS=VSS VDD=VDD 
Xs0_pad_6 pad_out $PINS pad=s0_6 DataOut=VSS VSS=VSS VDD=VDD 
Xs1_pad_0 pad_out $PINS pad=s1_0 DataOut=s0_PAD_0 VSS=VSS VDD=VDD 
Xs1_pad_1 pad_out $PINS pad=s1_1 DataOut=VSS VSS=VSS VDD=VDD 
Xs1_pad_2 pad_out $PINS pad=s1_2 DataOut=VSS VSS=VSS VDD=VDD 
Xs1_pad_3 pad_out $PINS pad=s1_3 DataOut=VSS VSS=VSS VDD=VDD 
Xs1_pad_4 pad_out $PINS pad=s1_4 DataOut=VSS VSS=VSS VDD=VDD 
Xs1_pad_5 pad_out $PINS pad=s1_5 DataOut=VSS VSS=VSS VDD=VDD 
Xs1_pad_6 pad_out $PINS pad=s1_6 DataOut=VSS VSS=VSS VDD=VDD 
Xg1936 INVX2 $PINS Z=n_205 A=chip_fsm_n_496 VSS=VSS VDD=VDD 
Xchip_fsm_next_state_reg[1] DFFQX1 $PINS Q=chip_fsm_next_state[1] CLK=clk_PAD 
+ D=n_204 VSS=VSS VDD=VDD 
Xg2393__2398 NAND3X1 $PINS Z=n_204 A=n_203 B=n_185 C=n_170 VSS=VSS VDD=VDD 
Xg2394__5107 NOR2X1 $PINS Z=n_203 A=n_190 B=n_202 VSS=VSS VDD=VDD 
Xchip_fsm_next_state_reg[0] DFFQX1 $PINS Q=chip_fsm_next_state[0] CLK=clk_PAD 
+ D=n_201 VSS=VSS VDD=VDD 
Xg2396__6260 NAND3X1 $PINS Z=n_202 A=n_199 B=n_177 C=n_181 VSS=VSS VDD=VDD 
Xchip_fsm_next_state_reg[2] DFFQX1 $PINS Q=chip_fsm_next_state[2] CLK=clk_PAD 
+ D=n_200 VSS=VSS VDD=VDD 
Xg2398__4319 NAND3X1 $PINS Z=n_201 A=n_197 B=n_198 C=n_187 VSS=VSS VDD=VDD 
Xg2399__8428 NAND3X1 $PINS Z=n_200 A=n_184 B=n_193 C=n_179 VSS=VSS VDD=VDD 
Xg2400__5526 OR2X1 $PINS Z=n_199 A=btn_dec_PAD B=n_196 VSS=VSS VDD=VDD 
Xg2401__6783 NOR2X1 $PINS Z=n_198 A=n_194 B=n_191 VSS=VSS VDD=VDD 
Xg2402__3680 NOR2X1 $PINS Z=n_197 A=n_182 B=n_192 VSS=VSS VDD=VDD 
Xg2403__1617 AND2X1 $PINS Z=n_196 A=n_195 B=n_180 VSS=VSS VDD=VDD 
Xg2404__2802 NAND3X1 $PINS Z=n_195 A=n_169 B=chip_state[0] C=n_150 VSS=VSS 
+ VDD=VDD 
Xg2405__1705 NOR2X1 $PINS Z=n_194 A=chip_state[1] B=n_189 VSS=VSS VDD=VDD 
Xg2406__5122 AND2X1 $PINS Z=n_193 A=n_178 B=n_188 VSS=VSS VDD=VDD 
Xg2407__8246 NOR2X1 $PINS Z=n_192 A=btn_mode_PAD B=n_183 VSS=VSS VDD=VDD 
Xg2408__7098 NOR2X1 $PINS Z=n_191 A=chip_fsm_n_496 B=n_186 VSS=VSS VDD=VDD 
Xg2409__6131 NOR2X1 $PINS Z=n_190 A=chip_state[0] B=n_173 VSS=VSS VDD=VDD 
Xg2410__1881 NOR2X1 $PINS Z=n_189 A=n_171 B=n_172 VSS=VSS VDD=VDD 
Xg2411__5115 NAND3X1 $PINS Z=n_188 A=n_161 B=n_149 C=n_154 VSS=VSS VDD=VDD 
Xg2412__7482 NAND3X1 $PINS Z=n_187 A=n_166 B=chip_state[0] C=n_8 VSS=VSS 
+ VDD=VDD 
Xg2413__4733 NOR2X1 $PINS Z=n_186 A=n_168 B=n_176 VSS=VSS VDD=VDD 
Xg2414__6161 OR2X1 $PINS Z=n_185 A=chip_state[2] B=chip_fsm_n_490 VSS=VSS 
+ VDD=VDD 
Xg2415__9315 OR2X1 $PINS Z=n_184 A=n_166 B=chip_fsm_n_490 VSS=VSS VDD=VDD 
Xg2416__9945 NAND3X1 $PINS Z=n_183 A=n_158 B=chip_state[2] C=btn_set_PAD 
+ VSS=VSS VDD=VDD 
Xg2417__2883 AND2X1 $PINS Z=n_182 A=n_161 B=n_175 VSS=VSS VDD=VDD 
Xg2418__2346 NAND3X1 $PINS Z=n_181 A=n_160 B=n_156 C=n_8 VSS=VSS VDD=VDD 
Xg2419__1666 NAND2X1 $PINS Z=n_180 A=n_176 B=n_159 VSS=VSS VDD=VDD 
Xg2420__7410 NAND2X1 $PINS Z=n_179 A=n_174 B=chip_state[1] VSS=VSS VDD=VDD 
Xg2421__6417 NAND3X1 $PINS Z=n_178 A=n_158 B=chip_state[2] C=n_165 VSS=VSS 
+ VDD=VDD 
Xg2422__5477 NAND3X1 $PINS Z=n_177 A=n_158 B=n_150 C=n_151 VSS=VSS VDD=VDD 
Xg2423__2398 NAND2X1 $PINS Z=n_175 A=n_164 B=n_154 VSS=VSS VDD=VDD 
Xg2424__5107 NOR2X1 $PINS Z=n_174 A=n_157 B=chip_fsm_n_496 VSS=VSS VDD=VDD 
Xg2425__6260 NOR2X1 $PINS Z=n_176 A=btn_mode_PAD B=n_167 VSS=VSS VDD=VDD 
Xg2426__4319 NAND2X1 $PINS Z=chip_fsm_n_490 A=n_158 B=chip_fsm_swFF_Q_9 VSS=VSS 
+ VDD=VDD 
Xg2427 INVX2 $PINS Z=n_173 A=n_172 VSS=VSS VDD=VDD 
Xg2428__8428 NOR2X1 $PINS Z=n_171 A=chip_state[0] B=n_166 VSS=VSS VDD=VDD 
Xg2429__5526 NAND2X1 $PINS Z=n_170 A=n_161 B=btn_inc_PAD VSS=VSS VDD=VDD 
Xg2430__6783 NOR2X1 $PINS Z=n_169 A=btn_inc_PAD B=n_166 VSS=VSS VDD=VDD 
Xg2431__3680 NOR2X1 $PINS Z=n_168 A=n_155 B=n_167 VSS=VSS VDD=VDD 
Xg2432__1617 NOR2X1 $PINS Z=n_172 A=n_150 B=n_160 VSS=VSS VDD=VDD 
Xg2433__2802 NAND2X1 $PINS Z=n_165 A=n_150 B=btn_set_PAD VSS=VSS VDD=VDD 
Xg2434__1705 NAND2X1 $PINS Z=n_164 A=n_150 B=btn_dec_PAD VSS=VSS VDD=VDD 
Xchip_backlight_light_reg DFFQSRX1 $PINS Q=n_162 CLK=clk_PAD 
+ D=chip_backlight_light_mode RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xg2438__5122 NAND2X1 $PINS Z=n_167 A=chip_state[1] B=n_154 VSS=VSS VDD=VDD 
Xg2439__8246 OR2X1 $PINS Z=n_166 A=n_151 B=chip_state[2] VSS=VSS VDD=VDD 
Xg2440 INVX2 $PINS Z=n_160 A=n_159 VSS=VSS VDD=VDD 
Xg2441__7098 NOR2X1 $PINS Z=n_157 A=btn_inc_PAD B=btn_dec_PAD VSS=VSS VDD=VDD 
Xg2442__6131 NAND2X1 $PINS Z=n_156 A=n_149 B=n_150 VSS=VSS VDD=VDD 
Xg2443__1881 OR2X1 $PINS Z=chip_fsm_n_496 A=chip_state[2] B=n_149 VSS=VSS 
+ VDD=VDD 
Xg2444__5115 AND2X1 $PINS Z=n_161 A=n_8 B=chip_state[2] VSS=VSS VDD=VDD 
Xg2445__7482 NOR2X1 $PINS Z=n_159 A=btn_set_PAD B=chip_state[2] VSS=VSS VDD=VDD 
Xg2446__4733 NOR2X1 $PINS Z=n_158 A=n_8 B=chip_state[0] VSS=VSS VDD=VDD 
Xg2447 INVX2 $PINS Z=n_155 A=btn_dec_PAD VSS=VSS VDD=VDD 
Xg2448 INVX2 $PINS Z=n_154 A=btn_inc_PAD VSS=VSS VDD=VDD 
Xg2449 INVX2 $PINS Z=n_8 A=chip_state[1] VSS=VSS VDD=VDD 
Xg2451 INVX2 $PINS Z=n_151 A=btn_set_PAD VSS=VSS VDD=VDD 
Xg2452 INVX2 $PINS Z=n_150 A=btn_mode_PAD VSS=VSS VDD=VDD 
Xg2453 INVX2 $PINS Z=n_149 A=chip_state[0] VSS=VSS VDD=VDD 
Xchip_backlight_current_count_reg[0] DFFQX1 $PINS 
+ Q=chip_backlight_current_count[0] CLK=n_10 D=n_7 VSS=VSS VDD=VDD 
Xchip_backlight_current_count_reg[1] DFFQX1 $PINS 
+ Q=chip_backlight_current_count[1] CLK=n_10 D=n_33 VSS=VSS VDD=VDD 
Xchip_backlight_current_count_reg[2] DFFQX1 $PINS 
+ Q=chip_backlight_current_count[2] CLK=n_10 D=n_39 VSS=VSS VDD=VDD 
Xchip_backlight_light_mode_reg DFFQX1 $PINS Q=chip_backlight_light_mode 
+ CLK=n_10 D=n_36 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_clk_seconds_reg DFFQSRX1 $PINS 
+ Q=chip_backlight_light_clk CLK=clk_PAD D=n_144 RESETB=VDD SETB=n_9 VSS=VSS 
+ VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[0] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[0] CLK=clk_PAD D=n_93 RESETB=VDD SETB=n_9 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[1] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[1] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_73 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[2] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[2] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_74 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[3] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[3] CLK=clk_PAD D=n_119 RESETB=VDD SETB=n_9 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[4] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[4] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_76 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[5] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[5] CLK=clk_PAD D=n_104 RESETB=VDD SETB=n_9 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[6] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[6] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_78 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[7] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[7] CLK=clk_PAD D=n_115 RESETB=VDD SETB=n_9 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[8] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[8] CLK=clk_PAD D=n_114 RESETB=VDD SETB=n_9 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[9] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[9] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_81 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[10] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[10] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_82 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[11] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[11] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_83 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[12] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[12] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_84 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[13] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[13] CLK=clk_PAD D=n_109 RESETB=VDD SETB=n_9 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[14] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[14] CLK=clk_PAD D=n_108 RESETB=VDD SETB=n_9 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[15] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[15] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_87 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[16] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[16] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_88 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[17] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[17] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_89 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[18] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[18] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_90 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[19] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[19] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_91 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[20] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[20] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_92 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[21] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[21] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_93 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[22] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[22] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_94 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[23] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[23] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_95 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[24] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[24] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_96 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_count_reg[25] DFFQSRX1 $PINS 
+ Q=chip_backlight_seconds_clk_count[25] CLK=clk_PAD 
+ D=chip_backlight_seconds_clk_n_97 RESETB=VDD SETB=n_9 VSS=VSS VDD=VDD 
Xchip_backlight_start_counter_reg DFFQSRX1 $PINS Q=chip_backlight_start_counter 
+ CLK=clk_PAD D=btn_light_PAD RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_clk_seconds_reg DFFQSRX1 $PINS Q=chip_clk_seconds CLK=clk_PAD D=n_145 
+ RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[0] DFFQSRX1 $PINS Q=chip_cd_count[0] CLK=clk_PAD D=n_92 
+ RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[1] DFFQSRX1 $PINS Q=chip_cd_count[1] CLK=clk_PAD 
+ D=chip_cd_n_73 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[2] DFFQSRX1 $PINS Q=chip_cd_count[2] CLK=clk_PAD 
+ D=chip_cd_n_74 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[3] DFFQSRX1 $PINS Q=chip_cd_count[3] CLK=clk_PAD D=n_94 
+ RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[4] DFFQSRX1 $PINS Q=chip_cd_count[4] CLK=clk_PAD 
+ D=chip_cd_n_76 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[5] DFFQSRX1 $PINS Q=chip_cd_count[5] CLK=clk_PAD D=n_141 
+ RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[6] DFFQSRX1 $PINS Q=chip_cd_count[6] CLK=clk_PAD 
+ D=chip_cd_n_78 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[7] DFFQSRX1 $PINS Q=chip_cd_count[7] CLK=clk_PAD D=n_140 
+ RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[8] DFFQSRX1 $PINS Q=chip_cd_count[8] CLK=clk_PAD D=n_139 
+ RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[9] DFFQSRX1 $PINS Q=chip_cd_count[9] CLK=clk_PAD 
+ D=chip_cd_n_81 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[10] DFFQSRX1 $PINS Q=chip_cd_count[10] CLK=clk_PAD 
+ D=chip_cd_n_82 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[11] DFFQSRX1 $PINS Q=chip_cd_count[11] CLK=clk_PAD 
+ D=chip_cd_n_83 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[12] DFFQSRX1 $PINS Q=chip_cd_count[12] CLK=clk_PAD 
+ D=chip_cd_n_84 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[13] DFFQSRX1 $PINS Q=chip_cd_count[13] CLK=clk_PAD D=n_134 
+ RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[14] DFFQSRX1 $PINS Q=chip_cd_count[14] CLK=clk_PAD D=n_133 
+ RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[15] DFFQSRX1 $PINS Q=chip_cd_count[15] CLK=clk_PAD 
+ D=chip_cd_n_87 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[16] DFFQSRX1 $PINS Q=chip_cd_count[16] CLK=clk_PAD 
+ D=chip_cd_n_88 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[17] DFFQSRX1 $PINS Q=chip_cd_count[17] CLK=clk_PAD 
+ D=chip_cd_n_89 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[18] DFFQSRX1 $PINS Q=chip_cd_count[18] CLK=clk_PAD 
+ D=chip_cd_n_90 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[19] DFFQSRX1 $PINS Q=chip_cd_count[19] CLK=clk_PAD 
+ D=chip_cd_n_91 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[20] DFFQSRX1 $PINS Q=chip_cd_count[20] CLK=clk_PAD 
+ D=chip_cd_n_92 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[21] DFFQSRX1 $PINS Q=chip_cd_count[21] CLK=clk_PAD 
+ D=chip_cd_n_93 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[22] DFFQSRX1 $PINS Q=chip_cd_count[22] CLK=clk_PAD 
+ D=chip_cd_n_94 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[23] DFFQSRX1 $PINS Q=chip_cd_count[23] CLK=clk_PAD 
+ D=chip_cd_n_95 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[24] DFFQSRX1 $PINS Q=chip_cd_count[24] CLK=clk_PAD 
+ D=chip_cd_n_96 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_cd_count_reg[25] DFFQSRX1 $PINS Q=chip_cd_count[25] CLK=clk_PAD 
+ D=chip_cd_n_97 RESETB=VDD SETB=n_5 VSS=VSS VDD=VDD 
Xchip_displayer_display_h1_reg[0] DFFQX1 $PINS Q=h0_PAD_0 CLK=clk_PAD D=n_53 
+ VSS=VSS VDD=VDD 
Xchip_displayer_display_m1_reg[0] DFFQX1 $PINS Q=m0_PAD_0 CLK=clk_PAD D=n_55 
+ VSS=VSS VDD=VDD 
Xchip_displayer_display_s1_reg[0] DFFQX1 $PINS Q=s0_PAD_0 CLK=clk_PAD D=n_54 
+ VSS=VSS VDD=VDD 
Xchip_displayer_enable_7seg_reg DFFQSRX1 $PINS Q=chip_displayer_enable_7seg 
+ CLK=clk_PAD D=n_40 RESETB=n_5 SETB=VDD VSS=VSS VDD=VDD 
Xchip_displayer_last_seconds_clk_reg DFFQX1 $PINS 
+ Q=chip_displayer_last_seconds_clk CLK=clk_PAD D=n_51 VSS=VSS VDD=VDD 
Xchip_fsm_state_reg[0] DFFQX1 $PINS Q=chip_state[0] CLK=clk_PAD D=n_28 VSS=VSS 
+ VDD=VDD 
Xchip_fsm_state_reg[1] DFFQX1 $PINS Q=chip_state[1] CLK=clk_PAD D=n_27 VSS=VSS 
+ VDD=VDD 
Xchip_fsm_state_reg[2] DFFQX1 $PINS Q=chip_state[2] CLK=clk_PAD D=n_17 VSS=VSS 
+ VDD=VDD 
Xchip_fsm_swFF_Q_reg DFFQX1 $PINS Q=chip_fsm_swFF_Q_9 CLK=clk_PAD D=n_41 
+ VSS=VSS VDD=VDD 
Xg4037__6161 XOR2X1 $PINS Z=n_145 A=chip_clk_seconds B=n_2 VSS=VSS VDD=VDD 
Xg4038__9315 XOR2X1 $PINS Z=n_144 A=chip_backlight_light_clk B=n_3 VSS=VSS 
+ VDD=VDD 
Xg4066__9945 AND2X1 $PINS Z=n_141 A=n_0 B=chip_cd_n_77 VSS=VSS VDD=VDD 
Xg4067__2883 AND2X1 $PINS Z=n_140 A=n_0 B=chip_cd_n_79 VSS=VSS VDD=VDD 
Xg4068__2346 AND2X1 $PINS Z=n_139 A=n_0 B=chip_cd_n_80 VSS=VSS VDD=VDD 
Xg4073__1666 AND2X1 $PINS Z=n_134 A=n_0 B=chip_cd_n_85 VSS=VSS VDD=VDD 
Xg4074__7410 AND2X1 $PINS Z=n_133 A=n_0 B=chip_cd_n_86 VSS=VSS VDD=VDD 
Xg4088__6417 AND2X1 $PINS Z=n_119 A=n_1 B=chip_backlight_seconds_clk_n_75 
+ VSS=VSS VDD=VDD 
Xg4092__5477 AND2X1 $PINS Z=n_115 A=n_1 B=chip_backlight_seconds_clk_n_79 
+ VSS=VSS VDD=VDD 
Xg4093__2398 AND2X1 $PINS Z=n_114 A=n_1 B=chip_backlight_seconds_clk_n_80 
+ VSS=VSS VDD=VDD 
Xg4098__5107 AND2X1 $PINS Z=n_109 A=n_1 B=chip_backlight_seconds_clk_n_85 
+ VSS=VSS VDD=VDD 
Xg4099__6260 AND2X1 $PINS Z=n_108 A=n_1 B=chip_backlight_seconds_clk_n_86 
+ VSS=VSS VDD=VDD 
Xg4103__4319 AND2X1 $PINS Z=n_104 A=n_1 B=chip_backlight_seconds_clk_n_77 
+ VSS=VSS VDD=VDD 
Xg4113__8428 AND2X1 $PINS Z=n_94 A=n_0 B=chip_cd_n_75 VSS=VSS VDD=VDD 
Xg4114__5526 NOR2X1 $PINS Z=n_93 A=chip_backlight_seconds_clk_count[0] B=n_3 
+ VSS=VSS VDD=VDD 
Xg4115__6783 NOR2X1 $PINS Z=n_92 A=chip_cd_count[0] B=n_2 VSS=VSS VDD=VDD 
Xg4117__3680 OR2X1 $PINS Z=n_1 A=chip_backlight_seconds_clk_count[0] B=n_283 
+ VSS=VSS VDD=VDD 
Xg4119__1617 OR2X1 $PINS Z=n_0 A=chip_cd_count[0] B=n_88 VSS=VSS VDD=VDD 
Xg4121__1705 OR2X1 $PINS Z=n_88 A=chip_cd_count[15] B=n_87 VSS=VSS VDD=VDD 
Xg4122__5122 NAND3X1 $PINS Z=n_87 A=n_85 B=chip_cd_count[14] 
+ C=chip_cd_count[13] VSS=VSS VDD=VDD 
Xg4124__7098 NOR2X1 $PINS Z=n_85 A=chip_cd_count[22] B=n_83 VSS=VSS VDD=VDD 
Xg4125__6131 NOR2X1 $PINS Z=n_84 A=chip_backlight_seconds_clk_count[6] B=n_82 
+ VSS=VSS VDD=VDD 
Xg4126__1881 OR2X1 $PINS Z=n_83 A=chip_cd_count[23] B=n_81 VSS=VSS VDD=VDD 
Xg4127__5115 NAND2X1 $PINS Z=n_82 A=n_80 B=chip_backlight_seconds_clk_count[5] 
+ VSS=VSS VDD=VDD 
Xg4128__7482 OR2X1 $PINS Z=n_81 A=chip_cd_count[21] B=n_79 VSS=VSS VDD=VDD 
Xg4129__4733 NOR2X1 $PINS Z=n_80 A=chip_backlight_seconds_clk_count[4] B=n_78 
+ VSS=VSS VDD=VDD 
Xg4130__6161 OR2X1 $PINS Z=n_79 A=chip_cd_count[20] B=n_77 VSS=VSS VDD=VDD 
Xg4131__9315 NAND3X1 $PINS Z=n_78 A=n_76 B=n_14 
+ C=chip_backlight_seconds_clk_count[3] VSS=VSS VDD=VDD 
Xg4132__9945 OR2X1 $PINS Z=n_77 A=chip_cd_count[18] B=n_75 VSS=VSS VDD=VDD 
Xg4133__2883 NOR2X1 $PINS Z=n_76 A=chip_backlight_seconds_clk_count[1] B=n_74 
+ VSS=VSS VDD=VDD 
Xg4134__2346 OR2X1 $PINS Z=n_75 A=chip_cd_count[19] B=n_73 VSS=VSS VDD=VDD 
Xg4135__1666 OR2X1 $PINS Z=n_74 A=chip_backlight_seconds_clk_count[21] B=n_72 
+ VSS=VSS VDD=VDD 
Xg4136__7410 OR2X1 $PINS Z=n_73 A=chip_cd_count[17] B=n_71 VSS=VSS VDD=VDD 
Xg4137__6417 OR2X1 $PINS Z=n_72 A=chip_backlight_seconds_clk_count[20] B=n_69 
+ VSS=VSS VDD=VDD 
Xg4138__5477 OR2X1 $PINS Z=n_71 A=chip_cd_count[16] B=n_70 VSS=VSS VDD=VDD 
Xg4139__2398 OR2X1 $PINS Z=n_70 A=chip_cd_count[12] B=n_67 VSS=VSS VDD=VDD 
Xg4140__5107 OR2X1 $PINS Z=n_69 A=chip_backlight_seconds_clk_count[19] B=n_68 
+ VSS=VSS VDD=VDD 
Xg4141__6260 OR2X1 $PINS Z=n_68 A=chip_backlight_seconds_clk_count[18] B=n_65 
+ VSS=VSS VDD=VDD 
Xg4142__4319 OR2X1 $PINS Z=n_67 A=chip_cd_count[25] B=n_66 VSS=VSS VDD=VDD 
Xg4143__8428 OR2X1 $PINS Z=n_66 A=chip_cd_count[24] B=n_63 VSS=VSS VDD=VDD 
Xg4144__5526 OR2X1 $PINS Z=n_65 A=chip_backlight_seconds_clk_count[17] B=n_64 
+ VSS=VSS VDD=VDD 
Xg4145__6783 OR2X1 $PINS Z=n_64 A=chip_backlight_seconds_clk_count[16] B=n_62 
+ VSS=VSS VDD=VDD 
Xg4146__3680 OR2X1 $PINS Z=n_63 A=chip_cd_count[11] B=n_61 VSS=VSS VDD=VDD 
Xg4147__1617 OR2X1 $PINS Z=n_62 A=chip_backlight_seconds_clk_count[23] B=n_60 
+ VSS=VSS VDD=VDD 
Xg4148__2802 OR2X1 $PINS Z=n_61 A=chip_cd_count[10] B=n_59 VSS=VSS VDD=VDD 
Xg4149__1705 OR2X1 $PINS Z=n_60 A=chip_backlight_seconds_clk_count[22] B=n_58 
+ VSS=VSS VDD=VDD 
Xg4150__5122 OR2X1 $PINS Z=n_59 A=chip_cd_count[9] B=n_57 VSS=VSS VDD=VDD 
Xg4151__8246 OR2X1 $PINS Z=n_58 A=chip_backlight_seconds_clk_count[15] B=n_56 
+ VSS=VSS VDD=VDD 
Xg4152__7098 NAND3X1 $PINS Z=n_57 A=n_52 B=chip_cd_count[8] C=chip_cd_count[7] 
+ VSS=VSS VDD=VDD 
Xg4155__6131 NAND3X1 $PINS Z=n_56 A=n_48 B=chip_backlight_seconds_clk_count[14] 
+ C=chip_backlight_seconds_clk_count[13] VSS=VSS VDD=VDD 
Xg4158__1881 OR2X1 $PINS Z=n_55 A=n_22 B=n_50 VSS=VSS VDD=VDD 
Xg4159__5115 OR2X1 $PINS Z=n_54 A=n_21 B=n_47 VSS=VSS VDD=VDD 
Xg4160__7482 NAND3X1 $PINS Z=n_53 A=n_43 B=n_20 C=n_16 VSS=VSS VDD=VDD 
Xg4161__4733 NOR2X1 $PINS Z=n_52 A=chip_cd_count[6] B=n_285 VSS=VSS VDD=VDD 
Xg4162__6161 MUX2X1 $PINS Z=n_51 A=chip_clk_seconds 
+ B=chip_displayer_last_seconds_clk S=reset_PAD VSS=VSS VDD=VDD 
Xg4166__9315 NAND3X1 $PINS Z=n_50 A=n_43 B=n_38 C=n_18 VSS=VSS VDD=VDD 
Xg4168__2883 NOR2X1 $PINS Z=n_48 A=chip_backlight_seconds_clk_count[12] B=n_45 
+ VSS=VSS VDD=VDD 
Xg4169__2346 OR2X1 $PINS Z=n_47 A=n_22 B=n_46 VSS=VSS VDD=VDD 
Xg4170__1666 MUX2X1 $PINS Z=n_46 A=s0_PAD_0 B=n_29 S=n_5 VSS=VSS VDD=VDD 
Xg4172__7410 OR2X1 $PINS Z=n_45 A=chip_backlight_seconds_clk_count[11] B=n_34 
+ VSS=VSS VDD=VDD 
Xg4176__5477 NAND3X1 $PINS Z=n_41 A=chip_fsm_n_490 B=n_32 C=n_26 VSS=VSS 
+ VDD=VDD 
Xg4177__2398 XOR2X1 $PINS Z=n_40 A=chip_displayer_enable_7seg B=n_25 VSS=VSS 
+ VDD=VDD 
Xg4178__5107 XOR2X1 $PINS Z=n_39 A=chip_backlight_current_count[2] B=n_24 
+ VSS=VSS VDD=VDD 
Xg4179__6260 AND2X1 $PINS Z=n_43 A=n_30 B=n_37 VSS=VSS VDD=VDD 
Xg4180__4319 NAND2X1 $PINS Z=n_38 A=n_21 B=chip_state[2] VSS=VSS VDD=VDD 
Xg4181__8428 NAND2X1 $PINS Z=n_37 A=n_22 B=chip_state[2] VSS=VSS VDD=VDD 
Xg4182__5526 OR2X1 $PINS Z=n_36 A=chip_backlight_current_count[2] B=n_23 
+ VSS=VSS VDD=VDD 
Xg4187__3680 NAND3X1 $PINS Z=n_34 A=n_12 B=n_15 
+ C=chip_backlight_seconds_clk_count[8] VSS=VSS VDD=VDD 
Xg4188__1617 XOR2X1 $PINS Z=n_33 A=chip_backlight_current_count[0] 
+ B=chip_backlight_current_count[1] VSS=VSS VDD=VDD 
Xg4189__2802 NAND3X1 $PINS Z=n_32 A=n_205 B=n_8 C=chip_fsm_swFF_Q_9 VSS=VSS 
+ VDD=VDD 
Xg4191__1705 NAND2X1 $PINS Z=n_30 A=n_29 B=n_5 VSS=VSS VDD=VDD 
Xg4192__5122 AND2X1 $PINS Z=n_28 A=n_5 B=chip_fsm_next_state[0] VSS=VSS VDD=VDD 
Xg4193__8246 AND2X1 $PINS Z=n_27 A=n_5 B=chip_fsm_next_state[1] VSS=VSS VDD=VDD 
Xg4194__7098 AND2X1 $PINS Z=n_29 A=chip_displayer_enable_7seg B=n_6 VSS=VSS 
+ VDD=VDD 
Xg4195__6131 OR2X1 $PINS Z=n_26 A=chip_state[0] B=n_6 VSS=VSS VDD=VDD 
Xg4196__1881 NOR2X1 $PINS Z=n_25 A=chip_displayer_last_seconds_clk B=n_11 
+ VSS=VSS VDD=VDD 
Xg4199 INVX2 $PINS Z=n_24 A=n_23 VSS=VSS VDD=VDD 
Xg4200 INVX2 $PINS Z=n_20 A=n_21 VSS=VSS VDD=VDD 
Xg4201__5115 NOR2X1 $PINS Z=n_19 A=chip_cd_count[2] B=chip_cd_count[1] VSS=VSS 
+ VDD=VDD 
Xg4202__7482 NAND2X1 $PINS Z=n_18 A=m0_PAD_0 B=reset_PAD VSS=VSS VDD=VDD 
Xg4203__4733 AND2X1 $PINS Z=n_17 A=n_5 B=chip_fsm_next_state[2] VSS=VSS VDD=VDD 
Xg4204__6161 NAND2X1 $PINS Z=n_16 A=h0_PAD_0 B=reset_PAD VSS=VSS VDD=VDD 
Xg4205__9315 NAND2X1 $PINS Z=n_23 A=chip_backlight_current_count[1] 
+ B=chip_backlight_current_count[0] VSS=VSS VDD=VDD 
Xg4206__9945 NOR2X1 $PINS Z=n_22 A=reset_PAD B=chip_state[1] VSS=VSS VDD=VDD 
Xg4207__2883 NOR2X1 $PINS Z=n_21 A=reset_PAD B=chip_state[0] VSS=VSS VDD=VDD 
Xg4208 INVX2 $PINS Z=n_15 A=chip_backlight_seconds_clk_count[10] VSS=VSS 
+ VDD=VDD 
Xg4209 INVX2 $PINS Z=n_14 A=chip_backlight_seconds_clk_count[2] VSS=VSS VDD=VDD 
Xg4211 INVX2 $PINS Z=n_12 A=chip_backlight_seconds_clk_count[9] VSS=VSS VDD=VDD 
Xg4216 INVX2 $PINS Z=n_11 A=chip_clk_seconds VSS=VSS VDD=VDD 
Xg4217 INVX2 $PINS Z=n_10 A=chip_backlight_light_clk VSS=VSS VDD=VDD 
Xg4218 INVX1 $PINS Z=n_9 A=chip_backlight_start_counter VSS=VSS VDD=VDD 
Xg4225 INVX2 $PINS Z=n_7 A=chip_backlight_current_count[0] VSS=VSS VDD=VDD 
Xg4226 INVX2 $PINS Z=n_6 A=chip_state[2] VSS=VSS VDD=VDD 
Xg4231 INVX2 $PINS Z=n_5 A=reset_PAD VSS=VSS VDD=VDD 
Xdrc_bufs4238 INVX2 $PINS Z=n_3 A=n_1 VSS=VSS VDD=VDD 
Xdrc_bufs4245 INVX2 $PINS Z=n_2 A=n_0 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g393__2346 XOR2X1 $PINS Z=chip_cd_n_95 
+ A=chip_cd_count[23] B=chip_cd_inc_add_23_19_n_272 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g394__1666 XOR2X1 $PINS Z=chip_cd_n_91 
+ A=chip_cd_count[19] B=chip_cd_inc_add_23_19_n_269 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g395__7410 XOR2X1 $PINS Z=chip_cd_n_90 
+ A=chip_cd_count[18] B=chip_cd_inc_add_23_19_n_278 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g396__6417 XOR2X1 $PINS Z=chip_cd_n_94 
+ A=chip_cd_count[22] B=chip_cd_inc_add_23_19_n_287 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g397__5477 XOR2X1 $PINS Z=chip_cd_n_93 
+ A=chip_cd_count[21] B=chip_cd_inc_add_23_19_n_284 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g398__2398 XOR2X1 $PINS Z=chip_cd_n_97 
+ A=chip_cd_count[25] B=chip_cd_inc_add_23_19_n_281 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g399__5107 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_269 
+ A=chip_cd_inc_add_23_19_n_278 B=chip_cd_count[18] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g400__6260 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_272 
+ A=chip_cd_inc_add_23_19_n_287 B=chip_cd_count[22] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g401__4319 XOR2X1 $PINS Z=chip_cd_n_92 
+ A=chip_cd_count[20] B=chip_cd_inc_add_23_19_n_296 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g402__8428 XOR2X1 $PINS Z=chip_cd_n_96 
+ A=chip_cd_count[24] B=chip_cd_inc_add_23_19_n_295 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g403__5526 XOR2X1 $PINS Z=chip_cd_n_89 
+ A=chip_cd_count[17] B=chip_cd_inc_add_23_19_n_291 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g404__6783 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_278 
+ A=chip_cd_inc_add_23_19_n_291 B=chip_cd_count[17] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g405__3680 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_281 
+ A=chip_cd_inc_add_23_19_n_295 B=chip_cd_count[24] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g406__1617 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_284 
+ A=chip_cd_inc_add_23_19_n_296 B=chip_cd_count[20] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g407__2802 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_287 
+ A=chip_cd_inc_add_23_19_n_296 B=chip_cd_inc_add_23_19_n_370 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g408__1705 NOR2X1 $PINS Z=chip_cd_n_88 
+ A=chip_cd_inc_add_23_19_n_292 B=chip_cd_inc_add_23_19_n_291 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g409__5122 XOR2X1 $PINS Z=chip_cd_n_87 
+ A=chip_cd_count[15] B=chip_cd_inc_add_23_19_n_306 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g410__8246 XOR2X1 $PINS Z=chip_cd_n_83 
+ A=chip_cd_count[11] B=chip_cd_inc_add_23_19_n_301 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g411__7098 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_291 
+ A=chip_cd_inc_add_23_19_n_304 B=chip_cd_count[16] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g412__6131 NOR2X1 $PINS Z=chip_cd_inc_add_23_19_n_292 
+ A=chip_cd_count[16] B=chip_cd_inc_add_23_19_n_304 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g413__1881 NOR2X1 $PINS Z=chip_cd_inc_add_23_19_n_295 
+ A=chip_cd_inc_add_23_19_n_321 B=chip_cd_inc_add_23_19_n_305 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g414__5115 NOR2X1 $PINS Z=chip_cd_inc_add_23_19_n_296 
+ A=chip_cd_inc_add_23_19_n_349 B=chip_cd_inc_add_23_19_n_305 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g415__7482 XOR2X1 $PINS Z=chip_cd_n_86 
+ A=chip_cd_count[14] B=chip_cd_inc_add_23_19_n_315 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g416__4733 XOR2X1 $PINS Z=chip_cd_n_82 
+ A=chip_cd_count[10] B=chip_cd_inc_add_23_19_n_311 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g417__6161 XOR2X1 $PINS Z=chip_cd_n_85 
+ A=chip_cd_count[13] B=chip_cd_inc_add_23_19_n_317 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g418__9315 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_301 
+ A=chip_cd_inc_add_23_19_n_311 B=chip_cd_count[10] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g419 INVX2 $PINS Z=chip_cd_inc_add_23_19_n_305 
+ A=chip_cd_inc_add_23_19_n_304 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g420__9945 NOR2X1 $PINS Z=chip_cd_inc_add_23_19_n_304 
+ A=chip_cd_inc_add_23_19_n_341 B=chip_cd_inc_add_23_19_n_319 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g421__2883 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_306 
+ A=chip_cd_inc_add_23_19_n_315 B=chip_cd_count[14] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g422__2346 XOR2X1 $PINS Z=chip_cd_n_84 
+ A=chip_cd_count[12] B=chip_cd_inc_add_23_19_n_325 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g423__1666 NOR2X1 $PINS Z=chip_cd_n_81 
+ A=chip_cd_inc_add_23_19_n_312 B=chip_cd_inc_add_23_19_n_311 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g424__7410 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_311 
+ A=chip_cd_inc_add_23_19_n_327 B=chip_cd_count[9] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g425__6417 NOR2X1 $PINS Z=chip_cd_inc_add_23_19_n_312 
+ A=chip_cd_count[9] B=chip_cd_inc_add_23_19_n_327 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g426__5477 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_315 
+ A=chip_cd_inc_add_23_19_n_325 B=chip_cd_inc_add_23_19_n_367 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g427__2398 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_317 
+ A=chip_cd_inc_add_23_19_n_325 B=chip_cd_count[12] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g428__5107 NAND3X1 $PINS Z=chip_cd_inc_add_23_19_n_319 
+ A=chip_cd_inc_add_23_19_n_336 B=chip_cd_count[15] C=chip_cd_count[14] VSS=VSS 
+ VDD=VDD 
Xchip_cd_inc_add_23_19_g429__6260 NAND3X1 $PINS Z=chip_cd_inc_add_23_19_n_321 
+ A=chip_cd_inc_add_23_19_n_338 B=chip_cd_count[23] C=chip_cd_count[22] VSS=VSS 
+ VDD=VDD 
Xchip_cd_inc_add_23_19_g430__4319 NOR2X1 $PINS Z=chip_cd_n_80 
+ A=chip_cd_inc_add_23_19_n_328 B=chip_cd_inc_add_23_19_n_327 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g431__8428 XOR2X1 $PINS Z=chip_cd_n_79 
+ A=chip_cd_count[7] B=chip_cd_inc_add_23_19_n_333 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g432__5526 NOR2X1 $PINS Z=chip_cd_inc_add_23_19_n_325 
+ A=chip_cd_inc_add_23_19_n_350 B=chip_cd_inc_add_23_19_n_341 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g433__6783 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_327 
+ A=chip_cd_inc_add_23_19_n_340 B=chip_cd_count[8] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g434__3680 NOR2X1 $PINS Z=chip_cd_inc_add_23_19_n_328 
+ A=chip_cd_count[8] B=chip_cd_inc_add_23_19_n_340 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g435__1617 XOR2X1 $PINS Z=chip_cd_n_78 
+ A=chip_cd_count[6] B=chip_cd_inc_add_23_19_n_351 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g436__2802 XOR2X1 $PINS Z=chip_cd_n_77 
+ A=chip_cd_count[5] B=chip_cd_inc_add_23_19_n_345 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g437__1705 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_333 
+ A=chip_cd_inc_add_23_19_n_351 B=chip_cd_count[6] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g438__5122 NOR2X1 $PINS Z=chip_cd_inc_add_23_19_n_336 
+ A=chip_cd_inc_add_23_19_n_368 B=chip_cd_inc_add_23_19_n_350 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g439__8246 NOR2X1 $PINS Z=chip_cd_inc_add_23_19_n_338 
+ A=chip_cd_inc_add_23_19_n_371 B=chip_cd_inc_add_23_19_n_349 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g440 INVX2 $PINS Z=chip_cd_inc_add_23_19_n_341 
+ A=chip_cd_inc_add_23_19_n_340 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g441__7098 NOR2X1 $PINS Z=chip_cd_inc_add_23_19_n_340 
+ A=chip_cd_inc_add_23_19_n_359 B=chip_cd_inc_add_23_19_n_352 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g442__6131 NOR2X1 $PINS Z=chip_cd_n_76 
+ A=chip_cd_inc_add_23_19_n_347 B=chip_cd_inc_add_23_19_n_345 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g443__1881 XOR2X1 $PINS Z=chip_cd_n_75 
+ A=chip_cd_count[3] B=chip_cd_inc_add_23_19_n_355 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g444__5115 NOR2X1 $PINS Z=chip_cd_inc_add_23_19_n_345 
+ A=chip_cd_inc_add_23_19_n_397 B=chip_cd_inc_add_23_19_n_359 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g445__7482 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_347 
+ A=chip_cd_inc_add_23_19_n_359 B=chip_cd_inc_add_23_19_n_397 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g446__4733 NAND3X1 $PINS Z=chip_cd_inc_add_23_19_n_349 
+ A=chip_cd_inc_add_23_19_n_362 B=chip_cd_count[16] C=chip_cd_count[17] VSS=VSS 
+ VDD=VDD 
Xchip_cd_inc_add_23_19_g447__6161 NAND3X1 $PINS Z=chip_cd_inc_add_23_19_n_350 
+ A=chip_cd_inc_add_23_19_n_373 B=chip_cd_count[8] C=chip_cd_count[9] VSS=VSS 
+ VDD=VDD 
Xchip_cd_inc_add_23_19_g448__9315 NOR2X1 $PINS Z=chip_cd_inc_add_23_19_n_351 
+ A=chip_cd_inc_add_23_19_n_365 B=chip_cd_inc_add_23_19_n_359 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g449__9945 NAND3X1 $PINS Z=chip_cd_inc_add_23_19_n_352 
+ A=chip_cd_inc_add_23_19_n_364 B=chip_cd_count[7] C=chip_cd_count[6] VSS=VSS 
+ VDD=VDD 
Xchip_cd_inc_add_23_19_g450__2883 XOR2X1 $PINS Z=chip_cd_n_74 
+ A=chip_cd_count[2] B=chip_cd_inc_add_23_19_n_361 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g451__2346 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_355 
+ A=chip_cd_inc_add_23_19_n_361 B=chip_cd_count[2] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g452__1666 NOR2X1 $PINS Z=chip_cd_n_73 
+ A=chip_cd_inc_add_23_19_n_375 B=chip_cd_inc_add_23_19_n_361 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g453__7410 NAND3X1 $PINS Z=chip_cd_inc_add_23_19_n_359 
+ A=chip_cd_inc_add_23_19_n_361 B=chip_cd_count[2] C=chip_cd_count[3] VSS=VSS 
+ VDD=VDD 
Xchip_cd_inc_add_23_19_g454__6417 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_361 
+ A=chip_cd_count[0] B=chip_cd_count[1] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g455__5477 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_362 
+ A=chip_cd_count[18] B=chip_cd_count[19] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g456 INVX2 $PINS Z=chip_cd_inc_add_23_19_n_364 
+ A=chip_cd_inc_add_23_19_n_365 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g457__2398 NAND2X1 $PINS Z=chip_cd_inc_add_23_19_n_365 
+ A=chip_cd_count[4] B=chip_cd_count[5] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g458 INVX2 $PINS Z=chip_cd_inc_add_23_19_n_367 
+ A=chip_cd_inc_add_23_19_n_368 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g459__5107 NAND2X1 $PINS Z=chip_cd_inc_add_23_19_n_368 
+ A=chip_cd_count[12] B=chip_cd_count[13] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g460 INVX2 $PINS Z=chip_cd_inc_add_23_19_n_370 
+ A=chip_cd_inc_add_23_19_n_371 VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g461__6260 NAND2X1 $PINS Z=chip_cd_inc_add_23_19_n_371 
+ A=chip_cd_count[20] B=chip_cd_count[21] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g462__4319 AND2X1 $PINS Z=chip_cd_inc_add_23_19_n_373 
+ A=chip_cd_count[10] B=chip_cd_count[11] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g463__8428 NOR2X1 $PINS Z=chip_cd_inc_add_23_19_n_375 
+ A=chip_cd_count[1] B=chip_cd_count[0] VSS=VSS VDD=VDD 
Xchip_cd_inc_add_23_19_g464 INVX2 $PINS Z=chip_cd_inc_add_23_19_n_397 
+ A=chip_cd_count[4] VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g393__5526 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_95 A=chip_backlight_seconds_clk_count[23] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_272 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g394__6783 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_91 A=chip_backlight_seconds_clk_count[19] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_269 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g395__3680 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_90 A=chip_backlight_seconds_clk_count[18] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_278 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g396__1617 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_94 A=chip_backlight_seconds_clk_count[22] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_287 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g397__2802 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_93 A=chip_backlight_seconds_clk_count[21] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_284 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g398__1705 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_97 A=chip_backlight_seconds_clk_count[25] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_281 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g399__5122 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_269 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_278 
+ B=chip_backlight_seconds_clk_count[18] VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g400__8246 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_272 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_287 
+ B=chip_backlight_seconds_clk_count[22] VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g401__7098 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_92 A=chip_backlight_seconds_clk_count[20] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_296 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g402__6131 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_96 A=chip_backlight_seconds_clk_count[24] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_295 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g403__1881 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_89 A=chip_backlight_seconds_clk_count[17] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_291 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g404__5115 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_278 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_291 
+ B=chip_backlight_seconds_clk_count[17] VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g405__7482 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_281 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_295 
+ B=chip_backlight_seconds_clk_count[24] VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g406__4733 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_284 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_296 
+ B=chip_backlight_seconds_clk_count[20] VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g407__6161 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_287 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_296 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_370 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g408__9315 NOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_88 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_292 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_291 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g409__9945 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_87 A=chip_backlight_seconds_clk_count[15] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_306 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g410__2883 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_83 A=chip_backlight_seconds_clk_count[11] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_301 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g411__2346 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_291 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_304 
+ B=chip_backlight_seconds_clk_count[16] VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g412__1666 NOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_292 
+ A=chip_backlight_seconds_clk_count[16] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_304 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g413__7410 NOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_295 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_321 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_305 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g414__6417 NOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_296 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_349 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_305 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g415__5477 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_86 A=chip_backlight_seconds_clk_count[14] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_315 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g416__2398 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_82 A=chip_backlight_seconds_clk_count[10] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_311 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g417__5107 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_85 A=chip_backlight_seconds_clk_count[13] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_317 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g418__6260 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_301 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_311 
+ B=chip_backlight_seconds_clk_count[10] VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g419 INVX2 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_305 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_304 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g420__4319 NOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_304 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_341 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_319 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g421__8428 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_306 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_315 
+ B=chip_backlight_seconds_clk_count[14] VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g422__5526 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_84 A=chip_backlight_seconds_clk_count[12] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_325 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g423__6783 NOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_81 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_312 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_311 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g424__3680 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_311 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_327 
+ B=chip_backlight_seconds_clk_count[9] VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g425__1617 NOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_312 
+ A=chip_backlight_seconds_clk_count[9] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_327 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g426__2802 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_315 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_325 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_367 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g427__1705 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_317 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_325 
+ B=chip_backlight_seconds_clk_count[12] VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g428__5122 NAND3X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_319 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_336 
+ B=chip_backlight_seconds_clk_count[15] C=chip_backlight_seconds_clk_count[14] 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g429__8246 NAND3X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_321 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_338 
+ B=chip_backlight_seconds_clk_count[23] C=chip_backlight_seconds_clk_count[22] 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g430__7098 NOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_80 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_328 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_327 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g431__6131 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_79 A=chip_backlight_seconds_clk_count[7] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_333 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g432__1881 NOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_325 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_350 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_341 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g433__5115 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_327 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_340 
+ B=chip_backlight_seconds_clk_count[8] VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g434__7482 NOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_328 
+ A=chip_backlight_seconds_clk_count[8] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_340 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g435__4733 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_78 A=chip_backlight_seconds_clk_count[6] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_351 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g436__6161 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_77 A=chip_backlight_seconds_clk_count[5] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_345 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g437__9315 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_333 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_351 
+ B=chip_backlight_seconds_clk_count[6] VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g438__9945 NOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_336 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_368 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_350 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g439__2883 NOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_338 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_371 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_349 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g440 INVX2 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_341 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_340 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g441__2346 NOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_340 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_359 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_352 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g442__1666 NOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_76 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_347 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_345 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g443__7410 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_75 A=chip_backlight_seconds_clk_count[3] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_355 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g444__6417 NOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_345 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_397 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_359 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g445__5477 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_347 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_359 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_397 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g446__2398 NAND3X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_349 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_362 
+ B=chip_backlight_seconds_clk_count[16] C=chip_backlight_seconds_clk_count[17] 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g447__5107 NAND3X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_350 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_373 
+ B=chip_backlight_seconds_clk_count[8] C=chip_backlight_seconds_clk_count[9] 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g448__6260 NOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_351 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_365 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_359 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g449__4319 NAND3X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_352 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_364 
+ B=chip_backlight_seconds_clk_count[7] C=chip_backlight_seconds_clk_count[6] 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g450__8428 XOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_74 A=chip_backlight_seconds_clk_count[2] 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_361 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g451__5526 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_355 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_361 
+ B=chip_backlight_seconds_clk_count[2] VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g452__6783 NOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_n_73 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_375 
+ B=chip_backlight_seconds_clk_inc_add_23_19_n_361 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g453__3680 NAND3X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_359 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_361 
+ B=chip_backlight_seconds_clk_count[2] C=chip_backlight_seconds_clk_count[3] 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g454__1617 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_361 
+ A=chip_backlight_seconds_clk_count[0] B=chip_backlight_seconds_clk_count[1] 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g455__2802 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_362 
+ A=chip_backlight_seconds_clk_count[18] B=chip_backlight_seconds_clk_count[19] 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g456 INVX2 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_364 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_365 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g457__1705 NAND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_365 
+ A=chip_backlight_seconds_clk_count[4] B=chip_backlight_seconds_clk_count[5] 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g458 INVX2 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_367 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_368 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g459__5122 NAND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_368 
+ A=chip_backlight_seconds_clk_count[12] B=chip_backlight_seconds_clk_count[13] 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g460 INVX2 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_370 
+ A=chip_backlight_seconds_clk_inc_add_23_19_n_371 VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g461__8246 NAND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_371 
+ A=chip_backlight_seconds_clk_count[20] B=chip_backlight_seconds_clk_count[21] 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g462__7098 AND2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_373 
+ A=chip_backlight_seconds_clk_count[10] B=chip_backlight_seconds_clk_count[11] 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g463__6131 NOR2X1 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_375 
+ A=chip_backlight_seconds_clk_count[1] B=chip_backlight_seconds_clk_count[0] 
+ VSS=VSS VDD=VDD 
Xchip_backlight_seconds_clk_inc_add_23_19_g464 INVX2 $PINS 
+ Z=chip_backlight_seconds_clk_inc_add_23_19_n_397 
+ A=chip_backlight_seconds_clk_count[4] VSS=VSS VDD=VDD 
Xg2 NAND3X1 $PINS Z=n_283 A=n_282 B=n_84 C=chip_backlight_seconds_clk_count[7] 
+ VSS=VSS VDD=VDD 
Xg3 NOR2X1 $PINS Z=n_282 A=chip_backlight_seconds_clk_count[24] 
+ B=chip_backlight_seconds_clk_count[25] VSS=VSS VDD=VDD 
Xg4302 OR2X1 $PINS Z=n_285 A=n_284 B=chip_cd_count[4] VSS=VSS VDD=VDD 
Xg4303 NAND3X1 $PINS Z=n_284 A=n_19 B=chip_cd_count[3] C=chip_cd_count[5] 
+ VSS=VSS VDD=VDD 
.ENDS
