# ####################################################################

#  Created by Genus(TM) Synthesis Solution 21.15-s080_1 on Tue Nov 28 17:45:53 MST 2023

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design soc_top

create_clock -name "clk" -period 20.0 -waveform {0.0 10.0} [get_ports clk]
group_path -weight 1.000000 -name C2C -from [list \
  [get_cells {chip_backlight_current_count_reg[0]}]  \
  [get_cells {chip_backlight_current_count_reg[1]}]  \
  [get_cells {chip_backlight_current_count_reg[2]}]  \
  [get_cells chip_backlight_light_mode_reg]  \
  [get_cells chip_backlight_seconds_clk_clk_seconds_reg]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[0]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[1]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[2]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[3]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[4]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[5]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[6]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[7]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[8]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[9]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[10]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[11]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[12]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[13]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[14]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[15]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[16]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[17]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[18]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[19]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[20]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[21]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[22]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[23]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[24]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[25]}]  \
  [get_cells chip_backlight_start_counter_reg]  \
  [get_cells chip_cd_clk_seconds_reg]  \
  [get_cells {chip_cd_count_reg[0]}]  \
  [get_cells {chip_cd_count_reg[1]}]  \
  [get_cells {chip_cd_count_reg[2]}]  \
  [get_cells {chip_cd_count_reg[3]}]  \
  [get_cells {chip_cd_count_reg[4]}]  \
  [get_cells {chip_cd_count_reg[5]}]  \
  [get_cells {chip_cd_count_reg[6]}]  \
  [get_cells {chip_cd_count_reg[7]}]  \
  [get_cells {chip_cd_count_reg[8]}]  \
  [get_cells {chip_cd_count_reg[9]}]  \
  [get_cells {chip_cd_count_reg[10]}]  \
  [get_cells {chip_cd_count_reg[11]}]  \
  [get_cells {chip_cd_count_reg[12]}]  \
  [get_cells {chip_cd_count_reg[13]}]  \
  [get_cells {chip_cd_count_reg[14]}]  \
  [get_cells {chip_cd_count_reg[15]}]  \
  [get_cells {chip_cd_count_reg[16]}]  \
  [get_cells {chip_cd_count_reg[17]}]  \
  [get_cells {chip_cd_count_reg[18]}]  \
  [get_cells {chip_cd_count_reg[19]}]  \
  [get_cells {chip_cd_count_reg[20]}]  \
  [get_cells {chip_cd_count_reg[21]}]  \
  [get_cells {chip_cd_count_reg[22]}]  \
  [get_cells {chip_cd_count_reg[23]}]  \
  [get_cells {chip_cd_count_reg[24]}]  \
  [get_cells {chip_cd_count_reg[25]}]  \
  [get_cells {chip_displayer_display_h1_reg[0]}]  \
  [get_cells {chip_displayer_display_m1_reg[0]}]  \
  [get_cells {chip_displayer_display_s1_reg[0]}]  \
  [get_cells chip_displayer_enable_7seg_reg]  \
  [get_cells chip_displayer_last_seconds_clk_reg]  \
  [get_cells {chip_fsm_state_reg[0]}]  \
  [get_cells {chip_fsm_state_reg[1]}]  \
  [get_cells {chip_fsm_state_reg[2]}]  \
  [get_cells chip_fsm_swFF_Q_reg]  \
  [get_cells {chip_fsm_next_state_reg[1]}]  \
  [get_cells {chip_fsm_next_state_reg[0]}]  \
  [get_cells {chip_fsm_next_state_reg[2]}]  \
  [get_cells chip_backlight_light_reg] ] -to [list \
  [get_cells {chip_backlight_current_count_reg[0]}]  \
  [get_cells {chip_backlight_current_count_reg[1]}]  \
  [get_cells {chip_backlight_current_count_reg[2]}]  \
  [get_cells chip_backlight_light_mode_reg]  \
  [get_cells chip_backlight_seconds_clk_clk_seconds_reg]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[0]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[1]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[2]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[3]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[4]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[5]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[6]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[7]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[8]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[9]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[10]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[11]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[12]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[13]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[14]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[15]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[16]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[17]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[18]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[19]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[20]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[21]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[22]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[23]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[24]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[25]}]  \
  [get_cells chip_backlight_start_counter_reg]  \
  [get_cells chip_cd_clk_seconds_reg]  \
  [get_cells {chip_cd_count_reg[0]}]  \
  [get_cells {chip_cd_count_reg[1]}]  \
  [get_cells {chip_cd_count_reg[2]}]  \
  [get_cells {chip_cd_count_reg[3]}]  \
  [get_cells {chip_cd_count_reg[4]}]  \
  [get_cells {chip_cd_count_reg[5]}]  \
  [get_cells {chip_cd_count_reg[6]}]  \
  [get_cells {chip_cd_count_reg[7]}]  \
  [get_cells {chip_cd_count_reg[8]}]  \
  [get_cells {chip_cd_count_reg[9]}]  \
  [get_cells {chip_cd_count_reg[10]}]  \
  [get_cells {chip_cd_count_reg[11]}]  \
  [get_cells {chip_cd_count_reg[12]}]  \
  [get_cells {chip_cd_count_reg[13]}]  \
  [get_cells {chip_cd_count_reg[14]}]  \
  [get_cells {chip_cd_count_reg[15]}]  \
  [get_cells {chip_cd_count_reg[16]}]  \
  [get_cells {chip_cd_count_reg[17]}]  \
  [get_cells {chip_cd_count_reg[18]}]  \
  [get_cells {chip_cd_count_reg[19]}]  \
  [get_cells {chip_cd_count_reg[20]}]  \
  [get_cells {chip_cd_count_reg[21]}]  \
  [get_cells {chip_cd_count_reg[22]}]  \
  [get_cells {chip_cd_count_reg[23]}]  \
  [get_cells {chip_cd_count_reg[24]}]  \
  [get_cells {chip_cd_count_reg[25]}]  \
  [get_cells {chip_displayer_display_h1_reg[0]}]  \
  [get_cells {chip_displayer_display_m1_reg[0]}]  \
  [get_cells {chip_displayer_display_s1_reg[0]}]  \
  [get_cells chip_displayer_enable_7seg_reg]  \
  [get_cells chip_displayer_last_seconds_clk_reg]  \
  [get_cells {chip_fsm_state_reg[0]}]  \
  [get_cells {chip_fsm_state_reg[1]}]  \
  [get_cells {chip_fsm_state_reg[2]}]  \
  [get_cells chip_fsm_swFF_Q_reg]  \
  [get_cells {chip_fsm_next_state_reg[1]}]  \
  [get_cells {chip_fsm_next_state_reg[0]}]  \
  [get_cells {chip_fsm_next_state_reg[2]}]  \
  [get_cells chip_backlight_light_reg] ]
group_path -weight 1.000000 -name C2O -from [list \
  [get_cells {chip_backlight_current_count_reg[0]}]  \
  [get_cells {chip_backlight_current_count_reg[1]}]  \
  [get_cells {chip_backlight_current_count_reg[2]}]  \
  [get_cells chip_backlight_light_mode_reg]  \
  [get_cells chip_backlight_seconds_clk_clk_seconds_reg]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[0]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[1]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[2]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[3]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[4]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[5]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[6]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[7]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[8]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[9]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[10]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[11]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[12]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[13]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[14]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[15]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[16]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[17]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[18]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[19]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[20]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[21]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[22]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[23]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[24]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[25]}]  \
  [get_cells chip_backlight_start_counter_reg]  \
  [get_cells chip_cd_clk_seconds_reg]  \
  [get_cells {chip_cd_count_reg[0]}]  \
  [get_cells {chip_cd_count_reg[1]}]  \
  [get_cells {chip_cd_count_reg[2]}]  \
  [get_cells {chip_cd_count_reg[3]}]  \
  [get_cells {chip_cd_count_reg[4]}]  \
  [get_cells {chip_cd_count_reg[5]}]  \
  [get_cells {chip_cd_count_reg[6]}]  \
  [get_cells {chip_cd_count_reg[7]}]  \
  [get_cells {chip_cd_count_reg[8]}]  \
  [get_cells {chip_cd_count_reg[9]}]  \
  [get_cells {chip_cd_count_reg[10]}]  \
  [get_cells {chip_cd_count_reg[11]}]  \
  [get_cells {chip_cd_count_reg[12]}]  \
  [get_cells {chip_cd_count_reg[13]}]  \
  [get_cells {chip_cd_count_reg[14]}]  \
  [get_cells {chip_cd_count_reg[15]}]  \
  [get_cells {chip_cd_count_reg[16]}]  \
  [get_cells {chip_cd_count_reg[17]}]  \
  [get_cells {chip_cd_count_reg[18]}]  \
  [get_cells {chip_cd_count_reg[19]}]  \
  [get_cells {chip_cd_count_reg[20]}]  \
  [get_cells {chip_cd_count_reg[21]}]  \
  [get_cells {chip_cd_count_reg[22]}]  \
  [get_cells {chip_cd_count_reg[23]}]  \
  [get_cells {chip_cd_count_reg[24]}]  \
  [get_cells {chip_cd_count_reg[25]}]  \
  [get_cells {chip_displayer_display_h1_reg[0]}]  \
  [get_cells {chip_displayer_display_m1_reg[0]}]  \
  [get_cells {chip_displayer_display_s1_reg[0]}]  \
  [get_cells chip_displayer_enable_7seg_reg]  \
  [get_cells chip_displayer_last_seconds_clk_reg]  \
  [get_cells {chip_fsm_state_reg[0]}]  \
  [get_cells {chip_fsm_state_reg[1]}]  \
  [get_cells {chip_fsm_state_reg[2]}]  \
  [get_cells chip_fsm_swFF_Q_reg]  \
  [get_cells {chip_fsm_next_state_reg[1]}]  \
  [get_cells {chip_fsm_next_state_reg[0]}]  \
  [get_cells {chip_fsm_next_state_reg[2]}]  \
  [get_cells chip_backlight_light_reg] ] -to [list \
  [get_ports h1_6]  \
  [get_ports h1_5]  \
  [get_ports h1_4]  \
  [get_ports h1_3]  \
  [get_ports h1_2]  \
  [get_ports h1_1]  \
  [get_ports h1_0]  \
  [get_ports h0_6]  \
  [get_ports h0_5]  \
  [get_ports h0_4]  \
  [get_ports h0_3]  \
  [get_ports h0_2]  \
  [get_ports h0_1]  \
  [get_ports h0_0]  \
  [get_ports m1_6]  \
  [get_ports m1_5]  \
  [get_ports m1_4]  \
  [get_ports m1_3]  \
  [get_ports m1_2]  \
  [get_ports m1_1]  \
  [get_ports m1_0]  \
  [get_ports m0_6]  \
  [get_ports m0_5]  \
  [get_ports m0_4]  \
  [get_ports m0_3]  \
  [get_ports m0_2]  \
  [get_ports m0_1]  \
  [get_ports m0_0]  \
  [get_ports s1_6]  \
  [get_ports s1_5]  \
  [get_ports s1_4]  \
  [get_ports s1_3]  \
  [get_ports s1_2]  \
  [get_ports s1_1]  \
  [get_ports s1_0]  \
  [get_ports s0_6]  \
  [get_ports s0_5]  \
  [get_ports s0_4]  \
  [get_ports s0_3]  \
  [get_ports s0_2]  \
  [get_ports s0_1]  \
  [get_ports s0_0]  \
  [get_ports colon]  \
  [get_ports light] ]
group_path -weight 1.000000 -name I2C -from [list \
  [get_ports clk]  \
  [get_ports reset]  \
  [get_ports btn_mode]  \
  [get_ports btn_set]  \
  [get_ports btn_inc]  \
  [get_ports btn_dec]  \
  [get_ports btn_light] ] -to [list \
  [get_cells {chip_backlight_current_count_reg[0]}]  \
  [get_cells {chip_backlight_current_count_reg[1]}]  \
  [get_cells {chip_backlight_current_count_reg[2]}]  \
  [get_cells chip_backlight_light_mode_reg]  \
  [get_cells chip_backlight_seconds_clk_clk_seconds_reg]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[0]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[1]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[2]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[3]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[4]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[5]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[6]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[7]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[8]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[9]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[10]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[11]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[12]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[13]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[14]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[15]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[16]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[17]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[18]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[19]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[20]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[21]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[22]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[23]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[24]}]  \
  [get_cells {chip_backlight_seconds_clk_count_reg[25]}]  \
  [get_cells chip_backlight_start_counter_reg]  \
  [get_cells chip_cd_clk_seconds_reg]  \
  [get_cells {chip_cd_count_reg[0]}]  \
  [get_cells {chip_cd_count_reg[1]}]  \
  [get_cells {chip_cd_count_reg[2]}]  \
  [get_cells {chip_cd_count_reg[3]}]  \
  [get_cells {chip_cd_count_reg[4]}]  \
  [get_cells {chip_cd_count_reg[5]}]  \
  [get_cells {chip_cd_count_reg[6]}]  \
  [get_cells {chip_cd_count_reg[7]}]  \
  [get_cells {chip_cd_count_reg[8]}]  \
  [get_cells {chip_cd_count_reg[9]}]  \
  [get_cells {chip_cd_count_reg[10]}]  \
  [get_cells {chip_cd_count_reg[11]}]  \
  [get_cells {chip_cd_count_reg[12]}]  \
  [get_cells {chip_cd_count_reg[13]}]  \
  [get_cells {chip_cd_count_reg[14]}]  \
  [get_cells {chip_cd_count_reg[15]}]  \
  [get_cells {chip_cd_count_reg[16]}]  \
  [get_cells {chip_cd_count_reg[17]}]  \
  [get_cells {chip_cd_count_reg[18]}]  \
  [get_cells {chip_cd_count_reg[19]}]  \
  [get_cells {chip_cd_count_reg[20]}]  \
  [get_cells {chip_cd_count_reg[21]}]  \
  [get_cells {chip_cd_count_reg[22]}]  \
  [get_cells {chip_cd_count_reg[23]}]  \
  [get_cells {chip_cd_count_reg[24]}]  \
  [get_cells {chip_cd_count_reg[25]}]  \
  [get_cells {chip_displayer_display_h1_reg[0]}]  \
  [get_cells {chip_displayer_display_m1_reg[0]}]  \
  [get_cells {chip_displayer_display_s1_reg[0]}]  \
  [get_cells chip_displayer_enable_7seg_reg]  \
  [get_cells chip_displayer_last_seconds_clk_reg]  \
  [get_cells {chip_fsm_state_reg[0]}]  \
  [get_cells {chip_fsm_state_reg[1]}]  \
  [get_cells {chip_fsm_state_reg[2]}]  \
  [get_cells chip_fsm_swFF_Q_reg]  \
  [get_cells {chip_fsm_next_state_reg[1]}]  \
  [get_cells {chip_fsm_next_state_reg[0]}]  \
  [get_cells {chip_fsm_next_state_reg[2]}]  \
  [get_cells chip_backlight_light_reg] ]
group_path -weight 1.000000 -name I2O -from [list \
  [get_ports clk]  \
  [get_ports reset]  \
  [get_ports btn_mode]  \
  [get_ports btn_set]  \
  [get_ports btn_inc]  \
  [get_ports btn_dec]  \
  [get_ports btn_light] ] -to [list \
  [get_ports h1_6]  \
  [get_ports h1_5]  \
  [get_ports h1_4]  \
  [get_ports h1_3]  \
  [get_ports h1_2]  \
  [get_ports h1_1]  \
  [get_ports h1_0]  \
  [get_ports h0_6]  \
  [get_ports h0_5]  \
  [get_ports h0_4]  \
  [get_ports h0_3]  \
  [get_ports h0_2]  \
  [get_ports h0_1]  \
  [get_ports h0_0]  \
  [get_ports m1_6]  \
  [get_ports m1_5]  \
  [get_ports m1_4]  \
  [get_ports m1_3]  \
  [get_ports m1_2]  \
  [get_ports m1_1]  \
  [get_ports m1_0]  \
  [get_ports m0_6]  \
  [get_ports m0_5]  \
  [get_ports m0_4]  \
  [get_ports m0_3]  \
  [get_ports m0_2]  \
  [get_ports m0_1]  \
  [get_ports m0_0]  \
  [get_ports s1_6]  \
  [get_ports s1_5]  \
  [get_ports s1_4]  \
  [get_ports s1_3]  \
  [get_ports s1_2]  \
  [get_ports s1_1]  \
  [get_ports s1_0]  \
  [get_ports s0_6]  \
  [get_ports s0_5]  \
  [get_ports s0_4]  \
  [get_ports s0_3]  \
  [get_ports s0_2]  \
  [get_ports s0_1]  \
  [get_ports s0_0]  \
  [get_ports colon]  \
  [get_ports light] ]
set_clock_gating_check -setup 0.0 
